### ISSUE TITLE
Re-use of already done work_VK9

### ISSUE THREAD

**Issue by Styx85** [Joshua-Ashton/d9vk#1]
Heads up for integrating dx9 into dxvk. I would love to see it.

Can you provide some ideas or information what to expect? Are you re-using already implemented functions like done by [Christopher Joseph Dean Schaefer](https://github.com/disks86/VK9) or is the way  you plan to implement it way different?

**Comment by disks86** [comment]
I don't want to put words in his mouth but he is basing his work on dxvk. When I started vk9 dxvk didn't exist and the two projects took different approaches.

**Comment by Joshua-Ashton** [comment]
No. I am not planning to.
