### ISSUE TITLE
Legend of the Heroes: Trails of the Sky

### ISSUE THREAD

**Issue by ZachBacon** [Joshua-Ashton/d9vk#100]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Legend of the Heroes: Trails of the Sky

### System information
- GPU: NVidia GTX 1060 6GB
- Driver: 430.64
- Wine version: Not using wine, Testing through Windows 10 Pro
- D9VK version: Git: da392277

### Apitrace file(s)
- https://casualgamer.ca/apitrace/d3d9/The%20Legend%20of%20Heroes-Trails%20in%20the%20Sky.tar.xz

### Log files
- [ed6_win_DX9_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3170117/ed6_win_DX9_d3d9.log)

**Comment by rphsoftware** [comment]
frog you, stole the 100th issue >:(

**Comment by Joshua-Ashton** [comment]
`Please describe your issue as accurately as possible` what is the issue?

**Comment by ZachBacon** [comment]
> `Please describe your issue as accurately as possible` what is the issue?

Apologies, I kinda had a major brain fart there. Entirely as accurately as possible is this. It's Black. Nothing seems to be rendered at at all.

**Comment by BillFleming** [comment]
This game has at least 2 issues.
First the video logo and intro don't work and cause the game to hang at a black screen. But this game has the config option to turn them off. Once you do it will load the menu and you can hear the music.
On D9VK however you cannot see anything on the screen, but you can still make menu selections with keyboard and here the feedback noise. Attached is log with videos turned off.

Used frogged proton tkg 4.8 for this one. 
[steam-251150.log](https://github.com/Joshua-Ashton/d9vk/files/3175400/steam-251150.log)

**Comment by CartoonFan** [comment]
It looks like it might be fixed, but you can verify if you want.

**Comment by Joshua-Ashton** [comment]
Apitrace is no longer up there so I'll take your word for it as I do not own the game.

If it needs to be re-opened its no biggie. :-)

**Comment by CartoonFan** [comment]
All right, sounds good.

**Comment by BillFleming** [comment]
With the latest release the game appears to be playable with the intro videos turned off. I at least got through the visible main menu and the beginning of the game starts as expected. (although it appears I would need to dig through a VM to find my old game saves to test more) So I imagine the game is at least playable until it tries to play some other video, which might not happen until the ending.

**Comment by aqxa1** [comment]
For the record, there looks to be just those two videos, going by the directory structure. You can play them directly with your favourite video player, "ed6_op.avi" and "ed6_logo.avi". The same applies for the two sequels, according to reports on ProtonDB.

**Comment by rodrigo21** [comment]
Install [LAVFilters](https://github.com/Nevcairiel/LAVFilters/releases) and use winetricks or protontricks to install amstream and quartz for the videos to work.

**Comment by arzardk** [comment]
Game works correctly with or without opening videos, but renders very slow (2-3 FPS) on my RX Vega 56 with latest d9vk and with d9vk 0.13f. Tested on Windows 10, don't know about Linux though.

Apitrace file: [The Legend of Heroes Trails in the Sky (GOG) (d3d9).xz](https://drive.google.com/open?id=1mV05K7Nub3ehES7_KDmQXXScIVhbb89i)
Log file from d9vk bc64e8e0263004908090da60b4c478a6573fe7d0: [ed6_win_DX9_d3d9.log](https://gist.github.com/arzardk/8780372907474914c8a7b79c25fbf6cb)

**Comment by NerosTie** [comment]
You can launch the game with this configuration:
![Screenshot_20190825_215709](https://user-images.githubusercontent.com/4572452/63655068-53acfd80-c783-11e9-90b4-f44971b21328.png)

Logo and Opening must be disabled (not related to d9vk) and "Render Target" on "off" (related to d9vk).

Unfortunately, when the game is launched and I hit on something (start, load, option), it crashes.

The log (with d9vk):
[TheLegendOfHeroes.log](https://github.com/Joshua-Ashton/d9vk/files/3538558/TheLegendOfHeroes.log)

**Comment by aqxa1** [comment]
I also have a performance problem with this game, although in my case, it's not in all locations. Here's an example:

With WineD3D:
![WineD3D](https://i.imgur.com/KKY49Yg.jpg)

With D9VK:
![D9VK](https://i.imgur.com/n4CGipn.jpg)

Beyond the performance difference, you can also see some slight differences in lighting.

[Apitrace](https://drive.google.com/file/d/1HAu6fxMvygcTeJGYDNZ5ArKoJOJCqd9R/view?usp=sharing)

The game performs fine in other locations.

GPU: RX 550 (also affects 5700 XT)
Proton: 4.11-6 (D9VK 0.90 git)

**Comment by Joshua-Ashton** [comment]
Managed to try this out with a friend who owns the game and it seems to be working fine at 125fps the whole time.

Can you double check that so I can close this? 😄 

![image](https://user-images.githubusercontent.com/21316711/69679311-bde57f00-109f-11ea-958d-3bd83d85eea8.png)


Also, the game worked fine with/without the Render Target option selected

**Comment by aqxa1** [comment]
Still broken for me. Did you check the next location, travelling south on the map? Because that spot is okay, but the next screen isn't.

**Comment by Joshua-Ashton** [comment]
I didn't no, I will try that.

**Comment by Joshua-Ashton** [comment]
Ah yes, I can repro now :)
