### ISSUE TITLE
Gothic 3: crashes on start

### ISSUE THREAD

**Issue by Riesi** [Joshua-Ashton/d9vk#101]
The game crashes due to an exception in d3d9.dll, but isn't explicit about it.
Luckily apitrace shows an unhandled exception at `DrawPrimitiveUP` when replaying the trace with d9vk, which is probably the same exception as when running the game.

### System information
- GPU: GTX 970
- Driver: 418.52.05
- Wine version: 4.7
- D9VK version: c8fb2d569675cd7ef37712b0b2d4efe53db752c6

### Apitrace file(s)
https://git.froggi.es/Riesi/tracehub/raw/master/traces/d3d9/Gothic%203%20%5Bnative%5D.tar.xz?inline=false

### Log files
[Gothic3_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3170401/Gothic3_d3d9.log)

**Comment by Joshua-Ashton** [comment]
Fixed by https://github.com/Joshua-Ashton/d9vk/commit/f12081366a342718530814f973c450b319964b8e
