### ISSUE TITLE
Unreal 227i/j working but black screen

### ISSUE THREAD

**Issue by donizettilorenzo** [Joshua-Ashton/d9vk#104]
Game starts (classic NaliCastle flyby intro), audio is OK, all seems working (the console IS working, blindly typing).....except for the screen output: total black :D

Using Oldunreal 227i/j patch of course for D3D9 support.

**Comment by Joshua-Ashton** [comment]
Its probably fixed function.

**Comment by DaRkL3AD3R** [comment]
Same situation for UT99 and Deus Ex with the D3D9 backend.

**Comment by crborga** [comment]
Also, having this same issues with World of Warcraft: The Burning Crusade expansion.

**Comment by NerosTie** [comment]
Because you have configured the patch to use OpenGL, you need to change that to Direct3D. I had the same issue with 227i.

**Comment by donizettilorenzo** [comment]
It's already set to D3D obviously.

Il giorno mer 29 mag 2019 alle ore 13:31 Neros <notifications@github.com>
ha scritto:

**Comment by Joshua-Ashton** [comment]
Tested UT99, works fine with d3d9 renderer.
