### ISSUE TITLE
Mount & Blade: Warband crash on launch

### ISSUE THREAD

**Issue by Bfgeshka** [Joshua-Ashton/d9vk#106]
Warband crashes after intro video. Works fine without d9vk.

Module selection window works fine.

### Software information
Game version 1.172 from gog.  Default configuration (dx9 rendering, no AA, using pixel shaders)

### System information
- GPU: r7 360
- Driver: mesa 19.2.0-devel (git-84816d1464) / llvm 9.0.0svn
- Wine version: 4.7 staging
- DXVK version: 0.11 release

### Apitrace file(s)
I wan't been successfull in capturing trace with or without d9vk for this game.

### Log files
[mb_warband_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3177104/mb_warband_d3d9.log). Other are clear.

**Comment by neVERberleRfellerER** [comment]
Works for me.
![Screenshot_20190514_133714](https://user-images.githubusercontent.com/11160972/57695033-85bfa700-764d-11e9-849d-3c0d1ce199b0.jpg)
Make sure you have necessary d3dx9_.dll andd3dcompiler. It seems game need:
```
d3dx9_27.dll
d3dx9_31.dll
d3dx9_41.dll
d3dx9_43.dll
d3dcompiler_43.dll
```

**Comment by Bfgeshka** [comment]
I've installed these specific dlls via winetricks and it didn't help. I've tried clean prefixes with installing either `d3dx9` or these libraries one by one and game said that that i didn't have directx installed. Sorry, but am I doint something wrong? I've lived with this prefix for so long that I've completely forgot how to do things.

**Comment by neVERberleRfellerER** [comment]
In the logs, i see
```
info:  DXVK: d9vk-0.10
```
But you say you have D9VK 0.11:
```
DXVK version: 0.11 release
```
Can you confirm it reports
```
info:  DXVK: v1.1.1
```
with your new wineprefix (ir reports this with my 0.11)?

**Comment by Bfgeshka** [comment]
i've noticed that it says '0.10' before, but '0.11' is how it is marked in releases, where i got it from. Did you build your one yourself?

**Comment by neVERberleRfellerER** [comment]
My bad. I indeed have version built from latest commit, But apitrace replays fine with 0.11.
But I see big problem here: I only have original mount and blade, not warband. I forgot these are different. I'll test with demo.

**Comment by Cat-Lady** [comment]
Side note: It affects all games on Warband engine (doh!), like "Carribenan: Blood and Gold", "With Fire and Sword", "viking Conquest", etc.

What is more strange, is that it crashes in same manner, even when using native d3d9 (non-d9vk) - it works *only* with build-in wined3d, so far. How game written for windows can work like that is a mystery for me.
My crash log, just in case:
https://zerobin.net/?a8e1bc4ebd140de3#787NDqJBqTn7R7HG8BL/QEr1oig//u18mKawTzxG08s=

**Comment by CartoonFan** [comment]
If it's still helpful, I have native Windows traces for the regular game and Warband.

Mount & Blade:
https://drive.google.com/file/d/1r5QTpKROEacsYf6jNjqmI7QP945smfPa/view?usp=sharing

Warband:
https://drive.google.com/file/d/1df8WfE-44IPTzC70lcEG_VoTerYqv3Ka/view?usp=sharing

**Comment by Cat-Lady** [comment]
Exactly same error at startup happens with Sid Meier's Pirates: Live the Life.

**Comment by K0bin** [comment]
> It crashes in d3d9_42.

No. It crashes in d3d**x**9_42. You're probably using the Wine implementation of d3dx9 despite the clear warning on the release page.

> Please do not use wine's d3d9x or d3dcompiler with d9vk. They make invalid API calls and generate bad shaders. I cannot stress this enough.

Install the Microsoft one using `winetricks d3dx9_42`

**Comment by neVERberleRfellerER** [comment]
> No. It crashes in d3dx9_42.

Just a typo, which is pretty clear from backtrace and d3d9_42 does not even exist.

> You're probably using the Wine implementation of d3dx9

No, I am not. I have full d3dx9 from winetricks.

**Comment by neVERberleRfellerER** [comment]
This is now fixed in `d3d9-fixed-function` branch. When I return master, it starts crashing again. There is still problem with invisible mouse cursors, but that is tracked in WoW WotLK issue (there is whole discussion about it).
![mb_warband_d9vk](https://user-images.githubusercontent.com/11160972/60361342-3b686e80-99de-11e9-849f-044c70465876.jpg)
(screenshot is wrongly scaled, because wine virtual desktop for some reason does not work properly with Vulkan in wine master).

**Comment by Cat-Lady** [comment]
Thats awesome news! I hope that it goes into master soon :)

**Comment by Cat-Lady** [comment]
As expected, in 0.13f, Warband and other games on its engine start properly to the main menu. World 3D map can be entered, albeit, with glitches (for example, in case of Viking's Conquest, terrain is half-transparent - you can see "submerged" part of models, in terrain, like base blocks of cities.

Entering battle crashes on all variants (both vanilla Warband and any specific modules I've tested - "viking's Conquest", "Caribbean: Blood and Gold").

**Comment by Cat-Lady** [comment]
As of version 0.20, 3D map doesn't show any glitches anymore (no more half-transparent terrain or full brightness). Entering battle mode freezes game (not crashes). Tested to be the case on all modules I've tested (vanilla Warband, "Viking's Conquest", "Caribbean: Blood and Gold").

Strange thing I've noticed - conversations (which are rendering characters like in battle and some terrain behind them) are working fine, with properly rendered stuff. No idea why battles still crash.

"Caribbean: Blood and Gold", that was able to start up to main menu and 3D map in 0.13f, now freezes upon initial load, just after changing cursor to "cutlass" (the game's one) on current version.

**Comment by money123451** [comment]
the game is still working fine its just skipping rendering move the game out of the center of the screen it spawned on or to a 2nd screen use a controller and battles work fine its just when the cursor (which is being moved to the middle of the screen) is also on top of the window it just dose not draw anything with d9vk don't have a clue why (might have something to do with not rendering the cursor and skipping everything else?) this game is very weird.

**Comment by money123451** [comment]
[this](https://www.taleworlds.com/en/Games/Warband/Download) is where you can get the latest version of the game demo.

**Comment by misyltoad** [comment]
![image](https://user-images.githubusercontent.com/21316711/74090943-b849e380-4aa9-11ea-92cc-c61c1711b907.png)

Seems to work fine here...

**Comment by Cat-Lady** [comment]
Still freezes in 3d battles as described in my previous comments, on 1.5.4. Attached are logs.
[bg_caribbean_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/4176427/bg_caribbean_d3d9.log)

Additionally, the game itself reports following errors in its own log (rgl_log.txt), which might be or not be relevant:

```
rgl_post_warning_line: Unable to get technique with name watermap_stratmap_high 
rgl_post_warning_line: Unable to get technique with name oim_standart_skin_bump_nospecmap_high 
rgl_post_warning_line: Unable to get technique with name oim_standart_flag_skin_bump_nospecmap 
rgl_post_warning_line: Unable to get technique with name watermap_no_anim 
rgl_post_warning_line: Unable to get technique with name blend_at_camera

```

Apart from that, where the game does work (menus, world map), textures are "corrupted" (blurry, pixelated), transparency doesn't seem to work properly, etc. Examples (be sure to check full image size):

D9VK:
![mb10](https://user-images.githubusercontent.com/6075406/74095584-68900a00-4af3-11ea-8084-eb3bac7ffa2c.jpg)

WineD3D:
![mb3](https://user-images.githubusercontent.com/6075406/74095589-747bcc00-4af3-11ea-91d4-7566112cf2bc.jpg)

D9VK:
![mb1](https://user-images.githubusercontent.com/6075406/74095593-7d6c9d80-4af3-11ea-8492-f56273c549c2.jpg)

WineD3D:
![mb5](https://user-images.githubusercontent.com/6075406/74095599-8e1d1380-4af3-11ea-83c3-e1bc0fa2f64b.jpg)

D9VK:
![mb2](https://user-images.githubusercontent.com/6075406/74095605-95dcb800-4af3-11ea-9c6e-48b6b69237c2.jpg)

WineD3D:
![mb4](https://user-images.githubusercontent.com/6075406/74095608-9c6b2f80-4af3-11ea-9170-640681911471.jpg)


I hope it helps to narrow down the issue.

**Comment by Cat-Lady** [comment]
Supplement:
I'm experiencing same graphical  glitches and 3d-battle mode freezes in native warband/warband demo. I'm getting the freezes even when trying to enter the tutorial.

**Comment by Cat-Lady** [comment]
As reported by @Riesi, the game freezes only when the mouse is moved - suggesting it is not D9VK/DXVK issue. Hoever, it keeps working fine with wined3d.

Apart from the very strange freeze, the highly degraded texture's resolution issue stands - as presented in the screenshots. As mentioned, I'm getting the degraded visuals issue on other games, too (for example: "Sid Meier's Pirates!")

**Comment by Cat-Lady** [comment]
I'm very glad to report that the game *both* stopped to crash when mouse is moved, *and* most corrupted graphics issues are gone - with the version 1.5.5.

I'm saying "most", cause - while the examples from main menu (sky) and in-game are occurring with "pixelated" graphics no more, strangely, the menu example (with strange transparency:
https://user-images.githubusercontent.com/6075406/74095593-7d6c9d80-4af3-11ea-8492-f56273c549c2.jpg

...is still the case.

Hoever, at this point it is only very minor nuisance, and the game is 100% perfectly and comfortably playable, now. Thank you!

PS.
It applies to all warband titles I'm aware of (including "Caribbean: Blood and Gold" and "Viking's Conquests").

**Comment by misyltoad** [comment]
There is a separate issue on the tracker for the transparency so I am going to close this now.
