### ISSUE TITLE
Change README.md

### ISSUE THREAD

**Issue by BlackDragonDv** [Joshua-Ashton/d9vk#11]
README.md is still from DXVK so maybe it should change to prevent confusion?

**Comment by TedsterTech** [comment]
Give me a few hours and I'll have something more useful written up

**Comment by doublez13** [comment]
Isn't the unofficial plan to to have this work merged back into DXVK?

**Comment by Joshua-Ashton** [comment]
> 
> 
> Isn't the unofficial plan to to have this work merged back into DXVK?

Yes.
