### ISSUE TITLE
ANNO 1404: Crash when starting game if both Atmospheric scattering and Normal mapping are on

### ISSUE THREAD

**Issue by MegWATTT** [Joshua-Ashton/d9vk#110]
When these options are both on, the game will crash when starting a new game or loading a save. This was tested on both Wine and Windows, and crash at the same moment.
This issue can't be reproduced with apitrace: the d3d9 can be replayed fine with D9VK. 
The following error is printed after the crash
`terminate called after throwing an instance of 'std::out_of_range'
  what():  array::at: __n (which is 256) >= _Nm (which is 256)`

### Software information
ANNO 1404 Venice, atmospheric scattering and normal mapping on

### System information
- GPU: AMD RX 570
- Driver: RADV / mesa 19.2-git
- Wine version: 4.8 Staging
- D9VK version: c8fb2d569675cd7ef37712b0b2d4efe53db752c6 

### Log files
[Addon_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3185162/Addon_d3d9.log)

**Comment by Joshua-Ashton** [comment]
Hi! I don't own this game sadly.

Would you be able to try attaching a debugger to the game and finding what file and line its crashing on?

**Comment by MegWATTT** [comment]
Do I need something specific to produce a debug build? I've used
`meson --cross-file build-win32.txt --buildtype debug --prefix /data/d9vk-debug build.w32` 
But I always end up with a link error:
`[246/247] Linking target src/d3d9/d3d9.dll.
FAILED: src/d3d9/d3d9.dll 
i686-w64-mingw32-g++  -o src/d3d9/d3d9.dll 'src/d3d9/ecc23b3@@d3d9@sha/d3d9_main.cpp.obj' 'src/d3d9/ecc23b3@@d3d9@sha/d3d9_interface.cpp.obj' 'src/d3d9/ecc23b3@@d3d9@sha/d3d9_monitor.cpp.obj' 'src/d3d9/ecc23b3@@d3d9@sha/d3d9_caps.cpp.obj' 'src/d3d9/ecc23b3@@d3d9@sha/d3d9_device.cpp.obj' 'src/d3d9/ecc23b3@@d3d9@sha/d3d9_cursor.cpp.obj' 'src/d3d9/ecc23b3@@d3d9@sha/d3d9_swapchain.cpp.obj' 'src/d3d9/ecc23b3@@d3d9@sha/d3d9_format.cpp.obj' 'src/d3d9/ecc23b3@@d3d9@sha/d3d9_common_texture.cpp.obj' 'src/d3d9/ecc23b3@@d3d9@sha/d3d9_texture.cpp.obj' 'src/d3d9/ecc23b3@@d3d9@sha/d3d9_surface.cpp.obj' 'src/d3d9/ecc23b3@@d3d9@sha/d3d9_volume.cpp.obj' 'src/d3d9/ecc23b3@@d3d9@sha/d3d9_common_buffer.cpp.obj' 'src/d3d9/ecc23b3@@d3d9@sha/d3d9_buffer.cpp.obj' 'src/d3d9/ecc23b3@@d3d9@sha/d3d9_shader.cpp.obj' 'src/d3d9/ecc23b3@@d3d9@sha/d3d9_vertex_declaration.cpp.obj' 'src/d3d9/ecc23b3@@d3d9@sha/d3d9_query.cpp.obj' 'src/d3d9/ecc23b3@@d3d9@sha/d3d9_multithread.cpp.obj' 'src/d3d9/ecc23b3@@d3d9@sha/d3d9_options.cpp.obj' 'src/d3d9/ecc23b3@@d3d9@sha/d3d9_stateblock.cpp.obj' 'src/d3d9/ecc23b3@@d3d9@sha/d3d9_sampler.cpp.obj' 'src/d3d9/ecc23b3@@d3d9@sha/d3d9_util.cpp.obj' 'src/d3d9/ecc23b3@@d3d9@sha/d3d9_initializer.cpp.obj' ../src/d3d9/d3d9.def -shared ../src/d3d9/d3d9.def -Wl,--start-group -Wl,--out-implib=src/d3d9/d3d9.dll.a src/dxso/libdxso.a src/dxvk/libdxvk.a src/util/libutil.a src/spirv/libspirv.a src/vulkan/libvkcommon.a /data/git/d9vk/lib32/vulkan-1.lib -pthread -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -Wl,--end-group -static -static-libgcc -static-libstdc++ -Wl,--add-stdcall-alias,--enable-stdcall-fixup 
/usr/bin/i686-w64-mingw32-ld : src/d3d9/ecc23b3@@d3d9@sha/d3d9_interface.cpp.obj : in function « ZN12IDirect3D9ExC2Ev » :
/usr/share/mingw-w64/include/d3d9.h:1590 : undefined reference to « vtable for IDirect3D9Ex »
/usr/bin/i686-w64-mingw32-ld : src/d3d9/ecc23b3@@d3d9@sha/d3d9_interface.cpp.obj:d3d9_interface.cpp:(.rdata$_ZTVN4dxvk9ComObjectIJ12IDirect3D9ExEEE[__ZTVN4dxvk9ComObjectIJ12IDirect3D9ExEEE]+0x54) : undefined reference to « IDirect3D9Ex::GetAdapterDisplayModeEx(unsigned int, D3DDISPLAYMODEEX*, D3DDISPLAYROTATION*)@16 »
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
`


I tried on Windows with Visual studio 17's debugger with a release build, but only displayed that on a dxvk-shader thread: `Exception thrown at 0x5404C091 (amdvlk32.dll) in Addon.exe: 0xC0000005: Access violation reading location 0x00000000.`
Didn't give any information about the call stack.

**Comment by neVERberleRfellerER** [comment]
Before you do the next steps, I reocommend to run the game in window, be it with game specific setting or wine virtual desktop as when debugger stops the game at crash, it might keep the game at top and you would bave to kill it from another virtual terminal, because you won't be able to see anything below the game.

Use winedbg:
```
winedbg game.exe
```
it will give you a winebg command prompt. Just write `c` and confirm with enter here and it will run the game. When it crashes, it will give you backtrace. Copy that here. Exit the winedbg with `q`.
Having debug build of D9VK would give better indication of where the problem starts.

**Comment by Joshua-Ashton** [comment]
Ah, can you validate shaders? There's a guide in the closed issue regarding spirv val errors on here.

**Comment by tsalwierz** [comment]
ANON 1404 is a black screen for me both with DX9 and DX10 or 11.

Not sure what logs you would need to debug this, let me know.

https://gist.github.com/tsalwierz/2dc697e25c8f50737613ed74696b60cf

**Comment by tsalwierz** [comment]
Yes, I'll try getting an apitrace from windows later today. It turns out the issue with DXVK is that the game requests D3D10 effects framework which isn't implemented yet. I don't believe this would affect D9VK though.

Wine debug log: https://gist.github.com/tsalwierz/f40e83ade411e0c384de92ee1a34a00f
d3d9: https://gist.github.com/tsalwierz/faf29d8e5e3723be83bfe3f10de8b17f

**Comment by MegWATTT** [comment]
Yes, Anno requires effects API for D3D10.
For D3D9, make sure you're using native d3dx9*.dll and d3dcompiler*.dll istead of tthose provided by Wine. If it's already the case, I don't know what could be wrong (It works fine for me on both radv and anv drivers)

As for spirv-val, I don't have any errors.
While using winedbg, the only thing printed is `Process of pid=0043 has terminated`. Note that the error printed on my first message doesn't show up.

**Comment by tsalwierz** [comment]
@MegWATTT 
Yup, got all of those set to native. I'm starting to consider that it may be a Nvidia issue, since it works for you on AMD.
I could try swapping my graphics card with a R9 290 to verify. I'll get the API trace later on today.

**Comment by MegWATTT** [comment]
I just learned about DXVK_LOG_LEVEL=debug. The last shader compiled before crash is "VS_ab3f426cf4cbc1f941c80ccab286d481d8f1d8b0", and isn't present when all problematic settings aren't set.
I only have .dxso* files, .spv ones aren't here:

[VS_ab3f426cf4cbc1f941c80ccab286d481d8f1d8b0.zip](https://github.com/Joshua-Ashton/d9vk/files/3198979/VS_ab3f426cf4cbc1f941c80ccab286d481d8f1d8b0.zip)

**Comment by Joshua-Ashton** [comment]
Can you please just provide an apitrace?

**Comment by tsalwierz** [comment]
@ Josuha-Ashton D3D9 trace:

https://drive.google.com/file/d/1os3I_J-ZvcHy5d42syiLRa9QQ8uv8TAw/view?usp=sharing

**Comment by kaktuspalme** [comment]
@Joshua-Ashton If you like that game, I'd donate it.

**Comment by Joshua-Ashton** [comment]
Is this still an issue?

**Comment by MegWATTT** [comment]
Yes, the initial issue is still here.
Apitrace [here](https://drive.google.com/open?id=1pTKHTTkQ8dgN4EiDT0JJDetdyU5tjJbc) but as I mentioned initially,the crash doesn't occur while replaying it.

**Comment by MegWATTT** [comment]
Looks like commit https://github.com/Joshua-Ashton/d9vk/commit/35918e2de0adb0e5ef6692f5d0007d7c9afdfd85 fixed this issue, thanks.
