### ISSUE TITLE
Skyrim: wrong underwater visuals

### ISSUE THREAD

**Issue by aufkrawall** [Joshua-Ashton/d9vk#111]
When diving in Skyrim, the underwater visuals are missing when being close to the surface, and sight gets completely blocked when diving deeper:

![Screenshot_20190518_094205](https://user-images.githubusercontent.com/13510490/57969531-2d9fe200-7978-11e9-9ef7-7b8d68ca7bc6.png)

![Screenshot_20190518_094251](https://user-images.githubusercontent.com/13510490/57969516-09dc9c00-7978-11e9-91f4-d7258c8e7beb.png)

### Software information
Latest Skyrim Steam version with maxed visuals

### System information
- GPU: RX 580
- Driver: Mesa 19.0.4
- Wine version: wine-staging-tkg 4.8-git
- D9VK version: 58669173

### Apitrace file(s)
For whatever reason, apitrace couldn't find its d3d9.dll, despite it supposedly being placed at the right location.

Edit: Somehow got one, but with d9vk active.

### Log files

[TESV_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3194060/TESV_d3d9.log)

**Comment by neVERberleRfellerER** [comment]
That first thing is in pretty much every game with water and it was like this even before 2000 and nothing has apparently changes since then. Fallout New Vegas, which is same engine, also suffers from this and it used to be this was even on Windows. I don't know if there is any meaningful solution to this (probably because underwater vision is done with fullscreen shader).
The second thing also seems to happen even on Windows:
https://steamcommunity.com/app/72850/discussions/0/45350791732820883/

**Comment by aufkrawall** [comment]
It supposedly looks correct with wined3d:
![Screenshot_20190518_153150](https://user-images.githubusercontent.com/13510490/57970510-3c8b9200-7982-11e9-8bad-7292f8b95c23.png)
![Screenshot_20190518_153209](https://user-images.githubusercontent.com/13510490/57970511-3c8b9200-7982-11e9-92d6-bbf41c4c921c.png)

**Comment by neVERberleRfellerER** [comment]
That's good to see and it also means that i have bad luck on water in games.
When you capture apitrace, use d3d9 set to "native than builtin" (`WINEDLLOVERRIDES="d3d9=n,b"`). It might be worth to try this variable: `TRACE_FILE='C:\some.trace'`, without it, I was never able to find my apitrace.

**Comment by aufkrawall** [comment]
Big thanks, that hint regarding Wine load order did the trick.
It seems just having apitrace d3d9.dll in the game's folder is enough then?
It btw. created the trace files in my user's desktop folder.

Here is an apitrace of wined3d:
https://drive.google.com/open?id=1ypUfJ5hKcvr7OTho2c8kLk5ovQ9c-KD1

**Comment by Joshua-Ashton** [comment]
The issue actually occurs for me on native d3d9. Not sure whether I should fix this or not.

**Comment by aufkrawall** [comment]
Ha, weird. It looks correct (like wined3d) here on Windows D3D9 with Polaris.
Disabling depth of field at least works as a.. workaround.

**Comment by Squall-Leonhart** [comment]
there is a mod on the nexus to fix this issue.

**Comment by aufkrawall** [comment]
They don't really fix it, but I'll guess it'll do.

**Comment by aufkrawall** [comment]
Yey, you've fixed it! Big thanks!
