### ISSUE TITLE
One Piece Pirate Warriors 3 fails to start

### ISSUE THREAD

**Issue by CartoonFan** [Joshua-Ashton/d9vk#112]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
One Piece Pirate Warriors 3 (Steam)

### System information
- GPU: GeForce GTX 960
- Driver: Nvidia 430.14.0
- Wine version: Wine TKG 4.8
- DXVK version: https://github.com/Joshua-Ashton/d9vk/commit/58669173dd95f00e800ce28f3caf03dd18512426

### Apitrace file(s)
https://drive.google.com/file/d/1vs87TTatDP9mpyo9eDxMmMpQQMZi91U_/view?usp=sharing

### Log files
- d3d9.log:
[oppw3_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3194712/oppw3_d3d9.log)

Game crashes with a gray screen almost instantly after loading. I pasted the errors from the terminal into the d3d9 log. Please let me know if I can improve this bug report.

EDIT: Replaced the trace file with a native Windows one.

**Comment by Joshua-Ashton** [comment]
> err:   D3D9: GetBackBuffer: iBackBuffer > 0 not supported


Yeah this'd cause it. I'll see what I can do to work around this

**Comment by Joshua-Ashton** [comment]
Can you try on the ``getbackbuffer-hack`` branch and see what affect this has?

**Comment by CartoonFan** [comment]
Alright, I'll try when I get a chance.

**Comment by CartoonFan** [comment]
So it doesn't crash immediately now, but it only displays a black screen. Audio plays and controller input is accepted. The console is spammed by apitrace's "warning: caught exception 0xc0000005", "flushing trace", and "D3D9: GetBackBuffer: iBackBuffer > 0 queried. Returning index 0."

Here is the updated trace and log, if you're curious.

[oppw3_d3d9_getbackbuffer_hack.log](https://github.com/Joshua-Ashton/d9vk/files/3200673/oppw3_d3d9_getbackbuffer_hack.log)


Trace:
https://drive.google.com/file/d/1v8bY7ZKWsfXwr6xZeL6ut2xH2rC43bzW/view?usp=sharing

**Comment by CartoonFan** [comment]
I changed the trace file in the description to one obtained from Windows, if that's helpful.

**Comment by CartoonFan** [comment]
The apitrace plays back well with the latest master, but I don't know if you want me to delay closing the bug until the backbuffer stuff gets merged in.

**Comment by CartoonFan** [comment]
So, I tried running the actual game, and it still seems to crash almost instantly. The apitrace still works well (albeit with the backbuffer warnings), so I'm not sure what's going on. I'm using a 32-bit prefix, just in case, but the same thing happened with the 64-bit prefix. Also, I haven't tried it with Proton recently, if that makes a difference.

d3d9.log:
[oppw3_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3440136/oppw3_d3d9.log)

trace:
https://drive.google.com/file/d/18oywHbJhIeCwhLwa7M1MXYRyKliC83z2/view?usp=sharing

**Comment by NerosTie** [comment]
> Also, I haven't tried it with Proton recently, if that makes a difference.

There is a bug with Proton 4.11: https://www.protondb.com/app/331600  
If you want to try, use 4.2.

On my side, tested with #793 and the issue is still the same.

**Comment by CartoonFan** [comment]
@NerosTie Good to know. I usually compile proton-tkg, but sometimes something goes wrong and I have to use an official version, so it's helpful knowing which ones work and which don't.

**Comment by misyltoad** [comment]
This works now, if you have any issues still feel free to re-open.

**Comment by CartoonFan** [comment]
Seems good to me too. Thanks!
