### ISSUE TITLE
Euro Truck Simulator 2: 3D rendering issue

### ISSUE THREAD

**Issue by kakurasan** [Joshua-Ashton/d9vk#113]
Broken rendering when D9VK is used (even when graphic setting is low). See screenshots.

wined3d:
![wined3d](https://user-images.githubusercontent.com/10556453/57977428-6c46a280-7a33-11e9-96c8-c38cc88107d6.png)

D9VK 5866917:
![D9VK](https://user-images.githubusercontent.com/10556453/57977427-6c46a280-7a33-11e9-8550-458ebda928a7.png)

### Software information
Euro Truck Simulator 2 (Demo version available from eurotrucksimulator2.com)

### System information
- GPU: Intel HD Graphics 510
- Driver: Mesa 19.1.0-rc2
- Wine version: 4.0
- D9VK version: 5866917

### Apitrace file(s)
- [eurotrucks2.trace.xz (233M, 1280x720 Windowed)](https://gitlab.com/kakurasan/github-attachments/raw/master/d9vk/eurotrucks2.trace.xz)

### Log files
- [eurotrucks2_d3d9.log.xz.zip](https://github.com/Joshua-Ashton/d9vk/files/3194752/eurotrucks2_d3d9.log.xz.zip)

**Comment by tsalwierz** [comment]
I'm unable to test this as the demo constantly crashes back to desktop for me. I've checked winehq and the game has a platinum rating, so the demo is probably very outdated or something.

**Comment by kakurasan** [comment]
@tsalwierz What wine version are you using? I tested with `EuroTruckSimulator2_1_34_0_34_setup.exe` (Press "Run in Demo mode") and it works fine. Does it crash only when D9VK is used?

**Comment by tsalwierz** [comment]
@kakurasan I was using the steam demo. I've since recreated my wine prefix so I'll give this another shot later on today.

**Comment by kakurasan** [comment]
This was recently fixed (It works fine as of 74f8922).
![ets2-d3d9-d9vk-74f8922](https://user-images.githubusercontent.com/10556453/58422235-0611ed80-80cd-11e9-9640-a4ce0a066125.png)
Thank you Joshua! 🐸
