### ISSUE TITLE
NFS Hot Pursuit black screen crash

### ISSUE THREAD

**Issue by Bednar87** [Joshua-Ashton/d9vk#114]
I can get into the main menu just fine but if I try to start the race, all I get is a black screen which results in a crash. Using d9vk 58669173 (https://git.froggi.es/joshua/d9vk/-/jobs/456/artifacts/download)

NFS11_d3d9.log

> info:  Game: NFS11.exe
info:  DXVK: v1.2
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD RADV VEGA10 (LLVM 8.0.0):
info:    Driver: 19.0.4
info:    Vulkan: 1.1.90
info:    Memory Heap[0]: 
info:      Size: 7920 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[2]: Property Flags = 0x7
info:    Memory Heap[2]: 
info:      Size: 8176 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:  Process set as DPI aware
info:  Enabled device extensions:
info:    VK_EXT_conditional_rendering
info:    VK_EXT_memory_priority
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  DXVK: Read 80 valid state cache entries
info:  DXVK: Using 2 compiler threads
warn:  D3D9: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  D3D9DeviceEx::ResetEx:
  Requested Presentation Parameters
    - Width:              1920
    - Height:             1200
    - Format:             A8R8G8B8
    - Auto Depth Stencil: false
    - Windowed:           false
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 9
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 16
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 37
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 38
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 60
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 136
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 137
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 141
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 142
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 145
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 146
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 154
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 155
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 158
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 161
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 166
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 172
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 173
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 178
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 179
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 182
warn:  D3D9DeviceEx::SetTextureStageState: Stub
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
  Buffer size:  1920x1200
  Image count:  2
info:  D3D9: Setting display mode: 1920x1200@60
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_FIFO_KHR
  Buffer size:  1920x1200
  Image count:  3
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_FIFO_KHR
  Buffer size:  1920x1200
  Image count:  3

NFS11_dxgi.log

>info:  Game: NFS11.exe
info:  DXVK: v1.2
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD RADV VEGA10 (LLVM 8.0.0):
info:    Driver: 19.0.4
info:    Vulkan: 1.1.90
info:    Memory Heap[0]: 
info:      Size: 7920 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[2]: Property Flags = 0x7
info:    Memory Heap[2]: 
info:      Size: 8176 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe

SYSTEM info:

>Computer Information:
    Manufacturer:  The Wine Project
    Model:  Wine
    No Touch Input Detected

>Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:         Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3800 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

>Operating System Version:
    Windows 7 (64 bit)
    Wine Version: wine-4.8 (Staging)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

>Video Card:
    Driver:  AMD RADV VEGA10 (LLVM 8.0.0)
    DirectX Driver Name:  aticfx32.dll
    Driver Version:  1.0
    DirectX Driver Version:  0.0.1216.4
    Driver Date: 1 1 2017
    OpenGL Version: 4.5
    Desktop Color Depth: 32 bits per pixel
    DirectX Card: AMD RADV VEGA10 (LLVM 8.0.0)
    VendorID:  0x1002
    DeviceID:  0x687f
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    No SLI or Crossfire Detected
    Primary Display Resolution:  1920 x 1200
    Desktop Resolution: 1920 x 1200
    Primary Display Size: 20.00" x 12.52" (23.58" diag)
                                            50.8cm x 31.8cm (59.9cm diag)
    Primary Bus Type Not Detected
    Primary VRAM: -1024 MB
    Supported MSAA Modes:  2x 4x 6x 8x 

>Sound card:
    Audio device: Pulseaudio

>Memory:
    RAM:  15998 Mb

>Miscellaneous:
    UI Language:  English
    Media Type:  Undetermined
    Total Hard Disk Space Available:  11539932 Mb
    Largest Free Hard Disk Block:  950333 Mb
    OS Install Date: May 08 2010
    Game Controller: None detected
    VR Headset: None detected

**Comment by NerosTie** [comment]
On my side, I can play the game (with d9vk 0.11) but I have an other issue. Cars are darker that it should be. Take a white car and it will be dark. It likes the light has no effect. But everything else is perfect.

**Comment by massatt212** [comment]
same problem with darksiders 2 death edition
and Ultimate marvel vs capcom 3 missing pixel on AMDVLK and windows AMD Driver

**Comment by ivan89el** [comment]
Appeared the reflection on the cars.

**Comment by NerosTie** [comment]
Just tested with the last git version, now the cars are not dark anymore but… the game is not in fullscreen anymore.

**Comment by NerosTie** [comment]
Everything looks good now. I think the issue can be closed.
Tested with #646.

**Comment by Bednar87** [comment]
agreed. works perfect now.
