### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by oliverklee** [Joshua-Ashton/d9vk#115]
If I see this correctly, the README still is the same as the DXVK README, which includes this paragraph:

> A Vulkan-based translation layer for Direct3D 10/11 which allows running 3D applications on Linux using Wine.

Instead, the README should make it clear that this project is about Direct3D 9 and not 10/11.

**Comment by Joshua-Ashton** [comment]
The README in release branches and for the releases themselves is updated.

I don't keep anything that shouldn't be merged into DXVK if that were to happen in the master branch.

**Comment by oliverklee** [comment]
Ah, makes sense. (I still find this confusing, but understand the rationale.)

Maybe update the GitHub repository description to explain this? Then this won't block any merging.
