### ISSUE TITLE
Half-life 2 is a black screen

### ISSUE THREAD

**Issue by tsalwierz** [Joshua-Ashton/d9vk#116]
https://i.imgur.com/Zg0PlmF.png

Commit c912e89 turns half-life 2 into a black screen.

5866917 is fully functional.

**Comment by Joshua-Ashton** [comment]
Should be fixed by https://github.com/Joshua-Ashton/d9vk/commit/e576a7519767387707a5684b6f31671e1e0e3032

**Comment by tsalwierz** [comment]
Yup, fixed. Thx!
