### ISSUE TITLE
Guild-Wars 2 with arcdps doesn't show.

### ISSUE THREAD

**Issue by DxCx** [Joshua-Ashton/d9vk#117]
Hey @Joshua-Ashton 

Arc-dps is a layout for GW2.
It is loaded as d3d9.dll hook itself, and then calls the system's d3d9.dll (d9vk in my case)
when i use it, i can confirm d9vk still works as expected (HUD shows), and arcdps logs shows that it is loaded to memory as well. but the added ui is missing.

I've created API trace file to capture it (See below).
and also analyzed it myself. (i dont have experiance at all to be honest, just dig into the qapitrace UI)
Anyhow, at frame (715) i'm opening extra dialogs,
and when i looked into the calls, i saw there are added `IDirect3DDevice9::SetScissorRect` calls.
so, i am -assuming- arcdps is using ScissorRect to dispaly the ui or doing it as well as part of it. (I am not familiar with d9 tbh, reading abit online shows that the actual draw is probably the `IDirect3DDevice9::DrawIndexedPrimitive" right after, but those i've found alot on the capture i made without arcdps loaded.

Anyhow, looking into SetScissorRect code, i've seen some recorder thingy that might disable the actual call.. wanted to hear your opinion about this (I am not expecting you to fix it, i know you probably have bugs with higher importance, but i am trying to fix it myself or at least do 90% of the work for you)

so, how do you think i should tackle it next?

PS: i've Also tried to replay the trace with d9vk as d3d9 but that failed,
how can i use the API trace to debug d9vk?

### information & Logs
- DXVK version: d9vk-58669173
- Log: [GW2-64_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3195611/GW2-64_d3d9.log)
- APITrace with arcdps: https://drive.google.com/open?id=1CuR9dTW1JCSlr7in3gn-DP9NQIrlLSk_ 
- APITrace without arcdps: https://drive.google.com/open?id=1crCsO5IKPhBruZPxeUSq7G72DLEApTvU

**Comment by Joshua-Ashton** [comment]
ARCDPS renders with fixed function which is the issue here.

Same as issue #60 
Which is on my todo list, but is a big task.

**Comment by Joshua-Ashton** [comment]
Not like you can even use the one for d912pxy either because that idiot decided to extend d3d9 to solve something that could be solved by binding a couple of very simple vertex and fragment shaders to do colorwrite passthru. :V

You can alternatively nag the ARCDPS devs to release their code and I could probably write a workaround in a few minutes.

**Comment by Joshua-Ashton** [comment]
If you do nag them and they don't want to release it, just tell them to stop using fixed func and use a couple of color passthru shaders.

(and also stop using state blocks with ALL because that's slow, just track that state yourself, it'd be much faster)

**Comment by DxCx** [comment]
Awsome thanks alot!

Do you need me to keep the apitrace on the drive for future ref?
Or you can run gw2 yourself? :)

**Comment by Joshua-Ashton** [comment]
There's nothing you could really do to help. Just wait until I get around to implementing it.

Your best bet for a solution right now would be to nag the devs of arcdps for a workaround.

**Comment by Joshua-Ashton** [comment]
I've nagged the ArcDPS dev about it, whether or not anything will come of that I have no idea. If not then you'll just have to wait til I implement it I guess.

**Comment by DxCx** [comment]
yeah so he responded me so:
```
i do ui via imgui, originally https://github.com/ocornut/imgui/tree/15d7f20d4fe17d20659878d9e827e78351853cff with p912pxy's mod of https://github.com/megai2/d912pxy/blob/master/thirdparty/imgui/d912pxy_impl/imgui_impl_dx9.cpp. basically a scrub for everything that happens in dx and drawing beyond that :p
```

**Comment by DxCx** [comment]
And this is the renderer code:
https://github.com/ocornut/imgui/blob/d88121ff5b90013647d1b27ee7d5012f1d85a452/examples/imgui_impl_dx9.cpp

(Showing me that the calls i suspected to be related to arcdps are indeed those - cool :))

**Comment by DxCx** [comment]
@Joshua-Ashton can we hack something through for imgui until fixed functions are implemented?
I don't mind implement it myself with abit of ypur guidance :)

**Comment by Joshua-Ashton** [comment]
Imgui is very simple rendering-wise. You should just need to do a color passhtru shader for PS and some very minimal transforms in VS. You can pass your matrices/whatever through to the VS using SetVertexShaderConstantF. Then bind these shaders before drawing and you should be set.

**Comment by Matthewx00** [comment]
Does anyone know if constant functions are implemented? Or are there any other [Guild Wars 2 Addons](https://green.wikia.org/wiki/User_blog:Snf98/Guild_Wars_2_Addons_-_Which_Ones_Should_You_Get%3F) that work similarly?

**Comment by gianlyx** [comment]
Hello guys any news about this? I would like to use arcdps along with dxvk.

**Comment by CartoonFan** [comment]
Have you already tried using the version at  https://github.com/doitsujin/dxvk? It's where d9vk development is nowadays.
