### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by tsalwierz** [Joshua-Ashton/d9vk#118]
Every commit past e576a7519767387707a5684b6f31671e1e0e3032 have build errors.

I'm sure you're aware of this already, but if not now you are :)

Happy coding!

**Comment by K0bin** [comment]
Maybe try also posting the build error...

**Comment by tsalwierz** [comment]
1e47e6912c37c83438b7bb7a9c520ba88e9dede0 build info: https://gist.github.com/tsalwierz/c33610bc31eada00d1848c01a449ae2d

**Comment by tsalwierz** [comment]
Issue is fixed as of 35a9423648153ecb08e195e5f0c400aa4f4ddc97, closing.
