### ISSUE TITLE
Guild Wars 2 sun reders as square

### ISSUE THREAD

**Issue by logan001** [Joshua-Ashton/d9vk#121]
The sun is render as a square instead of circle
this is the w10 logo with d9vk :)
![gw015](https://user-images.githubusercontent.com/6472378/58044235-f1bb7700-7b47-11e9-9846-565dd583de17.jpg)
and this is wine only
![gw002](https://user-images.githubusercontent.com/6472378/58044290-144d9000-7b48-11e9-8447-9b221f6ed6ca.jpg)

### System information
- GPU: GTX 970
- Driver: 418.52.05
- Wine version: 4.8 Staging without d9vk and 4.6 TKG (lutris) for d9vk 
- DXVK version: 35a9423648153ecb08e195e5f0c400aa4f4ddc97

### Apitrace file(s)
[Here](https://drive.google.com/open?id=1eNWUGiTYxXcUBeGK1VicgUaCKj_H0XRW)

### Log files
[Gw2-64_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3199338/Gw2-64_d3d9.log)
- dxgi.log: none

Edit: this issue is not recent. it has been around since d9vk started to work with GW2

**Comment by Jrugia** [comment]
I call this the 'Minecraft Sun', probably the very last remaining GW2 issue after yesterday's mouse fix.

**Comment by Espionage724** [comment]
On https://github.com/Joshua-Ashton/d9vk/commit/bee2c9a3c1abeebf37fa16b5b6d29e7718d3a70b, my sun seems to render normally in the same area (RADV on RX 580)

![Screenshot from 2019-05-21 18-44-12](https://user-images.githubusercontent.com/6378956/58135499-ca70b280-7bf8-11e9-9391-b781a3bfc734.png)

**Comment by logan001** [comment]
strange the issue is still there for me with nvidia.

**Comment by Joshua-Ashton** [comment]
Is this fixed by 86736ef0a3f8ede52256faba8cb37ae90550bc35 ?

**Comment by logan001** [comment]
nope. it's still present

**Comment by mylucky2018** [comment]
I don't know if there is a square sun before.
![gw2 gw2](https://user-images.githubusercontent.com/41288775/58208969-97254500-7d18-11e9-901b-e27e2a657836.png)

**Comment by Jrugia** [comment]
Since it hasn't been mentioned yet - The squared sun can only be seen with the Postprocessing set to 'High'.  I noticed in some areas it does render fine but mostly it's a square.

**Comment by logan001** [comment]
> I don't know if there is a square sun before.
> ![gw2 gw2](https://user-images.githubusercontent.com/41288775/58208969-97254500-7d18-11e9-901b-e27e2a657836.png)
the game also has day/night cycle. and some maps are cloudy all day. its normal to have no sun on it.
but sometime the sun can be very huge. like the one in dragon stand final boss.

**Comment by garpu** [comment]
I was out in Dragonfall, and the sun was round.  I haven't been able to see the sun (too cloudy, or nighttime) elsewhere or in Bloodtide Coast where the above screenshot was taken.  I did notice it was round in Lion's Arch.  (Nvidia, d9vk 0.11)

**Comment by logan001** [comment]
@garpu as Jrugia said do you have postprocessing at max? I didn't know that this is cause the issue but in the scene above if i set it to none/low the sun disappear completely (and the image look darker/ugly)

**Comment by garpu** [comment]
I have postprocessing turned off.  My computer's kind of old.

**Comment by logan001** [comment]
now that explain it why you don't see it. you have almost no sun.

**Comment by Iglu47** [comment]
@logan001 why diff wine ver? I think trouble in wine

d9vk-0.11ver
![gw2-with-d9vk](https://user-images.githubusercontent.com/25866099/58332642-4f9bd780-7e44-11e9-8a7b-b2cabfe0e009.png)
![gw2-without-d9vk](https://user-images.githubusercontent.com/25866099/58332643-50346e00-7e44-11e9-95b5-48462c322c34.png)

**Comment by Jrugia** [comment]
I've tested the game under Intel HD (5005U) and the sun renders correctly on Mesa 19.0 - Running Xubuntu 19.04.

**Comment by Joshua-Ashton** [comment]
@jeffbolznv So essentially, this shader's discard gets ignored on NV for some reason. If I swap the order of the killstate controlled discard and the alpha-test spec. constant controlled discard, or I move around the setting of the oC register a bit, it all works fine, but in this exact combination which should be the same, it just gets omitted for some reason. This only seems to happen on NV, and not RADV/AMDVLK. There is always the possibility I am doing something wrong, but it doesn't seem to be caught by spirv-val and works fine on other vendors.

[FS_95a7bdd850fbff093ecb0f1ebf5ea68b6f3df886.dxso.zip](https://github.com/Joshua-Ashton/d9vk/files/3219930/FS_95a7bdd850fbff093ecb0f1ebf5ea68b6f3df886.dxso.zip)

**Comment by jeffbolznv** [comment]
Thanks, I am investigating this.

**Comment by jeffbolznv** [comment]
I've identified the bug, we will fix it soon.

**Comment by Joshua-Ashton** [comment]
:+1: Cool! Thank you for your time. :)

**Comment by jeffbolznv** [comment]
This should be fixed in the most recent beta drivers at https://developer.nvidia.com/vulkan-driver

**Comment by logan001** [comment]
yes its fixed.
