### ISSUE TITLE
Alan Wake - in-game TV image not showing "video"

### ISSUE THREAD

**Issue by roman-bronis** [Joshua-Ashton/d9vk#123]
TV image in game is not displayed (compared to Proton 4.2-4).
Proton 4.2-4
![20190521225528_1](https://user-images.githubusercontent.com/1164597/58192267-9fea2c80-7cc0-11e9-93a1-86d77ee8ff57.jpg)  
D9VK
![20190521225743_1](https://user-images.githubusercontent.com/1164597/58192273-a4164a00-7cc0-11e9-900c-0bd684ed9094.jpg)

In-game setttings:
![20190522184038_1](https://user-images.githubusercontent.com/1164597/58192548-43d3d800-7cc1-11e9-9761-d8f4561e3ac4.jpg)
![20190522184035_1](https://user-images.githubusercontent.com/1164597/58192550-47675f00-7cc1-11e9-87f7-13a53ce884b5.jpg)

### Software information
Alan Wake

### System information
- GPU: nVidia GTX 1060 6GB
- Driver: 430.14
- Wine version: Proton 4.2-4
- D9VK version: fairly latest - bee2c9a3c1abeebf37fa16b5b6d29e7718d3a70b from here https://git.froggi.es/joshua/d9vk/-/jobs

### Log files
Sorry, no logs. Let me know how to make them and I will try.

**Comment by K0bin** [comment]
https://github.com/ValveSoftware/Proton/wiki/Proton-FAQ#how-to-enable-proton-logs

(Turning on DXVK logs will also turn on D9VK logs)

Also, record an apitrace as this is impossible to debug without one.

**Comment by roman-bronis** [comment]
How to get the apitrace from Steam proton game? I tried but no success.

**Comment by TedsterTech** [comment]
Can you describe how you tried? 


---- On Fri, 24 May 2019 16:42:33 +0000 notifications@github.com wrote ----



How to get the apitrace from Steam proton game? I tried but no success.

**Comment by aufkrawall** [comment]
Could it be there is some general issue with videos inside games (bink?)?
E.g. the Skyrim intro video doesn't get rendered with d9vk, while it does with wined3d/gallium nine.

**Comment by roman-bronis** [comment]
> Can you describe how you tried?
1. downloaded MSVC apitrace
2. unpacked x86 stuff (exes + libs) into Alan Wake folder (where exe is)
3. changed launch command to: apitrace.exe trace AlanWake.exe

**Comment by roman-bronis** [comment]
> Could it be there is some general issue with videos inside games (bink?)?
> E.g. the Skyrim intro video doesn't get rendered with d9vk, while it does with wined3d/gallium nine.

Cut-scenes and intros work. The issue is image in game-play TV screens ( CRTs and even LCD :) )

**Comment by TedsterTech** [comment]
> > Can you describe how you tried?
> 
> 1. downloaded MSVC apitrace
> 2. unpacked x86 stuff (exes + libs) into Alan Wake folder (where exe is)
> 3. changed launch command to: apitrace.exe trace AlanWake.exe

in this case, the way you should apitrace is by downloading from here:
https://release.froggi.es/apitrace/

**Comment by NerosTie** [comment]
![Screenshot_20190925_120302](https://user-images.githubusercontent.com/4572452/65593180-435d8d80-df90-11e9-8627-1994d71e9ba9.png)

It looks like it's fixed. The issue can be closed, I think.
