### ISSUE TITLE
Deadlight corrupted/garbled image

### ISSUE THREAD

**Issue by LeJimster** [Joshua-Ashton/d9vk#124]
### Software information
Deadlight low,medium,high settings - result is the same.  Weird corruption that fills entire screen if select a lower resolution and appears as a band across screen when played @ 1440p.

This may be a AMD only issue, as there is a [video](https://www.youtube.com/watch?v=AGGOfXPsGP0&) of the game being tested on a GTX 1050 that doesn't exibit the same problem.

### System information
- GPU: RX Vega 56
- Driver: Mesa 19.2.0-devel (git-629806b55b) + LLVM 9.0.0 (RADV)
- Wine version: Proton 4.2-4
- D9VK version: b1ce57c4

### Screenshots
1920x1200:
![Deadlight_1920x1200](https://user-images.githubusercontent.com/35663469/58218083-8b785500-7cfd-11e9-8a9e-f046008fda14.jpg)
2560x1440:
![Deadlight_2560x1400](https://user-images.githubusercontent.com/35663469/58218089-916e3600-7cfd-11e9-9696-1e81bf58b824.jpg)

### Apitrace file(s)
- [Deadlight_trace](https://drive.google.com/open?id=1oAFXw4MKM0qntLUbkiUW1TdoOty_J1vn)

### Log files
- d3d9.log: [LOTDGame_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3209856/LOTDGame_d3d9.log)

**Comment by neVERberleRfellerER** [comment]
On POLARIS10 pattern is same with both RADV and AMDVLK (2019.Q2.4).

**Comment by LeJimster** [comment]
Excellent! Confirmed fixed in f9449b9
