### ISSUE TITLE
Guild Wars 1 - Invisible UI

### ISSUE THREAD

**Issue by TheDaftRick** [Joshua-Ashton/d9vk#125]
In Guild Wars 1 the UI does not show on screen. 
The mouse cursor will change appearance when hovering over the UI elements.
There are also many missing textures

### Software information
Guild Wars 1

### System information
- GPU: GT-1030
- Driver: 430.14
- Wine version: tkg-4.6
- D9VK version: 0.11 and Master b1ce57c4

### Apitrace file(s)
- https://ufile.io/5aw32kbw

### Log files
- d3d9.log:
[Gw_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3209924/Gw_d3d9.log)

**Comment by oyvindln** [comment]
Also, if you log in (you can even though the UI doesn't show), most stuff other than the terrain doesn't render.

**Comment by TheDaftRick** [comment]
Looks like the UI is completely working with the latest master. Thank you
