### ISSUE TITLE
Saints Row 2 HUD and menus invisible, also missing intro logos and pre-mission animations

### ISSUE THREAD

**Issue by CartoonFan** [Joshua-Ashton/d9vk#126]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Saints Row 2 (GOG)

### System information
- GPU: GeForce GTX 960
- Driver: Nvidia 430.14.0
- Wine version: 4.8 TKG
- DXVK version: https://github.com/Joshua-Ashton/d9vk/commit/b1ce57c42cde01d8c99a14cf7cac5e1da4819d5d

### Apitrace file(s)
https://drive.google.com/file/d/1htKNAiMh8J3_NLqIjLVR3SG4oOaxC6-u/view?usp=sharing

### Log files
d3d9.log:
[SR2_pc_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3210355/SR2_pc_d3d9.log)

The Saints Row 2 menus and HUD are invisible, and some graphics do not display (such as the Gamespy logo and the pre-mission animations). I couldn't really get a screenshot because the game grabs the mouse early on.

EDIT: I've replaced the apitrace with one from Windows.

**Comment by ivan89el** [comment]
Fixed

**Comment by CartoonFan** [comment]
The apitrace looks good to me, so I'll close this.
