### ISSUE TITLE
Beyond Good and Evil loads to usable black screen

### ISSUE THREAD

**Issue by CartoonFan** [Joshua-Ashton/d9vk#132]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Beyond Good and Evil (GOG)

### System information
- GPU: Nvidia GeForce GTX 960
- Driver: 430.14.0
- Wine version: 4.8-r18 TKG
- DXVK version: https://github.com/Joshua-Ashton/d9vk/commit/de80c192c4c1b218df531d383b0d6bda710edf49

### Apitrace file(s)
https://drive.google.com/file/d/1ztIVe0e7V9TXct7p0a-maOuHSEhPBBIt/view?usp=sharing

### Log files
- d3d9.log:
[BGE_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3219996/BGE_d3d9.log)

Game loads to black screen. Options are selectable and audio is functional. I did not try starting the game.

EDIT: Updated the trace file. It's now a proper Windows trace, hopefully.

**Comment by neVERberleRfellerER** [comment]
d3dretrace replays black screen even with wined3d for me.

**Comment by K0bin** [comment]
If the trace was created using D9VK, create another one using WineD3D or (preferably) Windows.

**Comment by CartoonFan** [comment]
Alright, I'll do that as soon as I can.

For those who are curious, I've been trying to:

1. Test if the game works normally
2. Test with D9VK, using the d9vk_master in winetricks
3. Make a trace using apitrace's wrapper dlls, using native or native,builtin

The third step is probably where it went wrong, I imagine.

**Comment by CartoonFan** [comment]
I got a trace file from Windows this time.

**Comment by CartoonFan** [comment]
Hopefully it's not too disappointing or bad, but I realized that the Windows trace was actually from a computer with different hardware. Is it better to get a trace from the same computer or from a computer with Windows?

**Comment by K0bin** [comment]
Should be fine.

**Comment by CartoonFan** [comment]
Sounds great, I should be able to update my other bugs with Windows traces, then. Thanks!

**Comment by CartoonFan** [comment]
The apitrace looks good to me with the latest master.
