### ISSUE TITLE
NFS Carbon black win screen

### ISSUE THREAD

**Issue by Kattus** [Joshua-Ashton/d9vk#133]
Upon winning a race in NFS: Carbon, the background blurs to focus on the text up front, but with d9vk this results in just a black background. 

![wine](https://too.lewd.se/5380b99686d4_2019-05-26_17-11-15.webp)
![d9vk](https://too.lewd.se/331cef4ed8e2_2019-05-26_17-43-45.webp)

### Software information
Need for Speed: Carbon v1.4, max settings, 1280x1024

### System information
- GPU: GeForce GTX 1080
- Driver: 430.14
- Wine version: 4.9 (Staging)
- D9VK version: master de80c192c4c1b218df531d383b0d6bda710edf49

### Apitrace file(s)
https://gist.github.com/Kattus/adfcd62a209cdd71db3691f0b69066d4

### Log files
- d3d9.log: https://gist.github.com/Kattus/dfcb735dc1908f92a78bdedd546abd30
- dxgi.log: isn't created

**Comment by Riesi** [comment]
Looks like its working with latest master! @Kattus please test it for yourself and close the bug, if you can confirm.
![winscreen with d9vk](https://user-images.githubusercontent.com/27691485/60525997-bfc53500-9cef-11e9-9aa7-3bb4ead2b499.png)

**Comment by Kattus** [comment]
I can confirm this bug is fixed, while testing I have found many other bugs, but I think most of them are the fault of Wine. (one being that it outputs to wrong monitor while setting the res to another monitor et cetera.. it's one hell of a mess)

![working](https://too.lewd.se/16ef75539163_2019-07-02_19-44-55.webp)
in any case it works.
