### ISSUE TITLE
DeadPool - No Cutscenes or Intro Videos

### ISSUE THREAD

**Issue by alligatorshoes** [Joshua-Ashton/d9vk#138]
### Software information
DeadPool - PC Steam version.

### System information
- GPU: nVidia GTX 1070
- Driver: 418.74
- Wine version: 4.8 and/or Proton 4.2.5
- DXVK version: 0.12

### Apitrace file(s)

With D9VK I get no visuals on .bik videos in game - but you can hear them playing in the background as the audio is still active. All I see is a black screen. With D9VK turned off and using raw Wine/Proton, the videos load correctly.

**Comment by K0bin** [comment]
It's impossible to debug this without an apitrace or at the very least logs.

**Comment by Joshua-Ashton** [comment]
They likely render using fixed function.

**Comment by alligatorshoes** [comment]
> It's impossible to debug this without an apitrace or at the very least logs.

A fair point. A debug log literally doesn't show any issues or problems I'm afraid. I can still provide it if interested? I'm trying to get an apitrace but so far I'm not having much luck. I don't have access to a Windows machine. If you could assist me generating an apitrace via Steam I'm more than happy to provide this. Apologies for the lack of information thus far.

> They likely render using fixed function.
Aha, and as I understand it this isn't implemented yet is it?

Thanks for the amazing work on d9vk by the way!

**Comment by Joshua-Ashton** [comment]
Does this work now?

**Comment by NerosTie** [comment]
Yes, everything is alright now. You can close this issue.

**Comment by alligatorshoes** [comment]
Just confirming (as OP) that this does appear to be resolved now in latest Proton using PROTON_USE_D9VK=1 flag. Thank you :D
