### ISSUE TITLE
Hard Reset freezing after first enemy kill

### ISSUE THREAD

**Issue by xpander69** [Joshua-Ashton/d9vk#139]
Freezes after killing first enemy robot. Does not crash with wined3d

dmesg output on freeze:
```
[372457.659026] NVRM: GPU at PCI:0000:0a:00: GPU-949f5cab-1c1d-7259-3fb5-1970dcc00c65
[372457.659029] NVRM: GPU Board Serial Number: 
[372457.659031] NVRM: Xid (PCI:0000:0a:00): 69, Class Error: ChId 003e, Class 0000902d, Offset 000008b8, Data fffff607, ErrorCode 00000004
```

### Software information
Hard Reset (non-redux), Low and high settings, 1440p

### System information
- GPU: GTX 1080Ti
- Driver:430.14 (also used 418.56 previously)
- Wine version: 4.6-4.8 including staging as well as proton 4.2
- D9VK version: multiple versions up until 0.12 release

### Apitrace file(s)
https://mega.nz/#!BLg3kajR!hHdtIRdpLfnMMKkq3eOEKgypP4A1ZAPI_vXa5vVmeC0

### Log files
- d3d9.log:
[hardreset_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3238025/hardreset_d3d9.log)

- dxgi.log: 
[hardreset_dxgi.log](https://github.com/Joshua-Ashton/d9vk/files/3238022/hardreset_dxgi.log)

**Comment by VortexAcherontic** [comment]
Also I noticed the same with The Deadly Tower of Monsters, and as Ashton noticed in that Showcase I made of that game, that also Hard Reset seems to be leaking a massive amount of samplers.

**Comment by K0bin** [comment]
I'm just gonna put this here so it doesn't get burried on Discord. Here's what CME found out:

gotta sleep soon, but the hard reset trace triggers some validation errors:
VUID-VkBufferImageCopy-bufferRowLength-00203(ERROR / SPEC): msgNum: 0 - vkCmdCopyBufferToImage(): pRegion[0] bufferRowLength (1) must be a multiple of the compressed image's texel width (4).. The Vulkan spec states: If the calling command's VkImage parameter is a compressed image, bufferRowLength must be a multiple of the compressed texel block width (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkBufferImageCopy-bufferRowLength-00203)

and
VUID-VkBufferImageCopy-bufferImageHeight-00204(ERROR / SPEC): msgNum: 0 - vkCmdCopyBufferToImage(): pRegion[0] bufferImageHeight (1) must be a multiple of the compressed image's texel height (4).. The Vulkan spec states: If the calling command's VkImage parameter is a compressed image, bufferImageHeight must be a multiple of the compressed texel block height (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkBufferImageCopy-bufferImageHeight-00204)

and
UNASSIGNED-CoreValidation-Shader-PointSizeMissing(ERROR / SPEC): msgNum: 0 - Pipeline topology is set to POINT_LIST, but PointSize is not written to in the shader corresponding to VK_SHADER_STAGE_VERTEX_BIT.

**Comment by NerosTie** [comment]
The game doesn't hang anymore after the first enemy killed. 🎉
The issue can be closed :)
