### ISSUE TITLE
Anarchy Online crashes on launch

### ISSUE THREAD

**Issue by magzu** [Joshua-Ashton/d9vk#14]
Hello, 
I have been attempting to get Anarchy Online (the new engine which uses dx9) to work with d9vk.
But it results in the game crashing right after clicking "play" and its about to take you ingame. 
It gives a game crash message and before that message pops up my gnome desktop becomes really sluggish, not sure why that is happening but could be cause d9vk is in the early stages.

Anyways I wanted to help out by putting this issue out there and get some idea what is missing if anything is missing.

### Software information
Anarchy Online New Engine

### System information
- GPU: Nvidia Geforce 1070 gtx
- Driver: 418.43
- Wine version: Wine 4.3-staging
- D9VK version: build is from today, is there a build number? 

### Apitrace file(s)
Apitrace from a Windows10 machine with Geforce 680:
[Apitrace.zip](https://github.com/Joshua-Ashton/d9vk/files/3069518/Apitrace.zip)
I were unable to do an apitrace with the game via Wine but hope this is fine. 

### Log files
[anarchyonline_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3069552/anarchyonline_d3d9.log)

Game also spits out this logfile:  [AnarchyCrashLog.txt](https://github.com/Joshua-Ashton/d9vk/files/3069554/AnarchyCrashLog.txt)
Not sure if it is to any use but posting anyways.

Thank you in advance also thanks for the great work with d9vk so far.

**Comment by ahmed-elsayed2017** [comment]
Does it crash when using Wine without D9VK?

**Comment by magzu** [comment]
It works fine without D9VK with Wine. 
I do notice some spam in the terminal output that might be worth pointing out. 
Here is the terminal output:
[winelog.txt](https://github.com/Joshua-Ashton/d9vk/files/3069596/winelog.txt)

**Comment by Joshua-Ashton** [comment]
Can you try adding a LargeAddressAware flag to the game executable and trying again?

Cheers.

**Comment by magzu** [comment]
With that flag the game seems to open but it does not render anything.
![ksnip_20190411-184111](https://user-images.githubusercontent.com/25708064/55975151-9e712180-5c89-11e9-8a84-139d696f4b99.png)

d3d9 logfile looks about the same as the original i posted.

**Comment by magzu** [comment]
With that flag the game seems to open but it does not render anything.
![ksnip_20190411-184111](https://user-images.githubusercontent.com/25708064/55975151-9e712180-5c89-11e9-8a84-139d696f4b99.png)

d3d9 logfile looks about the same as the original i posted.

**Comment by magzu** [comment]
Been following the development and just reporting in progress.
After 0.11 i saw that there were some memory fixes. i see this now makes Anarchy Online actually launch every time but it displays a black window (the same happens in windows as well) 
![image](https://user-images.githubusercontent.com/25708064/57587602-d0cfa200-7507-11e9-9a71-dcd4a0bcc4b8.png)

here is d9vk log file from linux
[anarchyonline_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3170545/anarchyonline_d3d9.log)

And here is a d9vk log file from windows 10
[anarchyonline_d3d9-windows.log](https://github.com/Joshua-Ashton/d9vk/files/3170547/anarchyonline_d3d9-windows.log)

**Comment by magzu** [comment]
So I tested Anarchy Online again with 0.13 and i can report that i got it to work. shader compililing was a bit slow right after logging in and hitting the character selection but just give it time and it will work.

![ksnip_20190709-215958](https://user-images.githubusercontent.com/25708064/60919874-21a91000-a297-11e9-8ec7-e7bff823d056.png)

d9vk log for linux with wine: 
[AO-d9vk-log-0-13-linux-wine.txt](https://github.com/Joshua-Ashton/d9vk/files/3374722/AO-d9vk-log-0-13-linux-wine.txt)



Performance is okay. I did notice on my windows machine that the game had a blue tint going.
Shown here:

![ksnip_20190709-221651](https://user-images.githubusercontent.com/25708064/60920037-82d0e380-a297-11e9-973b-d767f82d4b0c.png)

d9vk log for windows: 
[AO-d9vk-log-0-13-windows.txt](https://github.com/Joshua-Ashton/d9vk/files/3374721/AO-d9vk-log-0-13-windows.txt)

Good work so far im so happy to see it start working so quickly :D

**Comment by Joshua-Ashton** [comment]
Is that a rendering bug? Just looks like Time of Day to me :-/

**Comment by magzu** [comment]
> Is that a rendering bug? Just looks like Time of Day to me :-/

yeah its not supposed to look like that, this is how night looks like: 
![ksnip_20190709-222403](https://user-images.githubusercontent.com/25708064/60920452-831dae80-a298-11e9-8751-f96e9ea66c09.png)

Seems like the blue tint is missing most of the ingame lightning like sunshaft (moonshaft?) and lights from x y z light sources. also walking indoor has the same blue tint. 

Tested this with the proton 4-11 GE (the custom proton) and it gave the same result. not sure why its happening. I know this game is quite the rubberband of a solution (techwise) so could just be random. I will experiment a bit more on the windows side with fresh install of the game and different ingame settings.

**Comment by magzu** [comment]
Also worth mentioning my wine tests consists of:
64bit prefix with esync turned off
wine-staging 4.9 was tested (without lutris) and ge-protonified-4.10 (via lutris) on the same wine prefix

**Comment by magzu** [comment]
So i have been experimenting as i have gotten some other Anarchy Online gamers to test d9vk.
They told me that all they got was a black screen. and i figured out that the new engine for this game creates its own shader cache. 

When i have d9vk enabled it seems to struggle a bit with creating the games shader cache. But if i disable d9vk and just run through ingame with wined3d and then enable d9vk it works fine.
Could the dxvk shader cache cause some conflicting issues here? 

Here is a image with a incomplete shader cache of the game with d9vk enabled:
![ksnip_20190724-203442](https://user-images.githubusercontent.com/25708064/61819224-d83df080-ae52-11e9-878f-752eb8a69a9d.png)


Also regarding the blue tint, it seems like d3dcompiler_43 is the one causing it. removing that from the prefix seems to make things work.

**Comment by Joshua-Ashton** [comment]
Can anyone provide a proper trace/see if this is still an issue? The trace provided was an OpenGL trace.

**Comment by Joshua-Ashton** [comment]
Can anyone see if this is still an issue? Cheers

**Comment by magzu** [comment]
I have been testing it alot and it does work now so this issue can be closed
