### ISSUE TITLE
A Hat in Time Crashing when entering Level

### ISSUE THREAD

**Issue by nex86** [Joshua-Ashton/d9vk#140]
Problem is that the game crashes whenever I enter a bigger level.
I can start a new game without any issues, but one I enter Mafia Town or load a newer save that has more areas of the space ship unlocked, the game will crash.

### Software information
A Hat in Time. All settings on low.

### System information
- GPU: Intel HD 615
- Driver: 26.20.100.6709 (can't go higher without sacrificing custom resolutions)
- Wine version: - 
- DXVK version: 0.12

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log:
[HatinTimeGame_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3238991/HatinTimeGame_d3d9.log)

**Comment by K0bin** [comment]
Please rerun the game with Vulkan validation layers.

> 26.20.100.6709 (can't go higher without sacrificing custom resolutions)

Old drivers *could* cause this.

**Comment by Joshua-Ashton** [comment]
Your driver is the cause of this, it's out of date.

In addition, it's also Intel on Windows which is a bit crap, not gonna lie there.
