### ISSUE TITLE
The Deadly Tower of Monster: Sampler count

### ISSUE THREAD

**Issue by VortexAcherontic** [Joshua-Ashton/d9vk#141]
### Software information
The Deadly Tower of Monsters

### Issue
Joshua Ashton found out that the game is leaking samplers and requested me to open up an issue with an Apitrace below this video https://www.youtube.com/watch?v=IpivIuDs3bA

Honestly, I have no idea what this means but he wished to have an apitrace, so here am I :D

### System information
- GPU: NVidia GeForce GTX 1080
- Driver: 430.14
- Wine version: Proton 4.2-5
- DXVK version: 0.12

### Apitrace file(s)
https://drive.google.com/open?id=1dmMUym2u5feU_jnmTdG54LqayR001C6F

**Comment by K0bin** [comment]
What's the issue?

**Comment by VortexAcherontic** [comment]
@K0bin Oh sorry completely forgot abut it ^^"
I updated the initial comment to containing the necessary in formations :D

**Comment by VortexAcherontic** [comment]
Okay I manged to get the Trace, I was just blind not to find it even if it was there. Located inside the Proton Prefix. 'pfx/users/steamuser/Desktop' currently I'm compressing and uploading. I'll check back when am I done :)

**Comment by VortexAcherontic** [comment]
Apitrace file provided. Hope that helps you out :)

@Joshua-Ashton fyi.

**Comment by K0bin** [comment]
The issue is that the game changes the MipmapLodBias a lot.

For lookup D9VK just checks if those are perfectly equal (which isn't the best idea for floats).

**Comment by VortexAcherontic** [comment]
May I can ask what this Sampler count is and means?
What is it exactly counting?

**Comment by K0bin** [comment]
As an oversimplification: it controls how you read from a texture.
D3D9 allows you to controls these values directly while Vulkan forces you to create a new sampler. So this game changes these valus (MipBias in particular) very frequently and D9VK creates TONS of new samplers because it can't reuse the old ones.

**Comment by VortexAcherontic** [comment]
Ah okay, I get the point.

But if VK always requests a new Sampler is there anyway to, well "fix" this?
As you said it compares new textures with new ones and like you said it's float and I wonder how to achieve that very similar textures still recognized as the same. So would a possible fix to make the comparison less sharp?

I'm very curious because I'm only familiar with OpenGL and very interested in VK too but did not do anything in VK yet :D

**Comment by Joshua-Ashton** [comment]
This got fixed a while back.
