### ISSUE TITLE
Richard Burns Rally - no menus

### ISSUE THREAD

**Issue by tones111** [Joshua-Ashton/d9vk#142]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Richard Burns Rally

There is a menu that is supposed to overlay a background scene.  The background is rendered, but not the menu graphics.

### System information
- GPU: AMD Radeon RX580
- Driver: 19.0.5
- Wine version: 4.9
- DXVK version: d9vk-0.12

### Apitrace file(s)
When I tried to capture a trace I got

> warning ... dxgitrace.dll was never used: application probably does not use this API

### Log files
[RBR.log](https://github.com/Joshua-Ashton/d9vk/files/3243402/RBR.log)

**Comment by K0bin** [comment]
> warning ... dxgitrace.dll was never used: application probably does not use this API

The instructions are wrong. You have to put apitrace's d3d9.dll into the game folder, not the dxgi ones.

**Comment by K0bin** [comment]
> warning ... dxgitrace.dll was never used: application probably does not use this API

The instructions are wrong. You have to put apitrace's d3d9.dll into the game folder, not the dxgi ones.

From the logs it seems like it's using fixed function stuff which isnt supported at the moment.

**Comment by NerosTie** [comment]
The menus are fixed:

![Screenshot_20190825_180009](https://user-images.githubusercontent.com/4572452/63652572-416e9780-c762-11e9-8792-67e8c7ac3b59.png)

But there is an issue with the sky which is black:

with d9vk:
![Screenshot_20190825_160338](https://user-images.githubusercontent.com/4572452/63652583-577c5800-c762-11e9-939c-08ccb72c1ea2.png)

without d9vk:
![Screenshot_20190825_160431](https://user-images.githubusercontent.com/4572452/63652587-5e0acf80-c762-11e9-8b1d-12d487e1346e.png)
 I also noticed a very specific bug: with or without d9vk the guy has no cap with the Nvidia GPU, but if I use my Intel GPU, he has a cap…

The apitrace: 

https://mega.nz/#!eyZ2zYBZ!36rv6e9PMmlGSrNSwFPM_n2Fevp-U9-_FQ-MDIzJXCU

**Comment by Joshua-Ashton** [comment]
Looks fine here on the trace? Can you re-test on latest master?

**Comment by NerosTie** [comment]
The sky is still black.

**Comment by Joshua-Ashton** [comment]
Can you replay your trace?

**Comment by NerosTie** [comment]
Yes: 
![Screenshot_20190917_140250](https://user-images.githubusercontent.com/4572452/65040059-de80b280-d953-11e9-86b7-7efcc2bd03d3.png)

**Comment by Joshua-Ashton** [comment]
When I play your trace the sky works fine. Hmmm

**Comment by Joshua-Ashton** [comment]
![image](https://user-images.githubusercontent.com/21316711/65213836-a5555900-da9f-11e9-81d3-384251d4bffa.png)

![image](https://user-images.githubusercontent.com/21316711/65213859-b69e6580-da9f-11e9-99da-d67819ab99d3.png)

Only happens on Nvidia

**Comment by Joshua-Ashton** [comment]
No SPIRV-val errors

**Comment by Joshua-Ashton** [comment]
Nothing that jumps out at me in the validation layer output either. Just a lot of the standard stuff.

**Comment by Joshua-Ashton** [comment]
Validation layer output

[output.txt](https://github.com/Joshua-Ashton/d9vk/files/3629443/output.txt)

**Comment by Joshua-Ashton** [comment]
Recompiling the vertex shader that draws the sky fixes the issue. May be a driver bug.

**Comment by Joshua-Ashton** [comment]
[shader.zip](https://github.com/Joshua-Ashton/d9vk/files/3629462/shader.zip)

**Comment by Joshua-Ashton** [comment]
Contains original shaders, recompiled shaders and spirv-dises

[shader.zip](https://github.com/Joshua-Ashton/d9vk/files/3629491/shader.zip)

**Comment by CME42** [comment]
I can't repro this on nvidia with 435.19.03:
![Bildschirmfoto von 2019-09-19 13-29-16](https://user-images.githubusercontent.com/11275913/65240504-b626be80-dae1-11e9-82b7-c2bfeeecac18.png)

**Comment by NerosTie** [comment]
Now, I have weird black glitches on the ground:

https://imgur.com/i867wzX

**Comment by tones111** [comment]
When I run on AMD the textures (trees, etc) drop out after about 2 minutes into the first stage.

I'm still unable to get apitrace to run.  I'm assuming I need a 32-bit windows build to run in wine but apitrace only points at 64-bit versions here: https://people.freedesktop.org/~jrfonseca/apitrace/

Any suggestions on how to capture a trace?

**Comment by Joshua-Ashton** [comment]
There is a x86 folder in the apitrace download.

**Comment by jotomo** [comment]
> When I run on AMD the textures (trees, etc) drop out after about 2 minutes into the first stage.

That is a long-standing (and very annoying) bug that also occurs with vanilla wine: https://bugs.winehq.org/show_bug.cgi?id=11531 
(Starting a stage isn't needed, staying in the main menu for a couple of minutes also triggers this)

**Comment by NerosTie** [comment]
The glitches I was talking about in my previous comment are gone. (tested with #888)

**Comment by tones111** [comment]
Thanks for linking the wine bug.  I discovered where I was going wrong with apitrace and now have a log and trace that demonstrate the dropped textures problem.  Thanks for the help.

[log](https://github.com/Joshua-Ashton/d9vk/files/3688689/RichardBurnsRally_SSE_d3d9.log)
[trace](https://drive.google.com/open?id=16ZS2VDJx_0edL021DEAB2bNAvGw9MpBp)

**Comment by misyltoad** [comment]
This works now for whatever reason on 450.12 🤷‍♂ 

![image](https://user-images.githubusercontent.com/21316711/75011855-8c026f80-5478-11ea-9ed6-4668f84ef8de.png)
