### ISSUE TITLE
Prince of Persia (2008) crashes at new game start

### ISSUE THREAD

**Issue by CartoonFan** [Joshua-Ashton/d9vk#144]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Prince of Persia (2008) (GOG)

### System information
- GPU: Nvidia GeForce GTX 960
- Driver: 430.14.0
- Wine version: 4.9 TKG
- DXVK version: https://github.com/Joshua-Ashton/d9vk/commit/1057b2e586f711b401c83a4ee9f1e1213fca0dbf

### Apitrace file(s)
https://drive.google.com/file/d/1O2H5ZMBOKp7UN7DBbnq9maxqzP03EZxA/view?usp=sharing

### Log files
- d3d9.log:
[Prince of Persia_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3244606/Prince.of.Persia_d3d9.log)

Prince of Persia (2008) crashes at the loading screen after selecting a new game.

**Comment by SDN-Arkhen** [comment]
That's not d9vk fault. Try enable vsync to fix it.

**Comment by CartoonFan** [comment]
Vsync is enabled, but it still freezes with an error message on my system.
![Prince of Persia error message](https://user-images.githubusercontent.com/29664894/58764129-8a72cf00-8518-11e9-8c5a-f41466186cdb.png)

Perhaps I should change the title to "crashes" instead of "hangs"?

There's also this in the console:
wine: Unhandled page fault on write access to 0x0000f801 at address 0x450061 (thread 004f)

The address is always 0x450061, as well. Builtin seems to work fine, I tried it with the same settings and things seemed OK.

**Comment by dlshinobi** [comment]
You can give a shot for "4GB Patch". https://ntcore.com/?page_id=371
For me it helped with 32-bits games like Dragon's Dogma Dark Arisen (dx9), Titan Quest Anniversary (dx11) and etc.

**Comment by CartoonFan** [comment]
It didn't seem to work for me (although the program is now crashing at 0x730091 instead of 0x450061).

**Comment by SDN-Arkhen** [comment]
Ah, so it crash. I thought it was loading loop bug in that game.

Anyway, can you try d9vk version 0.11. I may have similar problems like this with other game.

**Comment by CartoonFan** [comment]
As far I as I can tell, it still freeze crashes with 0.11 through lutris.

**Comment by CartoonFan** [comment]
It looks like it's fixed now. Thanks, everyone!
