### ISSUE TITLE
Treasure Adventure Game crashes on execution

### ISSUE THREAD

**Issue by CartoonFan** [Joshua-Ashton/d9vk#146]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Treasure Adventure Game (GOG)

### System information
- GPU: Nvidia GeForce GTX 960
- Driver: 430.14.0
- Wine version: 4.9 TKG
- DXVK version: https://github.com/Joshua-Ashton/d9vk/commit/1057b2e586f711b401c83a4ee9f1e1213fca0dbf

### Apitrace file(s)
https://drive.google.com/file/d/1I6qP2rxIBQWXUuAtWy-vA1aP_d4ODr4g/view?usp=sharing

### Log files
- d3d9.log:
[treasure_adventure_game_1.0_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3244620/treasure_adventure_game_1.0_d3d9.log)

Treasure Adventure Game crashes at launch. It unfortunately crashes before a proper log can be made, so I copied the terminal output to the log file pasted here.

The game is freeware and is available here, in the download section: http://robitgames.com/treasure-adventure-game/

**Comment by CartoonFan** [comment]
It looks like the original crash is fixed, but now the game crashes on something new. The terminal output when it closes is:

> 0009:fixme:vulkan:X11DRV_vkCreateWin32SurfaceKHR Application requires child window rendering, which is not implemented yet!
> terminate called after throwing an instance of 'dxvk::DxvkError'
>wine: Assertion failed at address 0xf7f5e959 (thread 0009), starting debugger...

Any ideas?

**Comment by Joshua-Ashton** [comment]
Looks like a Wine bug.

**Comment by CartoonFan** [comment]
Hmm, OK. Do you think the dxvk error is also wine-related? It seems to be the most consistent thing that shows up when I run the program.

**Comment by CartoonFan** [comment]
Here's a d9vk trace and a recent d3d9 log, if it helps debug the problem:

https://drive.google.com/file/d/11v6BjBvQR87OGHTsFtCIwm2qMQdvyUy-/view?usp=sharing

[treasure_adventure_game_1.0_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3412196/treasure_adventure_game_1.0_d3d9.log)

**Comment by CartoonFan** [comment]
Also, good call earlier. I tried using the child rendering fix from [here](https://bugs.winehq.org/show_bug.cgi?id=45277) and it loaded a little bit farther before freezing at a black screen. Unfortunately, there's no log :disappointed:

**Comment by CartoonFan** [comment]
Even more success! The updated child rendering patch using XComposite now loads the game. There's still no log, but there's terminal output. The patch is now [available in Wine-TKG](https://github.com/Tk-Glitch/PKGBUILDS/commit/849444874e230918ddc0c5bdd6b7469fbc9c3439), so I'm not sure whether to wait or to close this bug.
