### ISSUE TITLE
SWAT 4 and its expansion have black screen for some logos and main menu

### ISSUE THREAD

**Issue by CartoonFan** [Joshua-Ashton/d9vk#147]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
SWAT 4 (GOG)
SWAT 4: The Stetchkov Syndicate (GOG)

### System information
- GPU: Nvidia GeForce GTX 960
- Driver: 430.14.0
- Wine version: 4.9 TKG
- DXVK version: https://github.com/Joshua-Ashton/d9vk/commit/1057b2e586f711b401c83a4ee9f1e1213fca0dbf

### Apitrace file(s)
SWAT 4:
https://drive.google.com/file/d/1rzHiM_zd2cicEiIrAjoZGiXlm2bnDxMm/view?usp=sharing
https://drive.google.com/file/d/1CkCBOL4j2J7F8AYIuHlHcoNYAVFb6F_A/view?usp=sharing

SWAT 4: The Stetchkov Syndicate:
https://drive.google.com/file/d/1RNspnHsAPa-aXaEWw3HNIhc8uFtCDRvh/view?usp=sharing
https://drive.google.com/file/d/1PL5fjiDGq5Zy1yLauUdHvPlekyRkc74m/view?usp=sharing
https://drive.google.com/file/d/1h-N3LBdGY4tckqoZFUrIUxDWaaRYVfYB/view?usp=sharing

### Log files
SWAT 4:
- d3d9.log:
[Swat4_d3d9.log.gz](https://github.com/Joshua-Ashton/d9vk/files/3244629/Swat4_d3d9.log.gz)

SWAT 4: The Stetchkov Syndicate:
- d3d9.log:
[Swat4X_d3d9.log.gz](https://github.com/Joshua-Ashton/d9vk/files/3244632/Swat4X_d3d9.log.gz)

Some of the logos and the main menu for both SWAT 4 and its expansion have a black screen. I put both games together here since I feel the problems are very similar. The log files for these games were really big and involved spamming "warn:  D3D9DeviceEx::SetLight: Stub" and "warn:  D3D9DeviceEx::LightEnable: Stub". Also, apitrace split its traces into multiple files, even on Windows.

**Comment by K0bin** [comment]
> the log files for these games were really big and involved spamming "warn: D3D9DeviceEx::SetLight: Stub" and "warn: D3D9DeviceEx::LightEnable: Stub".

This means it was trying to use the d3d9 fixed function pipeline which d9vk currently doesnt support at all.

**Comment by CartoonFan** [comment]
This looks like it's fixed.
