### ISSUE TITLE
[feature request] Output warning to log if game uses fixed function

### ISSUE THREAD

**Issue by axredneck** [Joshua-Ashton/d9vk#148]
so we could know why game doesn't work.

**Comment by K0bin** [comment]
Technically it already does that, you just have to know what to look for. There's also the issue that some games set fixed func state and never use that.

**Comment by jp7677** [comment]
@K0bin Would you mind explaining which log statements may refer to fixed function usage?

**Comment by K0bin** [comment]
For example:
- SetTransform
- MultiplyTransform
- SetMaterial
- SetLight
- LightEnable

**Comment by axredneck** [comment]
`warn:  D3D9DeviceEx::SetTransform: Stub`
So Stalker SC uses fixed function. Sad.
