### ISSUE TITLE
Some keys FFXIII doesn't appear when using d9vk

### ISSUE THREAD

**Issue by torbol** [Joshua-Ashton/d9vk#150]
Some keys doesn't appear when using d9vk

Without d9vk:
![Captura de pantalla de 2019-06-01 16-24-39](https://user-images.githubusercontent.com/45130968/58749747-0c67e700-848a-11e9-9948-42be1dce8cef.png)

Using d9vk:
![Captura de pantalla de 2019-06-01 16-24-54](https://user-images.githubusercontent.com/45130968/58749753-1558b880-848a-11e9-9d73-287a8e02c3ea.png)

Proton log:
[steam-292120.log](https://github.com/Joshua-Ashton/d9vk/files/3243842/steam-292120.log)

D9VK log:
[ffxiiiimg_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3243861/ffxiiiimg_d3d9.log)

_Originally posted by @torbol in https://github.com/Joshua-Ashton/d9vk/issues/103#issuecomment-497950385_

**Comment by Joshua-Ashton** [comment]
Please provide an apitrace so I can replicate the issue.

**Comment by Glog78** [comment]
https://i.imgur.com/fevY882.png

looks fine to me with current master.

**Comment by Joshua-Ashton** [comment]
Gonna close this then, feel free to re-open if the problem is still present.
