### ISSUE TITLE
World of Warcraft black screen

### ISSUE THREAD

**Issue by wodim** [Joshua-Ashton/d9vk#151]
### Software information
World of Warcraft

### System information
- GPU: AMD R9 290
- Driver: amdgpu
- Wine version: wine-staging 4.9 
- DXVK version: 0.12

### Log files
WoW_d3d9.log: http://dpaste.com/1N3QM9B.txt
WoW.trace: https://mega.nz/#!8c9XFQhY!30eIbsYK4jtPWrUBdJ0MVU_7a3NIeRhGZvb333CXu18

World of Warcraft shows a black screen with only the HUD if you enable it.

**Comment by DxCx** [comment]
Isnt wow dx12?

**Comment by wodim** [comment]
WoW 1.12

**Comment by axredneck** [comment]
> dxgitrace.dll was never used

Sadly bug report template is incorrect. You need to put apitrace's d3d9.dll near game's exe file and set d3d9 to native in winecfg.

**Comment by wodim** [comment]
Now I get different errors.

```
000b:fixme:winediag:start_process Wine Staging 4.9 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
apitrace: loaded into Z:\mnt\windows\Store\Juegos\World of Warcraft 1.12\WoW.exe
apitrace: loaded into Z:\mnt\windows\Store\Juegos\World of Warcraft 1.12\WoW.exe
apitrace: tracing to C:\users\wodim\Desktop\WoW.2.trace
warning: ignoring call to unavailable function Direct3DCreate9
apitrace: unloaded from Z:\mnt\windows\Store\Juegos\World of Warcraft 1.12\WoW.exe
apitrace: loaded into Z:\mnt\windows\Store\Juegos\World of Warcraft 1.12\WoW.exe
apitrace: tracing to C:\users\wodim\Desktop\WoW.3.trace
warning: ignoring call to unavailable function Direct3DCreate9
apitrace: unloaded from Z:\mnt\windows\Store\Juegos\World of Warcraft 1.12\WoW.exe
apitrace: warning: caught exception 0xc0000005
warning: Z:\home\wodim\Downloads\apitrace-8.0.20190414-win32\bin\..\lib\wrappers\dxgitrace.dll was never used: application probably does not use this API
002a:fixme:kernelbase:AppPolicyGetProcessTerminationMethod 0xfffffffa, 0x32fe44
0009:fixme:kernelbase:AppPolicyGetProcessTerminationMethod 0xfffffffa, 0x33fe44
```

**Comment by wodim** [comment]
By setting d3d9 as "builtin then native" I get a 28 MB file, but I still get the following warning:

>warning: Z:\home\wodim\Downloads\apitrace-8.0.20190414-win32\bin\..\lib\wrappers\dxgitrace.dll was never used: application probably does not use this API

Would that file be sufficient?

**Comment by axredneck** [comment]
> warning: Z:\home\wodim\Downloads\apitrace-8.0.20190414-win32\bin..\lib\wrappers\dxgitrace.dll was never used: application probably does not use this API

You should not apitrace dxgi, only d3d9.
@Joshua-Ashton, please add correct instructions how to apitrace for D9VK!

**Comment by axredneck** [comment]
That's how to apitrace for D9VK: https://tracehub.froggi.es/

**Comment by crborga** [comment]
I have the same issue with TBC but I was confused about how to run apitrace. I suspect the it's the same problem for Vanilla whatever it is.

**Comment by wodim** [comment]
I keep getting the same warning:

```
$ wine /home/wodim/Downloads/apitrace-8.0.20190414-win32/bin/apitrace.exe trace -a d3d9 WoW.exe
...
warning: Z:\home\wodim\Downloads\apitrace-8.0.20190414-win32\bin\..\lib\wrappers\d3d9.dll was never used: application probably does not use this API
```

But well, in any case, it looks like it's creating a useful trace, so I'm attaching it to the first post.

**Comment by axredneck** [comment]
> wine /home/wodim/Downloads/apitrace-8.0.20190414-win32/bin/apitrace.exe

You don't need apitrace.exe, you just need d3d9.dll from apitrace

**Comment by crborga** [comment]
I have a trace from TBC but unable to upload it right now. 

⁣Sent from BlueMail ​

**Comment by crborga** [comment]
Here are some traces I ran from Windows natively.
Vanilla Trace https://mega.nz/#!vtpGiKpI!kn8QbuuARjdgwORYiyrCc3GgAvu_L1VeAbDTBACWa5E
TBC Trace https://mega.nz/#!2h5GyAiA!Ef9C737YEY_XDQtKyAa2YKxubZ3_jfAwkAob9L3_t88

**Comment by Riesi** [comment]
@wodim the apitraces posted from crborga dont render black anymore. Please recheck your issue on latest master. Automated builds can be found here: https://git.froggi.es/joshua/d9vk/-/jobs

**Comment by wodim** [comment]
I’m currently on vacation so if any of you want to try on my behalf that would be cool. I’m sure tbc/wotlk clients exhibit (or exhibited) the same issues.

**Comment by Riesi** [comment]
Ok yeah #156 reported that the black screen is fixed for Burning Crusade, so I guess you can close this. :)

**Comment by wodim** [comment]
Well, now there's no black screen but the entire game looks like an acid trip. Everything at full brightness, and many textures fail to load. I don't know if it's a bug or it's supposed to look like this.

![2019-07-16-131527_1920x1200_scrot](https://user-images.githubusercontent.com/1001553/61290283-ccf02280-a7cb-11e9-874c-50d49f45a2e1.png)
