### ISSUE TITLE
World of Warcraft: The Burning Crusade Black Screen

### ISSUE THREAD

**Issue by crborga** [Joshua-Ashton/d9vk#156]
Loading game presents a black login screen. Logging in blind you can hear yourself move around but you can only see the minimap move on screen.

### Software information
World of Warcraft: The Burning Crusade

### Log
https://mega.nz/#!bgQhxa7a!eWYxUOYJMh7XL7Fr18miNVAWciu_a-otS40NY1reYSI

### System information
- GPU: GTX 760
- Driver: NVIDIA
- Wine 4.9-staging + Windows: 8.1
- D9VK version: 0.12

### Apitrace file(s)
- https://mega.nz/#!2h5GyAiA!Ef9C737YEY_XDQtKyAa2YKxubZ3_jfAwkAob9L3_t88

I ran the trace under Windows which I read on another issue that would be even better.

**Comment by Riesi** [comment]
@crborga Your apitrace does not render black anymore on latest master. Please recheck your issue. Automated builds of latest d9vk can be found here: https://git.froggi.es/joshua/d9vk/-/jobs

**Comment by crborga** [comment]
Okay everything besides inventory icons and actionbar icons seems to work now. I will have to run another apitrace and post screenshot. 

⁣Sent from BlueMail ​

**Comment by Riesi** [comment]
Nahh its fine the The Burning Cursade apitrace shows the issue and I already forwarded it to Josh. There is an issue open that already mentions the icon issue, so you can close this one. :)
