### ISSUE TITLE
Mass Effect 2 - The Shining Ronald Taylor

### ISSUE THREAD

**Issue by neVERberleRfellerER** [Joshua-Ashton/d9vk#158]
One character (Ronal "Johnny" Taylor) is shining. He is mostly shining from distance, but I don't know what drives his shining and thus it's difficult to capture poweroff with apitrace (shining does not happen with wined3d). When shining stops with D9VK, it won't return even when going further away Taylor.

It is long term problem, I just always forget to report or I am doing something else when this comes randomly to my shiny mind.

Pictures below were downscaled to 1920x1080 from 3840x2160 to preserve free capacity of the Universe.

With D9VK:
![Screenshot_20190609_172353 png](https://user-images.githubusercontent.com/11160972/59160880-837d2b00-8adb-11e9-98f6-cefef15b8f5a.jpg)

With wined3d:
![Screenshot_20190609_172609 png](https://user-images.githubusercontent.com/11160972/59160904-ca6b2080-8adb-11e9-90a2-65e9d042fdf7.jpg)

[Closeup](https://en.wikipedia.org/wiki/File:The_shining_heres_johnny.jpg)

Shader validation does not show anything.

### Software information
Mass Effect 2

![settings](https://user-images.githubusercontent.com/11160972/59160734-824afe80-8ad9-11e9-8bfe-7d048e63e5bf.jpg)

### System information
- GPU: POLARIS10
- Driver: RADV git , LLVM 9.0.0; also with RADV 19.0.6 and AMDVLK 2019.Q2.4
- Wine version: wine-tkg-git 4.8
- DXVK version: d8b9b5fedf081a40f00d5c20d49099a6ead6ecdf

### Apitrace file(s)
(retrace correctly shows problem with D9VK and not with wined3d)
https://drive.google.com/open?id=1pcse8QJ4RFZRcvkzWyVHfNiTqYg1BiRS

### Log files
- d3d9.log: https://pastebin.com/tjiVh4bL
- dxgi.log: none

**Comment by K0bin** [comment]
Those warnings are irrelevant and caused by D9VK itself. Please post the full logs (to something like pastebin).

**Comment by neVERberleRfellerER** [comment]
> Those warnings are irrelevant and caused by D9VK itself.

I though so, but I wanted to follow the template without having to use another third party service.

> Please post the full logs (to something like pastebin)

Link is in updated OP and here https://pastebin.com/tjiVh4bL

**Comment by K0bin** [comment]
Should be fixed by f62e2c6c9c956a8f949ade53ee18414d4af86d34

**Comment by neVERberleRfellerER** [comment]
Confirming. Thank you.
![Screenshot_20190615_163754 png](https://user-images.githubusercontent.com/11160972/59552847-26c2ba00-8f8c-11e9-9f0d-1a89c903da01.jpg)
