### ISSUE TITLE
Collection of spirv-val errors

### ISSUE THREAD

**Issue by Riesi** [Joshua-Ashton/d9vk#16]
## How to check for spirv errors
0. Make 100% sure you are using the latest compiling master of d9vk before reporting! Otherwise you could encounter issues that are already fixed, which would be a waste of time for everybody.
1. use winetricks to install d3dx9 and d3dcompiler_43 otherwise your .dis will be useless!
2. set the envvar `DXVK_SHADER_DUMP_PATH=/home/user/.../dumplocation` to the location you want d9vk to dump its shaders (directories must exists)
3. run `spirv-val` on all of the dumped shaders:
```
for i in *.spv; do
echo $i
spirv-val $i
done
```
4. look for shader errors
5. Take the .spv and .dis file of the broken shader and zip them. Make sure .dis isn't corrupted. 
6. Post a comment with the error message and zip under this issue. You may keep a similar style to the existing comments.

## Checklist
- [x] Guild 2
- [x] Call of Duty 4

### Guild 2
Guild 2 crashes, but dumping the shaders and running spirv-val worked. So here are the invalid shaders.

- [x] VS_bca7

```
VS_bca7272b16585f37b83f01956056660e2d050e6b.spv
error: line 171: Result type (OpTypeInt) does not match the type that results from indexing into the composite (OpTypeFloat).
  %59 = OpCompositeExtract %int %58 0
```
[VS_bca7.zip](https://github.com/Joshua-Ashton/d9vk/files/3075391/VS_bca7.zip)

##### ------

This error occurred in multiple shaders, if you want a 2nd one please tell me.
- [x] VS_bf70
```
VS_bf70ef6d077b993bd733c73c480424a10d156f90.spv
error: line 248: Reached non-composite type while indexes still remain to be traversed.
  %137 = OpCompositeExtract %int %136 0
```
[VS_bf70.zip](https://github.com/Joshua-Ashton/d9vk/files/3075392/VS_bf70.zip)

### Call of Duty 4
```
FS_d3b510fb64530da674a5ac7001f747f9fbd09ed0.spv
error: line 752: ID 448[%cf2] defined in block 445[%445] does not dominate its use in block 577[%577]
  %577 = OpLabel
```
[FS_d3b5.zip](https://github.com/Joshua-Ashton/d9vk/files/3075415/FS_d3b5.zip)

**Comment by tim241** [comment]
* [ ] Far Cry 2
# Far Cry 2
```
FS_024a48a5260dc94a420fe2d14f80639f7ab38c23.spv
error: line 145: OpEntryPoint interfaces must be OpVariables with Storage Class of Input(1) or Output(3). Found Storage Class 6 for Entry Point id 2.
  %p1 = OpVariable %_ptr_Private_v4float Private
```
```
FS_e8981b165e82a2181953142be991fe90d3bff1be.spv
error: line 1824: ID 895[cf73] defined in block 369 does not dominate its use in block 1496
  %1496 = OpLabel
```
```
VS_0864411f21cbc6b4475d06d18867e7511999bc16.spv
error: line 8420: Id is 0
```
[FC2_shaders.zip](https://github.com/Joshua-Ashton/d9vk/files/3074963/FC2_shaders.zip)

**Comment by Joshua-Ashton** [comment]
Can you _**PLEASE**_ not use the shitty wine d3d9x that doesn't work with anything and resubmit disassembly.

Cheers

**Comment by CME42** [comment]
Far Cry 2
```
% spirv-val VS_2ad72b623eef1b3da92883020f9fe6813373fa81.spv
error: line 1505: Id is 0
% spirv-val FS_3021eee549c3abece762ea626f4cb15651609e7f.spv
error: line 233: OpLoad Result Type <id> '80[%80]' does not match Pointer <id> '50[%50]'s type.
  %81 = OpLoad %80 %50
```
[farcry2.zip](https://github.com/Joshua-Ashton/d9vk/files/3075301/farcry2.zip)

**Comment by Joshua-Ashton** [comment]
Is this on latest @CME42

**Comment by Valmar33** [comment]
Um... so, I've got, like, 3300 shaders to filter.

Is there a sane way to isolate the **2000** that have errors? :/

**Comment by Valmar33** [comment]
### Dragon's Dogma: Dark Arisen

    VS_344b5ee9d81f15e4c670d53ee8fe46d60dc299b7.spv
    error: line 2827: Id is 0

    FS_08d321a888c80a066b706180497969cdf8d13121.spv
    error: line 1320: ID 329[cf3] defined in block 325 does not dominate its use in block 320
      %320 = OpLabel

    FS_0001e3090fdf292faf483ee8d0f7beaee741f10a.spv
    error: line 131: OpEntryPoint interfaces must be OpVariables with Storage Class of Input(1) or Output(3). Found Storage Class 6 for Entry Point id 2.
      %p0 = OpVariable %_ptr_Private_v4float Private

[DragonsDogmaDarkArisen.tar.gz](https://github.com/Joshua-Ashton/d9vk/files/3076234/DragonsDogmaDarkArisen.tar.gz)

**Comment by tannisroot** [comment]
This is with latest d9vk (b91f6e210c643d7a6d1798044d1079982ff24d1c). The game crashes after playing intros.
### The Sims 4
```
FS_1ed916ea20151bcaecb34cb84088ce077b6874bb.spv
error: line 325: Expected Result Type to be a composite type
  %227 = OpCompositeConstruct %float %226 %226 %226 %226
```
```
FS_4a25fe0d3308a0c7922e927189f8bfa55b87c36c.spv
error: line 197: Expected Result Type to be a composite type
  %115 = OpCompositeConstruct %float %114 %114 %114 %114
```
[badbadshaders.zip](https://github.com/Joshua-Ashton/d9vk/files/3076541/badbadshaders.zip)

**Comment by Joshua-Ashton** [comment]
Are all these errors fixed now?

**Comment by Riesi** [comment]
My errors are fixed and probably the others too. We can always reopen, if anything new arises.
