### ISSUE TITLE
Mass Effect 3 messed up faces

### ISSUE THREAD

**Issue by dlshinobi** [Joshua-Ashton/d9vk#168]
Almost every character faces are messed up with blackness or washed up, especially Shepard. As far as I can tell this commit is guilty of this madness:
https://github.com/Joshua-Ashton/d9vk/commit/159c19db3da2a192996acece9fdd86a2ba586bb9#diff-25d902c24283ab8cfbac54dfa101ad31

current state:
![bad](https://user-images.githubusercontent.com/7222444/59465418-89547280-8e33-11e9-9705-7c456eeb5f7f.png)

should be:
![good](https://user-images.githubusercontent.com/7222444/59465445-96716180-8e33-11e9-8155-ae3330c0df17.png)

### Software information
Mass Effect 3

### System information
- GPU: nVidia GTX 960
- Driver: 418.52.10
- Wine version: 4.8 (staging)
- DXVK version: 0.12 master

### Apitrace file(s)
https://drive.google.com/drive/folders/1K7ZUZ41PdneYWC9ZkqDqPNZtFPQ5TrVn?usp=sharing

### Log files
https://drive.google.com/drive/folders/1K7ZUZ41PdneYWC9ZkqDqPNZtFPQ5TrVn?usp=sharing

**Comment by Joshua-Ashton** [comment]
Corrected by https://github.com/Joshua-Ashton/d9vk/commit/8e9569b000b71ee720553ac6670a1b8d10914359
