### ISSUE TITLE
Ultimate Marvel Vs. Capcom 3

### ISSUE THREAD

**Issue by massatt212** [Joshua-Ashton/d9vk#169]
Im not so good with reporting problems
but this is one of my favorite game
works good on Mesa But AMDVLK & AMDGPU Pro seems to give so much more performance and less stuttering, but their is a lil rendering problem if you own the game you can check it out yourself

![20190614100317_1](https://user-images.githubusercontent.com/43518479/59515011-2b07ae00-8e8c-11e9-8bfc-306c5315141b.jpg)
[umvc3_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3290928/umvc3_d3d9.log)

I wanted to report it before their another official release

**Comment by massatt212** [comment]
possible you can take a look at this game with amdvlk or amdgpu pro to fix texture bug

**Comment by Joshua-Ashton** [comment]
Please provide a trace as I do not own this game.

**Comment by misyltoad** [comment]
Closing as there was no trace and it was AMDVLK exclusive...
