### ISSUE TITLE
Mouse hidden in World of Warcraft: Wrath of The Lich King

### ISSUE THREAD

**Issue by pikashira** [Joshua-Ashton/d9vk#17]
I can move the mouse around and click everything just fine, I just can't see the mouse icon itself. This may have something to do with most 2D sprites not being shown properly. A screenshot of said glitches is shown below (should I open a different issue for that?).

![wow_sprites](https://user-images.githubusercontent.com/11667372/56053799-f91f8180-5d4c-11e9-93c5-c65bc5f4581b.png)
The minimap is invisible and the ability bar should be filled with ability sprites.

### Software information
World of Warcraft: Wrath of The Lich King

### System information
- GPU: AMD RX480
- Driver: free
- Wine version: 4.5
- DXVK version: master (65fc6f8)

### Apitrace file(s)
I tried getting an apitrace but couldn't get Wine to use apitrace's d3d9.dll, it just ignored the overrides.

### Log files
[Wow_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3074208/Wow_d3d9.log)

Sidenote: The game wouldn't even open yesterday, and today it's running smoothly, other than these issues above. Awesome!

**Comment by Joshua-Ashton** [comment]
It wants to make d3d9 to set a 'hardware cursor', this is currently not supported in DXUP and probably won't be for a little while until I find a decent solution.

It could probably be done similar to how the DXVK hud works.

https://docs.microsoft.com/en-us/windows/desktop/api/d3d9/nf-d3d9-idirect3ddevice9-setcursorproperties

**Comment by mikeloud** [comment]
Thanks for the quick reply!

I tried disabling the hardware cursor option in-game and the issue remains. This is the new log after that:

[Wow_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3074421/Wow_d3d9.log)

**Comment by toididiputs** [comment]
I can confirm something similar is happening in TBC 2.43 (I mentioned it over on r/linux_gaming).
For me the issue is the entire ui overlay not rendering.  Also some of the transparent water layers, skybox and some terrain lighting reflection/refraction(?) effects.  This is with proton 4.2, will test on 4.5 with latest mesa git and report back any differences.

**Comment by K0bin** [comment]
That's completely unrelated though.

The issue with WOW is that D3D9 has a function to set the mouse cursor which D9VK doesn't implement.

**Comment by toididiputs** [comment]
Sorry I wasn't clear. TBC is WOW The Burning Crusade, build 2.43.

**Comment by Grixin** [comment]
I'm also experiencing this on d9vk .10 on wow wotlk

**Comment by Riesi** [comment]
@pikashira Hardware cursor is implemented in latest master please recheck your issue.

**Comment by Joshua-Ashton** [comment]
Closing as there is another more active issue for this
