### ISSUE TITLE
Guild Wars 2 Texture problem is back

### ISSUE THREAD

**Issue by logan001** [Joshua-Ashton/d9vk#171]
Seems that there is again the problem with texture on the ground
this is without D9VK
![Screenshot from 2019-06-15 14-00-21](https://user-images.githubusercontent.com/6472378/59550838-a6df2480-8f78-11e9-829c-4d12667fcef8.png)

and this one is with d9vk
![Screenshot from 2019-06-15 14-20-58](https://user-images.githubusercontent.com/6472378/59550855-e73ea280-8f78-11e9-90ea-e9a3ba6be087.png)

### Software information
Name of the game, settings used etc.

### System information
- GPU: GTX 970
- Driver: 418.52.10
- Wine version:  tkg 4.6 (lutris)
- DXVK version: 08755c20129e36515cdc3109b30916cc5d58ee51

### Apitrace file(s)
[Here](https://drive.google.com/open?id=1bTcoR7NR3s7r179hXzwEH_JxaoWUiZGg)

### Log files
[Gw2-64_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3293058/Gw2-64_d3d9.log)

**Comment by K0bin** [comment]
Can you bisect D9VK to find the exact commit that introduced the regression?

**Comment by logan001** [comment]
ill try to use the frogy builds and see where it started

**Comment by logan001** [comment]
d8b9b5fe is the last froggy that works

from 9e81ad9c the texture is gone

**Comment by Joshua-Ashton** [comment]
Closed by https://github.com/Joshua-Ashton/d9vk/commit/8e9569b000b71ee720553ac6670a1b8d10914359
