### ISSUE TITLE
Guild Wars 2 DPI Scaling doesnt do anything

### ISSUE THREAD

**Issue by SpatiumPrinceps** [Joshua-Ashton/d9vk#172]
Hello, 

in GW2 the option DPI-scaling does not work at all. Whenever I check/uncheck the box the screen turns kinda white, like its rerendering some shadows or refreshing something but does not change the size of UI. 
It doesnt matter if this is done in fullscreen or windowed fullscreen. 
I also tried to run the game in a virtual desktop with the correct resolution of my screen, but didnt work.
Changing the interface size does work, its just super tiny on a 4k monitor, even on "Larger"

### Software information
- Guild Wars 2 (GW2)
- DPI Scaling (Button below "Interface Size")
- i3wm if this could be an issue, no compositor

### System information
- GPU: GTX1060
- Driver: 430.26.0
- Wine version: Lutris default (ge-protonified-nofshack-4.9-x86_64)
- D9VK version: 0.12
- Resolution: 3840x2160

### Log files
- d3d11.log: empty
- dxgi.log: empty 
- d9d9.log [link (its huge)](https://gitlab.com/uploads/-/system/temp/c3670cdd1ef7667d0dc0224d4fa51ff2/GW2-64_d3d9.log)
Log level is on debug. I might still be doing something wrong tho. Let me know if I can provide anything else to resolve this issue.

**Comment by TheDaftRick** [comment]
Have you tried a non protonified version of Wine?
I have noticed Proton and protonified versions of Wine don't recognize my monitor as accurately as others.

**Comment by SpatiumPrinceps** [comment]
> Have you tried a non protonified version of Wine?
> I have noticed Proton and protonified versions of Wine don't recognize my monitor as accurately as others.

I just tried a few other wine versions, all crashed after turning it on and off. 
If I use the standard non d9vk config from lutris (some pba esync enabled version) dpi scaling works flawless.

**Comment by SpatiumPrinceps** [comment]
This was a wine issue mostly. You have to adjust the DPI in winecfg for the in game options to work.
