### ISSUE TITLE
mk9 shows black screen instead of vidoes when using d9vk

### ISSUE THREAD

**Issue by aligodlike** [Joshua-Ashton/d9vk#173]
in mortal kombat komplete edition videos are not visible there is just black screen changing to wined3d fixes it but i need to run it with d9vk

- GPU: GTX 970
- Driver: 430.26
- Wine version: tkg 4.10
- DXVK version: d9vk 0.12 - dxvk 1.2.1

**Comment by Joshua-Ashton** [comment]
Given you didn't provide an apitrace I cannot test if I have fixed this w/ recent commits.

Can you see if this is fixed now on latest master, and if not provide a trace?
