### ISSUE TITLE
Sims 4 stops rendering anything after changing from Windowed mode to Fullscreen

### ISSUE THREAD

**Issue by tannisroot** [Joshua-Ashton/d9vk#175]
The issue is reproducible with the apitrace and wined3d works fine. Changing from fullscreen to windowed works fine but doing the opposite (windowed or borderless windowed to fullscreen) causes the game to render nothing but white. The sound keeps playing after that though.

### Software information
The game is Sims 4, I bought it on Origin but it has a free tiny demo too and IIRC it has the same issue.

### System information
- GPU: Nvidia GTX 1070
- Driver: 418.52.16 (happened with older driver too)
- Wine version: 4.10 (but happens with 4.0 too)
- D9VK version: 0.13f (and was present in all D9VK versions since Sims 4 started to work)

### Apitrace file(s)
https://drive.google.com/open?id=1YB3QJ9j22HOdCgaWclkPVlV56_uXDQtu

### Log files
[TS4_x64_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3408718/TS4_x64_d3d9.log)

**Comment by Joshua-Ashton** [comment]
Only seems to happen on NV.

**Comment by tannisroot** [comment]
Fixed by bc64e8e0263004908090da60b4c478a6573fe7d0
