### ISSUE TITLE
Assassin's Creed II issues found

### ISSUE THREAD

**Issue by AccountOneOff** [Joshua-Ashton/d9vk#176]
- [ ] Blood suspended in air

![Screenshot from 2019-06-16 17-45-00](https://user-images.githubusercontent.com/15083452/59572115-bb4a1c80-905f-11e9-97c2-1c707c6eb553.png)

- [ ] Hair not rendering right

![Screenshot from 2019-06-16 17-57-53](https://user-images.githubusercontent.com/15083452/59572825-868c9400-9064-11e9-92b3-235f97ebb26d.png)

- [ ] Black squared textures falling from sky

![Screenshot from 2019-06-16 18-04-34](https://user-images.githubusercontent.com/15083452/59572826-8c827500-9064-11e9-9407-5ca6f6081c93.png)

- [ ] Low poly hay

![Screenshot from 2019-06-16 18-10-25](https://user-images.githubusercontent.com/15083452/59572830-90ae9280-9064-11e9-8f34-76e0aa227a7e.png)

### Software information
All high settings; MSAA x2

### System information
- GPU: GTX 960
- Driver: 418.56
- Wine version: 4.6
- D9VK version: bb776e5e3583b2ced1da06e32c32f90b5e850c75

### Apitrace file(s)
- https://drive.google.com/file/d/1qavOf6brbxieRQQl747rK08cuU63XSiA/view

### Log files
- https://github.com/Joshua-Ashton/d9vk/files/3294855/AssassinsCreedIIGame_d3d9.log

**Comment by Joshua-Ashton** [comment]
Result of alpha test regression

Fixed by https://github.com/Joshua-Ashton/d9vk/commit/e98ceff97f721d4ca8f1d8c10742ce78dbffd76f
