### ISSUE TITLE
Borderlands 2 (Ultra HD) in-engine cutscenes are glitched in ultrawide resolution

### ISSUE THREAD

**Issue by lavadrop** [Joshua-Ashton/d9vk#177]
Just what the title says. The in-engine cut scenes are glitched, there's a squared area on the left where you can see something, but the rest of the screen is just black. Sometimes textures like the graffiti-like names show up. Subtitles are spared. Also, the lava from the Warrior encounter is transparent.

FMV cut scenes play normally.

### Software information
Borderlands 2 (Ultra HD DLC)

### System information
- GPU: RX 580 8 Gb
- Driver: OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.2.0-devel (git-a417c32 2019-06-15 disco-oibaf-ppa)
- Wine version: Proton 4.2-7
- DXVK version: 1.2-30
- d9vk version: 0.12

![lava](https://user-images.githubusercontent.com/6760790/59581687-4a285a80-909b-11e9-8723-be3c10d28dff.jpeg)
![jack](https://user-images.githubusercontent.com/6760790/59581688-4a285a80-909b-11e9-824a-fb12e5a97cce.jpeg)
![jack1](https://user-images.githubusercontent.com/6760790/59581689-4a285a80-909b-11e9-8888-2ed02f92cfb7.jpeg)
![lilith](https://user-images.githubusercontent.com/6760790/59581690-4a285a80-909b-11e9-927d-a51bb628a6bb.jpeg)

**Comment by edwin-v** [comment]
This was one thing I wanted to report. (see below).

After a discussion on Discord this appears to be an NVIDIA only issue.

!(https://steamuserimages-a.akamaihd.net/ugc/786355787333557717/37BA1B16F37CF2C88D2BADF0487B1BCFD1AC9EE7/)
!(https://steamuserimages-a.akamaihd.net/ugc/786355787333558174/903379C740BC644602D763E5E1EA9E63A5A190AB/)

**Comment by lavadrop** [comment]
Have you tried the Warrior fight? Lava texture is missing for me.

**Comment by edwin-v** [comment]
Only tried a few areas. Not that one.

@lavadrop Maybe add the ultrawide (or non-16:9) bit the title. Could be convenient for Joshua to instantly see what something is about.

**Comment by rkanati** [comment]
@lavadrop For reference, the lava is missing for me even without D9VK, ever since I started playing through Wine with the HD pack.

**Comment by lavadrop** [comment]
Are you also using 21:9 aspect ratio?

**Comment by rkanati** [comment]
@lavadrop no, and my cutscenes are fine; my point is that's likely a separate bug.

**Comment by edwin-v** [comment]
The cutscenes now render properly on ultrawide. I don't see which commit was responsible for it, so I don't know exactly when it was fixed.
