### ISSUE TITLE
Warhammer 40K Space Marine doesn't render 3D models

### ISSUE THREAD

**Issue by ronoverdrive** [Joshua-Ashton/d9vk#18]
Observed Results: On Windows 10 Videos and Menus render correctly. 3D rendering does not. At the start screen you should see an Ultramarine fighting Orcs and instead it is a black screen. Once into game play everything is a black screen. On WINE the game crashes after Warning Screen is displayed. I believe the crash is due to a WINE bug and not D9VK because its running otherwise on Windows 10.

### Software information
Warhammer 40,000 Space Marine

### System information
- GPU:  Geforce GTX 980ti (Linux), Geforce GTX 960 (Windows)
- Driver: 418.52.03 (Linux), 425.31 (Windows 10)
- Wine version: Wine-TKG 4.5 GIT
- DXVK version: master

### Apitrace file(s)
- apitrace: [Spacemarine.7z](https://mega.nz/#!mCxznAaT!1nlnP75-WRIP5Dc7nhD4kcWZjy3QyHUDGawVpb8Kkz0)

### Log files
- [Spacemarine_d3d9.log](https://mega.nz/#!nGxXUIIR!pSozhW08cI9AkdW_w4XRaDk5q7gsF0392fFMfLU_Fmw)

**Comment by neVERberleRfellerER** [comment]
I guess that these two are ultramarine and ork. Is it good?
![Screenshot_20190512_212402 png](https://user-images.githubusercontent.com/11160972/57586868-6ebd6f80-74fc-11e9-9c84-ad2d8d83d926.jpg)

**Comment by FuchtelJockel** [comment]
I tested it with proton 4.11-2 and it "works" (4fps but correct rendering) with wine3d. D9VK works for the intro but as soon as the menu appears will hang.
AMD RAVEN (DRM 3.32.0, 5.2.8-1-default, LLVM 8.0.1)
Mesa 19.1.3

**Comment by FuchtelJockel** [comment]
Correction: as soon as I move the mouse and the cursor shows up it hangs. I actually managed to play the game since the crosshair isn't affected.

**Comment by NerosTie** [comment]
Tested (#809) and everything is alright, the issue can be closed.
