### ISSUE TITLE
Borderlands 2 - Game uses all RAM and crashes

### ISSUE THREAD

**Issue by jerbear64** [Joshua-Ashton/d9vk#183]
I have gotten to a point in Borderlands 2 where I can reliably produce this issue if necessary.

This game has problems sometimes with claiming to run out of VRAM, which is already being tracked in #170. However, a secondary (and more severe) issue has manifested itself during my playthrough. Within seconds of loading my current savefile, the game will freeze, the game's audio will begin stuttering, disk I/O will rapidly increase (presumably swap being filled), and the system will become unresponsive. Within a few seconds I assume the low RAM killer kicks in, as Borderlands 2 will close itself- along with my browser, Steam, and Discord. D3D9 logs are flooded with `err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED` when this occurs.

This occurs both on v0.1.2 and the latest master (currently b787cf0). This does *not* happen on wined3d, although the game does manifest a VRAM error after a short while in this area on wined3d. gallium-nine was not tested.

Every setting maxed out except depth of field (disabled) and texture fade (disabled as part of the "out of video memory" mitigations mentioned in #170). All DLC installed, including the UHD texture pack.

### System information
- GPU: RX 580, 8GB
- Driver: Mesa 19.1.0
- Wine version: Proton 4.2-7

[Launcher_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3315646/Launcher_d3d9.log)

I captured an apitrace with wined3d, but the problem does not manifest itself in the retrace, and additionally `VK_ERROR_MEMORY_MAP_FAILED` does not show up in the d3dretrace d9vk logs, so it won't be of any use.

**Comment by Matoking** [comment]
I have the same issue, and can reproduce it consistently by loading my save file at Sanctuary. A few seconds after spawning and a few seconds into Handsome Jack's line the game will start to stutter before eventually making my desktop environment unusable. I have to force the OOM killer to make the system usable again. 

I recorded an apitrace with wined3d [here](https://drive.google.com/open?id=1d7G9m8dfYQEVNeAOMuUz5AhRnBuyyrvy).

The system information:
* OS: Arch Linux
* GPU: Vega 64
* Driver: Mesa 19.1.0
* Proton 4.2-7

**Comment by jerbear64** [comment]
That's the exact same spot I'm in. I had just gotten into Sanctuary, and was working on the Plan B mission.

-------- Original Message --------

**Comment by Matoking** [comment]
The game no longer freezes as of a0bfc932ca477b7c5973fe5fb843a5f5dcc5b7d3. Thanks for fixing the issue! :frog:

**Comment by Joshua-Ashton** [comment]
Cool!
