### ISSUE TITLE
Gothic 3 menu renders black [regression]

### ISSUE THREAD

**Issue by Riesi** [Joshua-Ashton/d9vk#185]
The main menu used to render fine until commit `988dd998bb8cab6c7b5b4c1f06637867f51844cf`
Now it renders only black.

### System information
- GPU: GTX970
- Driver: 430

### Apitrace file(s)
https://git.froggi.es/Riesi/tracehub/raw/master/traces/d3d9/Gothic%203%20%5Bnative%5D.tar.xz?inline=false

### Log files
[Gothic3_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3342938/Gothic3_d3d9.log)

**Comment by Joshua-Ashton** [comment]
This should be fixed now.

**Comment by Riesi** [comment]
It is indeed fixed and the intro videos render fine too!
