### ISSUE TITLE
Warhammer Online (return of reckoning) graphics pipelines keep going up few minutes until crash

### ISSUE THREAD

**Issue by mylucky2018** [Joshua-Ashton/d9vk#187]
currect version bug
hud show graphics pipelines : 70000+ keep going up few minutes until crash

currect version solved
https://github.com/Joshua-Ashton/d9vk/issues/28
fixed cant see any floating icon / hp_bar / all_name
fixed cant see any spell effects
        but a bit strange than the original special effects

### Software information
Warhammer Online (return of reckoning)

### System information
- GPU: GTX 750
- Driver: 430.14.0
- Wine version: 4.8
- DXVK version: https://github.com/Joshua-Ashton/d9vk/commit/db2612cf74d9a95c6a38c3376f72ff8eb660b453

### Log files
- d3d11.log:
- dxgi.log: 
[ror_debug190701.log](https://github.com/Joshua-Ashton/d9vk/files/3344315/ror_debug190701.log)
![ror2019-07-01_13-57-47 ror 4](https://user-images.githubusercontent.com/41288775/60417420-faa56b00-9c12-11e9-9639-0966e35a7504.png)

**Comment by Joshua-Ashton** [comment]
When I asked you to make this issue, I also asked for a trace 🐸

**Comment by mylucky2018** [comment]
thank you very much :)
crash bug was fixed with this version https://github.com/Joshua-Ashton/d9vk/commit/346883d49af1676b8415d585299d08212fdb2dae
