### ISSUE TITLE
Everquest Black Screen

### ISSUE THREAD

**Issue by ronoverdrive** [Joshua-Ashton/d9vk#19]
Observed Results: Black Screen with no music on start up. Up until yesterday's (4-11-19) update to git master everything rendered except for character models. This happens on both Windows 10 and WINE.

### Software information
Everquest

### System information
- GPU: Geforce GTX 980Ti (Linux), Geforce GTX 960 (Windows)
- Driver: 418.52.03 and 425.31 respectively
- Wine version: WINE-TKG 4.5 Git Master
- DXVK version: git master

### Apitrace file(s)
- [eqgame.7z](https://mega.nz/#!LaolzShC!y95BqJgenSNNgZ8EebzXROUq10z4Benbl61VUb9G0Q8)

### Log files
- d3d9.log: [eqgame_d3d9.log](https://mega.nz/#!uXx3xCSB!1j7x6oHePyA1uPcui7BE_Gv3us_TNBlw-7Njz3lUAdM)

**Comment by Joshua-Ashton** [comment]
This trace is completely buggered and writes out of bounds... Doesn't work on native for me either.

**Comment by Joshua-Ashton** [comment]
Is this still an issue? Can you make a new trace for this?

**Comment by ronoverdrive** [comment]
Sorry Josh, been having some WINE issues lately that I was able to finally work out. Game is working A-OK now.
