### ISSUE TITLE
WOLF RPG Editor: Rendering issue

### ISSUE THREAD

**Issue by kakurasan** [Joshua-Ashton/d9vk#190]
Broken rendering, see screenshots (Japanese sample game).

wined3d:
![wolfrpg2 10-sample-title-wined3d](https://user-images.githubusercontent.com/10556453/60518407-6f180100-9d1c-11e9-8ae2-178419035a7f.png)

D9VK a0bfc93:
![wolfrpg2 10-sample-title-d9vk-a0bfc93](https://user-images.githubusercontent.com/10556453/60518405-6e7f6a80-9d1c-11e9-8e53-d8c283f496ef.png)

A game called [Misao(操)](http://vgperson.com/games/misao.htm) uses WOLF RPG Editor and it has the same issue.

### Software information
Games based on WOLF RPG Editor

### System information
- GPU: Intel HD Graphics 510
- Driver: Mesa 19.1.1
- Wine version: 4.0.1
- DXVK version: a0bfc93

### Apitrace file(s)
- [Game.trace.xz.zip](https://github.com/Joshua-Ashton/d9vk/files/3350385/Game.trace.xz.zip) (2.9M, 640x480 Windowed)

### Log files
- [Game_d3d9.log.zip](https://github.com/Joshua-Ashton/d9vk/files/3350389/Game_d3d9.log.zip) (No stub warnings)

**Comment by Bfgeshka** [comment]
Have you tried other RPG Maker titles?

**Comment by Joshua-Ashton** [comment]
Interesting issue, looks like its related to vertex coloring at a blatant guess.

I will investigate this later, I cannot currently due to personal reasons. Cheers.

**Comment by kakurasan** [comment]
@Bfgeshka
I've tried some other games based on WOLF RPG Editor.

Games created with v2.10/v2.2x have the same issue.
Older games (v2.0x) won't start (Initializing doesn't finish, printing `warn:  D3D9SwapChainEx::GetRasterStatus: Stub` messages).

**Comment by Joshua-Ashton** [comment]
Looked at the renderdoc and debugged a bit today. Based on what I know about fixed function -- this is what I would expect the behaviour to be... There's obviously some quirk I am missing here hmmmm

**Comment by Joshua-Ashton** [comment]
Oh wait, its using fixed function vertex processing and a real shader. Hohoho this is interesting.

**Comment by Joshua-Ashton** [comment]
I noticed it only sets data for the first triangle. It could be wanting to use flat shading hmmm

**Comment by Joshua-Ashton** [comment]
Indeed it is.

**Comment by Joshua-Ashton** [comment]
Should be fixed by https://github.com/Joshua-Ashton/d9vk/commit/2addd6ed8c3d698db348c0d1973f3552a2cc1561, can you confirm?

**Comment by kakurasan** [comment]
Tested with adc2d84, "fixed". Thank you!
