### ISSUE TITLE
Arma II: no mouse cursor

### ISSUE THREAD

**Issue by delentef** [Joshua-Ashton/d9vk#191]
Hello, I have Arma II installed through Steam, but I play it with wine directly, I'm not using proton.

The game runs very well, but there is no mouse cursor. I played for about 10 minutes without issues except this one. The cursor never appears, not on the start menu, not on the map, and not when opening the menu in game.

Thanks for your work anyway!

### Software information
Arma II, standard installation

### System information
- GPU: Nvidia GTX980M (laptop), lspci reports "VGA compatible controller: NVIDIA Corporation GM204M [GeForce GTX 980M] (rev a1)"

- Driver: Nvidia Proprietary 430.26
- Wine version: 4.11 staging (package from fedora)
- DXVK version: d9vk is master as of July 4th

### Apitrace file(s)
Not relevant (?)

### Log files
- d3d11.log:
[arma2_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3361315/arma2_d3d9.log)

- arma2_dxgi.log is empy

- dxgi.log:

**Comment by Riesi** [comment]
I guess you grabbed a build on that day before Josh implemented the hardware cursor with 1e8fdd59d2f3e8266af469319a7543741b035299. I tried Arma2 OA and the cursor works (I could not get Arma 2 to start with proton)
![arma 2 with mouse cursor](https://user-images.githubusercontent.com/27691485/61169781-7da6b980-a561-11e9-9659-ba39546f9089.png)

**Comment by delentef** [comment]
Thanks for the info and the update, I'll give it another try then!

**Comment by delentef** [comment]
Works for me, thanks!!
