### ISSUE TITLE
Lunatic Rave 2: Weird translucency.

### ISSUE THREAD

**Issue by Ziemas** [Joshua-Ashton/d9vk#192]
### Software information
Lunatic Rave 2 is a japanese rhythm game built using fixed function D3D9, some graphics elements in this game display incorrectly through D9VK

Wined3d:
![2019-07-05-19:25:51](https://user-images.githubusercontent.com/5276694/60738182-b80ac800-9f5d-11e9-8b8e-8c7b4540c320.png)
D9VK:
![2019-07-05-19:26:35](https://user-images.githubusercontent.com/5276694/60738184-b80ac800-9f5d-11e9-998f-18189bbe46ac.png)

### System information
- GPU: GTX 780
- Driver: Nvidia 418.52.10
- Wine version: wine-4.11.r11.g53dad92c
- DXVK version: d9vk master as of 2019/07/05

### Apitrace file(s)
https://ziemas.se/lr2-transparency.trace

### Log files
https://ziemas.se/LR2body_d3d9.log

**Comment by Ziemas** [comment]
Oh I guess this looks very similar to #190, might be related?

**Comment by Joshua-Ashton** [comment]
Should be fixed by https://github.com/Joshua-Ashton/d9vk/commit/2addd6ed8c3d698db348c0d1973f3552a2cc1561, can you confirm?

**Comment by Ziemas** [comment]
Confirmed fixed :+1:
