### ISSUE TITLE
Lunatic Rave 2: Rendered area doesn't expand to fit window.

### ISSUE THREAD

**Issue by Ziemas** [Joshua-Ashton/d9vk#193]
With windowed mode in Lunatic Rave 2 the rendered area doesn't expand to fill the whole window.

Game window in D9VK:
![2019-06-30-17:37:47](https://user-images.githubusercontent.com/5276694/60740824-69fac200-9f67-11e9-9e70-6de4c99931d7.png)

d3dretrace running through wined3d:
![2019-07-05-20:45:46](https://user-images.githubusercontent.com/5276694/60740573-8cd8a680-9f66-11e9-84e4-58cd86612b82.png)

d3dretrace running through D9VK:
![2019-07-05-20:45:24](https://user-images.githubusercontent.com/5276694/60740581-982bd200-9f66-11e9-8a78-f0b2aba213be.png)

### System information
- GPU: GTX 780
- Driver: Nvidia 418.52.10
- Wine version: wine-4.11.r11.g53dad92c
- DXVK version: d9vk master as of 2019/07/05

### Apitrace file(s)
- https://ziemas.se/lr2-window-size.trace

### Log files
[LR2body_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3363740/LR2body_d3d9.log)

**Comment by Joshua-Ashton** [comment]
When expanding the window of the trace, it seems to work fine for me here on Windows (ie. it stretches)

Can you verify the behavior for you is opposite (ie. clipped)

**Comment by Ziemas** [comment]
Yes, for me it stays the same size.

d3dretrace through D9VK after having stretched out the window:
![2019-07-06-09:09:25](https://user-images.githubusercontent.com/5276694/60753062-e88a4a80-9fcd-11e9-805e-aea00d1961ce.png)

**Comment by Joshua-Ashton** [comment]
Then this isn't my bug. I have no idea whose it is though :-/

**Comment by Ziemas** [comment]
I guess you had a reason for changing this in the first place but I can work around the issue by doing this.

```
diff --git a/src/d3d9/d3d9_swapchain.cpp b/src/d3d9/d3d9_swapchain.cpp
index a9e91379..8b824e33 100644
--- a/src/d3d9/d3d9_swapchain.cpp
+++ b/src/d3d9/d3d9_swapchain.cpp
@@ -434,8 +434,8 @@ namespace dxvk {
       VkViewport viewport;
       viewport.x        = 0.0f;
       viewport.y        = 0.0f;
-      viewport.width    = float(m_swapImage->info().extent.width);
-      viewport.height   = float(m_swapImage->info().extent.height);
+      viewport.width    = float(info.imageExtent.width);
+      viewport.height   = float(info.imageExtent.height);
       viewport.minDepth = 0.0f;
       viewport.maxDepth = 1.0f;
       
@@ -1070,4 +1070,4 @@ namespace dxvk {
     return m_presentExtent != oldExtent;
   }
 
-}
\ No newline at end of file
+}

```

**Comment by Joshua-Ashton** [comment]
Interesting, I'll take a look at this later :-)

**Comment by Joshua-Ashton** [comment]
Can you try with this?

https://github.com/Joshua-Ashton/d9vk/commit/8490b27bf20b3ee20d0aa5d850e430841415e7e0

**Comment by Ziemas** [comment]
Yes, that fixes the issue. :+1:

**Comment by CartoonFan** [comment]
Can this bug be closed, then?
