### ISSUE TITLE
Star Wars The Force Unleashed Ultimate Sith Edition (iBackBuffer > 0 not supported)

### ISSUE THREAD

**Issue by VortexAcherontic** [Joshua-Ashton/d9vk#194]
The Launcher has no Text with D9VK and The Game itself crashes on start up with an `err:   D3D9: GetBackBuffer: iBackBuffer > 0 not supported`.
How ever, as you can see in the Logs below, the Back buffer Error only appears in the SWTFU_Launcher Log not in the actual game Log. So I'm not 100% sure if the iBackBuffer issue also applies for the game client.

### Software information
- Game: Star Wars The Force Unleashed Ultimate Sith Edition
- Settings: 1080p (There are no more options)

### System information
- GPU: GTX 1080
- Driver: 430.26
- Wine version: tkg-4.5-x86_64
- DXVK version: 0.12

### Apitrace file(s)
- [Apitrace](https://drive.google.com/open?id=18upvslGzDrkS9mpZ046dRjiuJHbMYTbU)

### Log files
- d3d9.log: [SWTFU_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3364644/SWTFU_d3d9.log)
[SWTFU Launcher_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3364645/SWTFU.Launcher_d3d9.log)

**Comment by K0bin** [comment]
The log of the game itself doesnt actually have `err: D3D9: GetBackBuffer: iBackBuffer > 0 not supported`, so it's unlikely that its crashing because of that.

**Comment by VortexAcherontic** [comment]
@K0bin I added the Apitrace as a strong compressed 7z file to reduce the upload file size. The original Trace was not modified :)

**Comment by K0bin** [comment]
I just noticed you tested the game with D9VK 0.12. We already fixed a bug that caused SWTFU to crash. Try it with the latest master.

**Comment by VortexAcherontic** [comment]
Works with the latest build (Artifact ID: #572) but Videos are stuttering and as you can see in the screenshot there are some ... glitches? BUT it starts and works fine, also the Launcher is now displaying text and not throwing the iBackBuffer error any more.

![Screenshot_20190709_140920](https://user-images.githubusercontent.com/11244092/60886826-36fc4b00-a253-11e9-8a24-9f3a8b97539c.png)

**Comment by K0bin** [comment]
Did you install Microsofts d3d**x**9 and d3dcompiler? The Wine implementations of those are broken and known to cause problems.

**Comment by VortexAcherontic** [comment]
Installed:

- d3dcompiler_42
- d3dcompiler_43
- d3dcompiler_47
- d3d9x

And still have those issues.

Do D9VK make use of those? Because with Wine D3D it's working as expected (how ever the performance of Wine D3D is crap ^^")

Here's another trace from that scene: https://drive.google.com/open?id=18V67R9TQsOCfF5W7qdjflZ7Aw_0EC-lh

**Comment by K0bin** [comment]
> Do D9VK make use of those? 

Not directly but the game uses these and feeds data it gets from them into D9VK.

I'll take a look at your trace when I'm home.

**Comment by VortexAcherontic** [comment]
All right, but I need to add something I mixed up before.

After installing the above mentioned win dlls I can not load the save game with D9VK enabled, with Wine D3D its still working:
`wine: Unhandled page fault on write access to 0x00000008 at address 0x654db664 (thread 0089), starting debugger...`

So the trace was made before adding d3dcompilers and d3d9x dlls.

Do you need another trace with the dlls changes?

**Comment by K0bin** [comment]
Can you try replaying (`wine d3dretrace.exe YOUR_TRACE.trace`) the Darth Vader prologue trace you added to the initial report with D9VK and those dlls?

**Comment by VortexAcherontic** [comment]
I assume you want me to retrace the Vader Trace with inside the SWTFU prefix and with the wine build I used with Lutris?

Seems to work as expected. 
![Screenshot_20190709_150038](https://user-images.githubusercontent.com/11244092/60889869-521e8900-a25a-11e9-9fbd-fd9c2d233690.png)

My command line instructions:
`export WINEPREFIX="/home/vortex/Games/star-wars-the-force-unleashed"`
`/home/vortex/.local/share/lutris/runners/wine/tkg-4.5-x86_64/bin/wine /home/vortex/Programme/Wine/apitrace-8.0.20190414/apitrace-8.0.20190414-win32/bin/d3dretrace.exe /home/vortex/Programme/Wine/api-traces/Star\ Wars\ The\ Force\ Unleashed\ \(2Disc\ Retail\ Version\).trace 
`

**Comment by K0bin** [comment]
And that's running with D9VK?

**Comment by VortexAcherontic** [comment]
Ouh replaying the trace WITH D9VK sorry, missed that.

That's with D9VK enabled:
![Screenshot_20190709_150433](https://user-images.githubusercontent.com/11244092/60890082-dd981a00-a25a-11e9-838d-10daaf675fd3.png)

I just enabled D9VK inside lutris launched the game so the launcher will come up and quit the game and than rerun my command line stuff.

Or do I need to enable D9Vk another way to use it with apitrace?

And this was rerun with the game opened in the background to make sure Lutris did not reverted the D9VK changes after the game quits. However I missing the DXVK_HUD.
![Screenshot_20190709_150657](https://user-images.githubusercontent.com/11244092/60890240-34055880-a25b-11e9-9e6e-0070c7cf64d5.png)

**Comment by VortexAcherontic** [comment]
I guess d3dretrace is not using the d9vk dlls:
![Screenshot_20190709_151012](https://user-images.githubusercontent.com/11244092/60890526-b7bf4500-a25b-11e9-9f5d-c4b88e531a97.png)

**Comment by VortexAcherontic** [comment]
Okay lutris seems to modify something on the prefix while launching the game, here is the trace with D9VK as you can see in the overlay. Looks as it should:

![Screenshot_20190709_153406](https://user-images.githubusercontent.com/11244092/60892177-fe626e80-a25e-11e9-8604-dc1d2eeabdf4.png)

And here is the 2nd trace with D9VK:
![Screenshot_20190709_153554](https://user-images.githubusercontent.com/11244092/60892308-3ec1ec80-a25f-11e9-9f51-b7deca7d9a20.png)


Looks also as it should. So I guess lutris is doing something it should not do?

**Comment by K0bin** [comment]
From what I know Lutris creates a separate Wine prefix for the game and you need to install D3DX9 and D3DCompiler into the Lutris prefix.

**Comment by VortexAcherontic** [comment]
I know I exported the Lutris wineprefix before running d3dretrace and such.
`/home/vortex/Games/star-wars-the-force-unleashed` is set as the prefix. And I ran winetricks through lutris inside it's wineprefix.

And here is the output from winecfg run through lutris inside the lutris star wars prefix.
THat's why I'm so confused about this behavior o.o
![Screenshot_20190709_154314](https://user-images.githubusercontent.com/11244092/60892945-45049880-a260-11e9-92dc-eca8894b0c7d.png)
![Screenshot_20190709_154334](https://user-images.githubusercontent.com/11244092/60892972-50f05a80-a260-11e9-8544-790dc8dea9b2.png)

**Comment by K0bin** [comment]
Can you post the console output (I think Lutris has a button for that) from running the game?

**Comment by tannisroot** [comment]
> Wine version: tkg-4.5-x86_64
that's a pretty old wine version. Can you try with ge-protonified-4.10 build? Or at least 4.9.

**Comment by VortexAcherontic** [comment]
@tannisroot The game wont even start with any non tkg wine build.

```
Running /home/vortex/.local/share/lutris/runners/wine/ge-protonified-4.10-x86_64/bin/wine /home/vortex/Games/star-wars-the-force-unleashed/drive_c/Program Files/Activision/Star Wars The Force Unleashed/SWTFU Launcher.exe
wine: configuration in '/home/vortex/Games/star-wars-the-force-unleashed' has been updated.
wine: Call from 0x7b453dac to unimplemented function shell32.dll.SHGetFolderPathW, aborting
wine: Unimplemented function shell32.dll.SHGetFolderPathW called at address 0x7b453dac (thread 000b), starting debugger...
Waiting on children
All children gone
Exit with returncode 1
```

With the latest tkg build (tkg-protonified-4.6-x86_64) the game will start but crash after loading the saved game:
This is only be fixed if I tell lutris to use my system libraries instead of the ones provided by lutris.

```
Running /home/vortex/.local/share/lutris/runners/wine/tkg-protonified-4.6-x86_64/bin/wine /home/vortex/Games/star-wars-the-force-unleashed/drive_c/Program Files/Activision/Star Wars The Force Unleashed/SWTFU Launcher.exe
wine: configuration in '/home/vortex/Games/star-wars-the-force-unleashed' has been updated.
info:  Game: SWTFU Launcher.exe
info:  DXVK: v1.2.3
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  Failed to create Vulkan 1.1 instance, falling back to 1.0
info:  GeForce GTX 1080:
info:    Driver: 430.26.0
info:    Vulkan: 1.1.99
info:    Memory Heap[0]: 
info:      Size: 8192 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 11981 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
info:  Process set as DPI aware
info:  Game: SWTFU Launcher.exe
info:  DXVK: v1.2.3
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  Failed to create Vulkan 1.1 instance, falling back to 1.0
info:  GeForce GTX 1080:
info:    Driver: 430.26.0
info:    Vulkan: 1.1.99
info:    Memory Heap[0]: 
info:      Size: 8192 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 11981 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
info:  Process set as DPI aware
info:  Enabled device extensions:
info:    VK_EXT_conditional_rendering
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_host_query_reset
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  DXVK: Read 12 valid state cache entries
info:  DXVK: Using 12 compiler threads
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  D3D9DeviceEx::ResetEx:
  Requested Presentation Parameters
    - Width:              1
    - Height:             1
    - Format:             X8R8G8B8
    - Auto Depth Stencil: false
    - Windowed:           true

warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 9
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 16
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 37
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 38
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 136
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 142
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 154
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 155
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 158
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 161
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 166
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 172
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 173
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 178
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 179
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 182
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
  Buffer size:  506x785
  Image count:  2
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
  Buffer size:  506x785
  Image count:  2
err:   D3D9: GetBackBuffer: iBackBuffer > 0 not supported
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
  Buffer size:  506x785
  Image count:  2
err:   D3D9: GetBackBuffer: iBackBuffer > 0 not supported
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
  Buffer size:  450x135
  Image count:  2
err:   D3D9: GetBackBuffer: iBackBuffer > 0 not supported
info:  Game: SWTFU Launcher.exe
info:  DXVK: v1.2.3
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  Failed to create Vulkan 1.1 instance, falling back to 1.0
info:  GeForce GTX 1080:
info:    Driver: 430.26.0
info:    Vulkan: 1.1.99
info:    Memory Heap[0]: 
info:      Size: 8192 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 11981 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
info:  Process set as DPI aware
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
  Buffer size:  450x466
  Image count:  2
err:   D3D9: GetBackBuffer: iBackBuffer > 0 not supported
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
  Buffer size:  450x466
  Image count:  2
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
  Buffer size:  450x466
  Image count:  2
Waiting on children
Waiting on children
wine: Unhandled exception 0xe06d7363 in thread 72 at address 0x7b44667c (thread 0072), starting debugger...
All children gone
Exit with returncode 0
```

I'll delete the current wine prefix and make a clean one to see if anything changes I case something got messed up by experiments and report back later :)

**Comment by tannisroot** [comment]
>The game wont even start with any non tkg wine build.

@VortexAcherontic `ge-protonified` builds should pretty much indentical to TKG builds.

**Comment by VortexAcherontic** [comment]
And how can I fix the error message appearing with the ge builds?
Is it an issue with the prefix or with something else?

`wine: Call from 0x7b453dac to unimplemented function shell32.dll.SHGetFolderPathW, aborting
wine: Unimplemented function shell32.dll.SHGetFolderPathW called at address 0x7b453dac (thread 000b), starting debugger...`

**Comment by VortexAcherontic** [comment]
@tannisroot and @K0bin after resetting the prefix and doing a clean install everything seems to work as intended.

So it was probably me fiddling around with the prefix and forgetting what I changed ^^"

![Screenshot_20190709_230624](https://user-images.githubusercontent.com/11244092/60922953-2fae5f00-a29e-11e9-8cb4-906cd7320fa2.png)
