### ISSUE TITLE
Beyond Good and Evil has multiple graphical issues

### ISSUE THREAD

**Issue by CartoonFan** [Joshua-Ashton/d9vk#195]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Beyond Good and Evil (GOG)

### System information
- GPU: Nvidia GeForce GTX 960
- Driver: 430.26.0
- Wine version: 4.12 TKG
- DXVK version: https://github.com/Joshua-Ashton/d9vk/commit/44e961c83ffd8ad5daf9b4e83eb7d831fdb28739

### Apitrace file(s)
https://drive.google.com/file/d/1eSGC2SHqAdvR0GGgbUYHOtZQond50A6a/view?usp=sharing (Around 1.1 GB compressed, 6.1 GB uncompressed)

### Log files
- d3d9.log: [BGE_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3365373/BGE_d3d9.log)

The in-game graphics seem to be...wrong. For example, the eye colors are unusual and the screen seems to overlaid with a pink filter that disappears after opening a menu, and the character intros are not displayed. The log is from playing somewhat longer than the apitrace, so I don't know if the "DOTPRODUCT" thing is in the apitrace. Also, the native Windows had flickering and stuff, so I don't know if that made it in. Thanks!

EDIT: Just wanted to give everyone an update on the progress made since I opened this bug.

Some things have improved:
- [x] Some text invisible

D9VK:

![20190810-181022](https://user-images.githubusercontent.com/29664894/62828421-d5edcd00-bb9a-11e9-8f16-e132e52e3414.png)
![20190810-172324](https://user-images.githubusercontent.com/29664894/62828428-0df51000-bb9b-11e9-8d78-69064fbc2f63.png)

- [x] Menu rendering

D9VK:

![20190810-172440](https://user-images.githubusercontent.com/29664894/62828435-3250ec80-bb9b-11e9-9635-c9cb2e8bc2b6.png)
![20190810-172452](https://user-images.githubusercontent.com/29664894/62828437-3aa92780-bb9b-11e9-9da5-d368d683a786.png)
![20190810-172552](https://user-images.githubusercontent.com/29664894/62828444-51e81500-bb9b-11e9-9b70-e0bc15e12ce8.png)

- [x]  Fog effect obscures much of the graphics

D9VK:

![20190815-174558](https://user-images.githubusercontent.com/29664894/63135990-d1535b00-bf84-11e9-908e-2202460e85f8.png)

- [x]  No clouds present

D9VK:

![20190916-184454](https://user-images.githubusercontent.com/29664894/65004926-01a75580-d8b3-11e9-90f0-a7ea795a5581.png)

Native:

![20190811222124_1](https://user-images.githubusercontent.com/29664894/62847689-65bf7400-bc8c-11e9-9b6a-cb1d9e9cdd2f.jpg)

- [x]  No sun present

D9VK:

![20190916-184454](https://user-images.githubusercontent.com/29664894/65004926-01a75580-d8b3-11e9-90f0-a7ea795a5581.png)

Native:

![20190811222124_1](https://user-images.githubusercontent.com/29664894/62847689-65bf7400-bc8c-11e9-9b6a-cb1d9e9cdd2f.jpg)

- [x]  NPC Eye colors are strange

D9VK:

![20190913-124354](https://user-images.githubusercontent.com/29664894/64893302-8d0eb580-d62b-11e9-8ad0-eb6f286ae09a.png)
![20190913-124126](https://user-images.githubusercontent.com/29664894/64893301-8d0eb580-d62b-11e9-9dfc-539a3da9aeea.png)

Native:

![20190811222853_1](https://user-images.githubusercontent.com/29664894/62847759-ce0e5580-bc8c-11e9-8329-b250f75ea5d8.jpg)
![20190811222810_1](https://user-images.githubusercontent.com/29664894/62847773-df576200-bc8c-11e9-8435-14e26a630d0f.jpg)

- [x]  "Streaked" textures

D9VK:

![20190913-135532](https://user-images.githubusercontent.com/29664894/64894766-78342100-d62f-11e9-8295-1a40107efc87.png)
![20190913-135922](https://user-images.githubusercontent.com/29664894/64894767-78ccb780-d62f-11e9-8acd-4b05a4d3baa0.png)

Native:

![20190811222907_1](https://user-images.githubusercontent.com/29664894/62847849-686e9900-bc8d-11e9-975f-1123f6553ad4.jpg)

- [x] Buttons not in proper position

D9VK:

![20190913-135235](https://user-images.githubusercontent.com/29664894/64894872-c34e3400-d62f-11e9-9288-e2f83f63eecf.png)
![20190913-135401](https://user-images.githubusercontent.com/29664894/64894873-c34e3400-d62f-11e9-8025-e42095f59e3c.png)

Native:

![20190811223354_1](https://user-images.githubusercontent.com/29664894/62848359-2dba3000-bc90-11e9-9996-6f40d11f722f.jpg)
![20190811223430_1](https://user-images.githubusercontent.com/29664894/62848375-3ad71f00-bc90-11e9-892b-b8db131fd7c0.jpg)

Some issues remain:

- [ ]  Minor text glitches around certain letters (N and S, for example)

D9VK :

![20190810-181013](https://user-images.githubusercontent.com/29664894/62828745-a0e57880-bba2-11e9-8440-f8b4d9b81028.png)

Native:

![20190811222016_1](https://user-images.githubusercontent.com/29664894/62847579-d87c1f80-bc8b-11e9-8b4f-25d4dc7e20b2.jpg)

- [ ]  Camera effect is warped

D9VK:

![20190810-172217](https://user-images.githubusercontent.com/29664894/62828476-7db7ca80-bb9c-11e9-829a-837494b5860e.png)
![20190810-173049](https://user-images.githubusercontent.com/29664894/62828484-a9d34b80-bb9c-11e9-978b-a5d9f5a9fda5.png)

Native:

![20190811222038_1](https://user-images.githubusercontent.com/29664894/62847600-fe092900-bc8b-11e9-85e5-9cf76a31698c.jpg)
![20190811222941_1](https://user-images.githubusercontent.com/29664894/62847607-05c8cd80-bc8c-11e9-9609-b508ee19e19f.jpg)

- [ ]  "Glow" missing on planet

D9VK:

![20190916-184426](https://user-images.githubusercontent.com/29664894/65004987-31eef400-d8b3-11e9-8bbb-9dc7776b3443.png)

Native:

![20190811222054_1](https://user-images.githubusercontent.com/29664894/64893049-f3df9f00-d62a-11e9-9bff-4aa0f38c0c32.jpg)

- [ ]  Character portraits obscured by white screen

D9VK:

![20190913-130908](https://user-images.githubusercontent.com/29664894/64893176-491bb080-d62b-11e9-9dfb-8a42fdbef372.png)

Native:

![20190811222149_1](https://user-images.githubusercontent.com/29664894/64893161-3bfec180-d62b-11e9-9605-8b2740368086.jpg)

- [ ] Protagonist eye colors are strange

D9VK:

![20190913-130842](https://user-images.githubusercontent.com/29664894/64891949-10c6a300-d628-11e9-88f8-afc48c1041ed.png)

Native:

![20190811222136_1](https://user-images.githubusercontent.com/29664894/62847697-740d9000-bc8c-11e9-8c53-9baba9dfb0f4.jpg)

- [ ]  Reflection issues

D9VK:

![20190810-172525](https://user-images.githubusercontent.com/29664894/62839366-020e5a00-bc3e-11e9-8893-04477ce967ee.png)

Native:

![20190811222336_1](https://user-images.githubusercontent.com/29664894/62847806-1c235900-bc8d-11e9-9bcc-8f1b456dbbca.jpg)

Anyway, that's about it. I know that was a lot of photos, but I thought they'd be helpful for describing what's happened. With the last issue, I may make another trace now that I know what I'm looking for.

EDIT 2: The new trace is done! It's a little bit longer than the first one, but I did more, so it's OK, I hope.

**Comment by Joshua-Ashton** [comment]
Yeah this renders as complete garbage for me on AMDVLK -- until you play with the menu. I'll take a look later :-)

**Comment by Joshua-Ashton** [comment]
Managed to get the pink filter you were talking about. This has fixed function resource hazards, that's a pain.

**Comment by CartoonFan** [comment]
All right, good luck! Is there anything else I can provide to help?

**Comment by NerosTie** [comment]
With #759, the sound in the first cutscene is not repeated but the sound is repeated in the main menu... It's related to d9vk, with previous versions it was the opposite.

**Comment by CartoonFan** [comment]
I agree, although I imagine it's still an effect of [this bug](https://bugs.winehq.org/show_bug.cgi?id=13046). Maybe the game is running more smoothly, so it doesn't get hung up at the main menu and doesn't loop as a result? I noticed some looping in the language selection screen if I don't wait there long enough.

**Comment by Joshua-Ashton** [comment]
I don't touch sound/audio at all, so I'm not too sure how this is possible. You sure you're not hitting some weird Wine bug?

**Comment by NerosTie** [comment]
@Joshua-Ashton Yes, I'm sure, there is a difference when you change the version of d9vk.

**Comment by CartoonFan** [comment]
It seems like an A/V sync issue, from what I can guess.

**Comment by CartoonFan** [comment]
The trace seems to have an issue that's not on D9VK or native Windows. This shadow appears in the menu portions of the trace:
![20190811-001906](https://user-images.githubusercontent.com/29664894/62831340-54b22c80-bbd2-11e9-9206-4b3c41305afd.png)

I'll try a few things to see if I can isolate the cause.

**Comment by NerosTie** [comment]
@CartoonFan wow, thanks for your work!

But now, I have something I really don't understand: the sound loop is reversed... again. How is that even possible? It's the same version of d9vk as before (#759). Could it be related to the Nvidia driver? The kernel? Something else?

**Comment by CartoonFan** [comment]
@NerosTie I agree. While I don't know the cause, if it happens in different places when using the same version of d9vk...It might be something else. The audio doesn't seem always seem to follow the video, even on Windows, but the audio does seem to be affected in Wine by when the game decides to unload the looping sound and load the next one, which usually starts a new loop. If I remember correctly, the loops seem to happen around certain events:

- Between the language selection and the title
- The title
- The beginning of the intro dialogue

I think the start of the music at the first battle seems to stop the current loop, and fixes things temporarily. I can't remember where the next loop happens, but it's very reproducible, usually even at the same spots, so I could just check if it's important enough. 

I guess what I'd like to say is that the cause is the dsound driver (since changing it to native fixes the issue), but perhaps performance is more variable in D9VK? I'm really not sure, though.

**Comment by NerosTie** [comment]
> I guess what I'd like to say is that the cause is the dsound driver (since changing it to native fixes the issue),

I can confirm, it doesn't loop anymore, but the sound is not synchronized, unfortunately.

**Comment by CartoonFan** [comment]
Yeah, that's an unfortunate side effect. Maybe [this fix](https://pcgamingwiki.com/wiki/Beyond_Good_%26_Evil#Audio_desynchronized_in_cutscenes) might help?

**Comment by NerosTie** [comment]
Tried with "strangle 60" but it doesn't even effective in the game with d9vk or vulkan (without d9vk + "strangle 50" it works).

So the game is probably running too fast. Can we say it's related to d9vk or not?

**Comment by CartoonFan** [comment]
I can't get the same results with strangle 50 + native dsound. The audio plays before the subtitles almost every time I try, d9vk or otherwise. At the moment, it doesn't seem like a direct d9vk thing to me, but if you have an issue where audio works properly with wined3d, but not with d9vk, it might be worth investigating.

**Comment by NerosTie** [comment]
> I can't get the same results with strangle 50 + native dsound

With d9vk or native?

**Comment by CartoonFan** [comment]
Either one. The audio keeps playing ahead of the video.

**Comment by NerosTie** [comment]
Yes, you are right.

**Comment by Mephistople** [comment]
Seems at least the fog is gone now, as with #767 2b6f0111 at least
![fogbegone](https://user-images.githubusercontent.com/53997310/63044855-a30b4800-bebe-11e9-9241-48554ee422a7.png)

**Comment by NerosTie** [comment]
Great!   
@Mephistople how do you cap the game to 60 fps?

**Comment by Mephistople** [comment]
I don't think the game support higher fps than 60, as far as I know.
Maybe it's different on higher refresh rates monitor, not sure.
These are the settings i used in the settings application at least:

![Graphics Settings](https://user-images.githubusercontent.com/53997310/63048294-c4bbfd80-bec5-11e9-97df-def709656a0b.png)
![advanced settings](https://user-images.githubusercontent.com/53997310/63048311-cc7ba200-bec5-11e9-856c-56995a43bb26.png)

**Comment by Mephistople** [comment]
I don't think the game support higher fps than 60, as far as I know.
Maybe it's different on higher refresh rates monitor, not sure.
These are the settings i used in the settings application at least:

![Graphics Settings](https://user-images.githubusercontent.com/53997310/63048294-c4bbfd80-bec5-11e9-97df-def709656a0b.png)
![advanced settings](https://user-images.githubusercontent.com/53997310/63048311-cc7ba200-bec5-11e9-856c-56995a43bb26.png)

**Comment by NerosTie** [comment]
I have more than 200 fps, so the game is very fast!

I will not try to solve it, I have a patched kernel, beta drivers for the Nvidia GPU and a patched xorg-server... (optimus is finally working :tada: )

But something like "strangle" which would work with vulkan would be useful to test BGE.

**Comment by CartoonFan** [comment]
> Seems at least the fog is gone now, as with #767 [2b6f011](https://github.com/Joshua-Ashton/d9vk/commit/2b6f011160be478fdc0fe65904e9d7698776ca05) at least
> ![fogbegone](https://user-images.githubusercontent.com/53997310/63044855-a30b4800-bebe-11e9-9241-48554ee422a7.png)

I agree, although it seems that the character intros display a completely white screen instead of the character's name now.

**Comment by Mephistople** [comment]
With #836 b385e24b issues related to "Streaked" textures and "Buttons not in proper position" has been fixed.

![Ground don't have  streaking  textures anymore](https://user-images.githubusercontent.com/53997310/64877135-49727680-d640-11e9-82e8-2f0d57c8e191.png)
![Buttons now in their right place](https://user-images.githubusercontent.com/53997310/64877142-4d05fd80-d640-11e9-9b59-ca7978a5b934.png)

**Comment by NerosTie** [comment]
But her eyes are still black!

**Comment by Mephistople** [comment]
huh not sure why he closed it already, 
all of the other issues except those two are still present.

Also found this while testing this build, not sure when it was introduced.
Might been a while ago.
Present both in the menus and the intro cutscene.
 
![same with menus](https://user-images.githubusercontent.com/53997310/64883507-15528200-d64f-11e9-8865-2bcc6dfcd803.png)
![Issues with intro cutscene](https://user-images.githubusercontent.com/53997310/64883521-1c799000-d64f-11e9-8ac8-de8650b7143e.png)

Maybe it's related to this issue #344

**Comment by Joshua-Ashton** [comment]
I was not aware there were more issues, sorry!

**Comment by CartoonFan** [comment]
> I was not aware there were more issues, sorry!

Sorry about that. I didn't see the recent updates until just a little while ago.

**Comment by Mephistople** [comment]
Downgraded my nvidia driver from 435.21 to 430.40, and it seems to fix the rectangles glitch.
So nothing wrong with d9vk in this case.

**Comment by NerosTie** [comment]
@Mephistople My Nvidia driver is 435.21 and I don't have these triangles.

![20190913222314_1](https://user-images.githubusercontent.com/4572452/64892648-45148080-d675-11e9-973e-3922c2c8af3c.jpg)

**Comment by CartoonFan** [comment]
I updated the main post to hopefully reflect the current state of things.

**Comment by Mephistople** [comment]
Thanks to #847 1dfe1a58, the sun is shining in Hillys.

![Sunspots](https://user-images.githubusercontent.com/53997310/64997058-24476780-d8cf-11e9-88b5-cc349b1a50c1.png)

**Comment by CartoonFan** [comment]
The sun's there, all right. The planetary glow issue's coming along well, too.

D9VK:
![20190916-184426](https://user-images.githubusercontent.com/29664894/65005062-737f9f00-d8b3-11e9-8c7f-7fbc2fbd0dcf.png)

Native:
![20190811222054_1](https://user-images.githubusercontent.com/29664894/65005080-898d5f80-d8b3-11e9-8c09-883eaadaf57b.jpg)

**Comment by NerosTie** [comment]
Take note that, 16 years later, BGE has been updated:

https://steamcommunity.com/app/15130/discussions/0/1609400247625380058/

(and now the game is only in english, thanks Ubi, french company and french game...)

**Comment by CartoonFan** [comment]
SettingsApplication doesn't work with D9VK for me. I posted a bug(#290), but apitrace couldn't grab anything, so it hasn't gone anywhere. One more thing to try now that apitrace has been updated, I guess.

As for the update:
Controller support! :smiley: 
English only! :confused: 
No buttton prompts! :unamused: 
UI stretching issues at 1080p! :astonished:  
10-40 FPS! :open_mouth: 

I haven't tried it myself, yet, but the comments that you linked to don't sound too good. You would think that they'd test and code more carefully for a 16-year-old game, but I guess not, if the reports can be believed. I have it on GOG, so hopefully they'll fix this stuff by the time the "update" rolls out there.

**Comment by NerosTie** [comment]
> SettingsApplication doesn't work with D9VK for me.

But even without d9vk I don't know how to launch it properly.

I think there is a curse with this game to be the worst port ever...

**Comment by CartoonFan** [comment]
Are you getting some kind of error message? It usually works after I set d3d9 to builtin through winecfg.

> I think there is a curse with this game to be the worst port ever...

Well, I think there are still worse ports out there, but, yeah, I agree, I guess.

**Comment by Mephistople** [comment]
Testet now with a recent job #997 4caa51ff.
And now all the remaining issues might be fixed.

![text in menues](https://user-images.githubusercontent.com/53997310/69825271-9826ba00-1206-11ea-9a14-ebd6b1414948.png)
![camera effect works](https://user-images.githubusercontent.com/53997310/69825286-a4ab1280-1206-11ea-9006-e800ae354ff7.png)
![EYES](https://user-images.githubusercontent.com/53997310/69825300-ad9be400-1206-11ea-9cc5-06e6140d6bf6.png)
![Character portraits  displays normally](https://user-images.githubusercontent.com/53997310/69825309-b2f92e80-1206-11ea-82e7-17238995179c.png)
![Reflection on the disc](https://user-images.githubusercontent.com/53997310/69825314-b7bde280-1206-11ea-96e6-a8af9498019b.png)

**Comment by CartoonFan** [comment]
Looks good to me, as well. I think we can finally close this.

Closing #195.
