### ISSUE TITLE
System Shock 2 textures change when player moves

### ISSUE THREAD

**Issue by CartoonFan** [Joshua-Ashton/d9vk#196]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
System Shock 2 (GOG)

### System information
- GPU: Nvidia GeForce GTX 960
- Driver: 430.26.0
- Wine version: 4.12 TKG
- DXVK version: https://github.com/Joshua-Ashton/d9vk/commit/44e961c83ffd8ad5daf9b4e83eb7d831fdb28739

### Apitrace file(s)
https://drive.google.com/file/d/1Cp0BLzGWt7tsnSxhr1r5etKQk62zbg_j/view?usp=sharing

### Log files
- d3d9.log:
[Shock2_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3365438/Shock2_d3d9.log)
[SS2_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3365440/SS2_d3d9.log)

In the game, the textures seem to change as you move, appearing to bend or warp. It's a pretty distracting effect, I think.

**Comment by Joshua-Ashton** [comment]
Looks like perspective correction is borked from a quick look. (ie w = 1)

Investigating now :-)

**Comment by Joshua-Ashton** [comment]
Oh wow, this game renders everything in window space! That's absolutely mental.

**Comment by Joshua-Ashton** [comment]
Fixed by https://github.com/Joshua-Ashton/d9vk/commit/6b6d7ab57c2821ac1891a7660c869295d79ada62
