### ISSUE TITLE
Need for Speed Underground: Artifacts on reflections, visible window and broken minimap

### ISSUE THREAD

**Issue by BlackDragonDv** [Joshua-Ashton/d9vk#197]
When using D9VK with Need for Speed Underground there are artifacts on road reflections, minimap doesn't show road (only start&end line and player&opponents indicators). There is also visible window border after starting any race which stays after race end. None of these bugs occur on wined3d excluding visible border - it's visible on Wine too but setting virtual desktop fixes problem (not for D9VK which have visible border no matter if virtual desktop is enabled or not). It's caused probably by mode change after race starts.

I also made screenshots
wined3d: ![wined3d](https://user-images.githubusercontent.com/20561200/60770729-a00e8200-a0de-11e9-9d1c-4e303562a34d.png)

d9vk: ![d9vk](https://user-images.githubusercontent.com/20561200/60770737-ae5c9e00-a0de-11e9-9b54-660843c57336.png)

### Software information
Need for Speed Underground (CD version)
Widescreen fix is also used (to force 1080p resolution) but without it situation looks same. It's not caused by it.
It seems visible window is common bug with this game (reported couple of time on WineHQ). Since it doesn't occur with virtual desktop on wined3d and always occur on d9vk I think it's worth reporting.

### System information
- GPU: Radeon RX 570
- Driver: Mesa 19.1.1 LLVM 8.0.0
- Wine version: 4.11 Staging
- DXVK version: https://github.com/Joshua-Ashton/d9vk/commit/44e961c83ffd8ad5daf9b4e83eb7d831fdb28739

### Apitrace file(s)
- https://drive.google.com/open?id=1Oo6x44PvJQo1FrAGA25Cin8R3x4YEuwz

### Log files
- d3d9.log: [speed_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3365836/speed_d3d9.log)

**Comment by ivan89el** [comment]
In the screenshots you can see the lack of light from the headlights. All these problems are present in NFS Underground 2.

**Comment by BlackDragonDv** [comment]
@ivan89el Yeah you're right. No idea why i didn't mentioned this. U1 and U2 works on same engine (correct me if I'm wrong) so fixing it for U1 should fix U2 also. I tried D9VK on NFS Carbon too and it was working without problems and basically with no differences to wined3d (well, performance was better).

**Comment by ivan89el** [comment]
@BlackDragonDv now it works well.

**Comment by NerosTie** [comment]
Thanks!

I can't make a report now, but I also noticed that the game switches to windowed mode before a race. Only happens with d9vk.

**Comment by DragonSWDev** [comment]
Yup, it's definitely fixed now. Window border is still visible after mode change but rendering itself is fine. Thanks!
