### ISSUE TITLE
The Sims 3 crashes upon loading a lot

### ISSUE THREAD

**Issue by akeart** [Joshua-Ashton/d9vk#199]
The Sims 3 crashes when loading a lot

### Software information
The Sims 3, Windowed, Ultra

### System information
- GPU: RX 580
- Driver: amdgpu 4.5 Mesa 19.0.6
- Wine version: 4.9
- DXVK version: 0.13

### Log files
- [TS3_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3373670/TS3_d3d9.log)

**Comment by akeart** [comment]
[TS3_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3373856/TS3_d3d9.log)
Here's another log with loglevel 1

**Comment by K0bin** [comment]
The logs dont show anything out of the ordinary, could you post the terminal output?

**Comment by Joshua-Ashton** [comment]
Can you give me more info about your graphics setup? Cheers.

**Comment by akeart** [comment]
> Can you give me more info about your graphics setup? Cheers.

Sure, give me details you need

**Comment by Joshua-Ashton** [comment]
What version of LLVM are you using?

**Comment by akeart** [comment]
> What version of LLVM are you using?
7.0.0 which is the latest version on Solus, so if it's LLVM the issue concerns more people than just me.

**Comment by tannisroot** [comment]
@akeart I've just tested the game myself on Nvidia and I observe no crashes. Perhaps Solus maintainers should be notified that their outdated LLVM might be causing issues?

**Comment by akeart** [comment]
Hello. As Solus updated LLVM to 8 and the issue still persists, I suppose it's a Solus issue.
