### ISSUE TITLE
Everquest 2 Black Screen

### ISSUE THREAD

**Issue by ronoverdrive** [Joshua-Ashton/d9vk#20]
Observed Results: Black Screen on start up. This happens on both Windows 10 and WINE.

### Software information
Everquest 2

### System information
- GPU: Geforce GTX 980Ti (Linux), Geforce GTX 960 (Windows)
- Driver: 418.52.03 and 425.31 respectively
- Wine version: WINE-TKG 4.5 Git Master
- DXVK version: git master

### Apitrace file(s)
- [Everquest2.7z](https://mega.nz/#!PGpVhC4B!MrF2_iB2m1QlPzEfZyraPE0_2jP2e0iHmu4TZ2H_QOY)
### Log files
- d3d9.log: [EverQuest2_d3d9.log](https://mega.nz/#!rGoBSQoA!g4IohjOjetXIHTL5LsCyBJF24_HAuwvGSb4Ach8v0zc)

**Comment by neVERberleRfellerER** [comment]
Is this good?
![Screenshot_20190508_000739](https://user-images.githubusercontent.com/11160972/57336444-2ed64100-7126-11e9-970d-be2d08bc1d86.jpg)

If so, check what native d3dx9_something game wants (try `strings *.exe *.dll | grep -i '\.dll$' | sort -fu | grep -i d3dx` in directory with game exe files) and use native versions of what it prints.
