### ISSUE TITLE
Clarification for "Please do not use wine's d3d9x or d3dcompiler with d9vk"?

### ISSUE THREAD

**Issue by Espionage724** [Joshua-Ashton/d9vk#200]
I was under the impression originally that this meant to not install DX9 from winetricks, but another person pointed out it's the opposite (not to use the default Wine DX9 but install it via winetricks).

I'm wondering if there could be some clarification as to what exactly is meant by this?

**Comment by K0bin** [comment]
D9VK implements D3D9.
D3D**X**9 is a extension library that builds on top of normal D3D9 (or D9VK in this case).
D3DCompiler is used to compile HLSL shaders to D3D Bytecode which gets fed into D9VK.

> **Please** do not use wine's `d3d9x` or `d3dcompiler` with d9vk. They make invalid API calls and generate bad shaders. ***I cannot stress this enough.***
That means you have to use the Microsoft versions of the dlls which you can install using Winetricks.

**Comment by Espionage724** [comment]
So just to be sure, if I use D9VK, it's necessary (according to the disclaimer) to also install some d3d9 package via winetricks? If so, what packages would be needed?

Looking at [winetricks](https://github.com/Winetricks/winetricks/blob/master/src/winetricks), it looks like there's an entry for D9VK, and [if I'm reading it right](https://github.com/Winetricks/winetricks/blob/master/src/winetricks#L6748), it looks like it installs `d3dcompiler_43` and `d3dx9`. But there's several other d3dcompiler_4* packages it seems too.

**Comment by K0bin** [comment]
Which d3dcompiler and d3dx9 entry you need depends on what the game loads. You can however just install all of them and that should be fine.

**Comment by Joshua-Ashton** [comment]
Basically what @K0bin said.

**Comment by shmerl** [comment]
Is there any way to fix Wine's versions not to have such problems? It would be better to avoid using blobs.

**Comment by K0bin** [comment]
Sure they are fixable but that's a lot of work and the backlog for the Wine guys is already pretty long right now.

**Comment by shmerl** [comment]
Are there known Wine bugs to track these?

**Comment by Espionage724** [comment]
Is this still relevant now that D9VK is merged with DXVK?

**Comment by K0bin** [comment]
Yes and it will be until Wine fix their implementations of those dlls.

**Comment by shmerl** [comment]
Is there a relevant bug to follow for this on the Wine bug tracker?
