### ISSUE TITLE
They Are Billions: Fonts fail to render

### ISSUE THREAD

**Issue by BangL** [Joshua-Ashton/d9vk#204]
Fonts completely fail to render.
EDIT: This issue is not new and always persisted, since i began testing a few weeks ago.

Here is how its looking with d9vk right now:
![TAB-d9vk](https://user-images.githubusercontent.com/551400/61126757-9fdeff80-a4ad-11e9-832e-d1ad6477809a.png)

Here is how it should look like (screenshot made with wined3d):
![TAB-wined3d](https://user-images.githubusercontent.com/551400/61126722-8e95f300-a4ad-11e9-9d62-a81ae016e439.png)

### System information
- GPU: Nvidia GTX 1050 Ti
- Driver: Nvidia 430.34-53 long lived
- Proton version: Proton 4.12.1.r4 (staging, esync)
- D9VK version: latest master branch (ed02e5)
- Winetricks: corefonts, gdiplus, dotnet472
- additionally installed to wine prefix: SlimDX (January 2012)

### Log files
[steam-644930.log](https://github.com/Joshua-Ashton/d9vk/files/3386334/steam-644930.log)

i've cut the log at around 3000 lines, because the game spams a lot of the failing textures at start (the top counter has a counting animation), therefore my original log was 700MB after just a few seconds. :D
Should not be important to have the full log though, since the same issue basically just repeats itself over and over again.

**Comment by Joshua-Ashton** [comment]
Can you get me a trace of this (preferably with WineD3D) so I can debug this? Cheers

**Comment by BangL** [comment]
i would love to, but i am honestly sure know how to do that wrapped inside of steam/proton :/

**Comment by BangL** [comment]
well. not a trace, but an actual debug log of d9vk..
[TheyAreBillions_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3390653/TheyAreBillions_d3d9.log)

so far, i didnt manage to get an apitrace out of this, still working on it..

**Comment by Joshua-Ashton** [comment]
Ah, looks like an issue I might have fixed recently. Can you try the latest master?

Builds available here:
https://git.froggi.es/joshua/d9vk/-/jobs

**Comment by BangL** [comment]
ha..
yup.. it is indeed fixed already now.
nice job! :)

**Comment by Joshua-Ashton** [comment]
ty enjoy :-)
