### ISSUE TITLE
Torchlight → textures issues

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#207]
![with d9vk](https://user-images.githubusercontent.com/4572452/61143792-7d5fdd00-a4d3-11e9-8975-067dab34a662.jpg)
![without d9vk](https://i.imgur.com/mtokd7j.jpg)

### Software information
![20190712183815_1](https://user-images.githubusercontent.com/4572452/61144120-4d650980-a4d4-11e9-88bf-91d70cc77fd1.jpg)

### System information
- GPU: Nvidia GT 730M
- Driver: 430.26-9
- Wine version: Proton 4.2
- DXVK version: 1.1.99

### Apitrace file(s)

[steam.trace.tar.gz](https://github.com/Joshua-Ashton/d9vk/files/3387259/steam.trace.tar.gz)

### Log files
[Torchlight_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3387260/Torchlight_d3d9.log)

**Comment by varris1** [comment]
https://github.com/Joshua-Ashton/d9vk/commit/6e30b504a0bc5f9b6091946dd5e1b12f2bf5a33d
should fix that

**Comment by Joshua-Ashton** [comment]
This was fixed (or at least, should be) before you made the issue ;P

Your time is appreciated however :-)

**Comment by NerosTie** [comment]
![20190714191847_1](https://user-images.githubusercontent.com/4572452/61187103-f85cfb00-a66d-11e9-9fa0-8f41d1047468.jpg)

With the last master, the textures are fixed but there is still a lighting issue.

The apitrace: (without d9vk installed):
https://mega.nz/#!bm5XzQja!RV4Dkj-V0FwA3ArUo2Oga_UZ08me9YGyA2UTxQuo9Y4

**Comment by Joshua-Ashton** [comment]
Known, FF lighting isnt implemented right now

**Comment by NerosTie** [comment]
Tested with #759, now some elements are blueish.

![20190810125153_1](https://user-images.githubusercontent.com/4572452/62821024-f5bacc00-bb6d-11e9-9b38-8686b1c19ccf.jpg)
