### ISSUE TITLE
Skydrift → crash after the logos

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#208]
You can see the first screen with all the logos then it crashes.

### Software information
Skydrift

### System information
- GPU: Nvidia GT 730M
- Driver: 430.26-9
- Wine version: Proton 4.2
- DXVK version: 0.13

### Apitrace file(s)
[steam.1.trace.tar.gz](https://github.com/Joshua-Ashton/d9vk/files/3387444/steam.1.trace.tar.gz)

### Log files
[SkyDrift_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3387445/SkyDrift_d3d9.log)

**Comment by Joshua-Ashton** [comment]
This is an OpenGL trace which is not useful to me. Please provide a D3D trace.

**Comment by NerosTie** [comment]
Ok, sorry, I definitely don't know what apitrace is...

Should I run:
`DEBUGGER="apitrace trace -dxgi" PROTON_LOG=1 DXVK_HUD=1 steam steam://rungameid/XXXXX`
or:
`DEBUGGER="apitrace trace -d3d9" PROTON_LOG=1 DXVK_HUD=1 steam steam://rungameid/XXXXX`
?

d9vk should be installed or not when I "apitrace" a game?

Thanks

**Comment by K0bin** [comment]
The Windows version of apitrace has a folder called libs/wrappers/. In there you'll find a d3d9.dll. Drop that next to the .exe of your game and start it (preferably with WineD3D). That will generate a D3D9 apitrace which will allow us to replay all D3D calls the game makes.

**Comment by NerosTie** [comment]
Well, I drop the d3d9.dll next to the .exe (SkyDrift.exe), I launch the game (with steam), it works but I don't see where or if a trace has been generated =/

**Comment by K0bin** [comment]
Apitrace for Windows often puts your traces onto the desktop so check that folder inside your Wine prefix.

**Comment by NerosTie** [comment]
Nothing, nowhere....
I'm sure it's not an issue with non-steam games, but with Steam, I have no idea how to use apitrace.

**Comment by K0bin** [comment]
- The game might change the working directory before loading d3d9.dll. See if you find a subdirectory with other dlls.
- Make sure you used the correct apitrace dll for your game. You most likely need the x86 one, not the x64 one.
- Maybe try a different game. You did open a couple of bug reports. Some games don't really work with apitrace.

**Comment by NerosTie** [comment]
Ok, I was stupid. For the records:

1- Download apitrace ([32bits](https://github.com/apitrace/apitrace/releases/download/8.0/apitrace-8.0.20190414-win32.7z))
2- extract d3d9.dll (from lib/wrappers)  and drop that next to the .exe of your game
3- open winecfg (protontricks APPID winecfg)
4- In "library", add d3d9 (native then building)
5- Play the game
6- the trace is in the "Desktop" folder of your prefix. For Steam it's inside [...]/compatdata/APPID/pfx/drive_c/users/steamuser/Desktop

So here is the trace for Skydrift: http://www.mediafire.com/file/ejjc19tt0ta9bxi/SkyDrift.trace/file

@K0bin is that ok? If so, I will upload the other ones.

**Comment by K0bin** [comment]
The steps look good. The trace is a bit small at 78mb but that might be fine if it's an older game and crashes really early.

For the record, please upload your other traces to a different hoster like Mega or Google Drive. Mediafire is really slow and your 80mb trace already takes 15 minutes to download at their rates.

**Comment by NerosTie** [comment]
Ok let's try with Mega and a 10min in the game : https://mega.nz/#!rmhWgAoA!wukmopnG5iGQw-BLAsGwQhEE9NI4N-S8fAzJXmkTBSM

**Comment by K0bin** [comment]
Both traces work perfectly with D9VK. D9VK might be returning something thats broken at some point and the game crashes because of that. The apitrace made with WineD3D or Windows D3D9 would have the correct value and work.

Can you try to make a trace with D9VK running?

**Comment by NerosTie** [comment]
With D9VK running: 
https://mega.nz/#!6jYUUKoI!FPXtte_C_cl5Rr7FlKsLAsBlDSNKIxi9PqJibsnqu3s

**Comment by K0bin** [comment]
Can you check if that PR fixes the issue?

**Comment by NerosTie** [comment]
@K0bin Yes, it doesn't crash anymore ! :tada: 
Unfortunately, in a race, everything is black.

![20190714172154_1](https://user-images.githubusercontent.com/4572452/61185684-67315880-a65c-11e9-915d-7f32bbfb3aad.jpg)

**Comment by K0bin** [comment]
That's a bummer. I guess I need *another* apitrace with D9VK now that it doesnt crash anymore.

Sorry if this is annoying but comparing the traces is the only real way to debug this. Your original WineD3D trace [works fine when replayed](https://i.imgur.com/RdM7sX4.png).

**Comment by NerosTie** [comment]
Don't worry!
https://mega.nz/#!iv4HFYAD!ufwKEMFauUGcovMLCYsfhruernOpw1PzctjdpEVeA38

**Comment by K0bin** [comment]
I think I've identified the issue.

Can you try my branch over at https://github.com/K0bin/d9vk/commits/managed-slice?

**Comment by Joshua-Ashton** [comment]
Works fine for me -- even without that patch.

**Comment by K0bin** [comment]
Should hopefully be fixed for you now. Please retry with the latest master.

**Comment by NerosTie** [comment]
It's not black anymore, but it's glitching.
(btw, compared to the opengl version, the trees are fixed 🌳)

**Comment by Joshua-Ashton** [comment]
Glitching in what way?

**Comment by NerosTie** [comment]
Blinking things and artifacts.

**Comment by K0bin** [comment]
This is honestly getting a bit annoying. Can I ask you for another D9VK apitrace?

**Comment by NerosTie** [comment]
No problem!
https://mega.nz/#!iu5jSIaY!da9dPVv3eYEISSmZ7Bg_q2lB0DKV-O_saKNXDKZsaIY
Tested with the last master.

**Comment by K0bin** [comment]
Thanks, I'll take a look at this later.

**Comment by K0bin** [comment]
Wasn't as clear cut this time. There's a vertex buffer that contains garbage data. We've identified a small issue with the Buffer locking mechanism and fixed that. That *could* be what caused your issue.

Please retest. You can find builds over at: https://git.froggi.es/joshua/d9vk/pipelines

**Comment by NerosTie** [comment]
Nothing changed unfortunately.

**Comment by K0bin** [comment]
We found the issue and fixed it. Please retest. I really hope we're finally done with this game.

**Comment by NerosTie** [comment]
Yes! It works :tada: 
Wow, that's cool! Thanks!
