### ISSUE TITLE
Dead or Alive 5 → "insufficient VRAM"

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#209]
When I launch the game, there is a white screen then a error about VRAM (it works without d9vk)

### Software information
Dead or Alive 5
![Screenshot_20190712_195138](https://user-images.githubusercontent.com/4572452/61148174-7ab6b500-a4de-11e9-9da8-f16273efe68f.png)

### System information
- GPU: Nvidia GT 730M
- Driver: 430.26-9
- Wine version: Proton 4.2
- DXVK version: 0.13

### Apitrace file(s)
~~[steam.trace.tar.gz](https://github.com/Joshua-Ashton/d9vk/files/3387458/steam.trace.tar.gz)~~
https://mega.nz/#!mrog2KJa!ySKt1DfKcYwEFXUtR-k9aNUiWBdddOHNf8Ho7SfOLno

### Log files
[game_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3387459/game_d3d9.log)

**Comment by Joshua-Ashton** [comment]
This is an OpenGL trace which is not useful to me. Please provide a D3D trace.

**Comment by NerosTie** [comment]
D3D trace (without d9vk installed):
https://mega.nz/#!mrog2KJa!ySKt1DfKcYwEFXUtR-k9aNUiWBdddOHNf8Ho7SfOLno

**Comment by NerosTie** [comment]
Could be related: https://github.com/doitsujin/dxvk/issues/1100

**Comment by K0bin** [comment]
That error isn't in the log but the log is also pretty old. I think Josh modified the way D9VK reports available memory since 0.13 so if the error still persists it could indeed be the Nvidia allocation issue.

Would you mind uploading a new log?

**Comment by NerosTie** [comment]
[steam-311730-d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3648061/steam-311730-d3d9.log)
[steam-311730-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3648062/steam-311730-d9vk.log)

Is that ok?

**Comment by K0bin** [comment]
That confirms that its not dxvk#1100. Probably related to `D3D9: GetBackBuffer: iBackBuffer > 0 not supported`

**Comment by NerosTie** [comment]
The issue is gone! 🎉

Unfortunately, the performance is worse than wined3d... (from ~60fps to ~50fps). I don't know why so I leave it open.

(tested with dxvk 1094)

**Comment by misyltoad** [comment]
I will renderdoc and generally profile this tomorrow (could be hitting on waits)

**Comment by NerosTie** [comment]
It looks like the performance issue is related to dxvk:

![Screenshot_20200519_161653](https://user-images.githubusercontent.com/4572452/82337702-5b38c480-99ec-11ea-80e3-3879f05f30b1.png)

With wined3d, the GPU is not overused like this. There are a lot of frames drops with dxvk for some reason.

**Comment by NerosTie** [comment]
Looks like the performances are good now!
