### ISSUE TITLE
TRON 2.0 → No menus

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#210]
With d9vk
![with d9vk](https://user-images.githubusercontent.com/4572452/61148876-13016980-a4e0-11e9-85a2-88a7e5fcf034.jpg)
Without d9vk
![without d9vk](https://user-images.githubusercontent.com/4572452/61148977-4b08ac80-a4e0-11e9-8cb9-697d212de0db.jpg)

### System information
- GPU: Nvidia GT 730M
- Driver: 430.26-9
- Wine version: Proton 4.2
- DXVK version: 0.13

### Apitrace file(s)
~~[steam.1.trace.tar.gz](https://github.com/Joshua-Ashton/d9vk/files/3387500/steam.1.trace.tar.gz)~~
https://mega.nz/#!f64DSSwT!57ZNi36o0YEvX_K8iGyuKw55ITF6PeybSpnITzRQeZg

### Log files
[Lithtech_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3387501/Lithtech_d3d9.log)

**Comment by Joshua-Ashton** [comment]
This is an OpenGL trace which is not useful to me. Please provide a D3D trace.

**Comment by NerosTie** [comment]
D3D trace (without d9vk installed): 
https://mega.nz/#!f64DSSwT!57ZNi36o0YEvX_K8iGyuKw55ITF6PeybSpnITzRQeZg

**Comment by NerosTie** [comment]
Fixed. Test with #725 (jobs).
