### ISSUE TITLE
Cold Fear → lighting issues

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#211]
With d9vk
![with d9vk](https://i.imgur.com/IQhhWyN.jpg)
Without d9vk
![without d9vk](https://i.imgur.com/K1WcAF0.jpg)

### System information

- GPU: Nvidia GT 730M
- Driver: 430.26-9
- Wine version: Proton 4.2
- DXVK version: 0.13

### Apitrace file(s)
~~[steam.2.trace.tar.gz](https://github.com/Joshua-Ashton/d9vk/files/3387576/steam.2.trace.tar.gz)~~
https://mega.nz/#!evQRiKoa!lL1qOOT7Uf758NYnSWwEKiX5T7DLg6ZmVHbHH8xsTfQ

### Log files
[coldfear_retail_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3387577/coldfear_retail_d3d9.log)

**Comment by Joshua-Ashton** [comment]
This is an OpenGL trace which is not useful to me. Please provide a D3D trace.

**Comment by NerosTie** [comment]
D3D trace (without d9vk installed): 
https://mega.nz/#!m3w1wSob!VlaAmKtdVan3ujOQmJYzoL7Ir06qCTOY8odDdlDwd38

**Comment by NerosTie** [comment]
Fixed :tada:   
Tested with #745 (jobs)
