### ISSUE TITLE
Ys Origin → tearing issue

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#212]
With d9vk + "glare"
![](https://i.imgur.com/X83gFp4.jpg)
With d9vk - "glare"
![20190712203617_1](https://user-images.githubusercontent.com/4572452/61150867-c5d3c680-a4e4-11e9-826a-ee8723a26632.jpg)

### Software information
![image](https://user-images.githubusercontent.com/4572452/61150943-f61b6500-a4e4-11e9-923c-ba8ffd9bbf58.png)

### System information
- GPU: Nvidia GT 730M
- Driver: 430.26-9
- Wine version: Proton 4.2
- DXVK version: 0.13

### Apitrace file(s)
~~[steam.3.trace.tar.gz](https://github.com/Joshua-Ashton/d9vk/files/3387631/steam.3.trace.tar.gz)~~
https://mega.nz/#!DnRRwSrC!Y3uknBSfEkR-z98BD4ZQUhSEzBy0b11VeVpipiOcnWM

### Log files
[yso_win_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3387632/yso_win_d3d9.log)

**Comment by Joshua-Ashton** [comment]
This is an OpenGL trace which is not useful to me. Please provide a D3D trace.

**Comment by CartoonFan** [comment]
Here's a D3D apitrace from Windows, if that's helpful: https://drive.google.com/file/d/1dh6VCk_fsV5EmxFSsUluKt60wLE6hOMa/view?usp=sharing

GPU: Nvidia GeForce GTX 960
Driver: 430.26.0
Wine version: 4.12.1 TKG
DXVK version: https://github.com/Joshua-Ashton/d9vk/commit/6e30b504a0bc5f9b6091946dd5e1b12f2bf5a33d

**Comment by NerosTie** [comment]
Personal D3D apitrace: https://mega.nz/#!DnRRwSrC!Y3uknBSfEkR-z98BD4ZQUhSEzBy0b11VeVpipiOcnWM

**Comment by Mephistople** [comment]
When I tested it today with #767 2b6f0111, it seems this issues has been fixed.
![glare enabled](https://user-images.githubusercontent.com/53997310/63117085-9eac6100-bf8a-11e9-97df-63300b9d0f4a.png)

**Comment by NerosTie** [comment]
Yes, it's gone :tada: 

But I see there is a tearing issue with d9vk and this game (and not with wined3d)

**Comment by CartoonFan** [comment]
I think I'm seeing a trend with https://github.com/Joshua-Ashton/d9vk/commit/2b6f011160be478fdc0fe65904e9d7698776ca05 : There are some improvements, but some drawbacks are also introduced as a result.

- In https://github.com/Joshua-Ashton/d9vk/issues/195 , the fog is gone, but the character intros have a white screen

- In https://github.com/Joshua-Ashton/d9vk/issues/212 , the glare is gone, but there's also tearing.

- In https://github.com/Joshua-Ashton/d9vk/issues/291 , the textures are fine, but the game crashes just before loading the first area

- In https://github.com/Joshua-Ashton/d9vk/issues/270 ,  the car colors are normal, but the game had blocky textures the first time I replayed the trace (the problem's gone now, though).

I guess "float emulation" is pretty important, huh?

**Comment by Joshua-Ashton** [comment]
Uh, none of this is related to that commit at all.

**Comment by CartoonFan** [comment]
No? OK, then. Maybe...something else? I mean, I feel like I ran these traces pretty recently. That's cool though, even if it is somewhat mysterious.

**Comment by NerosTie** [comment]
It looks like the tearing issue comes from kwin, the compositor.

But I'm still not sure why v-sync is broken with this game (+Beyond Good and Evil, Outrun 2006)

**Comment by NerosTie** [comment]
I will assume vsync is an issue on my side :man_shrugging:
