### ISSUE TITLE
Full Spectrum Warrior → glitches

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#213]
With d9vk
![20190712204859_1](https://user-images.githubusercontent.com/4572452/61151611-a50c7080-a4e6-11e9-8fa4-5aad13bd46ab.jpg)
Without d9vk
![20190712204314_1](https://user-images.githubusercontent.com/4572452/61151626-ac337e80-a4e6-11e9-9ae5-2feaa9006069.jpg)

### System information
- GPU: Nvidia GT 730M
- Driver: 430.26-9
- Wine version: Proton 4.2
- DXVK version: 0.13

### Apitrace file(s)
~~[steam.trace.tar.gz](https://github.com/Joshua-Ashton/d9vk/files/3387668/steam.trace.tar.gz)~~
https://mega.nz/#!T74TVa4A!43PcEIyI1XX5itxvoeAeF3ALFvvgofGwml3X5hijTKc

### Log files
[Launcher_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3387674/Launcher_d3d9.log)

**Comment by Joshua-Ashton** [comment]
This is an OpenGL trace which is not useful to me. Please provide a D3D trace.

**Comment by NerosTie** [comment]
D3D trace (without d9vk installed): 
https://mega.nz/#!T74TVa4A!43PcEIyI1XX5itxvoeAeF3ALFvvgofGwml3X5hijTKc

**Comment by NerosTie** [comment]
Fixed! 🥳
