### ISSUE TITLE
S.T.A.L.K.E.R. → lighting issues

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#214]
With d9vk
![20190712211902_1](https://user-images.githubusercontent.com/4572452/61153671-3c27f700-a4ec-11e9-98fd-ed14c0636556.jpg)
Without d9vk
![20190712212915_1](https://user-images.githubusercontent.com/4572452/61153710-56fa6b80-a4ec-11e9-8efb-99dd7e6fb338.jpg)

### System information

- GPU: Nvidia GT 730M
- Driver: 430.26-9
- Wine version: Proton 4.2
- DXVK version: 0.13

### Apitrace file(s)
~~[steam.2.trace.tar.gz](https://github.com/Joshua-Ashton/d9vk/files/3387764/steam.2.trace.tar.gz)~~
https://mega.nz/#!T2J3VKwY!cCpDyGMikZCTtwQzaC6Buj_jVJeWzXgcfssnf5Ca26Q
(without d9vk + Static Shadow enabled)

### Log files
The log file is too heavy, 122 Mo!

**Comment by Joshua-Ashton** [comment]
Your trace is OpenGL. Please provide a d3d trace

**Comment by CartoonFan** [comment]
From everything here, I'm guessing that this is from S.T.A.L.K.E.R: Shadow of Chernobyl, right?
I have a d3d trace from the GOG version, but I don't remember seeing these issues.

Apitrace:
https://drive.google.com/file/d/11AT9vAew6tJqosIW5NftintAK9GNuSW4/view?usp=sharing (1.4 G uncompressed)

Log:
[XR_3DA_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3388540/XR_3DA_d3d9.log)

GPU: Nvidia GeForce GTX 960
Driver: 430.26.0
Wine version: 4.12.1 TKG
DXVK version: https://github.com/Joshua-Ashton/d9vk/commit/6e30b504a0bc5f9b6091946dd5e1b12f2bf5a33d

@NerosTie , if you're wondering, a simple way to make d3d traces is to download an apitrace release from https://github.com/apitrace/apitrace and, once you extract it, take the relevant dlls from the wrappers folder and place them in the same folder as the game you want to test. It will make a trace and put it on the desktop.

Also, I had a question for @Joshua-Ashton . Is it important if the D9VK log does not strictly match the gameplay in the apitrace? The logs are usually smaller than the traces, and it's usually easier to do more than what's strictly necessary when I'm trying to get a log from the game, so there's normally more in the log than the relevant issue alone, which hopefully isn't misleading.

**Comment by axredneck** [comment]
Try Full Dynamic Lighting, it works better with D9VK, though still with some glitches.

**Comment by NerosTie** [comment]
@CartoonFan Yes, it's Shadow of Chernobyl, but it's probably the same thing with the 2 others STALKER.

@axredneck The full Dynamic Lighting fixes the 2 issues. So, it's an issue with the Static Shadows.

Here an apitrace withtout d9vk with the Static Shadows option enabled.

https://mega.nz/#!T2J3VKwY!cCpDyGMikZCTtwQzaC6Buj_jVJeWzXgcfssnf5Ca26Q

**Comment by NerosTie** [comment]
For some reason, with Proton 4.11, when I launch the game with `PROTON_USE_D9VK=1`, d9vk is not activated, so the game is running with wined3d. It's the only game with that issue in my list.

**Comment by axredneck** [comment]
@NerosTie it's a problem with Proton, not D9VK

**Comment by NerosTie** [comment]
With #759, but UI is fixed.

The lighting issue is still present.

**Comment by NerosTie** [comment]
Fixed! 🥳
