### ISSUE TITLE
Beyond Divinity → crash at launch

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#215]
Click "play", there is a black screen for 1s then it crashes.

### System information
GPU: Nvidia GT 730M
Driver: 430.26-9
Wine version: Proton 4.2
DXVK version: 0.13

### Apitrace file(s)
~~[steam.3.trace.tar.gz](https://github.com/Joshua-Ashton/d9vk/files/3387816/steam.3.trace.tar.gz)~~
https://mega.nz/#!m2QhwAqa!wwrKjuH8QS_8d8z52lPWCJnfLM4JqcFUYRN0zZTHWDo

### Log files
[steam-219760-d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3638653/steam-219760-d3d9.log)
[steam-219760-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3638654/steam-219760-d9vk.log)

**Comment by Joshua-Ashton** [comment]
This is an OpenGL trace which is not useful to me. Please provide a D3D trace.

**Comment by NerosTie** [comment]
D3D trace (without d9vk installed):
https://mega.nz/#!m2QhwAqa!wwrKjuH8QS_8d8z52lPWCJnfLM4JqcFUYRN0zZTHWDo

**Comment by NerosTie** [comment]
I have a new error when I launch the game:

![Screenshot_20190930_005856](https://user-images.githubusercontent.com/4572452/65840807-8e272e80-e31d-11e9-9f34-0f0b2a0c7b30.png)

**Comment by K0bin** [comment]
Now thats an interesting texture format: `fffffc19`

**Comment by Joshua-Ashton** [comment]
Interesting. Does that popup happen on latest master?

**Comment by NerosTie** [comment]
Both. In fact, it was introduced with #870.

**Comment by NerosTie** [comment]
In a different context, someone has found the source of the error:

https://sourceforge.net/p/dxwnd/discussion/general/thread/29148efa/

> Caught! The problem is in the Direct3D9::CheckDeviceType wrapper that does a harmful operation.

Maybe it can help?

**Comment by NerosTie** [comment]
Duplicate with https://github.com/doitsujin/dxvk/issues/3253

I close this one.
