### ISSUE TITLE
compile error: 'ARRAYSIZE' was not declared in this scope

### ISSUE THREAD

**Issue by CartoonFan** [Joshua-Ashton/d9vk#217]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Name of the game, settings used etc.

### System information
- GPU:
- Driver:
- Wine version: 
- DXVK version: 

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
- dxgi.log: 

D9VK has a fatal error during compilation. I think this is the relevant code:

`FAILED: src/d3d9/ecc23b3@@d3d9.dll@sha/d3d9_adapter.cpp.o 
wineg++ -Isrc/d3d9/ecc23b3@@d3d9.dll@sha -Isrc/d3d9 -I../../d9vk/src/d3d9 -I../../d9vk/./include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++1z -O3 -DNOMINMAX -m64 --no-gnu-unique -fvisibility=hidden -fvisibility-inlines-hidden -fPIC -MD -MQ 'src/d3d9/ecc23b3@@d3d9.dll@sha/d3d9_adapter.cpp.o' -MF 'src/d3d9/ecc23b3@@d3d9.dll@sha/d3d9_adapter.cpp.o.d' -o 'src/d3d9/ecc23b3@@d3d9.dll@sha/d3d9_adapter.cpp.o' -c ../../d9vk/src/d3d9/d3d9_adapter.cpp
../../d9vk/src/d3d9/d3d9_adapter.cpp: In member function ‘HRESULT dxvk::D3D9Adapter::GetAdapterIdentifier(DWORD, D3DADAPTER_IDENTIFIER9*)’:
../../d9vk/src/d3d9/d3d9_adapter.cpp:58:63: error: ‘ARRAYSIZE’ was not declared in this scope
   58 |     std::strncpy(pIdentifier->Description, props.deviceName,  ARRAYSIZE(pIdentifier->Description));
      |                                                               ^~~~~~~~~
winegcc: g++ failed`

The output looks a little better in the terminal, unfortunately when it's pasted here it doesn't look that great. Thanks!

**Comment by Joshua-Ashton** [comment]
What is it with Wine headers and being somehow worse than the MinGW ones...

Thanks for the heads up.

**Comment by CartoonFan** [comment]
You're welcome. Compile errors seem to be pretty rare for d9vk on my end, so I just wanted to let you know.

**Comment by CartoonFan** [comment]
I forgot to mention that there was a warning and a note a little earlier. Maybe it's related?

`[130/154] wineg++ -Isrc/d3d9/ecc23b3@@d3d9.dll@sha -Isrc/d3d9 -I../../d9vk/src/d3d9 -I../../d9vk/./include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++1z -O3 -DNOMINMAX -m64 --no-gnu-unique -fvisibility=hidden -fvisibility-inlines-hidden -fPIC -MD -MQ 'src/d3d9/ecc23b3@@d3d9.dll@sha/d3d9_main.cpp.o' -MF 'src/d3d9/ecc23b3@@d3d9.dll@sha/d3d9_main.cpp.o.d' -o 'src/d3d9/ecc23b3@@d3d9.dll@sha/d3d9_main.cpp.o' -c ../../d9vk/src/d3d9/d3d9_main.cpp
In file included from ../../d9vk/src/d3d9/d3d9_adapter.h:3,
                 from ../../d9vk/src/d3d9/d3d9_interface.h:3,
                 from ../../d9vk/src/d3d9/d3d9_main.cpp:5:
../../d9vk/src/d3d9/d3d9_include.h:15: warning: "DLLEXPORT" redefined
   15 | #define DLLEXPORT
      | 
In file included from ../../d9vk/src/d3d9/d3d9_main.cpp:1:
../../d9vk/src/d3d9/../dxgi/dxgi_include.h:5: note: this is the location of the previous definition
    5 |   #define DLLEXPORT __attribute__((visibility("default")))
      | `

**Comment by Joshua-Ashton** [comment]
For now can you just use MinGW builds

**Comment by CartoonFan** [comment]
OK, sounds good.

**Comment by Joshua-Ashton** [comment]
Should be fixed by 

https://github.com/Joshua-Ashton/d9vk/commit/0fd8fa066ea7202376ccd14b423bc95242af89d5

**Comment by CartoonFan** [comment]
All right, looks like it builds OK. Thanks again.

Closing #217.

**Comment by pchome** [comment]
https://github.com/Joshua-Ashton/d9vk/search?q=countof&type=Commits

@Joshua-Ashton could you share why not `std::size`?
