### ISSUE TITLE
Why not pull request this to proton

### ISSUE THREAD

**Issue by codeman101** [Joshua-Ashton/d9vk#218]
Hey Josh d9vk is awesome. Great work. It solved the graphics issue for me with Fable Anniversary and I'm extremely grateful. I'm curious to know if you've considered integrating this into the proton project as a pull request?

**Comment by Bfgeshka** [comment]
I recall it is planned to merge with dxvk later to have unified directx-to-vulkan layer.

**Comment by codeman101** [comment]
@Bfgeshka Cool. Is there an ETA?

**Comment by K0bin** [comment]
Just the good old 'when it's done'.

**Comment by codeman101** [comment]
@K0bin I'd love to try to help working on it if I can. I got a subscription to clion specifically so I could take a look at the code between the proton repo, the dxvk repo and this one. not sure how much I'll be able to help but I'm looking forward to taking a crack at it when I have the time.:relaxed:

**Comment by Tk-Glitch** [comment]
Integration is very straightforward and has been working fine on proton-tkg and proton-GE for a long while already, there's nothing to help with regarding it. The main problem with D9VK right now is the required native d3dx9/d3d_compiler libs dependency that Valve can't provide (and the arguably lower compatibility and stability vs wined3d, ofc, but that's being worked on).

**Comment by codeman101** [comment]
@Tk-Glitch Yeah if the wined3d compiler is not stable than the d3d compiler than it'd be great if d9vk could switch over to using the wined3d compiler

**Comment by K0bin** [comment]
It's not about 'switching over'. The wined3d compiler generates broken shaders that don't work on Windows D3D9 either.

It's also not 'more stable'. Whatever this is supposed to mean.

**Comment by codeman101** [comment]
@K0bin 
> It's not about 'switching over'. The wined3d compiler generates broken shaders that don't work on Windows D3D9 either.

No wonder wine has had such a hard time until recently.

>It's also not 'more stable'. Whatever this is supposed to mean.

Good point. I don't know either now that I think about it. LOL I was commenting to @Tk-Glitch  post.

**Comment by ryanmusante** [comment]
Do D9VK_master and DXVK conflict? Can I have both installed?

**Comment by K0bin** [comment]
> Can I have both installed?

Yes, should be fine.

**Comment by ryanmusante** [comment]
The dxgi.dll, d3d10.dll, d3d10_1.dll, d3d10core.dll, d3d11.dll are the same between the two?

For D9VK:
```
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
cf1950|OK  |   1.0MiB/s|/home/ryan/.cache/winetricks/d9vk_master/d9vk_master.zip

Status Legend:
(OK):download completed.
Executing cd /home/ryan
Executing mv /home/ryan/.wine/dosdevices/c:/windows/temp/_d9vk_master/build/dxvk-release/x32/dxgi.dll /home/ryan/.wine/dosdevices/c:/windows/system32/
Executing mv /home/ryan/.wine/dosdevices/c:/windows/temp/_d9vk_master/build/dxvk-release/x32/d3d9.dll /home/ryan/.wine/dosdevices/c:/windows/system32/
Executing mv /home/ryan/.wine/dosdevices/c:/windows/temp/_d9vk_master/build/dxvk-release/x32/d3d10.dll /home/ryan/.wine/dosdevices/c:/windows/system32/
Executing mv /home/ryan/.wine/dosdevices/c:/windows/temp/_d9vk_master/build/dxvk-release/x32/d3d10_1.dll /home/ryan/.wine/dosdevices/c:/windows/system32/
Executing mv /home/ryan/.wine/dosdevices/c:/windows/temp/_d9vk_master/build/dxvk-release/x32/d3d10core.dll /home/ryan/.wine/dosdevices/c:/windows/system32/
Executing mv /home/ryan/.wine/dosdevices/c:/windows/temp/_d9vk_master/build/dxvk-release/x32/d3d11.dll /home/ryan/.wine/dosdevices/c:/windows/system32/
Using native override for following DLLs: dxgi d3d9 d3d10 d3d10_1 d3d10core d3d11
Executing wine regedit /S C:\windows\Temp\_d9vk_master\override-dll.reg
```
For DXVK:
```
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
1cc8aa|OK  |   1.4MiB/s|/home/ryan/.cache/winetricks/dxvk/dxvk-1.3.tar.gz

Status Legend:
(OK):download completed.
Executing cd /home/ryan
------------------------------------------------------
Please refer to dxvk version 1.3 release notes... See: https://github.com/doitsujin/dxvk/releases/tag/v1.3
------------------------------------------------------
------------------------------------------------------
Please refer to current dxvk base graphics driver requirements... See: https://github.com/doitsujin/dxvk/wiki/Driver-support
------------------------------------------------------
Executing cd /home/ryan/.wine/dosdevices/c:/windows/temp/_dxvk
Executing tar -zxf /home/ryan/.cache/winetricks/dxvk/dxvk-1.3.tar.gz
Executing mv /home/ryan/.wine/dosdevices/c:/windows/temp/_dxvk/dxvk-1.3/x32/dxgi.dll /home/ryan/.wine/dosdevices/c:/windows/system32/
Executing mv /home/ryan/.wine/dosdevices/c:/windows/temp/_dxvk/dxvk-1.3/x32/d3d10.dll /home/ryan/.wine/dosdevices/c:/windows/system32/
Executing mv /home/ryan/.wine/dosdevices/c:/windows/temp/_dxvk/dxvk-1.3/x32/d3d10_1.dll /home/ryan/.wine/dosdevices/c:/windows/system32/
Executing mv /home/ryan/.wine/dosdevices/c:/windows/temp/_dxvk/dxvk-1.3/x32/d3d10core.dll /home/ryan/.wine/dosdevices/c:/windows/system32/
Executing mv /home/ryan/.wine/dosdevices/c:/windows/temp/_dxvk/dxvk-1.3/x32/d3d11.dll /home/ryan/.wine/dosdevices/c:/windows/system32/
Using native override for following DLLs: dxgi d3d10 d3d10_1 d3d10core d3d11
Executing wine regedit /S C:\windows\Temp\_dxvk\override-dll.reg
000b:fixme:winediag:start_process Wine TkG 4.12.1 is a testing version containing experimental patches.
```

**Comment by K0bin** [comment]
The D3D10, D3D10core, D3D10_1, D3D11 and DXGI dlls are straight from the DXVK version D9VK is based on. Those are unmodified and you can simply replace them with the upstream DXVK dlls as you like.

The only dll that's used by D**9**VK is D3D9.dll.

**Comment by tannisroot** [comment]
RESOLVED FIXED 🐸
