### ISSUE TITLE
TERA Online crash on Windows and corrupted textures on WINE

### ISSUE THREAD

**Issue by ronoverdrive** [Joshua-Ashton/d9vk#22]
On Windows 10 it crashes at the character select screen, but on WINE it does not crash. Instead it has corrupted textures and NPC hover text is rotated 90 degrees.
[Example 1](https://i.imgur.com/9yXYkr8.png)
[Example 2](https://i.imgur.com/43gfXUX.png)

### Software information
TERA Online

### System information
- GPU: Geforce GTX 980Ti (Linux), Geforce GTX 960 (Windows)
- Driver: 418.52.03 and 425.31 respectively
- Wine version: WINE-TKG 4.5 Git Master
- DXVK version: git master

### Apitrace file(s)
- [TERA.7z](https://mega.nz/#!qKpQGSqb!uuhz1-NT4-CyNtX1RNL4P5Rj4D_bOMLXhKdtGnTOA0Y)

### Log files
- [Linux TERA_d3d9.log](https://mega.nz/#!yT5mAKhA!rKnGpvjhuMSqQahhT5pFTEwdWNazdjRbmGNikwH9vvU)
- [Windows TERA_d3d9.log](https://mega.nz/#!yLhUnaAI!wyji1bDU1IiwuXvokdVnIeYxeRNi4GitW0pfnw3afZI)

**Comment by Joshua-Ashton** [comment]
Trace plays back fine here with latest changes, I think?

I'm not too sure what the game is meant to look like heh.

Can you please verify this? :)

**Comment by ronoverdrive** [comment]
Well on my end name tags for PCs and NPCs are rotated 90 degrees and textures that have movement to simulate wind like tree leaves moving incorrectly.

https://i.imgur.com/afbcE1H.png is an example of the name tag issue. I'll try to get a video up of spastic textures I'm talking about and an updated trace with more game play.

**Comment by Joshua-Ashton** [comment]
Trace looks fine to me, let me know if there are any issues -- feel free to re open.
