### ISSUE TITLE
Need for Speed: Most Wanted (2005) - Frogged colours

### ISSUE THREAD

**Issue by ThisNameIsntTaken** [Joshua-Ashton/d9vk#220]
Need for Speed: Most Wanted used to work for a while. However, a recent commit has caused a regression:

![nfsmw](https://user-images.githubusercontent.com/44706448/61174832-1a8b4600-a5a6-11e9-87c6-7c6c37c0ab00.png)

I bisected it, and the problem appears to be caused by 983eae5. Reverting it fixes the issue.

### Software information
Need for Speed: Most Wanted at max settings.

### System information
- GPU: RX 580 4GB
- Driver: Mesa-ACO-Git on Linux, Radeon Software 19.7.1. on Windows
- Wine version: Staging 4.12.1
- D9VK version: 067a2e5

### Apitrace file(s)
- https://mega.nz/#!q3AnjSqK!VcOgsoM9bOdk8rjwxUm0yugpS7aXt5wfCjTWXk3V6vQ

### Log files
- [speed_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3389060/speed_d3d9.log)

**Comment by Joshua-Ashton** [comment]
Should be fixed as of https://github.com/Joshua-Ashton/d9vk/commit/f1920139576feaf1789b9b99f650ecf0d8aa6668 and any missing textures should be fixed as of https://github.com/Joshua-Ashton/d9vk/commit/ed8aa8badf1ec7c83760ea689ceff5f7fdcea678
