### ISSUE TITLE
Borderlands 2 still freezes

### ISSUE THREAD

**Issue by Liemaeu** [Joshua-Ashton/d9vk#223]
Borderlands 2 still freezes/crashes with the latest d9vk. ("ran out of memory").
Lowering the graphic options doesn't help.
Without d9vk Borderlands 2 runs fine, but with less fps.
Without d9vk my VRAM utilization is around 40-50% (normal, like in every other game), but with d9vk it is over 70% (on the same graphic settings).

My System:
GTX 970 (latest Nvidia 418 Driver)
Proton 4.2-9

**Comment by kelvinhbo** [comment]
Most 32 bit games will crash on D9VK using an NVIDIA card.

**Comment by lavadrop** [comment]
Out of memory crash here too with RX 580 (latest Mesa/ACO) and Proton 4.2-9

**Comment by eNTi** [comment]
I can attest to the fact that Borderlands 2 works perfectly well with d9vk using a geforce gtx 770 with 2gb.

Driver Version: nvidia-ck-haswell 2:430.26-9
D9VK version: 0.13f

The only really weird thing is... that proton created a 64bit prefix while the game client only runs at 32bit. I wasn't even aware that this was possible.

**Comment by eNTi** [comment]
One more thing (sorry edit doesn't work for me for some reason): I had to disable the texture pack addon.

**Comment by Liemaeu** [comment]
@eNTi Thank you very much! Uninstalling the Ultra HD Texturepack DLC helped. No more crashes/freezes.
