### ISSUE TITLE
Cable error

### ISSUE THREAD

**Issue by logan001** [Joshua-Ashton/d9vk#224]
I have a strange problem with d9vk and Guild wars 2.
If i create a new profile for this game in lutris with or without the script from lutris, i will get an a monitor error if i have set refresh at 120Hz. The error is about Incorrect cable and to use the cable that came with the monitor.
Also there is a weird resolution in the beginning when the error appears. for 1-2 sec when while the error is on the monitor the image is pixelated. i don't know how to describe it. i can see text made of lines of pixels.
this happens only when the game starts with 120Hz. 
if i start the game with 60 Hz and change the refresh to 120Hz i have no error on the monitor.

the strange part is that i have a old profile in lutris that gives no error even with the 120Hz.
this is the profile that i 1st created when d9vk started.

i've try it on linuxmint/arch both have same behavior. 
Lutris profile that works in linuxmint

### Software information
Guild Wars 2 (i don't have another to try 120 Hz)

### System information
- GPU: 970 GTX
- Driver: 418.52.14 (and older)
- Wine version: i've tested with Tk 4.6 or newer from lutris or [pkbuilds](https://github.com/Tk-Glitch/PKGBUILDS)
- DXVK version: b11d085 and older

### Log files
[dvi cable error](https://drive.google.com/open?id=1wUaZWzhJOAwOhX3xdWuqE1SN4EfHz0kU)
[dvi no error](https://drive.google.com/open?id=19gx7vAi6CjAcJ3Nj2pFhUWcmLtRgcnoH)

**Comment by garpu** [comment]
Now that you mention it, I did have a strange monitor reset Friday night.  I'm on 60hz for both game and desktop, however.  I didn't think the two were related.  I played GW2 all day yesterday and no issues, though.  (Nvidia 430.26, 1050ti, d9vk  0.13.)

**Comment by logan001** [comment]
is your monitor capable of more than 60Hz? If so, you can try and change refresh rate and restart the game. see if you get any error

**Comment by garpu** [comment]
I don't, sorry. :(

**Comment by Joshua-Ashton** [comment]
Can you please try the branch https://github.com/Joshua-Ashton/d9vk/tree/d3d9-cable-error and see if it corrects your issue?

Cheers.

**Comment by logan001** [comment]
the error is still there
created a custom lutris prefix (tkg 4.6 as the profile that work) and installed the build but still have the same error
also with wine staging 4.12.1 have the same error

**Comment by Joshua-Ashton** [comment]
Can you please explain what the issue is, slowly step by step with pictures if possible. I don't really understand what the issue is.

**Comment by logan001** [comment]
[Here](https://drive.google.com/open?id=10sTX4vjbNw6yEq9EDE8dHUADZb7aZwEw) 2 videos. I can't make it more clear than that. 
In cable error you can see the error on the monitor and also see that the monitor has to go to "initializations"
sorry for shaking

**Comment by Joshua-Ashton** [comment]
Have you tried fixing your cable? 🐸

Either way, I get my information about the display from Wine so shout at them if its wrong and returning things you don't actually support.

I can't repro this and I still don't know why you think this is my issue...

**Comment by Tk-Glitch** [comment]
Because it only happens with D9VK, and not with DXVK nor wined3d. And that's my fault for redirecting him here. But yeah this is 300% weird. My display does that if I enforce 120Hz while using an HDMI cable instead of DVI dual link, but that's not limited to an app or library. It would yell at me the moment it switches to 120Hz, on any OS/game/API.

**Comment by K0bin** [comment]
Could also be single link DVI.
Maybe the reason why this only happens with D9VK is that WineD3D for some reason doesnt expose/use the 120hz modes.

I also have a 120hz BenQ screen and I've never seen that error. So yeah, use a proper cable if you want to use high refresh rates.

**Comment by logan001** [comment]
just for info: the cable has no problem. only d9vk gives this error. 
the monitor can go up to 144 Hz without any error.
the monitor is always at 120Hz by default.
i've notice diablo 3 shows the resolution and refresh rates but does not change refresh rate at all unless i change the resolution too.
i don't know why the GW2 change the refresh when the monitor is already at 1080/120Hz.

**Comment by logan001** [comment]
fyi: i've kind of fix the problem in a strange way.
what i did:
create a profile of guidwar 2 and install it if necesary (i just change the path to an already installed game) from lutris with d9vk support.
disable dxvk in lutris (don't know if its necesary)
install d9vk-master.6573579ef2e92bdbec8cd64fcf14d0ab825de4dd.zip without symlink in the wineprefix of the game (see lutris information)
trying to start the game will fail with a crash from guildwars (i don't know why recent build of lutris make the game crash if dxvk is disable in lutris but d9vk is installed)
now enable dxvk (the same dxvk profile it was before).
the game will start without any cable error.
it will still change some refresh/resolution (i dont know exactly what) as it goes blank 1 or 2 times. but monitor error is gone and also i have no pixelated image that was coming up when cable error message was showing before the display change back to correct format
this is strange workaround for this issue. i have no clue why installing this version will fix the error.
i've teste this on mint and arch
both times worked.
i've come up with this method while thinking what else was different from new profiles that created the cable error and the very 1st profile that i use d9vk and had no monitor error.
i've have yet to be 100% sure but so far it fix the problem.

i thought to post it here 'cause Tk-Glitch said there was one more person on discord that has similar issue. maybe it will help, maybe not. but for me it finally solved this cable error from happening every time i start guildwars2

**Comment by Tk-Glitch** [comment]
Yeah @Faalagorn was the one with a similar issue (not sure if it was with GW2 though). I'm not sure I got all the pieces right, but I'm glad you at least found a way to workaround the issue. Maybe it can help in some ways.

**Comment by Faalagorn** [comment]
Never tested it with GW2 :D I only had it pop once in Minecraft Story Mode with D9VK
