### ISSUE TITLE
TrackMania Nations Forever - Unclickable menu items

### ISSUE THREAD

**Issue by ThisNameIsntTaken** [Joshua-Ashton/d9vk#225]
Clicking on menu items in the game doesn't seem to work. Cycling through menu items with Tab and then pressing Enter also doesn't work. The problem only appears to happen when D9VK is added to the mix, the menu works fine on native d3d9, wined3d and G9.

The game is available for free, either from [Steam](https://store.steampowered.com/app/11020/TrackMania_Nations_Forever/), or the [website](http://trackmaniaforever.com/nations/). If you are on Windows 8 or 10, you might need [this](https://steamcommunity.com/sharedfiles/filedetails/?id=448953593) workaround.

### Software information
TrackMania Nations Forever

### System information
- GPU: RX 580 4GB
- Driver: Mesa-ACO-Git on Linux, Radeon Software 19.7.1. on Windows
- Wine version: Staging 4.12.1
- D9VK version: c6753c5

### Apitrace file(s)
- [TMNF.tar.xz](https://mega.nz/#!r3ZA2QIb!buzzIpKvXwo4HmFNDZW_gxUGub3MMQo_MMkJ-I41JfM)

### Log files
- [TmForever_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3390062/TmForever_d3d9.log)

**Comment by MegWATTT** [comment]
Hello,
A workaround is to Alt-Tab out of the game then re-focus on it.

**Comment by ThisNameIsntTaken** [comment]
Fixed by c73ab8f.

The game used to create its window and right before it started to display the actual game, it displayed another window with a message that the display driver is out of date. As of the mentioned commit, it no longer does that and the menu items are clickable even without alt-tab-ing.
