### ISSUE TITLE
Ys II - Ingame dialog does not show

### ISSUE THREAD

**Issue by almostalive** [Joshua-Ashton/d9vk#229]
### Software information
Ys II from GOG. clean win32 prefix, only disabled movie playback for no troubles and keeping the prefix clean.

Should look like this
![Image of correct rendering](https://i.postimg.cc/k5MHWNPR/Screenshot-from-2019-07-14-20-56-03.png)

d9vk looks like this
![Image of incorrect rendering](https://i.postimg.cc/wv7bG6v6/Screenshot-from-2019-07-14-21-05-05.png)

### System information
- GPU: Iris Pro 5200
- Driver: Mesa-git at 19.2.0_devel.113086.4e102a6de72-1
- Wine version: 4.12.1.r5.g1b15ab1b
- D9VK version: 065aeac2ab2575943eed58da4189c99a06e4d233

### Apitrace file(s)
https://dropfiles.org/SNw 

### Log files
- d3d9.log: https://gist.github.com/almostalive/68fe88637ba32532129227fb94480031

**Comment by Joshua-Ashton** [comment]
Should be fixed by https://github.com/Joshua-Ashton/d9vk/commit/4595800624b1a63e19557ed24612c0150dc4683a

Please try again on latest master :-)

**Comment by almostalive** [comment]
Yep, that fixed it. Thank you very much!
