### ISSUE TITLE
Game render error on Illusion game

### ISSUE THREAD

**Issue by l12436** [Joshua-Ashton/d9vk#230]
### Software information
Artificial Girl 3 make by Illusion.

### System information
- GPU: GTX 1060
- Driver: 430.26
- Wine version: wine-staging 4.12.1
- DXVK version: v1.3.0

### Apitrace file(s)
[Apitrace](http://www.mediafire.com/file/0twbablg0f9l2h6/JS3.tar.xz/file)

### Log files
[JS3_Makeu_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3604573/JS3_Makeu_d3d9.log)

Most of the game that made by ILLUSION will have this issue. There are also some other game will effect by this BUG.

I have attach a screenshot 
Correct-Screenshot.png:is the game should be
Incorrect-Screenshot.png: is the game that render by d9vk
[Screenshot.tar.gz](https://github.com/Joshua-Ashton/d9vk/files/3392312/Screenshot.tar.gz)

There already a bug report and patch in wine-staging.
BUG Report: [Bug Report](https://bugs.winehq.org/show_bug.cgi?id=39057)
Fixed Patch: [Patch](https://github.com/wine-staging/wine-staging/tree/master/patches/wined3d-Indexed_Vertex_Blending)

Hope this will help you debug.

Native
![Screenshot_20191203_230403](https://user-images.githubusercontent.com/2596649/70062774-a23f2300-1621-11ea-819b-563a8b41eefa.png)

D9vk
![Screenshot_20191203_230553](https://user-images.githubusercontent.com/2596649/70062789-acf9b800-1621-11ea-9d07-b41a1edf85c0.png)

**Comment by Joshua-Ashton** [comment]
Would be great if we could keep to sane formats for compressed traces in the future.

What you provided was a .TPXZ (never heard of that) containing a file called JS3 (which is a .tar without the extension) containing the trace and log.

It's a good thing I checked that that was a tar inside otherwise I would have just told you to do it again. Please just use something like .tar.xz or something *sane* in future.

**Comment by Joshua-Ashton** [comment]
Looks like it needs fixed function vertex blending

**Comment by l12436** [comment]
> Would be great if we could keep to sane formats for compressed traces in the future.
> 
> What you provided was a .TPXZ (never heard of that) containing a file called JS3 (which is a .tar without the extension) containing the trace and log.
> 
> It's a good thing I checked that that was a tar inside otherwise I would have just told you to do it again. Please just use something like .tar.xz or something _sane_ in future.

Ok my bad, That is actually tar.xz, the xz file that I use just rename to tpxz.
http://www.mediafire.com/file/0twbablg0f9l2h6/JS3.tar.xz/file

**Comment by l12436** [comment]
Update add screenshot.

**Comment by Joshua-Ashton** [comment]
Can you try as of 4bad731f472ffffa685d412dfae73e906e97d5e5?

Should be fixed now: https://git.froggi.es/joshua/d9vk/-/jobs

**Comment by l12436** [comment]
OK, I will try it now, thanks for fixing.

**Comment by l12436** [comment]
arm mostly fixing. but with some weird bug.
![image](https://user-images.githubusercontent.com/2596649/70367105-f2dfa600-18d7-11ea-8ce0-0d61db78a15f.png)

This is the log
[JS3_Makeu_d3d9.log.gz](https://github.com/Joshua-Ashton/d9vk/files/3934613/JS3_Makeu_d3d9.log.gz)

**Comment by Joshua-Ashton** [comment]
Can you try now? I believe this should be fixed for realsies. Verified it with your trace.

**Comment by l12436** [comment]
OK, I am trying now.

**Comment by Joshua-Ashton** [comment]
🐸

**Comment by l12436** [comment]
All fixed, Thanks for your help !!!!!!

**Comment by Joshua-Ashton** [comment]
No worries. Might be a lil' bit slow but that's just because the game is *really* stupid and special.

It uses indices, 0, 1 and 255 which means we have to upload 256 matrices every time they change 😢.
