### ISSUE TITLE
Undertale not loading at all in D9VK

### ISSUE THREAD

**Issue by NightSprinter** [Joshua-Ashton/d9vk#232]
Simply put, with this game will not run with D9VK at all.  Command line just repeatedly outputs "warn:  D3D9SwapChainEx::GetRasterStatus: Stub" as a result.  It works fine without D9VK.

### Software information
Undertale, default settings, no ReShade injection yet.

### System information
- GPU: GeForce GTX-1060 3GB
- Driver: 430.34 Proprietary
- Wine version: 4.11
- DXVK version: 0.13 and master (installed via winetricks, not sure how to install winelib build on Feedora)
- Distribution:  Fedora 30 Design Suite

### Apitrace file(s)
https://drive.google.com/open?id=1VppEl9FgwrsOqOES6tBbbtgSULT1LvJH

### Log files
[UNDERTALE_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3393229/UNDERTALE_d3d9.log)

**Comment by Joshua-Ashton** [comment]
Should be fixed by https://github.com/Joshua-Ashton/d9vk/commit/21208bb32dc4da38bd73f40c1a488cf215e2b25c

Can you verify?

**Comment by NerosTie** [comment]
It works for me.
