### ISSUE TITLE
Painkiller → crash at launch

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#234]
Click play, nothing happen then it stops.

### System information
GPU: Nvidia GT 730M
Driver: 430.26-9
Wine version: Proton 4.2
DXVK version: 0.13

### Apitrace file(s)
https://mega.nz/#!qnQwyaIZ!d4WLqKcleemsG1kp4Z50CzQv8wVIaOwnUTBZrwVgEzA

### Log files
d3d: [Painkiller-39530.log](https://github.com/Joshua-Ashton/d9vk/files/3393906/Painkiller-39530.log)
d9vk: [Painkiller-d9vk-39530.log](https://github.com/Joshua-Ashton/d9vk/files/3393908/Painkiller-d9vk-39530.log)

**Comment by Joshua-Ashton** [comment]
> `225877.304:0029:002a:fixme:vulkan:X11DRV_vkCreateWin32SurfaceKHR Application requires child window rendering, which is not implemented yet!`

Not my bug, there's a patch for support in this Wine on the mailing list.

**Comment by NerosTie** [comment]
It works with wined3d, so it's a bug with Vulkan itself?

**Comment by Joshua-Ashton** [comment]
It's a WineVulkan bug. There's a patch to fix it on the mailing list:

https://source.winehq.org/patches/data/167679

**Comment by shoober420** [comment]
I hope this gets added to Wine/Proton soon. I made a issue about it on the Proton github.

https://github.com/ValveSoftware/Proton/issues/3234
