### ISSUE TITLE
Split/Second → Cars' textures are not rendered well

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#236]
With d9vk
![](https://i.imgur.com/gJPvbOe.jpg)
Without d9vk
![](https://i.imgur.com/P67CXhb.jpg)

### System information
GPU: Nvidia GT 730M
Driver: 430.26-9
Wine version: Proton 4.2
DXVK version: 0.13

### Apitrace file(s)
Unfortunately, the game crashes after the logos when I want to apitrace it.
https://mega.nz/#!DnYUnCLC!nI4_-u6Rgk0zXWnKPGir5mv7DJVD41PnWaNTDZreDpo

### Log files
d3d: [SplitSecond-297860.log](https://github.com/Joshua-Ashton/d9vk/files/3394011/SplitSecond-297860.log)

**Comment by qdevpl** [comment]
Is it 0.13 or 0.13f version?

**Comment by NerosTie** [comment]
Tested with 0.13 but I have the same result with the last master.

**Comment by NerosTie** [comment]
Fixed! :tada: 
(tested with #797)
