### ISSUE TITLE
Aronline: Render error in some map

### ISSUE THREAD

**Issue by l12436** [Joshua-Ashton/d9vk#240]
### Software information
ARonline - MMO online game

### System information
- GPU: GTX 1060
- Driver: 480.26
- Wine version: 4.12.1
- DXVK version: 0.1.3

### Apitrace file(s)
https://www.mediafire.com/file/gh9709kba59kj0d/aro.7z/file

### Log files
[game.bin_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3394617/game.bin_d3d9.log)

AROnline is crash right after game loading, but we did not occur crash in vanilla wine d3d9

**Comment by l12436** [comment]
![image](https://user-images.githubusercontent.com/2596649/65816825-2c8a9580-e233-11e9-9820-ddf3ef1e42c4.png)
[game.bin_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3665474/game.bin_d3d9.log)
current Aronline on latest master. Aronline could run successfully but with some render error.

**Comment by Joshua-Ashton** [comment]
Can you please make a trace of the rendering error?

**Comment by l12436** [comment]
OK, I will try to provide this. I maybe very huge file.

**Comment by l12436** [comment]
new Trace file which at the location of Black texture.
https://www.mediafire.com/file/k8c08by2a7mtaxd/AROnline.trace.xz/file
