### ISSUE TITLE
Oblivion → some effects are broken

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#241]
With d9vk
![](https://i.imgur.com/ijeLuIl.jpg)
Without d9vk
![](https://i.imgur.com/GnVkP3q.jpg)

### System information
GPU: Nvidia GT 730M
Driver: 430.26-9
Wine version: Proton 4.2
DXVK version: 0.13

### Apitrace file(s)
https://mega.nz/#!GiAQFaSR!V9TaMH-wMguRWIyyPG_7titAXNEV5Rdm013kpN6HhS0

### Log files
d3d9: 
[Oblivion-22330.log](https://github.com/Joshua-Ashton/d9vk/files/3394624/Oblivion-22330.log)

**Comment by aufkrawall** [comment]
Where is that?

**Comment by NerosTie** [comment]
New Sheoth Palace, Shivering Isles.

**Comment by Joshua-Ashton** [comment]
Fixed by

https://github.com/Joshua-Ashton/d9vk/commit/e0f34a305904665fe5cb9e81b577fd9fdd6732b0
