### ISSUE TITLE
Enhancement request: HUD font size

### ISSUE THREAD

**Issue by JayGuerette** [Joshua-Ashton/d9vk#243]
I'd like an option to change the HUD font size. Either a global scaling option, something like:
DXVK_HUD_SIZE=nn
Or a per-item pixel-height sizing option:
DXVK_HUD=version:10,fps:20

By the way: this is working flawlessly on Guild Wars 2. It's 3-4x FPS over native Wine and within 5-10 FPS of Windows. It's amazing.

**Comment by Joshua-Ashton** [comment]
Please make this request to upstream:
https://github.com/doitsujin/dxvk/

Cheers 🐸

**Comment by K0bin** [comment]
No need to do that, he won't implement it.

The hud is strictly for debugging and doitsujin has turned down numerous HUD feature request to avoid unnecessary feature creep.
