### ISSUE TITLE
3D Rad not starting

### ISSUE THREAD

**Issue by agent188** [Joshua-Ashton/d9vk#244]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Name of the game, settings used etc.

### System information
- GPU: Intel HD Graphics 530
- Driver: 19.1.2
- Wine version: wine-4.12.1
- DXVK version: 

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
- dxgi.log: 

[3DRad_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3398448/3DRad_d3d9.log)

**Comment by Joshua-Ashton** [comment]
> Apitrace file(s)
Put a link here

Please do.

**Comment by agent188** [comment]
link to the program I'm trying to run?

**Comment by Joshua-Ashton** [comment]
An APITrace of it running with wined3d/Windows

**Comment by CartoonFan** [comment]
From the bug template:

> When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (**see https://github.com/apitrace/apitrace**) so that the issue can be reproduced.

This may also be helpful:

> if you're wondering, a simple way to make d3d traces is to download an apitrace release from https://github.com/apitrace/apitrace and, once you extract it, take the relevant dlls from the wrappers folder and place them in the same folder as the game you want to test. It will make a trace and put it on the desktop.

**Comment by Joshua-Ashton** [comment]
If by 3D Rad you mean the weird game engine thing?

I downloaded it and it works fine -- but it relies on child window rendering.

**Comment by agent188** [comment]
yes it's a game engine

**Comment by agent188** [comment]
Is there a patch that is associated with windows?

**Comment by agent188** [comment]
![image](https://user-images.githubusercontent.com/41228098/61653292-a26a0200-acc2-11e9-88e5-a3314b8a18a7.png)
what am I doing wrong?

**Comment by Joshua-Ashton** [comment]
Well for a start it's not DXGI API, it's d3d9. I don't need a trace as I have the app installed on my PC. Can you just send me the full console output of you starting the game.

**Comment by agent188** [comment]
[angry-agent@asus-pc 3D Rad ]$ wine 3DRad
info:  Game: 3DRad.exe
info:  DXVK: d9vk-0.13
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  Intel(R) HD Graphics 530 (Skylake GT2):
info:    Driver: 19.1.2
info:    Vulkan: 1.1.102
info:    Memory Heap[0]: 
info:      Size: 4776 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0xf
info:    Memory Heap[1]: 
info:      Size: 1024 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0xf
info:  Process set as DPI aware
info:  Enabled device extensions:
info:    VK_EXT_conditional_rendering
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_host_query_reset
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  DXVK: Read 0 valid state cache entries
info:  DXVK: Using 2 compiler threads
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  D3D9DeviceEx::ResetEx:
  Requested Presentation Parameters
    - Width:              898
    - Height:             673
    - Format:             X8R8G8B8
    - Auto Depth Stencil: true
    - Windowed:           true

warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 9
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 16
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 37
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 38
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 136
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 142
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 154
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 155
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 158
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 161
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 166
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 172
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 173
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 178
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 179
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 182
0009:fixme:vulkan:X11DRV_vkCreateWin32SurfaceKHR Application requires child window rendering, which is not implemented yet!
terminate called after throwing an instance of 'dxvk::DxvkError'

abnormal program termination
0009:fixme:msvcrt:__clean_type_info_names_internal (0x101c8894) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x783ccb48) stub
[angry-agent@asus-pc 3D Rad ]$

**Comment by agent188** [comment]
my game that was created on the 3D Rad engine also does not start
```
[angry-agent@asus-pc ~ ]$ wine '/home/angry-agent/Загрузки/WMan/WMan 1.3.7/WMan.exe' 
info:  Game: WMan.exe
info:  DXVK: d9vk-0.13
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  Intel(R) HD Graphics 530 (Skylake GT2):
info:    Driver: 19.1.2
info:    Vulkan: 1.1.102
info:    Memory Heap[0]: 
info:      Size: 4776 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0xf
info:    Memory Heap[1]: 
info:      Size: 1024 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0xf
info:  Process set as DPI aware
info:  Enabled device extensions:
info:    VK_EXT_conditional_rendering
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_host_query_reset
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  DXVK: Read 2 valid state cache entries
info:  DXVK: Using 2 compiler threads
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  D3D9DeviceEx::ResetEx:
  Requested Presentation Parameters
    - Width:              1366
    - Height:             768
    - Format:             X8R8G8B8
    - Auto Depth Stencil: true
    - Windowed:           true

warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 9
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 16
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 37
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 38
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 136
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 142
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 154
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 155
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 158
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 161
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 166
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 172
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 173
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 178
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 179
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 182
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
  Buffer size:  1366x768
  Image count:  2
info:  D3D9DeviceEx::ResetEx:
  Requested Presentation Parameters
    - Width:              1366
    - Height:             768
    - Format:             X8R8G8B8
    - Auto Depth Stencil: true
    - Windowed:           true

warn:  DxsoCompiler::processInstruction: unhandled opcode: TexM3x3Pad
warn:  DxsoCompiler::processInstruction: unhandled opcode: TexM3x3Pad
warn:  DxsoCompiler::processInstruction: unhandled opcode: TexM3x3VSpec
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_FIFO_KHR
  Buffer size:  1366x768
  Image count:  3
info:  Enabled device extensions:
info:    VK_EXT_conditional_rendering
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_host_query_reset
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  DXVK: Read 2 valid state cache entries
info:  DXVK: Using 2 compiler threads
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  D3D9DeviceEx::ResetEx:
  Requested Presentation Parameters
    - Width:              1366
    - Height:             768
    - Format:             X8R8G8B8
    - Auto Depth Stencil: true
    - Windowed:           true

info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
  Buffer size:  1366x768
  Image count:  2
info:  D3D9DeviceEx::ResetEx:
  Requested Presentation Parameters
    - Width:              1366
    - Height:             768
    - Format:             X8R8G8B8
    - Auto Depth Stencil: true
    - Windowed:           true

warn:  DxsoCompiler::processInstruction: unhandled opcode: TexM3x3Pad
warn:  DxsoCompiler::processInstruction: unhandled opcode: TexM3x3Pad
warn:  DxsoCompiler::processInstruction: unhandled opcode: TexM3x3VSpec
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_FIFO_KHR
  Buffer size:  1366x768
  Image count:  3
0009:fixme:olepicture:OLEPictureImpl_Load Unknown stream header magic: 20534444
0009:fixme:olepicture:OLEPictureImpl_Load Unknown stream header magic: 00001007
0009:fixme:olepicture:OLEPictureImpl_Load Unknown magic 0080, 128 read bytes:
80 00 00 00 00 00 00 00 80 00 
00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 20 00 
00 00 41 00 00 00 00 00 00 00 
20 00 00 00 00 00 ff 00 00 ff 
00 00 ff 00 00 00 00 00 00 ff 
02 10 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 
0009:err:olepicture:OleLoadPicture IPersistStream_Load failed
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED
err:   DxvkMemoryAllocator: Memory allocation failed
  Size:      8294400
  Alignment: 16
  Mem flags: 0xe
  Mem types: 0x3
err:   Heap 0: 1440 MB allocated, 1131 MB used, 1848 MB allocated (driver), 4776 MB available (driver), 4776 MB total
err:   Heap 1: 256 MB allocated, 63 MB used, 384 MB allocated (driver), 1024 MB available (driver), 1024 MB total
terminate called after throwing an instance of 'dxvk::DxvkError'

abnormal program termination
0009:fixme:msvcrt:__clean_type_info_names_internal (0x101c8894) stub
0009:fixme:msvcrt:__clean_type_info_names_internal (0x783ccb48) stub
[angry-agent@asus-pc ~ ]$ 

```
link to the game: https://github.com/agent188/WMan/releases/download/1.3.7/WMan.1.3.7.exe

**Comment by Joshua-Ashton** [comment]
Yeah, not my bug. There's a patch to implement this in Wine to fix this around somewhere.

https://www.winehq.org/pipermail/wine-devel/2019-July/148646.html
