### ISSUE TITLE
forcing anisotropic filtering not implemented

### ISSUE THREAD

**Issue by aufkrawall** [Joshua-Ashton/d9vk#245]
Hello,
for DXVK, there is `d3d11.samplerAnisotropy`. However, there is no equivalent in D9VK. Some silly games like TESIV: Oblivion don't have an AF setting, and radv is the only Vulkan driver that supports forcing AF.
Thus it would be great if there was `d3d9.samplerAnisotropy`.

**Comment by Joshua-Ashton** [comment]
Can you try https://github.com/Joshua-Ashton/d9vk/tree/d3d9-sampler-anisotropy and see if this satisfies you.

Should be available on this frog job when it's done
https://git.froggi.es/joshua/d9vk/-/jobs/667

I am however hesitant to increase overhead here...

**Comment by aufkrawall** [comment]
Thanks, it works great!
Do you have a particular concern regarding overhead? I've quickly benchmarked Oblivion in 720p in a town (CPU limit), and the fps are unchanged by forcing AF. :)

**Comment by aufkrawall** [comment]
Found an issue with the water effect, it loses detail when forcing AF via D9VK.
![Screenshot_20190717_122709_ergebnis](https://user-images.githubusercontent.com/13510490/61368653-a515c300-a88e-11e9-9455-bfd8f59b1e1f.jpg)
![Screenshot_20190717_122734_ergebnis](https://user-images.githubusercontent.com/13510490/61368654-a515c300-a88e-11e9-8a4b-7ee8fd0a1e65.jpg)
It works via RADV though.

**Comment by Joshua-Ashton** [comment]
> Do you have a particular concern regarding overhead? I've quickly benchmarked Oblivion in 720p in a town (CPU limit, unlocked fps), and the fps are unchanged by forcing AF. :)

I kinda just don't want to add more options that get checked in hot paths

> Found an issue with the water effect, it loses detail when forcing AF via D9VK. It seems it looks like the water would look at a distance, which may indicate a mipmapping issue?

No idea, you're forcing the game to do things it's not meant to so it doesn't surprise me that things can look a bit bodged at times.

**Comment by aufkrawall** [comment]
Yeah, though it works without issues with every driver that supports forcing AF :) .
Dunno if there is anything interesting in how radv implemented it:
https://cgit.freedesktop.org/mesa/mesa/commit/?id=3871dd7a92624675bd45d9d596bbe34c33d7bb4d

**Comment by Joshua-Ashton** [comment]
I force pushed to that branch, can you try again?

**Comment by aufkrawall** [comment]
It is fixed, proper AF in Oblivion with amdvlk driver :+1: :
![Screenshot_20190717_161003](https://user-images.githubusercontent.com/13510490/61382841-c934cc80-a8ad-11e9-8be8-8b765eef3372.png)

**Comment by Joshua-Ashton** [comment]
Merged.
