### ISSUE TITLE
[Regression] GTA IV - Frogged textures

### ISSUE THREAD

**Issue by ThisNameIsntTaken** [Joshua-Ashton/d9vk#247]
Commit f90163b broke GTA IV's textures, Alt+Tab-ing out and back also makes the textures look completely different every single time. Reverting this commit fixes the issue.

![Screenshot_20190717_135451](https://user-images.githubusercontent.com/44706448/61374123-da74dd80-a89b-11e9-9737-3097ec6218a7.png)

![Screenshot_20190717_135539](https://user-images.githubusercontent.com/44706448/61374128-de086480-a89b-11e9-93ef-1015973c609e.png)

### Software information
Grand Theft Auto IV

### System information
- GPU: RX 580 4GB
- Driver: Mesa ACO Git, AMDVLK 2019.Q3.2
- Wine version: Proton-4.11-GE-1
- D9VK version: 3e36478

### Apitrace file(s)
- [Same trace that can be found in issue #99](https://mega.nz/#!DEFnDQLI!G0fkUFzyZSvxbImQbB8xsSFNTX4bt_IWPoOXfbUalG8)

### Log files
- [GTAIV_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3401745/GTAIV_d3d9.log)

**Comment by K0bin** [comment]
The apitrace in issue #99 doesn't have the issue. It looks just fine.
