### ISSUE TITLE
Graphical Issues in The King of Fighters '98: Ultimate Match (may affect other Neo-Geo ports on Steam)

### ISSUE THREAD

**Issue by NightSprinter** [Joshua-Ashton/d9vk#253]
While the game does run, and the graphical issues I have shown in a screenshot in the ReShade thread have improved, the graphical glitching during matches (sprites/background objects disappearing, reappearing, and sometimes reappearing with incorrect colour palettes) still make the game unplayable with D9VK.  WineD3D has no issue whatsoever with the game.  As the title suggests, this may affect every other Neo-Geo port on Steam as well if used with D9VK (though I only have this game to test).

### Software information
The King of Fighters '98:  Ultimate Match - Final Edition

### System information
- GPU: GeForce GTX-1060 3GB
- Driver: 340.43
- Wine version: Proton 4.2-9
- DXVK version: D9VK 1.30 (latest GIT, winelib build

### Apitrace file(s)
- https://drive.google.com/open?id=1-jxhiRrTKbaUGbsuQv3g73uItxEg3kpq

### Log files
- d3d9.log:[KingOfFighters98UM_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3404686/KingOfFighters98UM_d3d9.log)

[Note:  for some reason, I could only get a log file by using the Windows Steam client and running the game, which crashes in standalone WINE.  I'll keep at it to try and get a proper log file from Proton.]

![Screenshot from 2019-07-18 13-59-12](https://user-images.githubusercontent.com/52381903/61480618-54709980-a964-11e9-935f-356dcae04f1f.png)

**Comment by NightSprinter** [comment]
Just adding a new screenshot of how the glitchiness is currently with the git version tested.

**Comment by Joshua-Ashton** [comment]
Renders fine for me 🤷‍♀️

Can you re-test on latest master -- and failing that, a MinGW build?

**Comment by NightSprinter** [comment]
If it's possible to make a MinGW build in Fedora, I can try that.  I just remember reading in the issue with that, the only way so far to build in Fedora was with the --winelib flag.

**Comment by Joshua-Ashton** [comment]
You can get the latest builds here

https://git.froggi.es/joshua/d9vk/-/jobs

**Comment by NightSprinter** [comment]
I retested on both, and the issues still persist for me on the newest master from git.  Both the compiled winelib version, and the MinGW build you linked to.

**Comment by Riesi** [comment]
The trace replays fine for me on Nvidia with `418.52.16`. Could you try to replay your trace too? Maybe the issue does not show in the trace.

**Comment by NightSprinter** [comment]
Yeah, that's strange as hell.  Why would the trace replay just fine, but actually playing the game have the massive issues?
