### ISSUE TITLE
CoD MW 2 dropped framerate with that commit

### ISSUE THREAD

**Issue by zvova7890** [Joshua-Ashton/d9vk#256]
I was build latest git version and checkout CoD. With this version I had frame rate on my location around 25fps, but I'm remember that I had around 45fps before. Then I'm bisect and found that are 90bb7aeae5903b4e5757faabd65b1fe5f85f4fc1 commit is slow down this game.

ArchLinux, nvidia 650m, latest proprietary driver

**Comment by Joshua-Ashton** [comment]
Can you send me a log? Would be beneficial to get some system info here.

**Comment by zvova7890** [comment]
[iw4sp_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3412158/iw4sp_d3d9.log)

There is nvidia GT 650M notebook, 12gb ram, linux 5.2.1-arch1-1-ARCH, and nvidia 430.34-1

**Comment by Joshua-Ashton** [comment]
Do you have a log from both before and after that commit so I can compare?

**Comment by zvova7890** [comment]
Yes, but it same. Zero diff

**Comment by Joshua-Ashton** [comment]
Can you try on latest master?

**Comment by zvova7890** [comment]
Wow, great, it work again, thanks :)

**Comment by Joshua-Ashton** [comment]
I don't understand why, but great.

**Comment by zvova7890** [comment]
Don't know how it happen, but again i have 25-26fps in this game %) 
I tried to roll back to commit that was work fine(244c983950d58143f000f83e8307c2f026853881), but it can not compile. Any idea?

**Comment by zvova7890** [comment]
Lol... this game is one big surprise :) I'm switched back to OpenGL layer, the game warn about configuration changed and ask about reset configuration - I'm press "Yes". Then load some level(BTW, opengl performance ok), play some time and exit from game. Than repeat setup_d9vk, again reset configuration... game return 40+ fps. 
Don't know WTF, but this may help some one

**Comment by Joshua-Ashton** [comment]
It's probably just you hitting VRAM limits due to other things being open or not at the time.

The 650M is a fairly low-spec card

**Comment by zvova7890** [comment]
Yes, but it is a dedicated card, my main card is Intel. So i run this with PRIME, and it always had free ~2G VRAM. I had log m_availableMemory, and it return around 1967 MB, so I'm don't know what realy happen

**Comment by zvova7890** [comment]
```
  int64_t D3D9DeviceEx::DetermineInitialTextureMemory() {
    auto memoryProp = m_adapter->GetDXVKAdapter()->memoryProperties();

    VkDeviceSize availableTextureMemory = 0;

    for (uint32_t i = 0; i < memoryProp.memoryHeapCount; i++) {
      VkMemoryHeap& heap = memoryProp.memoryHeaps[i];
      // ------> Is here need this check?
      if (heap.flags & VK_MEMORY_HEAP_DEVICE_LOCAL_BIT)
        availableTextureMemory += memoryProp.memoryHeaps[i].size;
    }

    constexpr VkDeviceSize Megabytes = 1024 * 1024;

    // The value returned is a 32-bit value, so we need to clamp it.
    VkDeviceSize maxMemory = (VkDeviceSize(m_d3d9Options.maxAvailableMemory) * Megabytes) - 1;
    availableTextureMemory = std::min(availableTextureMemory, maxMemory);

    return int64_t(availableTextureMemory);
  }
```

>> VK_MEMORY_HEAP_DEVICE_LOCAL_BIT specifies that the heap corresponds to device local memory. Device local memory may have different performance characteristics than host local memory, and may support different memory property flags.

Is these check is really need? Is textures can not be store to the "shared" memory? If remove this check, DetermineInitialTextureMemory return 4227661823 in my case, and the game always run smooth. How do you think? I'm believe the problem is hidden somewhere here :)

**Comment by Joshua-Ashton** [comment]
I'm not a big fan of doing that. While you *can* store textures there, it is probably going to be much slower if the heap is not device local.

Do you have access to a Windows setup? What does GetAvailableTextureMem return for you there?

I don't own any devices with shared memory in this way. :-/

**Comment by zvova7890** [comment]
Ok, I will try. Also interest what return default wine opengl-layer translator, because it work fine

**Comment by zvova7890** [comment]
So, here is result of 650M:

```
// dxvk master:					2144337920
// dxvk with removed local mem bit check:	4290772992
// windows 10:					4291821568
// pure wine:					2141192192
```

I guess we can remove this check safety.
