### ISSUE TITLE
Eldritch shows yellow lines

### ISSUE THREAD

**Issue by rohit-n** [Joshua-Ashton/d9vk#26]
Eldritch shows yellow lines in 3D rendering. I found commit 92217a533a351dda609f2d7592eb632baa121f14 to be causing this.

### Software information
Eldritch

### System information
- GPU: GeForce GT 730 (GeForce GTX 1070 was also tested)
- Driver: 397.93.0
- Wine version: None (Windows 10)
- DXVK version: git master

### Apitrace file(s)
- https://drive.google.com/open?id=19-Bj7qnaFHDijshAky_dnI2OVy0CPK2E

### Log files
- https://drive.google.com/open?id=1ZEdgww5DJA_otCMoNxThWRW_YbKcnFKP

**Comment by Joshua-Ashton** [comment]
This was fixed
