### ISSUE TITLE
dxvk::DxvkError when trying to run with Borderlands 2

### ISSUE THREAD

**Issue by FichteFoll** [Joshua-Ashton/d9vk#260]
Trying to launch Borderlands 2 results in a cryptic `dxvk::DxvkError` and (through the debug log) a couple missing vulkan extensions. However, these extensions are included in `vulkaninfo` (except for `VK_KHR_win32_surface`).

Please find the logs below:
- [steam-49520.d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3419502/steam-49520.d9vk.log)
- [vulkaninfo.log](https://github.com/Joshua-Ashton/d9vk/files/3419503/vulkaninfo.log)

### Software information

Borderlands 2, latest patch, following the installation instructions at [this reddit thread](https://www.reddit.com/r/linux_gaming/comments/bypm2z/will_the_new_borderlands_2_dlc_come_to_linux/). The game runs without d9vk, i.e. steps 5-9.

### System information

    OS: Arch
    GPU: Radeon HD 7950
    Driver/LLVM version: Mesa 19.1.2, amdgpu 19.0.1, amdvlk-git r77.eee58c8-1
    Kernel version: 5.2.0-arch2-1-ARCH
    Proton version: 4.2-9
    D9VK: 0.13f

If you need further info / log files, please ask. I can also try the master branch if you believe this to be related, but at the moment I'm not actually sure where the problem lies and whether the vulkan driver is at fault.

---

Related issue where I commented first: https://github.com/ValveSoftware/Proton/issues/2791

**Comment by Joshua-Ashton** [comment]
You need a Vulkan driver.

**Comment by FichteFoll** [comment]
Isn't amdvlk a vulkan driver? How could vulkaninfo produce this output when I didn't have a driver?

```
VkPhysicalDeviceDriverProperties:
=================================
        driverID   = 2
        driverName = AMD open-source driver
        driverInfo =
        conformanceVersion:
                major    = 1
                minor    = 1
                subminor = 1
                patch    = 2
```

**Comment by Joshua-Ashton** [comment]
Because you need both a 32 bit driver also.

**Comment by FichteFoll** [comment]
I don't know why that never occured to me. Thanks for the help, installing `lib32-amdvlk` worked.

Although I get pretty terrible shader stutter with it, but that's a different problem.
