### ISSUE TITLE
Broken character rendering in Artificial Academy 2

### ISSUE THREAD

**Issue by OrdinaryMagician** [Joshua-Ashton/d9vk#261]
First of all, please don't judge. Characters render fine without d9vk, but with it everything just goes wrong. Textures go black and faces are detached from the head (the latter was a common issue in older wine versions but was fixed recently).

### Software information
Artificial Academy 2, installed through AA2Mini and with the most recent AA2Unlimited update. The character maker was used for this report. Just displaying any character is enough to reproduce the issue.

### System information
- GPU: NVIDIA GTX 1060
- Driver: 430.34
- Wine version: 4.12.1 (Staging)
- DXVK version: 0.13f

### Apitrace file(s)
- N/A, running through apitrace causes the game to freeze when loading.

### Log files
- [AA2Edit_d3d9.log.zip](https://github.com/Joshua-Ashton/d9vk/files/3422558/AA2Edit_d3d9.log.zip)

What I expected:
![2019-07-23-163343](https://user-images.githubusercontent.com/2286785/61721275-802abf80-ad68-11e9-8d41-cf9fefff1610.png)
What I got:
![2019-07-23-163016](https://user-images.githubusercontent.com/2286785/61721296-87ea6400-ad68-11e9-9ce3-df5cbb7b2a5c.png)

**Comment by geneishouko** [comment]
The shadows issue should be fixed by now in d9vk but the broken face is still there and a workaround patch fixes it: 
```
diff --git a/src/d3d9/d3d9_caps.h b/src/d3d9/d3d9_caps.h
index fb70300d..a7d0a6c4 100644
--- a/src/d3d9/d3d9_caps.h
+++ b/src/d3d9/d3d9_caps.h
@@ -11,9 +11,9 @@ namespace dxvk::caps {
   constexpr uint32_t MaxTextureBlendStages        = MaxSimultaneousTextures;
   constexpr uint32_t MaxSimultaneousRenderTargets = D3D_MAX_SIMULTANEOUS_RENDERTARGETS;
 
-  constexpr uint32_t MaxFloatConstantsVS          = 256;
-  constexpr uint32_t MaxFloatConstantsPS          = 224;
-  constexpr uint32_t MaxOtherConstants            = 16;
+  constexpr uint32_t MaxFloatConstantsVS          = 8192;
+  constexpr uint32_t MaxFloatConstantsPS          = 8192;
+  constexpr uint32_t MaxOtherConstants            = 2048;
   constexpr uint32_t MaxFloatConstantsSoftware    = 8192;
   constexpr uint32_t MaxOtherConstantsSoftware    = 2048;
```

**Comment by OrdinaryMagician** [comment]
Ah, the ol' constant limit issue.

**Comment by Joshua-Ashton** [comment]
Issue fixed by https://github.com/Joshua-Ashton/d9vk/commit/2f10f2e74939420b5fa1a3d8a11aea9ddb8a63b4

**Comment by OrdinaryMagician** [comment]
I'd call it a partial fix, tbh. Female characters render fine, but male characters always have a misaligned right eye.
