### ISSUE TITLE
Tomb Raider Anniversary → when the antialiasing is on, the game freezes

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#264]
with d9vk
![20190726110115_1](https://user-images.githubusercontent.com/4572452/61947704-3c24fe00-afa6-11e9-827a-fc5d669c6ef2.jpg)

without d9vk
![20190726105900_1](https://user-images.githubusercontent.com/4572452/61947717-4515cf80-afa6-11e9-854a-339f925e64d9.jpg)

- GPU: Nvidia GT 730M
- Driver: 430.26-9
- Wine version: Proton 4.2
- DXVK version: #725 (jobs)

### Apitrace file(s)
antialiasing off:  
https://mega.nz/#!z3AhXYhK!8B8cuX6LzsrtPir3sXYCg7gPs6lTHI0GMtmOTG2T7UA
antialiasing on:
https://mega.nz/#!22RVnYzC!0NqH04L9namTkdSCk6COfB5Z5TBBBDH8IoOP_L1e3tY

### Log files
[steam-8000-wined3d.log](https://github.com/Joshua-Ashton/d9vk/files/3435451/steam-8000-wined3d.log)

**Comment by Jrugia** [comment]
@NerosTie: 
Can you try the latest build from master branch: https://git.froggi.es/joshua/d9vk/-/jobs

The shadows seem to work fine with it:
![TRA](https://user-images.githubusercontent.com/13750621/62009161-63bdc700-b15c-11e9-81f5-7dcb5c56acea.jpg)

The only feature left for this game is the Antialiasing, if turned on the game freezes on the first cutscene when starting a new game or loading.

**Comment by NerosTie** [comment]
Yes, shadows are here with the latest build :tada:  (unfortunately, still glitchy but it's the game's fault).

I have the same issue with the Antialiasing. Should I close this issue or change the title?

**Comment by Jrugia** [comment]
If you ran the apitrace with the Antialiasing on, I think a rename would be enough.

**Comment by lemonzest79** [comment]
I have also noticed shadows missing on this game, and also Legend both when running around Croft Manor, in Underworld I noticed square blocks in the fire/heat haze but I'll make another ticket for that.

System specs are

Wine Staging 4.14, Mesa 19.1.4, Fedora 30, MSI Radeon RX 580 8GB, current d9vk master installed via winetricks on a fresh 32bit prefix.

**Comment by NerosTie** [comment]
The apitrace with the antialiasing on: 

https://mega.nz/#!22RVnYzC!0NqH04L9namTkdSCk6COfB5Z5TBBBDH8IoOP_L1e3tY

(sorry for the delay)
