### ISSUE TITLE
Outrun 2006 → the water is black

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#265]
with d9vk
![Screenshot_20190726_121139](https://user-images.githubusercontent.com/4572452/61948095-37ad1500-afa7-11e9-9c50-adf9ab6f8f79.png)

without d9vk
![Screenshot_20190726_122104](https://user-images.githubusercontent.com/4572452/61948126-4abfe500-afa7-11e9-824a-2c3db0f27917.png)

### System information
- GPU: Nvidia GT 730M
- Driver: 430.26-9
- Wine version: Proton 4.2
- DXVK version: #725 (jobs)

### Apitrace file(s)
https://mega.nz/#!22w33a5R!riiq_HSfepZVc_IIKAcNkvBZZVBv52HamCzPCjdWbAo
(with apitrace, the game was veeeeeery slow (5-6fps) and it glitched at the end of the trace so ignore this part. But you can see water at the beginning of the race)

### Log files
[outrun-d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3435470/outrun-d3d9.log)

**Comment by K0bin** [comment]
The logs are using both Wine's D3DX and WineD3D.

Please post actual D9VK logs and use Microsofts D3DX (and D3DCompiler) dlls.

**Comment by NerosTie** [comment]
[OR2006C2C.EXE_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3435584/OR2006C2C.EXE_d3d9.log)

Is that ok?

**Comment by Joshua-Ashton** [comment]
> warn:  DxsoCompiler::processInstruction: unhandled opcode: TexM3x3VSpec
warn:  DxsoCompiler::processInstruction: unhandled opcode: TexBemL

Probably this

**Comment by NerosTie** [comment]
The water is no longer black :tada: 
![Screenshot_20190909_223204](https://user-images.githubusercontent.com/4572452/64564394-b7bded00-d351-11e9-8c66-45accd3a3267.png)

But the FPS are not capped. I still don't know if it comes from d9vk or not. Because of that, the game is running too fast and it's unplayable.

**Comment by Joshua-Ashton** [comment]
FPS is capped for me in your trace. Can you provide a trace made with d9vk?

**Comment by NerosTie** [comment]
https://mega.nz/#!nmghkYRJ!QFOlewtxXOcw7ae4kO2KL-O_fgWZZUQI8SxEyajkO0o

And this is what I have when I retrace the previous trace:

https://imgur.com/GrVTVJM

**Comment by Joshua-Ashton** [comment]
Yeah but it still runs really fast on native playback

**Comment by NerosTie** [comment]
Ok, it could be related to https://github.com/doitsujin/dxvk/issues/399 and can be fixed with https://github.com/pchome/VkGHL/releases

The parameter I use with Steam: 
```FPS=60 VK_LAYER_PATH=. VK_INSTANCE_LAYERS="VK_LAYER_LUNARG_VkGHL"```

Tested with Ys Origin, STALKER, Full Spectrum Warrior, Far Cry, Crysis (well, the menu) and Beyond Good & Evil. And yes, it works... but I'll have to do that with every games using d9vk and dxvk, it's really an annoying thing. (I don't have this issue when there is no layer like vkcube, GZDOOM, vkQuake, The Talos Principle, etc...)

But I have 2 examples (with d9vk) where I don't need this workaround: Skullgirls and Psychonauts (60fps and 30fps). Why?

😕
