### ISSUE TITLE
Divinity II → shadows are shaking when you move the camera

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#266]
https://i.imgur.com/Y1C8Itn.mp4

### System information
- GPU: Nvidia GT 730M
- Driver: 430.34
- Wine version: Proton 4.2
- DXVK version: #725 (jobs)

### Apitrace file(s)
https://mega.nz/#!L2B31SpZ!Go5TDsa8HKVNkd3o4r_WvH64mE-pOzkiWbprGn8J8Tc

### Log files
[steam-219780.log](https://github.com/Joshua-Ashton/d9vk/files/3436422/steam-219780.log)

**Comment by NerosTie** [comment]
It's an issue when the option "Timeslice Shadow Update" is activated.

**Comment by tannisroot** [comment]
I tried the trace and I can't reproduce it anymore with latest DXVK.

**Comment by NerosTie** [comment]
Tested with #793 and the issue is still here.

**Comment by NerosTie** [comment]
It looks like the issue is gone.
Tested with #801.
