### ISSUE TITLE
Call of Duty 2 → crash when launching a new game or resume it

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#267]
I can't run Call of Duty 2, World at War and Modern Warfare. When I want to run it, it crashes and I have this message (for CoD2):

![Screenshot_20190726_162225](https://user-images.githubusercontent.com/4572452/61963982-24ad3b80-afcd-11e9-91ba-519bb19c0042.png)

Tested with Lutris + retail CD and I have the same issue and the same log.

### System information
- GPU: Nvidia GT 730M
- Driver: 430.34
- Wine version: Proton 4.2
- DXVK version: #725 (jobs)

### Log files
[CoD2SP_s_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3436472/CoD2SP_s_d3d9.log)

**Comment by NerosTie** [comment]
With #759 the games still crashes at launch but with no error message this time.

**Comment by NerosTie** [comment]
This is what I have with World at War: 

![Screenshot_20190828_145853](https://user-images.githubusercontent.com/4572452/63857704-7a964a00-c9a4-11e9-8f83-b046be65d672.png)

Again, an error about "out of video memory".

I have the same issue with Dead or Alive 5:
![Screenshot_20190828_150115](https://user-images.githubusercontent.com/4572452/63857845-b3362380-c9a4-11e9-9819-08acc9835da8.png)

And probably other games that crash without an error.

**Comment by K0bin** [comment]
```
err:   D3D9: Cannot create texture:
err:     Type:    3
err:     Format:  D3D9Format::D24S8
err:     Extent:  400x300x1
err:     Samples: 4
err:     Layers:  1
err:     Levels:  1
err:     Usage:   2
err:     Pool:    0
```

That's the issue. D24S8 should be supported though. Not sure whats going on here.

**Comment by NerosTie** [comment]
Now, I can launch the game! :tada: 
Unfortunately, it hangs after the video when I launch a chapter.

**Comment by NerosTie** [comment]
Fixed by disabling "esync".
