### ISSUE TITLE
Dead Space → no shadows

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#268]
with d9vk
![](https://i.imgur.com/2BBVEzi.jpg)

without d9vk
![](https://i.imgur.com/izurDk3.jpg)

### System information
- GPU: Nvidia GT 730M
- Driver: 430.34
- Wine version: Proton 4.2
- DXVK version: #725 (jobs)

### Apitrace file(s)
https://mega.nz/#!juADkYpB!D2PaJ4ZWNY0NdOVq3bouO-SG0Af53CzDR5-nY1m0_hI

### Log files
[steam-17470.log](https://github.com/Joshua-Ashton/d9vk/files/3436756/steam-17470.log)

**Comment by CME42** [comment]
The shadows in the trace are working correctly for me on the latest master. Can you check if they are working for you? Get the latest build here: https://git.froggi.es/joshua/d9vk/-/jobs

**Comment by K0bin** [comment]
Dead Space appears to have different rendering paths depending on which (hack-)formats are available.
Comparing different apitrace this sticks out:
Nvidia Windows
R32F
DF24 => D3DERR_NOTAVAILABLE
D24S8
INTZ
1111774798 (NVDB)
NULL

AMD Windows
R32F
DF24
1111774798 (NVDB) => D3DERR_NOTAVAILABLE

D9VK
R32F
DF24
1111774798 (NVDB) => D3DERR_NOTAVAILABLE

**Comment by NerosTie** [comment]
We have shadows! :tada: 

But there is still an issue with the lights:

with d9vk:
![20190826004439_1](https://user-images.githubusercontent.com/4572452/63656943-6af7e500-c79b-11e9-98eb-d221e1f0ade0.jpg)

without d9vk:
![20190826004651_1](https://user-images.githubusercontent.com/4572452/63656949-76e3a700-c79b-11e9-8ee4-fe65de82882a.jpg)

With d9vk, it's brighter.

**Comment by K0bin** [comment]
https://i.imgur.com/1MyHK5n.jpg

I can confirm the brightness issue. Left one is Windows D3D9.

**Comment by K0bin** [comment]
Josh found a small issue with the way D9VK handles gamma ramps. Please retest.

**Comment by NerosTie** [comment]
Nothing changed, unfortunately.

**Comment by Joshua-Ashton** [comment]
If you're playing full screen then I experienced the same brightness change on Windows only in that mode.

It won't capture on a screenshot with native tho

**Comment by K0bin** [comment]
D3D9 and WineD3D change the system level gamma, which doesn't show up on screenshots. D9VK does the gamma correction using a shader.

That's why D3D9 and WineD3D screenshots look darker than D9VK screenshots.
From eyeballing it, it looks identical to me compared to Windows D3D9.

**Comment by NerosTie** [comment]
Hm, I disagree, it's not the screenshots, there is a real difference. Just try to switch between fullscreen and windowed, you'll see.

**Comment by K0bin** [comment]
> Just try to switch between fullscreen and windowed, you'll see.
This also happens with Windows D3D9.
