### ISSUE TITLE
Splinter Cell Chaos Theory unrerndered. Sound still on.

### ISSUE THREAD

**Issue by DanishJohn** [Joshua-Ashton/d9vk#27]
### Software information
Splinter Cell Chaos Theory Ubisoft original CDs (I assume the steam version should be similar but I'm testing with Lutris + D9VK).
Goes in-game but nothing is rendered, all black screen. You can still hear the sound.

### System information
- GPU:GTX 1060 6GB
- Driver:418.49
- Wine version: tkg-4.5 wine
- DXVK version: latest master

### Apitrace file(s):
-unable to provide one.

### Log files
[d3d9.log:](https://gist.github.com/DanishJohn/f636605aeec2da23183207330d1d9f9b)

**Comment by neVERberleRfellerER** [comment]
Is this still a problem? If so, could you test with demo? This one renders correctly:
https://www.moddb.com/games/tom-clancys-splinter-cell-chaos-theory/downloads/splinter-cell-chaos-theory-demo-updated
Can you confirm?
![Screenshot_20190530_191359](https://user-images.githubusercontent.com/11160972/58650650-8758c280-830f-11e9-99bd-93593ec9e22a.jpg)

**Comment by Joshua-Ashton** [comment]
I've debugged this game before for another issue in it so I know this is fixed.

If it isn't for you then please re-opn the issue.
