### ISSUE TITLE
Grand Theft Auto: San Andreas has graphics and gameplay issues

### ISSUE THREAD

**Issue by CartoonFan** [Joshua-Ashton/d9vk#270]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Grand Theft Auto San Andreas (Steam 12120)

### System information
- GPU: Nvidia GTX 960
- Driver: 430.34.0
- Wine version:  4.12.1 TKG
- DXVK version: https://github.com/Joshua-Ashton/d9vk/commit/bc64e8e0263004908090da60b4c478a6573fe7d0

### Apitrace file(s)
https://drive.google.com/file/d/1PmN6V0aXpUYCKG14GS2BCpL5_4ZrwcYi/view?usp=sharing

Motion blur and first mission lockup trace:
https://drive.google.com/file/d/1ADG7IdhmrCxUgb3KRIMg9icgnZkkmgwt/view?usp=sharing

### Log files
- d3d9.log:
[gta-sa_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3438878/gta-sa_d3d9.log)

Hello! I've noticed a weird bug where most vehicles are colored beige up close, but regain their color when viewed at a distance. Some environmental elements are also affected (walls, lights, etc.) It doesn't seem to affect people or motorcycles. 

Thanks!

EDIT: Replaced the trace with a tar.xz.

EDIT 2: 

Here's a summary of what's been seen so far:

- [x] Lighting issues

- [x] Car texture coloring

- [x] Motion blur

- [x] First mission freeze

I added another trace which includes motion blur and the first mission gameplay. Cheats were used to obtain a fast car with nitrous, but shouldn't affect anything else.

**Comment by NerosTie** [comment]
The game has also a lighting issue.

with d9vk
![20190728225330_1](https://user-images.githubusercontent.com/4572452/62012793-012fef80-b18b-11e9-976b-0ab8c94200df.jpg)

without d9vk
![20190728225523_1](https://user-images.githubusercontent.com/4572452/62012796-0db44800-b18b-11e9-9606-3a97ad6bd455.jpg)

**Comment by tannisroot** [comment]
^ That's because D9VK is lacking fixed function lightning implementation.

**Comment by Guy1524** [comment]
To avoid spam I'm just going to report here that the "motion blur" when traveling fast on vehicles is broken on d9vk

**Comment by tannisroot** [comment]
Master has ff lightning now so please retest.

**Comment by CartoonFan** [comment]
Lighting looks like it's fixed.

**Comment by tannisroot** [comment]
> texture problems still present.
would be nice to get some screenshots of that mb?

**Comment by CartoonFan** [comment]
Alright, I'll get a screenshot of that soon.

**Comment by NerosTie** [comment]
Cars when they are close:
![20190810212322_1](https://user-images.githubusercontent.com/4572452/62826048-6f29dd00-bbb5-11e9-808c-c56a167ca0b5.jpg)

When they are far:
![20190810212345_1](https://user-images.githubusercontent.com/4572452/62826054-79e47200-bbb5-11e9-9577-3e81880c25f4.jpg)

**Comment by CartoonFan** [comment]
Ha, beat me to it.

Also, there's this weird case in the intro where the car texture is blue instead:

![GTASA-20190810-122505](https://user-images.githubusercontent.com/29664894/62826121-22b9af80-bb6b-11e9-9aba-85edc56f1a94.png)
 
Also, I haven't been able to get through the first mission; The game seems to lock up when starting it and my computer slows to a crawl, requiring me to kill the process.

**Comment by CartoonFan** [comment]
@Guy1524 , this is the closest I could get to showing motion blur. I can't really tell the difference between native and d9vk here. Could you post a screenshot or something else that shows the motion blur issue? It'd be really appreciated. Thanks!

D9VK:
![20190811-140818](https://user-images.githubusercontent.com/29664894/62847216-fa74a280-bc89-11e9-9f5f-b9486f8b5a14.png)

Native:
![20190811221554_1](https://user-images.githubusercontent.com/29664894/62847314-6f47dc80-bc8a-11e9-9a77-ee7b7ed1e62a.jpg)

**Comment by CartoonFan** [comment]
All right, I added a second trace which hopefully highlights these issues.

**Comment by ThisNameIsntTaken** [comment]
Starting from 3831767, CJ and all the NPCs look like this:
![gta_sa](https://user-images.githubusercontent.com/44706448/63497960-3a772900-c4c5-11e9-8812-2e365ca46497.png)

[gta_sa_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3529017/gta_sa_d3d9.log)

I tried making an apitrace, but it doesn't show the issue.

**Comment by NerosTie** [comment]
I can confirm. 

With #716 the game was perfect.

**Comment by CartoonFan** [comment]
I've got the same thing here. Also, the fullscreen game window is only using the top-left corner for me instead of the whole screen, but I don't know if that's D9VK's issue (it didn't happen with previous commits).

**Comment by Joshua-Ashton** [comment]
Can't replicate the fog issue on any of my GTA SA traces

**Comment by Joshua-Ashton** [comment]
Can you make a trace with d9vk?

**Comment by Riesi** [comment]
d9vk trace that showed the issue for me on replay:
https://drive.google.com/open?id=1Zg2BgHB8yeh9dFggJXFa7qvqqKOAJTmT

**Comment by Guy1524** [comment]
@CartoonFan The issue actually only happened on my first session playing, the motion blur was offset by about 50% of the screen.  However now I can no longer reproduce it, so it's probably best to just ignore it unless somebody re-encounters it.

**Comment by CartoonFan** [comment]
@Guy1524 Sounds good to me. I'll update the main post accordingly. Thanks for replying!

**Comment by CartoonFan** [comment]
The fog issue looks like it's fixed for me as of https://github.com/Joshua-Ashton/d9vk/commit/625bf3032a0e1e1b22de739e7651f23fc8da6ae9 . Great job! I also noticed that with the first mission issue, the audio continues to play while the video stays at the mission title, and the audio is fairly quiet compared to what I remember. 

With my resolution issue, this is supposedly 1024x768 fullscreen, according to the game:
![20190822-165956](https://user-images.githubusercontent.com/29664894/63557610-5b0fa500-c4fe-11e9-89ce-5da70d05fdad.png)

The game renders it as seen, black borders and all.

**Comment by CartoonFan** [comment]
So, a small update:

- The resolutions are still weird for me. I might try a widescreen patch in the future to make my native resolution available, if nothing else (It's not available at all, probably a fault of the game).

- The video freezing on the first mission (and consequently the audio issues) seem to be related to anti-aliasing. Turning it off allows me to progress further.

**Comment by NerosTie** [comment]
On my side, with #778, everything is good. But yes, the game freezes when there is a transition to a cutscene when the antialiasing is on (could it be related to https://github.com/Joshua-Ashton/d9vk/issues/264#issuecomment-515771619 ?)

**Comment by CartoonFan** [comment]
Awesome! I managed to get my resolution fixed for now by disabling the proton fullscreen patch on Wine-TKG 4.13+. I'm pretty sure it worked before, but maybe something happened. Who knows? I'm just happy to find a workaround.

**Comment by NerosTie** [comment]
I don't have any issue with the resolution with Proton, it's weird, but I don't think it's related to d9vk.

**Comment by CartoonFan** [comment]
I agree, at least for now. With wined3d, it's like a borderless window, and with d9vk, those black borders are there. That's pretty much the only difference I can see. Virtually every time I changed resolution, I got an effect similar to https://github.com/Joshua-Ashton/d9vk/issues/270#issuecomment-524122513, even with a clean prefix (+d9vk/dxvk), changing settings, etc. Right now, disabling the fullscreen patch is the only thing so far that has worked almost every time. But I'm definitely glad to hear that it works well for you.

**Comment by Joshua-Ashton** [comment]
I have a fix hopefully in the works for this.

**Comment by Joshua-Ashton** [comment]
Can you try with https://github.com/Joshua-Ashton/d9vk/commit/8490b27bf20b3ee20d0aa5d850e430841415e7e0?

**Comment by CartoonFan** [comment]
All right, I'll give it a try.

**Comment by CartoonFan** [comment]
Great work! The fullscreen issue seems to be fixed for me with both games I had problems with (this one and Forgotten Realms: Demon Stone). On another note, it's still amazing that I can make a game like this hang indefinitely simply by changing resolutions too often, but as usual, I'm not sure if that's a D9VK bug yet or not. More testing, right? Again, though, stellar job!

**Comment by NerosTie** [comment]
> Forgotten Realms: Demon Stone

Btw, if you have the time, can you upload an apitrace for this game? (issue with the logo and the white textures)

**Comment by CartoonFan** [comment]
> > Forgotten Realms: Demon Stone
> 
> Btw, if you have time, can you upload an apitrace for this game? (issue with the logo and the white textures)

Yeah, I noticed that too. I have a Windows trace already, but the issues don't show up there, so I just want to make one with D9VK and then I'll be ready. Thanks!

**Comment by Joshua-Ashton** [comment]
Can this be closed?

**Comment by CartoonFan** [comment]
What should I about the antialiasing-related hang? Should I make a separate bug, or close this and wait for #264, or something else? I'm OK with closing it if the remaining stuff is handled in another bug.

**Comment by Riesi** [comment]
@CartoonFan could you try #328 and see if it fixes the hang?

**Comment by CartoonFan** [comment]
All right, I'll try it.

**Comment by CartoonFan** [comment]
OK, It seems that the game no longer hangs during cutscenes. There are a few stutters for me near the beginning of the game, but those seem to go away eventually. However, the game seems to be ignoring Wine-TKG's Proton fullscreen patch and changing my desktop resolution when I change it in-game. Do you happen to know anything about this? I can open a separate bug if you think it's not related.

In any case, I guess it's time to close this bug, as the original issues are fixed and my problems here are smaller and more specific.

Closing #270.
