### ISSUE TITLE
Metal Slug X crashes with D9VK

### ISSUE THREAD

**Issue by CartoonFan** [Joshua-Ashton/d9vk#271]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Metal Slug X (GOG)

### System information
- GPU: Nvidia GTX 960
- Driver: 430.34.0
- Wine version: 4.12.1 TKG
- DXVK version: https://github.com/Joshua-Ashton/d9vk/commit/bc64e8e0263004908090da60b4c478a6573fe7d0

### Apitrace file(s)
Windows trace: https://drive.google.com/file/d/1XRPZGaYNST3STihY6NdxKnjBFujoKEec/view?usp=sharing

D9VK trace: https://drive.google.com/file/d/1M-0AhscF0TKM99Wfr47wFRsdP0_tUgA6/view?usp=sharing

### Log files
- d3d9.log:
[mslugx_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3438880/mslugx_d3d9.log)

Hello there! Metal Slug X crashes before loading the logos with D9VK. Wined3d and Windows seem to work fine, and the windows trace plays back nicely with D9VK, so I'm not sure what's wrong. Thanks!

EDIT: Updated the trace to tar.xz.

**Comment by Joshua-Ashton** [comment]
Crash is in ANGLE code.

I tried to debug this all day but ANGLE is a PITA to compile and none of my builds were functional. Will try again tomorrow...

**Comment by CartoonFan** [comment]
All right, sounds good. If it doesn't work out, there's also a Linux version of the game available, so I'm happy with whatever you can do.

**Comment by Joshua-Ashton** [comment]
Managed to compile Microsoft's ANGLE library. Unfortunately using that makes the game work fine which is not helpful.

**Comment by Joshua-Ashton** [comment]
Closed by 0c84d72941f8798770a6dec54fa7e57a711f5e8d

**Comment by CartoonFan** [comment]
Thanks, @Joshua-Ashton!
