### ISSUE TITLE
Gun seems to want opcode: Phase for something

### ISSUE THREAD

**Issue by CartoonFan** [Joshua-Ashton/d9vk#272]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Gun (GOG)

### System information
- GPU: Nvidia GTX 960
- Driver: 430.34.0
- Wine version: 4.12.1 TKG
- DXVK version: https://github.com/Joshua-Ashton/d9vk/commit/bc64e8e0263004908090da60b4c478a6573fe7d0

### Apitrace file(s)
https://drive.google.com/file/d/1tpXEFx9CLDAOcMjuB5S1R9MfkyMaLsoo/view?usp=sharing

### Log files
- d3d9.log:
[Gun_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3438892/Gun_d3d9.log)

Hi there. This is less of a visible bug, and more of something I can't see, I think. Gun seems to want opcode:Phase (among other things) for something, but I can't really tell what. My best guess is some effect on the main menu(maybe the trees or something), but I really can't tell what's wrong apart from the colors not being as rich as on my other monitor. Hopefully, it's at least good as evidence for the function being used in something. Thanks!

**Comment by Joshua-Ashton** [comment]
We don't need to do anything to handle PHASE.

**Comment by CartoonFan** [comment]
@Joshua-Ashton , are there some things you that you know you don't need? I've seen various "Unhandled render state", "Unhandled opcode", or "ConvertFormat" warnings in the logs, even when there doesn't appear to be obvious bugs present. Would you prefer to have the "bug" submitted and then close it, like this one, or do you have something else in mind? Do you only want visible issues submitted? This is really the first project I can remember submitting multiple bugs to, and it's somewhat difficult to know what's needed without a technical background. Thanks again!

**Comment by Joshua-Ashton** [comment]
Please don't report random warnings if things aren't visibly wrong.

**Comment by CartoonFan** [comment]
All right.
