### ISSUE TITLE
Risen 3 - random black flicker

### ISSUE THREAD

**Issue by aufkrawall** [Joshua-Ashton/d9vk#273]
The whole screen sometimes turns black for a few milliseconds, seems to happen rather randomly when moving the camera or walking around.
I've noticed that sometimes the volumetric fog volumes or fog shadows show some "popping" with native D3D9, maybe there is a corelation (well, or maybe not ;) )?

The black flicker though only occurs with D9VK (with any AMD driver).

D9VK log:
[Risen3_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3443032/Risen3_d3d9.log)

Windows D3D9 apitrace:
https://drive.google.com/open?id=1mJEY-ZjNyGWxFI6pAR5-3b7uNQwvwfdK

D9VK RenderDoc capture:
https://drive.google.com/open?id=1kdx3rph61M8Zwc4gbBCtFc-nm4RHn_5H

**Comment by K0bin** [comment]
That's weird.

So you made the apitrace with Windows D3D9.
When I now use Windows D3D9 to replay it, it shows the issue.

Sorry but I just gotta ask: are you sure you made that trace with Windows D3D9?
Otherwise this may just be a weird game bug. Although I dont remember seeing this when I played throught the game on Windows.

**Comment by aufkrawall** [comment]
I let it create the apitrace by throwing the d3d9.dll into its folder on Windows, so it's basically impossible that D9VK was used. ;)

If I recall it correctly, the issue isn't there either with wined3d. Will recheck.

**Comment by aufkrawall** [comment]
As expected, no random black flicker with wined3d.

**Comment by aufkrawall** [comment]
The flicker/flashing can also be white. Perhaps this indicates an issue with the eye adaptation shader?

**Comment by K0bin** [comment]
I didn't see flicker when replaying with Windows D3D9, saw some broken geometry. I'm gonna take another look at this.

**Comment by K0bin** [comment]
I'm seeing some geometry that goes crazy which might be whats causing your flicker.

That's also happening with D3D9 though which as I said is pretty weird. Probably some kind of apitrace bug.

The issue *could* be related to nested locking of buffers. That's something the game does that we don't support yet. Apitrace probably trips over that as well.

I do have the game so I'm probably just gonna test it myself.

**Comment by K0bin** [comment]
Please retest.

**Comment by aufkrawall** [comment]
It seems dark and bright flashing is still unchanged with 9cb88bae7b7130d00c61ebfe7efe9b82fd7d6979 .

**Comment by K0bin** [comment]
You didn't just replay the apitrace to test it, did you? The actual game seems to work fine for me now.

**Comment by aufkrawall** [comment]
Actual game capture showing the issue with 1h old D9VK build:
https://www.youtube.com/watch?v=_HFfd36c2DM&feature=youtu.be

**Comment by K0bin** [comment]
Meh. As you can see, this is hard to reproduce. I have no idea how to even fix this. Apitrace doesn't work with the game and hitting that one frame window with renderdoc isnt gonna happen.

**Comment by K0bin** [comment]
Can you try this build?
[risen 3 test.zip](https://github.com/Joshua-Ashton/d9vk/files/3541474/risen.3.test.zip)

**Comment by aufkrawall** [comment]
Thanks for your efforts. With your build, it seems to happen only directly after loading a savegame, but not otherwise.
It btw. seems to be fully reproducible that it happens directly after loading a savegame for the first time. I wonder if that is really 100% artifact free with d3d9/wined3d, going to recheck..

**Comment by K0bin** [comment]
I can reproduce the 1 frame flickers at the spot in the video. But only at that spot.

**Comment by aufkrawall** [comment]
With native d3d9, there can be a short flicker directly after loading a savegame, but it never occurs afterwards when moving the camera.

**Comment by jarrard** [comment]
I played this on my 1080TI when it was alive, and didn't see any black flicker on it. D9VK however did have a bit of stutter going on thanks to crap shader caching or something (it passes). 

I was even able to get reshade working which was nice, however several times I did get some sort of startup issue or blackscreen happening due to the movie intro files not working well under D9VK, also once or twice I had a corrupt shader file which causes everything to render black (or dark).

D9VK should probably put the shader file in the exe folder for easier finding. (rather then digging through the prefix folders)

**Comment by K0bin** [comment]
> D9VK however did have a bit of stutter going on thanks to crap shader caching or something

Shaders need to get compiled once before they can be cached.

> D9VK should probably put the shader file in the exe folder for easier finding. (rather then digging through the prefix folders)

If you mean the state cache: that's what it does by default unless you change the path in the config file.

**Comment by jarrard** [comment]
> If you mean the state cache:

Well this game had stutters whenever you encountered something new like a new NPC or area. (eventually it reduced however). 

Also I never really messed with a config file, d9vk was dumping the cache file into the wine prefix automatically (can't remember specifics, but it wasn't the exe folder).

**Comment by aufkrawall** [comment]
Good news: I can't reproduce it anymore with 23f4ac020568609ba07dd15ec4806b991111fd18 .

**Comment by aufkrawall** [comment]
@Joshua-Ashton and others:
Is there anything known about Risen 2 inventory issues? I can't find anything on the tracker.
The issue is that in the inventory/charachter menu, the picture is cropped with black bars to the left and right, making the game basically unplayable.
I can open a new issue (hopefully) with renderdoc capture if required.

**Comment by K0bin** [comment]
That isn't a known issue. Please make a bug report over at dxvk.
