### ISSUE TITLE
Psychonauts has missing animations

### ISSUE THREAD

**Issue by CartoonFan** [Joshua-Ashton/d9vk#274]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Psychonauts (GOG, Steam)

### System information
- GPU: Nvidia GTX 960
- Driver: 430.34.0
- Wine version: 4.12.1 TKG
- DXVK version: https://github.com/Joshua-Ashton/d9vk/commit/5f7e87f597c4c1924f4ce79042ac7367a3a51c8c

### Apitrace file(s)
https://drive.google.com/file/d/11ty1kLEcjUH5Zt0o0emSz2YEz4nlfmJ3/view?usp=sharing

### Log files
- d3d9.log:
[Psychonauts_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3445095/Psychonauts_d3d9.log)

Hello! Psychonauts is missing some "animations" being played on background objects.

Windows:
![Psychonauts_windows](https://user-images.githubusercontent.com/29664894/62099639-9c849b80-b243-11e9-905d-cdd5ccfe0c12.png)

![Psychonauts_windows_2](https://user-images.githubusercontent.com/29664894/62099656-ac9c7b00-b243-11e9-89d2-fa26b63e8766.png)

D9VK:
![Psychonauts_d9vk_alt](https://user-images.githubusercontent.com/29664894/62099733-e3729100-b243-11e9-80d5-e26e58ff118b.png)

![Psychonauts_d9vk_2](https://user-images.githubusercontent.com/29664894/62099665-bb832d80-b243-11e9-8085-4a4f0afe1022.png)

Thanks!

EDIT: Updated the trace to tar.xz.

**Comment by NerosTie** [comment]
I just want to say that the glasses from the main protagonist are no longer black: 

![20190909221439_1](https://user-images.githubusercontent.com/4572452/64563312-5bf26480-d34f-11e9-944d-8aa06b994c3c.jpg)

Tested with #833

**Comment by CartoonFan** [comment]
I didn't even notice that. Maybe it's due to the TexM3x3VSpec implementation? Either way, it's still a plus, yeah?

**Comment by tannisroot** [comment]
> Maybe it's due to the TexM3x3VSpec implementation

I've just tried the trace and that projection still doesn't render with 0.21, which has that RS implemented.

**Comment by CartoonFan** [comment]
Ah, sorry, @tannisroot, I was referring to the glasses issue mentioned in https://github.com/Joshua-Ashton/d9vk/issues/274#issuecomment-529647364. I tested the game recently and the projections are indeed still invisible.
