### ISSUE TITLE
THUG Pro (Tony Hawk's Underground 2 mod) has issues with online play

### ISSUE THREAD

**Issue by akeart** [Joshua-Ashton/d9vk#275]
When playing THUG Pro, some levels seem to have a very long freeze, which hinders online play. If I for example, start a server with College level, the server will be visible in the list, but if I start server with Boston level, the connection between OpenSpy and the game times out (apparently) and the server will not be visible.

### Software information
Name of the game, settings used etc.

### System information
- GPU: RX 550
- Driver: Mesa
- Wine version: lutris-4.12.1-x86_64
- DXVK version: 0.13f

**Comment by Joshua-Ashton** [comment]
Does it work fine with Wine? I don't do any networking stuff...

An APITrace would also be useful to see if I can see why it's freezing

**Comment by Joshua-Ashton** [comment]
If you can get more info and its still replicable feel free to re-open...

**Comment by akeart** [comment]
Sorry, I forgot about this! This issue hasn't occured long time, so I guess it was just a fluke with my system.
