### ISSUE TITLE
Call of Duty: WaW, MW, and MW2 crash when loading into maps on Radeon cards

### ISSUE THREAD

**Issue by serebit** [Joshua-Ashton/d9vk#276]
When running any of the aforementioned Call of Duty games on Linux with the below system configuration, the games run correctly until a map is loaded. As soon as the game attempts to display the game world, it crashes with no error message. This behavior is the same across all 3 games, although the individual issues may be unrelated. Not all games with D9VK have this issue on my system-- most notably, A Hat in Time functions perfectly.

### Software information
The issue has been noted in the following games:
- Call of Duty: World at War
- Call of Duty 4: Modern Warfare
- Call of Duty: Modern Warfare 2

### System information
- GPU: RX 480 8GB
- Driver: Mesa 19.0.6
- Wine version: Proton 4.11
- D9VK version: 0.13f and master

### Log files
- Modern Warfare: [steam-7940.log](https://github.com/Joshua-Ashton/d9vk/files/3449434/steam-7940.log)
- World at War: [steam-10090.log](https://github.com/Joshua-Ashton/d9vk/files/3449436/steam-10090.log)
- Modern Warfare 2: [steam-10180.log](https://github.com/Joshua-Ashton/d9vk/files/3449438/steam-10180.log)

**Comment by K0bin** [comment]
The logs aren't particularly helpful. 

We need an apitrace (the part of the issue template you removed). https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace

Also try installind Microsofts D3D**X**9 and D3DCompiler using something like Protontricks.

**Comment by Joshua-Ashton** [comment]
Pretty sure an apitrace won't be helpful given the game works on Windows :-/

**Comment by money123451** [comment]
have you tried with ogl gta Iv has stopped working with 4.11 with both d9vk and wined3d where 4.2 with both the latest master of d9vk and wined3d goes ingame

**Comment by Riesi** [comment]
@serebit since you are using proton. Could you try to set `PROTON_FORCE_LARGE_ADDRESS_AWARE=1 %command%` as the launch option for the games?
I remember patching my games with LAA, because they were crashing on certain maps, but the proton option is easier.

**Comment by lacc97** [comment]
Seems to be related to #246?

**Comment by wundrweapon** [comment]
>Could you try to set `PROTON_FORCE_LARGE_ADDRESS_AWARE=1 %command%` as the launch option for the games?

Now that D9VK is included in Proton, I used the following launch options. Note, T4M is not in use: `PROTON_USE_D9VK=1 %command% PROTON_FORCE_LARGE_ADDRESS_AWARE=1 %command%`  
This made the map load, but my FOV just kinda got progressively smaller for a few seconds with bad response time before crashing altogether. Additionally, the menu is at 45FPS, which is what I had without D9VK in use.

**Comment by serebit** [comment]
@Riesi Enabling `PROTON_FORCE_LARGE_ADDRESS_AWARE=1` does not seem to affect the crashes. I also should mention that the crashes *only* occur when D9VK is enabled.

**Comment by wundrweapon** [comment]
On my end, I started messing with some settings. Seems like if my settings are low and I use T4M, and I move/turn slowly and carefully for the first few minutes (during which the game is *brutally* crash-prone), I can get stable gameplay between 90 and 120FPS. Note that I'm talking about Der Riese here, as campaign (Burn 'em Out, anyway) can play crash-free albeit with horrendous framerates.

**Comment by K0bin** [comment]
Try installing D3DCompiler and D3D**X**9 using Protontricks.

**Comment by K0bin** [comment]
Installing Microsofts D3DX9 and D3DCompiler didn't help here, right?

**Comment by serebit** [comment]
@K0bin Just tested, and installing `d3dcompiler_47` and `d3dx9` via winetricks in the game's proton wineprefix did not affect the crashes, at least not in World at War.

**Comment by K0bin** [comment]
I can confirm that the game works perfectly fine on Windows with D9VK. 

Can you try running the game with normal Wine (ofc with D9VK installed) running Windows Steam?

**Comment by serebit** [comment]
Just tested COD4 running Windows Steam with D9VK 0.12 installed via winetricks. The game crashed in the same place, but I got a popup with the following error log instead of a simple CTD.

[cod4-error.txt](https://github.com/Joshua-Ashton/d9vk/files/3463246/errorlog.txt)

**Comment by Joshua-Ashton** [comment]
Crash is in your driver. Interesting, got a trace I can check out?

**Comment by serebit** [comment]
@Joshua-Ashton Here's the D3D trace from running Steam via wine. I ran `WINEDEBUG=-all,-fixme,+d3d wine "/home/serebit/.wine/drive_c/Program Files (x86)/Steam/Steam.exe" >> file.log 2>&1`, which opened Steam, then ran COD4 and started the mission FNG. Same error as the one above. 
[cod4-trace.log](https://github.com/Joshua-Ashton/d9vk/files/3464465/file.log)

**Comment by K0bin** [comment]
That's not an apitrace.

https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace <- This is what we need to debug this.

**Comment by serebit** [comment]
That page says I should disable D9VK to generate an apitrace. If it's an issue with D9VK, and I can't reproduce the problem with vanilla D3D, should I just run apitrace with D9VK?

-------- Original Message --------

**Comment by K0bin** [comment]
No, use WineD3D to generate the apitrace.

**Comment by serebit** [comment]
Sorry, I just fail to see how a non-D9VK apitrace would help, since I can't reproduce the problem without D9VK enabled.

-------- Original Message --------

**Comment by K0bin** [comment]
apitrace records all D3D9 calls the game makes and allows us to replay those calls later.
If the game crashes the problematic api call isnt gonna be in the trace.

**Comment by serebit** [comment]
Ah, okay. I'll generate the trace then. Thanks for the explanation!

-------- Original Message --------

**Comment by serebit** [comment]
Here's the apitrace for COD4: https://drive.google.com/open?id=1mZWJtD2d41h-OXfZQk3-Qs9sFPniZRZX

**Comment by K0bin** [comment]
That trace replays fine with D9VK for me.

![grafik](https://user-images.githubusercontent.com/1131720/62455258-3d101980-b776-11e9-98a2-6a0430c51a34.png)

I also noticed that your logs show it crashing after calling something in D3DX9. So please double check that you have Microsofts `d3dx9_34` installed and that the Wine overrides are set to native for that dll.

If that's the case I'm gonna need a apitrace recorded with D9VK after all and I'll probably look have to compare the two.

**Comment by serebit** [comment]
Here's the D9VK apitrace @K0bin: https://drive.google.com/open?id=1KiYIUr6dlA2WYWvTsCBYIXoG43PJQimZ

**Comment by NerosTie** [comment]
I tested WaW and MW with #852 and they work well, probably MW2 too (Linux + Proton + Nvidia). The only one I have an issue is CoD 2.

**Comment by serebit** [comment]
@NerosTie This seems to be an issue with the AMD Linux driver, so it's no surprise that you aren't affected

**Comment by serebit** [comment]
Any progress on this?

**Comment by K0bin** [comment]
Try running the games with Vulkan validation layers.

**Comment by serebit** [comment]
[steam-7940.log](https://github.com/Joshua-Ashton/d9vk/files/3780972/steam-7940.log)

This is COD4's log with launch options `PROTON_USE_D9VK=1 PROTON_LOG=1 VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation %command%` in Steam. Doesn't seem to offer any clues to me, but you might spot something.

**Comment by Joshua-Ashton** [comment]
`err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED`

Doesn't look good

**Comment by serebit** [comment]
Fixed as of latest D9VK with `PROTON_FORCE_LARGE_ADDRESS_AWARE=1` or a couple config options. Closing.
