### ISSUE TITLE
Warhammer Online (return of reckoning) Black Screen with sound and cursor

### ISSUE THREAD

**Issue by xpander69** [Joshua-Ashton/d9vk#28]
Black Screen, with cursor and sound playing

### Software information
Warhammer Online, Windowed and fullscreen tested.

### System information
- GPU: GTX 1080Ti
- Driver: 418.56
- Wine version: 4.5 staging
- D9VK version: b91f6e21

### Apitrace file(s)
none atm, can do if needed

### Log files
- d3d9.log: 
[WAR_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3081206/WAR_d3d9.log)

- dxgi.log: 
[WAR_dxgi.log](https://github.com/Joshua-Ashton/d9vk/files/3081207/WAR_dxgi.log)

**Comment by xpander69** [comment]
Ok i got it running with winetricks d3dcompiler_47, i can see menu buttons, hear music. crashes after loading screen though:

Wine errors:
```
0087:fixme:d3dx:D3DXLoadSurfaceFromMemory Unhandled filter 0x3.
0087:fixme:d3dx:D3DXCreateTextureFromFileInMemoryEx Generation of mipmaps for compressed pixel formats is not implemented yet.
0087:fixme:d3dx:D3DXLoadSurfaceFromMemory Unhandled filter 0x3.
0087:err:d3d:x8r8g8b8_to_dxtn Failed to allocate memory for conversion
0087:fixme:d3dx:D3DXCreateTextureFromFileInMemoryEx Texture loading failed.
0087:fixme:d3dx:D3DXCreateTextureFromFileInMemoryEx Texture loading failed.
0087:fixme:d3dx:D3DXCreateTextureFromFileInMemoryEx Texture loading failed.
0087:fixme:d3dx:D3DXCreateTextureFromFileInMemoryEx Generation of mipmaps for compressed pixel formats is not implemented yet.
0087:fixme:d3dx:D3DXCreateTextureFromFileInMemoryEx Texture loading failed.
0087:fixme:d3dx:D3DXCreateTextureFromFileInMemoryEx Texture loading failed.
0087:fixme:d3dx:D3DXCreateTextureFromFileInMemoryEx Texture loading failed.
0087:fixme:d3dx:D3DXCreateTextureFromFileInMemoryEx Generation of mipmaps for compressed pixel formats is not implemented yet.
0087:fixme:d3dx:D3DXCreateTextureFromFileInMemoryEx Texture loading failed.
0087:fixme:d3dx:D3DXCreateTextureFromFileInMemoryEx Texture loading failed.
0087:fixme:d3dx:D3DXCreateTextureFromFileInMemoryEx Texture loading failed.

```

d3d9.log:
https://pastebin.com/zGzsdWrE

d3d9.log was 144MB big, but with spamming the same thing constantly so i used pastebin and cut the crap out of it

**Comment by xpander69** [comment]
Just updating this here with new information:
d9vk: 65b8ace7
I'm now able to get into the game, but it doesn't render much:

![ss_29042019_20 20 26](https://user-images.githubusercontent.com/1345116/56914562-1a0e0380-6abd-11e9-97aa-d466698e73f4.png)


log: https://pastebin.com/HDCyEXU3

**Comment by mylucky2018** [comment]
wine d9vk verison spam errors
warn:  Direct3DDevice9Ex::SetMaterial: Stub
![螢幕快照_2019-04-30_18-18-13 csmt](https://user-images.githubusercontent.com/41288775/56957021-74b86580-6b78-11e9-89f8-72a3e5f84298.png)
![螢幕快照_2019-04-30_18-21-37 d9vk](https://user-images.githubusercontent.com/41288775/56957033-797d1980-6b78-11e9-9c73-488f7e24b6fb.png)

**Comment by neVERberleRfellerER** [comment]
Both D3DXLoadSurfaceFromMemory and D3DXCreateTextureFromFileInMemoryEx are in d3dx9_36
https://github.com/wine-mirror/wine/blob/4e44d74afb12b40f673e3be0a91cd523013544cd/dlls/d3dx9_36/texture.c#L566
https://github.com/wine-mirror/wine/blob/4e44d74afb12b40f673e3be0a91cd523013544cd/dlls/d3dx9_36/surface.c#L1818
Maybe native version could help.

**Comment by Joshua-Ashton** [comment]
Don't use Wine's d3dx9. They're not accurate and don't work with d9vk. I should investigate *why* but given the real ones don't have issues, just use those for now.

**Comment by mylucky2018** [comment]
wine-tkg-staging-esync-marchopt-git-4.7
d9vk verison spam errors
warn: Direct3DDevice9Ex::SetMaterial: Stub
cant see name and hp bar
cant see all spell effects
wine errors a lot of spam (warn:  Direct3DDevice9Ex::SetMaterial: Stub and warn:  Direct3DDevice9Ex::LightEnable: Stub)
[edit-wine-errors.log](https://github.com/Joshua-Ashton/d9vk/files/3133442/edit-wine-errors.log)
![2019-04-30_18-18-13 csmtvsd9vk](https://user-images.githubusercontent.com/41288775/56999481-e8428d00-6be1-11e9-9053-b6b797ff71f1.png)

**Comment by Joshua-Ashton** [comment]
Game uses NVAPI + fixed function...

**Comment by xpander69** [comment]
@mylucky2018 how do you get it to render? i have same wine-tkg-staging-esync-marchopt-git-4.7 and tried all the latest D9VK versions, but it still renders like it's on the picture i posted here. Did you do any additional tricks?

**Comment by mylucky2018** [comment]
gpu gtx 750
nvidia driver 418.56
success at any wine version staging / vanilla / aur etc....
my installation process

wineboot -u
env WINEPREFIX=$HOME/.wine2/ror /usr/bin/winecfg

env WINEPREFIX=$HOME/.wine/ror sh winetricks --unattended --force allfonts msxml3 d3dx9 dotnet40

env WINEPREFIX=$HOME/.wine/ror /usr/share/d9vk/setup_dxvk.sh install

work WAR.exe or WAR-64.exe

Just as usual nothing special setup method.
only bug cant see name and hp bar and no all spell effects
and only graphics bug in select char window ( there is no graphics problem when entering the game ) 
![2019-05-03_04-51-08 ror1](https://user-images.githubusercontent.com/41288775/57107618-0a174d80-6d63-11e9-9db5-d1bfdf67ec21.png)

**Comment by xpander69** [comment]
@mylucky2018 Thanks. I only had winetricks dotnet40, installed d3dx9 also now and i dont see any issues, hp bar and spell effects seemed to work also, didnt test too long atm. I didnt install the allfonts.

![ss_03052019_00 40 18](https://user-images.githubusercontent.com/1345116/57108754-5ac78000-6d3c-11e9-938a-f73b32168ce9.png)

**Comment by Joshua-Ashton** [comment]
Is this fixed? Can this be closed?

**Comment by xpander69** [comment]
still need to install d3dx9 via winetricks to make it render properly. but the original black screen issue is gone. So i think the original issue can be closed?

**Comment by sigzegv** [comment]
@Joshua-Ashton is there any way you fix the bright ground texturing that happen in wined3d (and btw also in d9vk but that should not happen)

**Comment by sigzegv** [comment]
in some spots lightning tries to pop but it doesn't correctly displays

d9vk
![wow-1 12-spot-d9vk](https://user-images.githubusercontent.com/6304596/62479953-e4a93e00-b7ae-11e9-8ec0-e6bd7d2f6aab.png)

wined3d
![wow-1 12-spot-wined3d](https://user-images.githubusercontent.com/6304596/62479970-eb37b580-b7ae-11e9-8e73-4ee15f04c2e2.png)

I noticed clipping fog effects are not present
![wow-1 12-d9vk](https://user-images.githubusercontent.com/6304596/62480049-1fab7180-b7af-11e9-96a3-1c37d5ff16e1.png)
![wow-1 12-wined3d](https://user-images.githubusercontent.com/6304596/62480052-220dcb80-b7af-11e9-8c0f-05475b6aa6eb.png)

**Comment by K0bin** [comment]
If you're seeing the same issue with D9VK and WineD3D, make sure you have the Microsoft versions of both d3dcompiler and d3d**x**9 installed.

**Comment by xpander69** [comment]
yeah the bright groundtexture issue is superbly annoying and i have no clue what causes it. It also happens with wined3d

Upper one is how it should look:
![winvswine-warhammer](https://user-images.githubusercontent.com/1345116/63214171-799c2780-c11d-11e9-91c2-d7e7a7c14e8b.jpg)

**Comment by xpander69** [comment]
So managed to get the apitrace finally (thanks to masush5 from frog discord server)

This apitrace is with wined3d: https://mega.nz/#!MOh2VKLb!7qOb_2KdSmX5wQi3UR1sodY0fQ8Yg8qdyt9Gi2372ro

overly bright groundtexture happens with both, d9vk and wined3d so i dont know if this apitrace is of any help.

i also needed to install d3dx9_34.dll otherwise with both d9vk and wined3d the game doesnt render at all.

**Comment by sigzegv** [comment]
the launcher's window (launcher is a .net app) renders black. I remember I didn't had this issue in older d9vk releases.

**Comment by xpander69** [comment]
The odd thing is that it renders black for me only on the left monitor. on the right monitor its all fine. 
Anyway this game still has the overly bright ground texture issue and it still requires d3dx9_34 to render correctly (minus the bright ground texture)

**Comment by xpander69** [comment]
without **d3dx9_34**  (just using the d9vk without any d3dx9 stuff from winetricks) it renders like this:
![ss_18122019_00 14 32](https://user-images.githubusercontent.com/1345116/71039072-f4a53700-212b-11ea-8f99-63e14b636d3b.png)

and the **d9vk.log**: 
[WAR_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3975710/WAR_d3d9.log)

**Comment by Joshua-Ashton** [comment]
I don't care about supporting wine's d3dx9 implementations, they're broken.

**Comment by xpander69** [comment]
Gonna close it as its not D9VK problem anymore.

**Comment by sigzegv** [comment]
Just to understand (because I need to understand) @Joshua-Ashton about the bright texture issue why I could happen in both wine3d3 and d9vk but not on windows ? Could it be becuase it's "should" already be broken on window (but fixed by some magic ?)
