### ISSUE TITLE
Battlefield: Bad Company 2 → black glitches

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#281]
with d9vk
![20190802155528_1](https://user-images.githubusercontent.com/4572452/62377156-90018b00-b542-11e9-8f89-562a83a73d8e.jpg)

without d9vk
![20190802155800_1](https://user-images.githubusercontent.com/4572452/62377193-a0196a80-b542-11e9-9698-f12205f24e78.jpg)

### Software information
Force DirectX9: https://pcgamingwiki.com/wiki/Battlefield:_Bad_Company_2#Force_DirectX_Level

### System information
- GPU: Nvidia GT 730M
- Driver: 430.40
- Wine version: Proton 4.11
- DXVK version: #742 (jobs)

### Apitrace file(s)
https://mega.nz/#!PzxDgIiS!kRFcVfhEcZ4MnYJEKVJNYZIQRvmt2lPfY-bU_2HOdh0

### Log files
~~[steam-24960.log](https://github.com/Joshua-Ashton/d9vk/files/3461686/steam-24960.log)~~
[steam-24960.log](https://github.com/Joshua-Ashton/d9vk/files/3541786/steam-24960.log)

**Comment by K0bin** [comment]
Interesting, the D3D11 renderer apparently had the exact same issue with DXVK.

https://github.com/doitsujin/dxvk/issues/267#issuecomment-380252160

**Comment by K0bin** [comment]
BTW your logs were made with WineD3D. That's not all that useful to us.

**Comment by NerosTie** [comment]
oops!
[steam-24960.log](https://github.com/Joshua-Ashton/d9vk/files/3541780/steam-24960.log)

**Comment by K0bin** [comment]
So looking at this with Renderdoc:
The game does an early Z pass and the black squares are apparently the result of fragments that failed the depth test during the actual geometry pass.

**Comment by NerosTie** [comment]
The black artifacts in the background are gone (tested with #998, 0.30 and 0.22 and they are gone for all of them, I think it has been resolved by the new Nvidia driver).

But the shadows are still broken:
https://imgur.com/39dEimw

**Comment by Joshua-Ashton** [comment]
Probably depth bias

**Comment by NerosTie** [comment]
Everything seems to be fixed with DXVK 1.5.1 :-)
