### ISSUE TITLE
Anno 1404

### ISSUE THREAD

**Issue by Bumbadawg** [Joshua-Ashton/d9vk#284]
EDIT: the culprit is the AA (MSAA?) 

Using D9VK from Proton 4.11, Anno 1404 runs with great performance, but there is an issue with the ingame cinematic rendering ([i mentionned it here](https://github.com/ValveSoftware/Proton/issues/641#issuecomment-517914148))

here are my graphics settings
![Screenshot_20190804_142236](https://user-images.githubusercontent.com/1251056/62423669-fb6a6a80-b6b2-11e9-9c5c-e3f9babbf9a7.png)

the "PiP" bug
![Screenshot_20190804_142402](https://user-images.githubusercontent.com/1251056/62423670-fc030100-b6b2-11e9-838a-0e9839833db6.png)

[steam-33350.log](https://github.com/Joshua-Ashton/d9vk/files/3464881/steam-33350.log)

**Comment by NerosTie** [comment]
The issue here is the Antialiasing filtering option, if you disable it, the ingame cinematic are fixed.

Related issues: https://github.com/Joshua-Ashton/d9vk/issues/264#issuecomment-515771619 https://github.com/Joshua-Ashton/d9vk/issues/270#issuecomment-524210259

**Comment by NerosTie** [comment]
The issue is still here. What is odd about this game is that you need to install d3dx9 manually otherwise you just have a black screen, even with d9vk.

**Comment by Bumbadawg** [comment]
yes, d9vk doesn't replace D3D, it links it to your Vulkan libraries. Although it should be installed by default when using Proton, which is not so this can be reported to Proton's issues.
i tested latest master commit, it didn't fix the MSAA PiP bug.

**Comment by Joshua-Ashton** [comment]
D9VK does replace D3D, that's the whole purpose of it.

**Comment by Joshua-Ashton** [comment]
Please provide an APITrace.

**Comment by Bumbadawg** [comment]
[trace](https://framadrop.org/r/e-8LDZDMjE#lZwOgdXhzG0/UJCAjIY+huEDNoIylbakgrYI18pNDp4=)
it seems to only happen with MSAAx4, not the X8 option

**Comment by Joshua-Ashton** [comment]
Please try with https://git.froggi.es/joshua/d9vk/-/jobs/934

**Comment by Joshua-Ashton** [comment]
Feel free to re-open if its still broken but this fixes it on my end on Nvidia and AMD

**Comment by Bumbadawg** [comment]
That fixed it, thank you @Joshua-Ashton =)
