### ISSUE TITLE
Grand Theft Auto: Episodes from Liberty City

### ISSUE THREAD

**Issue by hitman249** [Joshua-Ashton/d9vk#286]
### Software information
Grand Theft Auto: Episodes from Liberty City  
Version 1.0.2.0

The original Grand Theft Auto IV is no problem

### System information
- GPU: AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.27.0, 4.19.44-041944-generic, LLVM 8.0.0) (0x67df)
- Driver: RADV 19.2.0-devel
- Wine version:  Proton 4.11
- D9VK version: Build #748 master - f637f64d Aug 5, 2019 3:01pm

![Screenshot_20190805_221301](https://user-images.githubusercontent.com/1325326/62475054-6c527500-b7ce-11e9-9d24-375149e6e69b.png)

### Log files
- d3d9.log:
[Grand Theft Auto: Episodes from Liberty City.log](https://github.com/Joshua-Ashton/d9vk/files/3468242/Grand.Theft.Auto.Episodes.from.Liberty.City.log)

**Comment by Kattus** [comment]
This looks really similar to #99 
For what it's worth, this does not happen on nvidia.

**Comment by ThisNameIsntTaken** [comment]
Inside the game's directory (where EFLC.exe is located) create a dxvk.conf file with the following line:
`d3d9.hasHazards = True`

This should fix the issue.

**Comment by hitman249** [comment]
`d3d9.hasHazards = True`  
Thank you, it solved the problem

there is still a bug with the sky
![Screenshot_20190805_230456](https://user-images.githubusercontent.com/1325326/62478648-c60a6d80-b7d5-11e9-88e5-4e7d5633b94a.png)

**Comment by K0bin** [comment]
Should work out of the box now with new D9VK builds.
