### ISSUE TITLE
World of Warcraft 1.12 Missing ground specular

### ISSUE THREAD

**Issue by sigzegv** [Joshua-Ashton/d9vk#288]
Here on ground, some effects (speculars ? ) seems to be missing. I say ground here but it could be elsewhere than ground.

wined3d / windows
![wow-1 12-spot-wined3d](https://user-images.githubusercontent.com/6304596/62542805-d9145080-b85c-11e9-8f04-a326628177da.png)

d9vk
![wow-1 12-spot-d9vk](https://user-images.githubusercontent.com/6304596/62542822-e2052200-b85c-11e9-943a-2adfb8d406ae.png)

### System information
- GPU: gtx1070
- Driver: nv 430.40
- Wine version: ge protonified 4.10
- DXVK version: 1.3.1

### Apitrace file(s)
-  https://mega.nz/#!P7h2lYzZ!xxmM6fORdSpzf_0fxosiV-YQbVUa6WC5a-Pc4p5eLkw

### Log files
- [WoW_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3472467/WoW_d3d9.log)

**Comment by Joshua-Ashton** [comment]
![image](https://user-images.githubusercontent.com/21316711/63021634-eb177400-be98-11e9-9af8-07b5151a8f6f.png)

**Comment by sigzegv** [comment]
sorry I put the link with the key, should be ok now

**Comment by Joshua-Ashton** [comment]
Should be fixed now, can you verify?

**Comment by sigzegv** [comment]
I can confirm it's fixed ! thank you
