### ISSUE TITLE
World of Warcraft 1.12: Fog missing (fixed fog func unimplemented)

### ISSUE THREAD

**Issue by STiAT** [Joshua-Ashton/d9vk#289]
Hi Josh,

As mentioned in #219, I create a new ticket for the issue with the fixed func fog, closing #219 with the creation of this ticket.

### Software information
World of Warcraft 1.12 Client

### System information
```
GPU: AMD Radeon RX 460 Graphics
Driver: Mesa 19.0.6
Wine version: wine-4.12.1
D9VK version: d9vk-f637f64
LLVM 8.0
```
### API Trace
Sorry for wandering around like an idiot, but I have tremendous input lag when running in apitrace mode, my PC isn't the best and I wanted to show the clipping in/out (as you use the records for reproducing, sorry for the length/size :p).
https://drive.google.com/open?id=1blpFOEPSjxLHTWq9wPEJgyxi7d7VSxJ9

### Screenshots
Wine
![Screenshot from 2019-08-06 00-56-42](https://user-images.githubusercontent.com/1781015/62500205-babf3e00-b7e5-11e9-8ed2-a815602c318a.png)

Wine with D9VK
![Screenshot from 2019-08-06 00-57-34](https://user-images.githubusercontent.com/1781015/62500228-c9a5f080-b7e5-11e9-97e3-47677bbcc787.png)

**Comment by Joshua-Ashton** [comment]
Closed by 38317670396f3699b86311eb20d74e827a8f2cc5
