### ISSUE TITLE
Payday the heist draws transparent cylinder on the top half of the screen

### ISSUE THREAD

**Issue by Shished** [Joshua-Ashton/d9vk#29]
Game draws cylinder on the top half of the screen which obscures the view, it scales with FOV angle.
Screenshot:
https://steamuserimages-a.akamaihd.net/ugc/972124142076415321/779FFB141C269EDBB3DBE6A9F9910B233B96A185/

### Software information
Payday the heist, latest version on Steam, any settings.

### System information
- GPU: GTX 1060
- Driver: 418.52.03
- Wine version: 4.6 vanilla, Proton 4.2
- D9VK version: git master

### Apitrace file(s)
https://drive.google.com/file/d/14IaQWzw5Y7SHK7QNTD-0GNQLxcQ9L24B

### Log files
- d3d9.log: https://pastebin.com/asLq8yRq

**Comment by money123451** [comment]
should be fixed now retest.

**Comment by Shished** [comment]
Can confirm , this issue is now fixed. Can i use the same trace file to report other bugs in this game?

**Comment by Joshua-Ashton** [comment]
sure
