### ISSUE TITLE
Beyond Good And Evil config utility crashes with d9vk

### ISSUE THREAD

**Issue by CartoonFan** [Joshua-Ashton/d9vk#290]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace.
DO NOT use DXVK together with apitrace!

### Software information
Beyond Good and Evil (GOG) config tool

### System information
- GPU: Nvidia GeForce GTX 960
- Driver: 430.34.0
- Wine version: 4.13 TKG
- DXVK version: https://github.com/Joshua-Ashton/d9vk/commit/b25eaf65e7731d42263b78d091de672cdc791e05

### Apitrace file(s)
Windows: https://drive.google.com/file/d/1E-WN4czSyZuwJHI6PAxj8dyCpGN2YWGT/view?usp=sharing

D9VK: https://drive.google.com/file/d/1EI4Iqk5FrQb0zbcztfqcdb_ytaO7z-Ti/view?usp=sharing

### Log files
- d3d9.log:
[SettingsApplication_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3474258/SettingsApplication_d3d9.log)

- d3d11.log: N/A
- dxgi.log: N/A

Hello! Beyond Good and Evil's settings application "SettingsApplication.exe" seems to crash under D9VK. The traces don't render any frames (likely due to using ddraw), so they're pretty small. If you need it, I can probably get a trace with ddraw, but hopefully this is good enough for now. Thanks!

**Comment by K0bin** [comment]
Does it work with Wine?

Your apitraces are pretty useless at 7kb size. It's literally initializing D3D9 and then releasing it without drawing anything. All of that works fine with D9VK.

**Comment by CartoonFan** [comment]
It works with WineD3D, yes. I guess ddraw is the way to go, then?

**Comment by misyltoad** [comment]
Moved to https://github.com/doitsujin/dxvk/issues/1545
