### ISSUE TITLE
Alan Wake

### ISSUE THREAD

**Issue by ByCybernetik** [Joshua-Ashton/d9vk#294]
At the beginning of the level "The Signal" in the cafe humans when you pass near them, they disappear. D9VK linux
![20190807220311_1](https://user-images.githubusercontent.com/45942960/62695192-7b0f7680-b9de-11e9-8a93-6d959bb8ca12.jpg)

In native Direct3D9, humans become transparent. Native D39 Windows
![20190807185359_1](https://user-images.githubusercontent.com/45942960/62695868-e4dc5000-b9df-11e9-8695-185c378ec142.jpg)

### Software information
Alan Wake (Steam), Ultra setting

### System information
- GPU: AMD Radeon R9 290
- Driver: 4.5 (Compatibility Profile) Mesa 19.2.0-devel (git-486b33558a)
- Wine version: Proton 4.11-1
- DXVK version: Master 08.08.19 

### Apitrace file(s)
- https://drive.google.com/open?id=1vAYcQI_nXzEH5xSnXBBvY5OYCbHgFGo2

### Log files
- d3d9.log: 
[AlanWake_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3480988/AlanWake_d3d9.log)

- d3d11.log:
- dxgi.log:

**Comment by baryluk** [comment]
The same happens even when using Wine without d9vk for me.  AMD Fury X, Mesa 19.3.0-devel (git-ce76be9933). All characters (4 of them in total) suddenly disappears.

**Comment by Joshua-Ashton** [comment]
Closed this as it fixes it in the trace.

I would really like to hear if it works for you, and anyone who has an NV card.

**Comment by NerosTie** [comment]
![20191009234201_1](https://user-images.githubusercontent.com/4572452/66522966-f41a6f80-eaee-11e9-9dd6-d64a4b74a4ec.jpg)


This is what I have. They are transparent but with a grid of points and horizontals lines inside.
With WineD3D, there is no transparency at all, so I can't compare.

Also, why is there no sound during the cutscenes with d9vk? oO
