### ISSUE TITLE
shade wrath of angels dont show any character in game

### ISSUE THREAD

**Issue by mrdeathjr28** [Joshua-Ashton/d9vk#295]
shade wrath of angels dont show any character in game

first level

![bgn](https://user-images.githubusercontent.com/6601480/62804714-ae700500-bab3-11e9-983a-7f162c39aa51.png)

2nd level

![2nd](https://user-images.githubusercontent.com/6601480/62804751-ccd60080-bab3-11e9-97b7-235283adc6c1.png)

PC Demo

https://www.moddb.com/games/shade-wrath-of-angels/downloads/shade-wrath-of-angels-demo-1-01

Nvidia Drivers 418.52.18 (run package)

Xubuntu 18.04 x64 - Kernel 4.17.12 generic (ubuntu mainline) -

CPUFreq: Performance

CPU: Core i3 8350K Tri-Core (Coffelake 14nm) 5.0Ghz + Zalman CNPS 10x Performa+

MEMORY: 8GB DDR4 2400mhz (4x2) Mushkin (dual channel: 37.5 gb/s)

GPU: Gigabyte Nvidia Geforce GTX 1050 OC (GP107 14nm: 640 Shaders / 40 TMUS / 32 ROPS) Windforce 2GB DDR5 7000Mhz 128Bit (110Gb/s)

MAINBOARD: ASUS Z370-P

**Comment by CartoonFan** [comment]
@mrdeathjr28 You might also want to help the developers by making an apitrace using [this guide](https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace) and then attaching the trace you made and the d3d9 log (it's found somewhere in the game's directory, usually something like "name of the exe"_d3d9.log) to your bug report. Thanks!

**Comment by mrdeathjr28** [comment]
@CartoonFan 

As comment before in discord in my case posted games dont produce correct trace

But main goal of this post is allow other users can trace

**Comment by CartoonFan** [comment]
Oh, I see. Didn't know that, thanks! Did the game produce any d3d9 logs?

**Comment by CartoonFan** [comment]
Well, no problem, I have my own here in case it didn't work out.

d3d9.log:
[Shade_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3489353/Shade_d3d9.log)

Windows trace: 
https://drive.google.com/file/d/1DtPAHxoT_s74TLDLzLrDBqoTxbXCAPtH/view?usp=sharing

Hope this helps!

**Comment by CartoonFan** [comment]
Characters seem to be rendered as of https://github.com/Joshua-Ashton/d9vk/commit/a054aa6ac4f76bfa585381e80c9f1f36a4847a04, but some models and textures are now broken for me:

![20191002-220653](https://user-images.githubusercontent.com/29664894/66100817-42fd5d80-e561-11e9-9fb5-0a8e294a9935.png)
![20191002-220700](https://user-images.githubusercontent.com/29664894/66100826-47297b00-e561-11e9-80a7-4b24247d223c.png)
![20191002-220713](https://user-images.githubusercontent.com/29664894/66100832-501a4c80-e561-11e9-8c76-ba9a98e5a78d.png)

**Comment by misyltoad** [comment]
Fixed.
