### ISSUE TITLE
black and white 2 show black textures

### ISSUE THREAD

**Issue by mrdeathjr28** [Joshua-Ashton/d9vk#296]
black and white 2 show black textures

![baw2](https://user-images.githubusercontent.com/6601480/62805088-93ea5b80-bab4-11e9-937e-b61e200c4e55.png)

PC Demo

https://www.gamepressure.com/download.asp?ID=11208

Nvidia Drivers 418.52.18 (run package)

Xubuntu 18.04 x64 - Kernel 4.17.12 generic (ubuntu mainline) -

CPUFreq: Performance

CPU: Core i3 8350K Tri-Core (Coffelake 14nm) 5.0Ghz + Zalman CNPS 10x Performa+

MEMORY: 8GB DDR4 2400mhz (4x2) Mushkin (dual channel: 37.5 gb/s)

GPU: Gigabyte Nvidia Geforce GTX 1050 OC (GP107 14nm: 640 Shaders / 40 TMUS / 32 ROPS) Windforce 2GB DDR5 7000Mhz 128Bit (110Gb/s)

MAINBOARD: ASUS Z370-P

**Comment by CartoonFan** [comment]
All right, here you go:

d3d9.log:
[BW2Demo_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3489372/BW2Demo_d3d9.log)

Windows apitrace:
https://drive.google.com/file/d/1qwgeKRZrcJRUsSjdF8JkZsrTWCnLDXpU/view?usp=sharing

Hope this helps.

**Comment by Joshua-Ashton** [comment]
Fixed by https://github.com/Joshua-Ashton/d9vk/commit/4866e321f168acf0147fee52ed7adc9cd8e72598

**Comment by mrdeathjr28** [comment]
thanks black and white 2 rendering problem are fixed in last frog build

![bw2](https://user-images.githubusercontent.com/6601480/64558522-a3ee9880-d309-11e9-89e1-b31851a6e158.png)
