### ISSUE TITLE
MSAA causes much higher performance hit with D9VK

### ISSUE THREAD

**Issue by ThisNameIsntTaken** [Joshua-Ashton/d9vk#299]
The performance hit for activating MSAA in pretty much any game appears to be much higher with D9VK compared to native D3D9. The testing was done on Windows, but the same performance hit is observable on Linux as well.

<details>
	<summary>A couple games with MSAA off vs. on</summary>

## Call of Duty 4 - No AA:

| Resolution                                       | D3D9              | D9VK              |
|--------------------------------------------------|-------------------|-------------------|
| 2560x1080                                        | 91 fps (16% GPU)  | 91 fps (21% GPU)  |
| 5120x2160                                        | 91 fps (52% GPU)  | 91 fps (63% GPU)  |

## Call of Duty 4 - 4xAA:

| Resolution                                       | D3D9              | D9VK              |
|--------------------------------------------------|-------------------|-------------------|
| 2560x1080                                        | 91 fps (20% GPU)  | 91 fps (34% GPU)  |
| 5120x2160                                        | 91 fps (67% GPU)  | 87 fps (99% GPU)  |

## Half-Life 2 - No AA:

| Resolution                                       | D3D9              | D9VK              |
|--------------------------------------------------|-------------------|-------------------|
| 2560x1080                                        | 285 fps (26% GPU) | 285 fps (28% GPU) |
| 5120x2160                                        | 285 fps (43% GPU) | 285 fps (55% GPU) |

## Half-Life 2 - 8xMSAA:

| Resolution                                       | D3D9              | D9VK              |
|--------------------------------------------------|-------------------|-------------------|
| 2560x1080                                        | 285 fps (34% GPU) | 285 fps (90% GPU) |
| 5120x2160                                        | 285 fps (90% GPU) | 103 fps (99% GPU) |

## Need for Speed: Most Wanted (2005) - No AA:

| Resolution                                       | D3D9              | D9VK              |
|--------------------------------------------------|-------------------|-------------------|
| 2560x1080                                        | 87 fps (26% GPU)  | 90 fps (25% GPU)  |
| 5120x2160                                        | 87 fps (53% GPU)  | 90 fps (56% GPU)  |

## Need for Speed: Most Wanted (2005) - Max AA:

| Resolution                                       | D3D9              | D9VK              |
|--------------------------------------------------|-------------------|-------------------|
| 2560x1080                                        | 87 fps (36% GPU)  | 90 fps (55% GPU)  |
| 5120x2160                                        | 87 fps (92% GPU)  | 53 fps (99% GPU)  |

## Need for Speed: Underground 2 - No AA:

| Resolution                                       | D3D9              | D9VK              |
|--------------------------------------------------|-------------------|-------------------|
| 2560x1080                                        | 120 fps (30% GPU) | 120 fps (28% GPU) |
| 5120x2160                                        | 120 fps (75% GPU) | 120 fps (75% GPU) |

## Need for Speed: Underground 2 - Max AA:

| Resolution                                       | D3D9              | D9VK              |
|--------------------------------------------------|-------------------|-------------------|
| 2560x1080                                        | 120 fps (50% GPU) | 120 fps (69% GPU) |
| 5120x2160                                        | 85 fps (99% GPU)  | 54 fps (99% GPU)  |

## Vindictus - No AA:

| Resolution                                       | D3D9              | D9VK              |
|--------------------------------------------------|-------------------|-------------------|
| 2560x1080                                        | 60 fps (35% GPU)  | 60 fps (33% GPU)  |
| 5120x2160                                        | 60 fps (70% GPU)  | 60 fps (75% GPU)  |

## Vindictus - 4xMSAA:

| Resolution                                       | D3D9              | D9VK              |
|--------------------------------------------------|-------------------|-------------------|
| 2560x1080                                        | 60 fps (42% GPU)  | 60 fps (51% GPU)  |
| 5120x2160                                        | 56 fps (99% GPU)  | 37 fps (99% GPU)  |
</details>

### Software information
Any game with MSAA

### System information
- GPU: RX 580 4GB
- Driver: Radeon Software 19.7.5. on Windows, Mesa ACO Git on Linux
- D9VK version: 9e10bca

### Apitrace file(s)
- [hl2.7z](https://mega.nz/#!dfoG1ICb!zkscdHGVFWRbaaIhS0IjTAj_3YfpHlJ781RURpQs2no)
Probably won't be useful, I was just deactivating and reactivating MSAA in the menu.

### Log files
- [hl2_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3489915/hl2_d3d9.log)

**Comment by aufkrawall** [comment]
I can confirm this in Counter-Strike: Source:
no MSAA: 716fps (I unlocked the framerate)
8xMSAA: 192fps

Quite an extreme hit for MSAA in an old forward renderer. This is with RX 570 on RADV ACO.

**Comment by ryao** [comment]
This issue also affects DXVK. Nobody knows why it happens or how to fix it.

**Comment by aufkrawall** [comment]
> This issue also affects DXVK. Nobody knows why it happens or how to fix it.

I can't confirm this with Crysis 1. I set "high" quality config to equal "very high" so that more effects can be used with D3D9 vs. 10. Performance hit with no MSAA vs. 4xMSAA:
DXVK: 74fps -> 59fps
D9VK: 66fps -> 44fps

**Comment by Joshua-Ashton** [comment]
I can't replicate this on AMDVLK on Windows. I am able to hit 300fps (the cap, consistently) at 4K with 8x MSAA on Portal 2 with my Vega 56.

**Comment by ryao** [comment]
People reporting this problem appear to all be on Polaris. It might be a driver issue that only affects Polaris.

**Comment by ghost-420** [comment]
> I can't replicate this on AMDVLK on Windows. I am able to hit 300fps (the cap, consistently) at 4K with 8x MSAA on Portal 2 at the start of sp_a1_intro2 with my Vega 56.
> 
> Which is better than native, which only gets around 260-270.

fps_max 0 to uncap.

**Comment by Joshua-Ashton** [comment]
I know 🐸 I wasn't testing anything though, I was just playing Portal 2 :b

**Comment by Joshua-Ashton** [comment]
There's basically nothing I can do about this. Sorry.

Vulkan sample counts are Vulkan sample counts, and there isn't really anything I can change -- especially if I can't repro the behaviour myself.

**Comment by Joshua-Ashton** [comment]
There is a renderstate to disable antialiasing (ie. render non-msaa to an msaa rt) but we can't implement that, and even if we had an extension there are certain limitations that games don't respect that make it unviable. (ie. sample count of depth stencil, depth write quirks wrt this on certain hw)
