### ISSUE TITLE
Compilation fault with multiple errors.

### ISSUE THREAD

**Issue by Kerrung** [Joshua-Ashton/d9vk#3]
### System information
- OS: Arch Linux
- D9VK version: 246c6cd

### Log files
[d9vk-build-log.txt](https://github.com/Joshua-Ashton/d9vk/files/2922000/d9vk-build-log.txt)

**Comment by Joshua-Ashton** [comment]
Yes, I'll get around to it.

Haven't looked into compiling on Linux yet.

**Comment by Joshua-Ashton** [comment]
For reference, this issue is fixed now.

**Comment by Kerrung** [comment]
Thank you!
