### ISSUE TITLE
Nicewrench graphics glitches

### ISSUE THREAD

**Issue by rohit-n** [Joshua-Ashton/d9vk#30]
### Software information
Nicewrench (available [here](http://number-none.com/blow/prototypes/nicewrench/nicewrench.zip))

### System information
- GPU: GeForce GT 730
- Driver: 397.93.0
- Wine version: None (Windows 10)
- DXVK version: 526cb1717cca16da1a8e2b32dbc45e8c9ba8dbe4

### Apitrace file(s)
- https://drive.google.com/open?id=1kydekCILk5glThgDDv-zOTwNwYDZ8qo0

### Log files
[d3dretrace_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3091439/d3dretrace_d3d9.log)

**Comment by rohit-n** [comment]
The graphical glitches no longer appear in current builds, so I'm closing this.

**Comment by Joshua-Ashton** [comment]
nice
