### ISSUE TITLE
infernal show in black various objects

### ISSUE THREAD

**Issue by mrdeathjr28** [Joshua-Ashton/d9vk#300]
infernal show in black various objects

![infg](https://user-images.githubusercontent.com/6601480/62896336-7ae0e500-bd16-11e9-9124-d9f40caa348b.png)

PC Demo

https://www.gamepressure.com/download.asp?ID=14438

Nvidia Drivers 418.52.18 (run package)

Xubuntu 18.04 x64 - Kernel 4.17.12 generic (ubuntu mainline) -

CPUFreq: Performance

CPU: Core i3 8350K Tri-Core (Coffelake 14nm) 5.0Ghz + Zalman CNPS 10x Performa+

MEMORY: 8GB DDR4 2400mhz (4x2) Mushkin (dual channel: 37.5 gb/s)

GPU: Gigabyte Nvidia Geforce GTX 1050 OC (GP107 14nm: 640 Shaders / 40 TMUS / 32 ROPS) Windforce 2GB DDR5 7000Mhz 128Bit (110Gb/s)

MAINBOARD: ASUS Z370-P

**Comment by mrdeathjr28** [comment]
infernal trace

https://mega.nz/#!6V0nyQBY!Nix4naeBR4TduU97cFBJYBee7Lna_h8VpwRoqM3vZYE

**Comment by CartoonFan** [comment]
Did you get a d3d9 log when you ran the program?

**Comment by Joshua-Ashton** [comment]
Can you try ``d3d9.allowLockFlagReadonly = False``

**Comment by mrdeathjr28** [comment]
issue still present

**Comment by SDN-Arkhen** [comment]
Here's a debug log for the demo version of this game. That black textures are also appear in the demo with the latest master. Unimplemented features?
[game_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3721184/game_d3d9.log)

**Comment by NerosTie** [comment]
The apitrace is not available anymore. 

I installed the demo but it crashes on launch (not related to DXVK I think), maybe there is a solution with winetricks but I didn't find it.

@mrdeathjr28 can you retest?

**Comment by mrdeathjr28** [comment]
i remove various traces because dont have any activity

@NerosTie 

wait a sec......

**Comment by mrdeathjr28** [comment]
issue fixed

![infj](https://user-images.githubusercontent.com/6601480/94464405-0bc98880-0184-11eb-9128-44624f85a26e.jpg)

thanks josh
