### ISSUE TITLE
Half Life 2 mod Neotokyo crashes after map load

### ISSUE THREAD

**Issue by glubsy** [Joshua-Ashton/d9vk#301]
This will probably be noise since the game is very obscure and abandoned, but hopefully will be useful somehow.

Neotokyo runs fine on some maps, but other maps crash the game as reported [here](https://github.com/ValveSoftware/Proton/issues/2447#issuecomment-520656354). The game crashes during map load. 

I'm using Valve's Proton 4.11, with `PROTON_USE_D9VK=1`. Without it the game runs fine, albeit not as good as D9VK, and with some minor graphical glitches (as mentioned in the topic above) most likely due to something related to [this](https://github.com/ValveSoftware/dxvk/blob/0b21ef187aa50d97e1f0fa4f02fc47d0a63c5c5f/dxvk.conf#L29) although disabling this workaround doesn't change anything in wineD3D anyway (the "fog" glitch).

Haven't tested with latest commits in master.

> Before the next step, make sure you disable or get rid of D9VK files first, as it's preferred that you use WineD3D to make an apitrace.

The game doesn't crash with WineD3D, only with D9VK. I can't generate an apitrace by using Valve's Proton 4.11 with launch parameter `PROTON_USE_WINED3D=1`, because the game wouldn't crash. 

The apitrace below has been generated with D9VK active in Proton 4.11, so it's probably useless? Sorry about that.

### Software information
Game: hl2.exe NeotokyoSource mod
Settings: launch option in Steam client: `PROTON_LOG=1 PROTON_USE_D9VK=1 %command% -console +voice_loopback 1 -nojoy`

### [System information](https://gist.github.com/glubsy/8930de18e83adb497905097091e9789c/0fb5fbe55a58ec582be86dccd0251dce5be8b956)
- GPU: GTX 670MX
- Driver: nvidia 430.40
- Wine version: 4.11 ?
- DXVK version:  0b21ef187aa50d97e1f0fa4f02fc47d0a63c5c5f dxvk (v1.3.2-4-g0b21ef18) ?
- D9VK version:  1c5ce36e36d87a7160b47675153406bbe68f02f3 d9vk (v0.90-1653-g1c5ce36e) ?
- Proton: 1565123138 proton-4.11-2

### Apitrace file(s)
- ~~[hl2.trace.tar.xz](https://mega.nz/#!ZrRBhayS!zzmhuTsFtCW9cTXNqTCfujj1n4DOuNX0Ifo44dGOuUY)~~ See below for a trace without d9vk. 

### Log files
- [hl2_d3d9.log](https://gist.github.com/glubsy/3e71c053a006078f0e273290d947e652)
- d3d11.log: none
- [hl2_dxgi.log](https://gist.github.com/glubsy/3e71c053a006078f0e273290d947e652)

**Comment by glubsy** [comment]
Here an apitrace of hl2.exe crashing consistently after loading a map (nt_redlight_ctg) with  `PROTON_USE_WINED3D=1`. [link](https://mega.nz/#!A3gSwCya!Oe_BVQFvB1smgYWK7u2QYcv832_qQ25Lfl7md_aTfaw)

**Comment by glubsy** [comment]
The game crashes when graphics settings in game are the default ones. This might be an issue on Windows too, so you should probably disregard that one.

Here is another trace where graphics settings are set to lower texture quality.

Model detail: from High -> Medium
Texture details: from High -> Medium
Shader detail: from High -> Low
Water detail: from Reflect World -> Simple Reflections

Apparently, setting Texture Detail to high is what crashes consistently, even on Windows. So this is most likely not related to d9vk nor Wine at all. 

In that trace, I immediately went back to the main menu after loading and rendering the map correctly, then exited the game. The game did not crash [link](https://mega.nz/#!VqQlTS6S!HvXPHgNe9YW1D1IyQQQ524fB-jGW6TGYjvoeYT8nBy0)

**Comment by Joshua-Ashton** [comment]
Thanks for the clear report, I will look into this.

Source games are always fairly straight forward to debug.

**Comment by Joshua-Ashton** [comment]
I wasn't able to replicate this in the game myself.
Possibly a Wine bug?

![image](https://user-images.githubusercontent.com/21316711/63021365-54e34e00-be98-11e9-8aca-0e275980c451.png)

**Comment by glubsy** [comment]
Thanks for having looked into this. 

I had not thought it would be related to WINE since the game only crashes with d9vk and not wined3d. Or perhaps it's an issue with Vulkan and the GPU driver? Although that sounds unlikely because an AMD GPU user is experiencing the same type of crash with d9vk (Linux also). 

Would you recommend a way to investigate this further? 
I suppose I'll have to report to the WINE project eventually but I'm not really sure what to report.

Also not really sure that the `DxvkMemoryAllocator` error is really what crashes the game, considering there is no report of any exception thrown (see this [dxvk issue](https://github.com/doitsujin/dxvk/issues/747) for example). Maybe I should report to DXVK?

**Comment by glubsy** [comment]
I've managed to work around the crash by adding the launch parameter `PROTON_FORCE_LARGE_ADDRESS_AWARE=1` which "Forces Wine to enable the LARGE_ADDRESS_AWARE flag for all executables." according to the [documentation](https://github.com/ValveSoftware/Proton/blob/proton_4.11/README.md).

However, the game is a hitching a lot in some areas (mostly the main street in nt_redlight_ctg), and I got this repeated error "Too many vertex format changes in frame, whole world not rendered" in the hl2 console. Not sure if it's related.

**Comment by Joshua-Ashton** [comment]
I've experienced `Too many vertex format changes in frame, whole world not rendered` in Source when developing Blade Symphony. Pretty sure D9VK can't cause that.

**Comment by glubsy** [comment]
You're right, I got a bit carried away. this is definitely not related to the renderer. Edited the post to redact that.

Didn't realize you were part of the Blade Symphony team, congrats on releasing such a nice game. Impressive work. I like Puny Human's games. :)

**Comment by Joshua-Ashton** [comment]
I wasn't part of the team when it started -- I just did the Winter [2017? maybe? or maybe it was 2018] and Harmonious Prelude update.

**Comment by glubsy** [comment]
With Proton 4.11-3, the infamous [fog glitch](https://github.com/ValveSoftware/Proton/issues/2447#issuecomment-485277660) (which also happens with regular wined3d) has suddenly appeared in D9VK! I thought we would be safe, but no.

![d9vk now produces the fog glitch with Proton 4.11-3!](https://i.imgur.com/SgA85sm.png)

with fog_override = 1 (and sv_cheats 1), we get the preferred rendering:
![fog_override = 1 with d9vk / proton 4.11-3](https://i.imgur.com/Cl6e41M.png)

The dxgi.nvapiHack = False in dxvk.conf doesn't fix it either. (the line `DXGI: NvAPI workaround enabled, reporting AMD GPU` is not printed to the dxgi log which confirms the config is applied)

However this is a cheat convar which means we can't use it in multiplayer servers. Since fog_override seems to render things correctly, I think we can rule out a faulty graphics driver.

[hl2_dxgi.log and hl2_d3d9.log](https://gist.github.com/glubsy/dc93f786dab9f7a749466461cb8ca58a)

Is there a way to look for that with apitrace?
Still not sure what part of the Source engine handles this fog shader thing. 
This happens in Windows too on some hardware (and drivers), both nVidia and AMD. Nobody could find what exactly is the root of the problem though. It happens consistently under Wine, although it didn't happen with the previous version of Proton and D9VK (that was d9vk-v0.90-1653-g1c5ce36e)

**Comment by Joshua-Ashton** [comment]
I'll take a look at what the game is doing tomorrow. Thanks for bringing this to my attention. Should be an ez fix given it's a Source game :)

**Comment by Joshua-Ashton** [comment]
![image](https://user-images.githubusercontent.com/21316711/65378087-c9858580-dcab-11e9-8458-9e24c84b5047.png)

Fog looks fine to me... Exactly the same as native.

**Comment by Joshua-Ashton** [comment]
Also the crash is not my bug, it happens on native d3d9 too.

**Comment by Joshua-Ashton** [comment]
Closing this as it isn't my bug.
