### ISSUE TITLE
Guild Wars 2 - High Frametimes on FoV autozoom 

### ISSUE THREAD

**Issue by SpatiumPrinceps** [Joshua-Ashton/d9vk#302]
Hello,

in guild wars 2 there are fights, where the camera zooms automatically out. Whenever this happens, there is a massive spike in frametimes. The spike lasts for exactly 40 seconds, gpu usage drops to 50-70%. 
An example can be watched here: https://youtu.be/uaeUKPnBXiM

How to reproduce:  
Enter fractals of the mists on level 99 in challenge mote. As soon as you move your character within the boundaries of the first line (I was pointing out the trigger with my mouse in the video) the spike starts.  

### Software information
Guild Wars 2 
No matter what settings were used, this issue was reproducible. 
This issue was reproduced on multiple wine versions (4.13, 4.12, 4.11, 4.10), on multiple driver versions (430.40, 418.52.20), multiple d9vk versions (.13f, build 709) and on wined3d9. 

### System information
- GPU: GTX 1060
- Driver: 418.52.20
- Wine version: Lutris 4.13
- DXVK version: build 709

### Apitrace file(s)
I was unable to trace with wined3d9 because of this crash on startup
`
apitrace: warning: caught exception 0xc0000005  
apitrace: flushing trace
`
Here is a trace with d9vk. The last 15 seconds are relevant. 
https://mega.nz/#!dLw1jaCa!-c7KSvQHUrRer3-_uDpH6-iDp8e5KKjvg5tFiX4iol8

**Comment by Joshua-Ashton** [comment]
Log of an instance when it happened?

**Comment by SpatiumPrinceps** [comment]
Sorry for wasting your time by not providing a log right away. 
This log was taken with zen kernel, 430.40 driver, lutris-4.13 and d9vk build 709
"debug" log level.
https://mega.nz/#!cDBgmCSL!vaRPuiiqQ2aJb57vnDKm6F_CvK4P5GF2CPQ7U3AsTNk

**Comment by SpatiumPrinceps** [comment]
I spent a couple more hours on this issue testing out on more systems and talked to friends. This issue is also on windows without d9vk or any other wrapper present. Therefore it is not an issue in wine or d9vk, but once again arena nets vault. 

I redirected this to arena net, but I highly doubt they will fix it. 
Thanks for your service joshua.
