### ISSUE TITLE
Vindictus - Ice looks darker than native

### ISSUE THREAD

**Issue by NorbertHarangozo** [Joshua-Ashton/d9vk#303]
The ice appears to be darker than it should be. The screenshots were taken on Windows, because the game doesn't run with Proton/Wine due to anticheat issues. Replaying the apitrace on Linux shows the same problem.

How it looks like:
![Vindictus_D9VK](https://user-images.githubusercontent.com/44706448/63195338-9fb8bd80-c072-11e9-88d0-9e59996d1e3a.jpg)

How it should look like:
![Vindictus_D3D9](https://user-images.githubusercontent.com/44706448/63195323-992a4600-c072-11e9-9186-0124e010fb0f.jpg)

### Software information
Vindictus

### System information
- GPU: RX 580 4GB
- Driver: Radeon Software 19.8.1. on Windows, RADV ACO on Linux
- D9VK version: da8c837

### Apitrace file(s)
- [Vindictus.7z](https://mega.nz/file/M8YBmYRT#QH5c_at0r0_SK1C4gjq0sCUVI1yhqltILWENQOVJDvo)

### Log files
- [Vindictus_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3511025/Vindictus_d3d9.log)

**Comment by misyltoad** [comment]
This appears to render fine now on the trace.

Please re-open if you still have issues :)

**Comment by NorbertHarangozo** [comment]
I've tried DXVK master. The fog is no longer missing, but the ice still looks like the same as it did before.

Ingame on Windows (with DXVK):
![ingame](https://user-images.githubusercontent.com/44706448/74691264-5d6b6700-51e2-11ea-86e0-05115752cc9b.jpg)

Replaying the trace on Linux:
![trace](https://user-images.githubusercontent.com/44706448/74691282-69efbf80-51e2-11ea-8a26-6a7a2c03c4fb.png)

As a reminder, this is how it looks like on native:
![](https://user-images.githubusercontent.com/44706448/63195323-992a4600-c072-11e9-9186-0124e010fb0f.jpg)

**Comment by NorbertHarangozo** [comment]
@Joshua-Ashton Just in case you aren't aware, this issue is still present. I can't re-open the issue, because it was closed by you.

**Comment by misyltoad** [comment]
The ice renders fine in the trace for me :-/

Not too sure what the issue is there, does it render fine when you play back the trace too?

**Comment by NorbertHarangozo** [comment]
Nope, it doesnt, it looks like this:
![Screenshot_20200320_155147](https://user-images.githubusercontent.com/44706448/77175394-e0722c80-6ac2-11ea-8ecf-c221d2f5bea0.png)
Not sure how to describe it. If you compare the last two screenshots from my [Feb 18 comment](https://github.com/Joshua-Ashton/d9vk/issues/303#issuecomment-587186551), it doesn't quite look the same as native, which looks like a brighter shade of blue.

I've also tried replaying the trace on Windows as well, looks fine on native, but it looks incorrect when I use DXVK.

**Comment by NorbertHarangozo** [comment]
Using the option `d3d9.forceSamplerTypeSpecConstants = True` seems to improve the situation.

Native:
![native](https://user-images.githubusercontent.com/44706448/83057695-9162ed80-a057-11ea-9932-b82c4dd137d1.png)
DXVK with `d3d9.forceSamplerTypeSpecConstants = True`:
![dxvk](https://user-images.githubusercontent.com/44706448/83057759-a3449080-a057-11ea-8fd8-16080871a5f3.png)

**Comment by Bartholomew00** [comment]
This game is great. I have a [Vindictus accounts](https://mmoauctions.com/vindictus/accounts) and I play this game a lot. In my opinion, she is great.

**Comment by NerosTie** [comment]
The apitrace is not available anymore.

**Comment by NorbertHarangozo** [comment]
Thanks for noticing. I've reuploaded it: [Vindictus.7z](https://mega.nz/file/NJ1DkazC#W5OIBREG5txgG2l6Ujq8XaJ9ct4X1cVdsbVvZIR52Ok)

**Comment by NerosTie** [comment]
Thanks. It looks like it's still darker.

**Comment by NorbertHarangozo** [comment]
This is now being tracked at doitsujin/dxvk#2715.
