### ISSUE TITLE
A Hat in Time: D3D9DeviceEx::SetRenderState: Unhandled render state warnings

### ISSUE THREAD

**Issue by ryao** [Joshua-Ashton/d9vk#304]
[HatinTimeGame_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3511409/HatinTimeGame_d3d9.log)

After doing a quick test of A Hat in Time on D9VK 0.13f on Windows 7, I saw some warnings about unhandled render states in the log. According to log and the documentation, the following render states are unimplemented:

- D3DRS_SHADEMODE (9)
- D3DRS_LASTPIXEL (16)
- D3DRS_FOGEND (37)
- D3DRS_FOGDENSITY (38)
- D3DRS_CLIPPING (136)
- D3DRS_LOCALVIEWER (142)
- D3DRS_POINTSIZE (154)
- D3DRS_POINTSIZE_MIN (155)
- D3DRS_POINTSCALE_A (158)
- D3DRS_MULTISAMPLEANTIALIAS (161)
- D3DRS_POINTSIZE_MAX (166)
- D3DRS_POSITIONDEGREE (172)
- D3DRS_NORMALDEGREE (173)
- D3DRS_MINTESSELLATIONLEVEL (178)
- D3DRS_MAXTESSELLATIONLEVEL (179)
- D3DRS_ADAPTIVETESS_Y (181)
- D3DRS_ADAPTIVETESS_Z (182)

https://docs.microsoft.com/en-us/windows/win32/direct3d9/d3drenderstatetype

All of these are listed as being unimplemented in the current master:

https://github.com/Joshua-Ashton/d9vk/blob/605296b4670340ebf08ff7f81ac3968e8164f00a/src/d3d9/d3d9_device.cpp#L3289

I did not see any effect on graphical quality, but I thought that the information that there is software using these features might be useful.

**Comment by K0bin** [comment]
Please run the game again with the latest master.
When the game calls ResetEx to reset all device state, D9VK used to call SetRenderState which would print those log lines. So it looks like all of those are actually caused by D9VK itself.
It no longer does that but those changes aren't in any release yet.

**Comment by ryao** [comment]
[HatinTimeGame_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3511538/HatinTimeGame_d3d9.log)

@K0bin That fixed most of the warnings, except for one:

```
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_ADAPTIVETESS_Y
```

Performance is the same as 0.13f.

By the way, I tried building in cygwin to save time. For anyone who want to do the same, install the Vulkan SDK and run these commands to build d9vk:

```
# Workaround broken vulkan-1.dll test that doesn't allow `-L  /cygdrive/c/Windows/System32/` to be passed.
ln -s /cygdrive/c/Windows/System32/vulkan-1.dll /usr/lib/gcc/x86_64-w64-mingw32/7.4.0/

# Fetch repository
git clone https://github.com/Joshua-Ashton/d9vk.git

cd d9vk
env PATH="$PATH:/cygdrive/c/VulkanSDK/1.1.114.0/Bin" meson --native-file build-win64.txt --buildtype release --prefix /tmp/d9vk build.w64
cd build.w64
ninja -v install
```

Do the following to make A Hat in Time use it:

```
# Workaround not knowing the equivalent of LD_LIBRARY_PATH on Windows; also, I have no idea why the mingw64 toolchain is dynamically linking stdc++ when it was told to make it static.
 cp /usr/x86_64-w64-mingw32/sys-root/mingw/bin/{libstdc++-6.dll,libwinpthread-1.dll,libgcc_s_seh-1.dll} /tmp/d9vk/bin/d3d9.dll /cygdrive/c/Program\ Files\ \(x86\)/Steam/steamapps/common/HatinTime/Binaries/Win64/
cd  /cygdrive/c/Program\ Files\ \(x86\)/Steam/steamapps/common/HatinTime/Binaries/Win64
./HatinTimeGame
```

Some paths might need to be adjusted for versions. You will need to remove libstdc++-6.dll, libwinpthread-1.dll, libgcc_s_seh-1.dll, d3d9.dll, HatinTimeGame_d3d9.log and HatinTimeGame.dxvk-cache from the directory to undo that afterward.

**Comment by K0bin** [comment]
Looks like it's using a driver hack. I'll look into this tomorrow.

I'm just going to keep using MSVC, that works fine for me.

**Comment by ryao** [comment]
@K0bin I wanted to use MSVC, but declined to do so after reading the license terms. In specific, term 5a:

```
Data Collection. The software may collect information about you and your use of the software, and send that to Microsoft. Microsoft may use this information to provide services and improve our products and services. You may opt-out of many of these scenarios, but not all, as described in the software documentation. There are also some features in the software that may enable you and Microsoft to collect data from users of your applications. If you use these features, you must comply with applicable law, including providing appropriate notices to users of your applications together with Microsoft’s privacy statement. Our privacy statement is located at https://go.microsoft.com/fwlink/?LinkID=824704. You can learn more about data collection and its use from the software documentation and our privacy statement. Your use of the software operates as your consent to these practices.
```

https://visualstudio.microsoft.com/license-terms/mlt031819/

That was unacceptable to me, so I went with Cygwin. It would have been faster had I rebooted to Gentoo Linux and built a toolchain there, but I figured that I would work out how to use Cygwin to avoid the need to go back and forth in the future.

**Comment by K0bin** [comment]
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_ADAPTIVETESS_Y Value 1297108803

The matching FourCC to 1297108803 is `C0PM` and there is absolutely no documentation about that.

**Comment by ryao** [comment]
@Joshua-Ashton Could we get an undocumented label to help track things that need documentation?

**Comment by Joshua-Ashton** [comment]
We have that in master.

**Comment by K0bin** [comment]
I think he means a label on GitHub for the issue.

As I said this is a non-issue and Hat in Time probably just passes bullshit.

**Comment by ryao** [comment]
@Joshua-Ashton It would be nice if we understood what it intended to do here. Maybe we could ask the game developer what they expected direct3d to do. Anyway, a label to mark this issue would be nice until we know unless you want to go with wontfix and close this. It is your call.

**Comment by Joshua-Ashton** [comment]
You want to know what COPM means? I can find out though, if anything. Out ATM.

**Comment by K0bin** [comment]
C0PM (zero instead of O)

**Comment by ryao** [comment]
Unexplained warnings could point to underlying issues, so it is a possible loose end. It would be nice if we knew what it meant.

I understood the other warnings about format changes to adapt to vulkan driver limitations were harmless, but I have no clue about this one.

**Comment by K0bin** [comment]
UE3 sets COPM when the config option `EnableMinimalNVIDIADriverShaderOptimization` is activated.

We've decided to just silence the warning because there's no documentation on it and we're outperforming Windows D3D9 drivers anyway.

**Comment by ryao** [comment]
Nice find. Here is a link to the relevant patch:

https://github.com/Joshua-Ashton/d9vk/commit/8132809401acca8d4372324ae80e6ed80c704c31

I am closing this as it is fixed.
