### ISSUE TITLE
Grim Dawn can't get past menu

### ISSUE THREAD

**Issue by ghost** [Joshua-Ashton/d9vk#308]
Grim Dawn menu renders incorrectly, unable to move mouse from center screen, seems to be being grabbed. When using D3D9, the game only launches and gets to the menu specifically with x64 D9VK. x86 D9VK and x86/x64 WineD3D get stuck on a black screen when launching and generate 1kb traces.  
  

D3D9 screenshot: https://github.com/casualRR/d9vk-trace/raw/master/d3d9.jpg  
D3D11 screenshot: https://github.com/casualRR/d9vk-trace/raw/master/d3dx.jpg
 
### Software information
Grim Dawn, running with Steam launch options: PROTON_USE_D9VK=1 D9VK_HUD=1 %command% /d3d9 /x64

### System information
- GPU: Intel HD 520
- Driver: Mesa 19.1.4-1
- Wine version: Proton 4.11-2
- DXVK version: D9VK v.013f

### Apitrace file(s)
WineD3D9 black screen launch generated a 1Kb useless trace, so here's a D9VK one in lieu of nothing: https://github.com/casualRR/d9vk-trace/raw/master/gd_trace.7z

### Log files
[steam-219990.log](https://github.com/Joshua-Ashton/d9vk/files/3528701/steam-219990.log)

**Comment by LeJimster** [comment]
Experiencing the same issue when I launch in d3d9 mode, it seems like you can move the mouse freely for a second when the game is loading into the menus and then its locked in place, if you try to move the mouse you see it flickering around where it's locked.
DXVK works perfectly with dx11 on this game.

@casualRR fyi it's DXVK_HUD for the stats ;-)

If needed I can always boot into windows and try creating a trace from there.  Let me know.

### System information
- GPU: RX Vega 56
- Driver: Mesa 19.2.0-dev (ACO/LLVM 8.0.1)
- Wine version: Proton 4.11-2
- DXVK version: D9VK v.013f

### Log files
[grimdawn-32bit-steam-219990.log](https://github.com/Joshua-Ashton/d9vk/files/3513143/grimdawn-32bit-steam-219990.log)
[grimdawn-64bit-steam-219990.log](https://github.com/Joshua-Ashton/d9vk/files/3513144/grimdawn-64bit-steam-219990.log)
[Grim Dawn_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3513145/Grim.Dawn_d3d9.log)
[Grim Dawn_d3d11.log](https://github.com/Joshua-Ashton/d9vk/files/3513146/Grim.Dawn_d3d11.log)
[Grim Dawn_dxgi.log](https://github.com/Joshua-Ashton/d9vk/files/3513148/Grim.Dawn_dxgi.log)

**Comment by casualRR** [comment]
@LeJimster I just uninstalled Forgotten Gods to see if it made a difference - no dice, same problem.  
I also tried running at more normal resolution (was at 1080x720, catering to my 3:2 aspected laptop). The issue persisted at 1280x720. I might try the dev branch of Mesa too.

**Comment by LeJimster** [comment]
I just tried Proton 4.11-3 with Grim Dawn and the mouse works fine now, I don't notice any other bugs like you are experiencing, seems like they're Intel specific?

**Comment by NerosTie** [comment]
Tested with DXVK 1352 + Proton 5.0-9. Everything is ok.

@Joshua-Ashton I think you can safely close this issue. (the apitrace is not even available anymore)
