### ISSUE TITLE
Witcher 2 Glitches

### ISSUE THREAD

**Issue by lemonzest79** [Joshua-Ashton/d9vk#309]
Witcher 2 Glitches

Mens heads are flickering in this capture, and also getting the odd lag spike and other visual glitches

![Screenshot from 2019-08-18 16-59-37](https://user-images.githubusercontent.com/40669977/63227073-8a5ea300-c1da-11e9-8a95-64b8dce9af40.png)

The Witcher 2 GOG Edition

### Software information

Running Wine Staging 4.14 on Fedora 30 x86_64, installed d9vk_master from winetricks version 8113e4c on a fresh 32bit prefix

### System information

- GPU: MSI Radeon RX 580 8GB
- Driver: Mesa 19.1.4
- Wine version: Staging 4.14
- DXVK version: master da8c837

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log: [witcher2_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3513241/witcher2_d3d9.log)

- d3d11.log:
- dxgi.log:

**Comment by K0bin** [comment]
> Apitrace file(s)
    Put a link here

Please actually do that.

**Comment by lemonzest79** [comment]
https://1drv.ms/u/s!AgH-T_tmw6C20iG2MwJYgjkiicG-?e=txeIKN

Apitrace, had to use d9vk as WineD3D just sat on a black screen for 5 mins doing nothing.

**Comment by K0bin** [comment]
That's probably fine in this case.

**Comment by K0bin** [comment]
https://i.imgur.com/QeGxdXz.jpg

This might be a driver bug. It looks fine on Nvidia with D9VK.

**Comment by lemonzest79** [comment]
Did you rotate the camera to look at the men pushing the wheel, their heads flicker/glitch.

**Comment by K0bin** [comment]
Yes.

Your trace is broken because the game does something very retarded that D9VK didn't handle properly.
I fixed that in #313 

Because of that I made a new apitrace with Windows D3D9. https://mega.nz/#!8bRmyYYJ!JXZtTAigaxFmghD8kCEIR5FfRk9LqHs9s00n7dt0WGY

**Comment by CME42** [comment]
The game is trying to access stuff outside of the UBO range of 256 in the vertex shader, so it's reading memory garbage which results into those flickering heads.

**Comment by K0bin** [comment]
Witcher 1 has the exact same problem (#15)

**Comment by Zeioth** [comment]
on d9vk-master + nvidia driver 435.19.02 I get to see the GUI but the game itself is a black screen. 

I also tried with d9vk 0.20, same result.
![w2](https://user-images.githubusercontent.com/3357792/64206884-c1e87300-ce9b-11e9-9e73-e3622b1dcaa0.png)

**Comment by Joshua-Ashton** [comment]
Should be fixed now.
