### ISSUE TITLE
Shadow Hardvest Ops shows flickering

### ISSUE THREAD

**Issue by mrdeathjr28** [Joshua-Ashton/d9vk#311]
Shadow Hardvest Ops shows flickering but with wined3d show black screen

![shops](https://user-images.githubusercontent.com/6601480/63230153-875db580-c1ce-11e9-9b31-7275e31578ce.png)

d9vk log:

https://mega.nz/#!PUsjTSqS!NOsvWpjSyu6wj0vYeEhRXH-pOtTPmiuZs75V3c4ShZ0

Trace:

https://mega.nz/#!Dc90FIqI!BTYNyP6sysgxZ1TRyoZ4VE3Tolm0-T1IfNvSlGfJ6ew

Nvidia Drivers 418.52.18 (run package)

Xubuntu 18.04 x64 - Kernel 4.17.12 generic (ubuntu mainline) -

CPUFreq: Performance

CPU: Core i3 8350K Tri-Core (Coffelake 14nm) 5.0Ghz + Zalman CNPS 10x Performa+

MEMORY: 8GB DDR4 2400mhz (4x2) Mushkin (dual channel: 37.5 gb/s)

GPU: Gigabyte Nvidia Geforce GTX 1050 OC (GP107 14nm: 640 Shaders / 40 TMUS / 32 ROPS) Windforce 2GB DDR5 7000Mhz 128Bit (110Gb/s)

MAINBOARD: ASUS Z370-P

**Comment by K0bin** [comment]
Screenshots are appreciated when making GitHub issues. Same for the logs.
That's a lot more useful than what CPU fan you use...

**Comment by mrdeathjr28** [comment]
@K0bin yeah maybe later but trace is more important for josh

**Comment by mrdeathjr28** [comment]
issue stay fixed with lastest frog build
