### ISSUE TITLE
Medal of honor crashes with both 0.13f and 0.20rc1 releases

### ISSUE THREAD

**Issue by oscarbg** [Joshua-Ashton/d9vk#315]
see screenshoot:
![image](https://user-images.githubusercontent.com/669305/63477554-e567f280-c485-11e9-8769-a1d813937905.png)

apart from screenshoot log shows:
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_ADAPTIVETESS_Y
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT

### Software information
Medal of Honor (2010)

### System information
- GPU: NV Titan V
- Driver: 436.02
- Wine version: none run from Windows 
### Log files
- d3d9.log: (from 0.20rc)
[moh_d3d9 - copia.log](https://github.com/Joshua-Ashton/d9vk/files/3527857/moh_d3d9.-.copia.log)

**Comment by oscarbg** [comment]
Ok sorry.. seems to be an issue running with MSI afterburner OSD enabled..
strange enough was testing earlier today "Medal of Honor Airborne" and D9VK + MSI Afterburner didn't have any issue working together.. may be something specific in this game..

**Comment by oscarbg** [comment]
guess no serious issue as people uses D9VK on Linux tough.. will close as soon as requested..

**Comment by Joshua-Ashton** [comment]
If this isn't my bug then I see no reason for this to stay open :b

**Comment by oscarbg** [comment]
yep.. 
at least a finding: this game "uses/needs" D3DRS_ADAPTIVETESS_Y.. 
warn: D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_ADAPTIVETESS_Y
