### ISSUE TITLE
Torchlight Texture bug

### ISSUE THREAD

**Issue by liberodark** [Joshua-Ashton/d9vk#316]
Hi,

Have try Torchlight with D9VK is work but have little graphique bug.

### Software information
Torchlight 1.15
Just run and play no have change any settings.

### System information
- GPU: GTX 2070
- Driver: 430.40
- Wine version: Proton 4.11
- DXVK version: 0.13f

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log: [Torchlight_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3527923/Torchlight_d3d9.log)

- d3d11.log:
- dxgi.log:

![image](https://user-images.githubusercontent.com/4238928/63478753-4d6d0780-c48b-11e9-8db0-b5f8be4b27c6.png)

**Comment by NerosTie** [comment]
https://github.com/Joshua-Ashton/d9vk/issues/207

**Comment by K0bin** [comment]
> Apitrace file(s)
> Put a link here

Please upload an apitrace of the issue.

**Comment by NerosTie** [comment]
Tested with #801 and every graphical issues are gone. Unfortunately I have a fps drop from ~100 to ~60 and a tearing issue, just like https://github.com/Joshua-Ashton/d9vk/issues/212#issuecomment-521748892

**Comment by liberodark** [comment]
how to make apitrace ?

**Comment by NerosTie** [comment]
https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace

But don't worry, it was my fault. The fps drop was because it was apitracing and the tearing issue comes from the Nvidia beta driver (vsync doesn't work with vulkan)

@Joshua-Ashton I think everything is fine for Torchlight now, you can close it.

**Comment by liberodark** [comment]
Fixed on 0.20 :D
