### ISSUE TITLE
Serious Sam II → the cutscenes are green and duplicated + black textures

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#317]
with d9vk:
![20190822200002_1](https://user-images.githubusercontent.com/4572452/63538182-a4b8b980-c517-11e9-991b-6f14251d1d80.jpg)

### System information
- GPU: Nvidia GT 730M
- Driver: 435.17
- Wine version: Proton 4.11
- DXVK version: #775

### Apitrace file(s)
https://mega.nz/#!v6oiDaZR!yFF_GXAQSWWOZg53vS-rI1b9nAdYZSgt_joP2JJTfjk

### Log files
[steam-204340.log](https://github.com/Joshua-Ashton/d9vk/files/3531369/steam-204340.log)

**Comment by Joshua-Ashton** [comment]
Nice, looks like when it can't make a YCbCr format, it just goes ahead and uploads that data to a regular texture 🤦‍♂

**Comment by NerosTie** [comment]
Well, there is an other issue:

![20190907205212_1](https://user-images.githubusercontent.com/4572452/64479045-92927880-d1b1-11e9-9396-e05a86a5d5d4.jpg)

Should I apritrace it?

**Comment by Joshua-Ashton** [comment]
Log? And sure

**Comment by NerosTie** [comment]
https://mega.nz/#!6qYkDSQD!JSnu83rF0s6J87crKgYEvsYJuZhAeFuuZ52WXCk6Elc


[steam-204340-d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3586975/steam-204340-d3d9.log)
[steam-204340-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3586976/steam-204340-d9vk.log)

**Comment by Joshua-Ashton** [comment]
Should fix the black textures.

**Comment by Joshua-Ashton** [comment]
The rest of this issue is superceded by #378

**Comment by Joshua-Ashton** [comment]
The video was fixed with https://github.com/Joshua-Ashton/d9vk/commit/878dbf355f9f5e749ba5673dd008c6879de2f425
