### ISSUE TITLE
Artificial Academy 2: Eyes glitch

### ISSUE THREAD

**Issue by geneishouko** [Joshua-Ashton/d9vk#322]
Some facial features like eye white and eye lids in Artificial Academy 2 get displaced and clip in full software vertex processing mode.

![image](https://user-images.githubusercontent.com/38262047/63642219-c766e180-c681-11e9-829d-e1f8feb52709.png)

### Software information
Game: Artificial Academy 2
Settings: Full Software Vertex Processing Mode

### System information
- GPU: Nvidia GTX 1050
- Driver: 430.34
- Wine version: 4.12.1
- DXVK version: git master (0f7f87a7)

### Apitrace file
- https://mega.nz/#!xB4WQKzR!eK-5OGRqCS_Hc0v2HoNmQQjfWUWyA_WVbomGi-u0--w

To properly replay the trace under wine without d9vk you may have to use a patched wined3d dll to place in your 32 bit system folder. You can find such dll here: https://github.com/aa2g/AA2Unlimited/releases/tag/v1.5.3

### Log files
- d3d9.log:
[AA2Edit_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3537547/AA2Edit_d3d9.log)

**Comment by Joshua-Ashton** [comment]
Can you try as of 4bad731f472ffffa685d412dfae73e906e97d5e5?

Should be fixed now: https://git.froggi.es/joshua/d9vk/-/jobs

**Comment by OrdinaryMagician** [comment]
Can confirm it's fixed with the latest release. No more melty eyes.
