### ISSUE TITLE
Borderlands 2 depth buffer only cleared for 1/6th of the screen

### ISSUE THREAD

**Issue by kiroma** [Joshua-Ashton/d9vk#323]
So I've tried but unfortunately I could not get an apitrace.
Only happens while in first person camera.
https://youtu.be/WlXlUcO9B_0

### Software information
Borderlands 2, independent of any settings.

### System information
- GPU: GTX950M
- Driver: 430.40
- Wine version: Proton 4.11.2
- D9VK version: 0.13f

**Comment by K0bin** [comment]
0.12 is pretty old. Does this happen with 0.13f and/or the latest master version?

**Comment by kiroma** [comment]
Ah, Proton ships with 0.13f, my bad.

**Comment by kiroma** [comment]
Just compiled master, seems it got fixed somewhere along the way.
