### ISSUE TITLE
Flickering in Sims 2 on Nvidia

### ISSUE THREAD

**Issue by tannisroot** [Joshua-Ashton/d9vk#324]
Sometimes, the characters in Sims 2 can start to flickering - parts of their bodies will start to disappear and reappear very quickly. So far it seems like this issue only affects Nvidia (RADV/AMDVLK aren't affected).
To illustrate:
![Peek 2019-08-21 22-21](https://user-images.githubusercontent.com/10602045/63644857-b5755500-c6fa-11e9-997c-1d7e28ae19c2.gif)

### System information
- GPU: NVIDIA GTX 1070
- Driver: 430.40
- Wine version: 4.14
- D9VK version: 13f5048c

### Game demo
To reliably reproduce the flickering issue, it's best to install and use this game demo:
https://drive.google.com/open?id=1ZxjlzJi8cbD_RWABnHayrPp5JLwDxQs0
then extract this file and copy `84799b7f_e70d5012.package` from it to `My Documents/EA Games/The Sims 2 Body Shop/SavedSims/`
[84799b7f_e70d5012.zip](https://github.com/Joshua-Ashton/d9vk/files/3539167/84799b7f_e70d5012.zip)
and then use this saved template to trigger the issue.

### Apitrace file(s)
Game demo crashes during tracing.

### Log files
- d3d9.log: [TS2BodyShop_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3537792/TS2BodyShop_d3d9.log)

**Comment by Joshua-Ashton** [comment]
Was able to repro on my RTX 2060 Super on 431.60

Took a bit of playing around (ie. randomizing characters/opening/closing menus) for it to happen.

**Comment by tannisroot** [comment]
Should be fixed now!
