### ISSUE TITLE
Black rectangles instead of shadows in Sims 2

### ISSUE THREAD

**Issue by tannisroot** [Joshua-Ashton/d9vk#325]
When set to High, the shadows under the sims become a black rectangle. 
Should be noted that this issue affects native d3d9 as well, but only on new drivers - at least for Nvidia, it doesn't happen on drivers that are older than 327 (like 320, for example).
Also, it can be easily workarounded with the use of a game mod. 
In case it might be needed, I extracted game's original material shader responsible for shadows:
[original.txt](https://github.com/Joshua-Ashton/d9vk/files/3537812/original.txt)
And in addition, same shader but modded to fix the issue:
[simShadowFix04.txt](https://github.com/Joshua-Ashton/d9vk/files/3537813/simShadowFix04.txt)
To illustrate:
![Screenshot from 2019-08-25 06-24-17](https://user-images.githubusercontent.com/10602045/63645200-84e4e980-c701-11e9-8a26-a1d43c534548.png)

### System information
- GPU: Nvidia GTX 1070
- Driver: 430.40
- Wine version: 4.14
- DXVK version: 13f5048c

### Apitrace file(s)
https://drive.google.com/open?id=1CmUlo3XG-34YTOK769rZ9LhWNB6j4C56

### Log files
- d3d9.log: [Sims2EP9_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3537815/Sims2EP9_d3d9.log)

**Comment by Kattus** [comment]
This happens on Windows as well, known issue.
https://simsvip.com/2014/07/20/the-sims-2-ultimate-collection-remove-black-squares/

In other words, works as intended!

**Comment by tannisroot** [comment]
@Kattus as I mentioned, it doesn't happen with old drivers, so the game seems to be relying on some broken behavior that was fixed in new drivers. So it would be nice to perhaps fine a way to emulate old driver behavior.

**Comment by NerosTie** [comment]
It's indeed a known bug: https://pcgamingwiki.com/wiki/The_Sims_2#Black_Square_Shadows

I don't think it's related to d9vk.

**Comment by tannisroot** [comment]
It kind of is and kind of isn't. This bug only appears in new driver versions, while while old drivers can still render shadows just fine. Which means there must be a way to emulate that old driver behavior and support it in D9VK.
And some other D3D9 implementations already do this - for example, dgvoodoo2.

**Comment by NerosTie** [comment]
So, it's an issue with the driver and not with d9vk.

**Comment by tannisroot** [comment]
No, it's an issue that affects both modern native D3D9 implementation and D9VK.

**Comment by NerosTie** [comment]
Exactly why I say it's not d9vk's fault :yum:

**Comment by tannisroot** [comment]
Fixed by https://github.com/Joshua-Ashton/d9vk/commit/58daddb31ccbcadb6a878104545e42526609ad77

**Comment by NerosTie** [comment]
Eh, I was wrong =/

**Comment by Joshua-Ashton** [comment]
It wasn't D9VK's fault. This bug is caused by a completely untested broken shadow renderpath. Thanks Maxis. I merely worked around this game bug by disallowing A8 render targets,
