### ISSUE TITLE
S.T.A.L.K.E.R.: Call of Pripyat crashes at boot (DX9)

### ISSUE THREAD

**Issue by shoober420** [Joshua-Ashton/d9vk#332]
Software information

Game: STALKER: Call of Pripyat
Settings: Enhanced Full Dynamic Lightning (DX9) (renderer_r2.5)

System information

GPU: NVIDIA GEFORCE 760 GTX
Driver: 435.17 proprietary
Wine version: Proton 4.11-2
DXVK version: 0.13f

When trying to run CoP, the game crashes at startup when you have DX9 mode selected. I'm using Arch Linux.

**Comment by axredneck** [comment]
Does the game use D9VK?
(Works for me with DXVK)

**Comment by axredneck** [comment]
> Are you sure it’s really using DXVK and not WINED3D?

GOG version works for me with DXVK and Wine in D3D10/11 modes, also it works with WineD3D in D3D9 static/dynamic modes. Didn't try Stalker CoP with D9VK yet but Stalker SoC works with D9VK.

**Comment by axredneck** [comment]
> ...mentioning to install some d3dcompiler dlls, but I'm trying to avoid downloading any proprietary microsoft dlls personally

Sadly D9VK needs these Windows dlls.

**Comment by Joshua-Ashton** [comment]
> I noticed some DXVK issue threads, one from you, mentioning to install some d3dcompiler dlls, but I'm trying to avoid downloading any proprietary microsoft dlls personally.

That's not my problem. Wine's versions are kinda broken.
