### ISSUE TITLE
World of Warcraft: The Burning Crusade Icons render issue

### ISSUE THREAD

**Issue by XXXBold** [Joshua-Ashton/d9vk#333]
Some of the Ability Icons are not rendered properly with d9vk, but are fine with wine d3d9.

Wine D3D9:
![tbc_wined3d9](https://user-images.githubusercontent.com/30773753/63709983-96c0ac80-c827-11e9-887c-1a89e1fb0301.png)

d9vk:
![tbc_d9vk](https://user-images.githubusercontent.com/30773753/63710015-a9d37c80-c827-11e9-8e69-ca724ff6b81a.png)

Probably it's something similar as in https://github.com/Joshua-Ashton/d9vk/issues/174

### Software information
World of Warcraft: The Burning Crusade Client (v2.4.3)

### System information
- OS: Linux Mint 19.1 Cinnamon
- GPU: AMD Radeon R9 290X
- Driver: mesa 19.2-git (oibaf ppa)
- Wine version: 4.11 (Steam Proton 4.11.2)
- DXVK version: D9VK from #753 from https://git.froggi.es/joshua/d9vk/pipelines

### Apitrace file(s)
- https://lots-of.space/s/WWiTmxKfZJY5gga

### Log files
- d3d9.log: 
[Wow_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3542155/Wow_d3d9.log)

**Comment by sigzegv** [comment]
maybe the same as here https://github.com/Joshua-Ashton/d9vk/issues/174

**Comment by misyltoad** [comment]
Hi, the apitrace link is dead.

Can you test with the latest DXVK master?

**Comment by XXXBold** [comment]
Seems this is fixed with a more recent Version of D9VK/DXVK. Will close this for now.
