### ISSUE TITLE
Gothic 3: Forsaken Gods Enhanced Edition (render issues)

### ISSUE THREAD

**Issue by jarrard** [Joshua-Ashton/d9vk#334]
Game tested with latest D9VK and no render issues exist anymore, however there is performance problems to consider, the game gets only 16fps or so for some reason. 

Apitrace and logs will be posted later on.. If needed

### Software information
Gothic 3: Forsaken Gods Enhanced Edition

### System information
- GPU: 1080TI  (now alive)
- Driver: 435
- Wine version: Proton 4.11-1/2 ----- GE-4
- DXVK/D9VK version: packaged with proton / GE

### Apitrace file(s)
Win10 - https://www.dropbox.com/s/x7u3mb2su8owiii/Gothic%20III%20Forsaken%20Gods.7z?dl=0

### Log files
- d3d9.log: 
[steam-65600.log](https://github.com/Joshua-Ashton/d9vk/files/3593402/steam-65600.log)

- d3d11.log: tba
- dxgi.log: tba

**Comment by K0bin** [comment]
Probably Readonly locking again. Whats the name of the exe of the game?

**Comment by jarrard** [comment]
> Probably Readonly locking again. Whats the name of the exe of the game?

Gothic III Forsaken Gods.exe

**Comment by K0bin** [comment]
We have the config option in place for that game. Can you post logs?

**Comment by jarrard** [comment]
> We have the config option in place for that game. Can you post logs?

My video card is dead and in for RMA, so until that comes back I can't post logs :(

**Comment by K0bin** [comment]
In that case it probably works just fine with 0.20.

**Comment by jarrard** [comment]
This has beened fixed for latest d9vk version, now it seems to render correctly. 

HOWEVER a new issue has arisen, and that is fps is only 16-17fps at 4k or close to at other resolutions. Not sure if this can be improved on, under windows it does appear to get 60fps or so.

**Comment by K0bin** [comment]
> HOWEVER a new issue has arisen, and that is fps is only 16-17fps at 4k or close to at other resolutions. Not sure if this can be improved on, under windows it does appear to get 60fps or so.

What's your GPU utilization like? Are you GPU or CPU bound?

**Comment by jarrard** [comment]
I have Conky installed now so I'll monitor it while a test for a bit and see. 

Will post results here:

**Comment by jarrard** [comment]
Updated with performance results of Linux vs Windows. Something is definitely going wrong.

**Comment by jarrard** [comment]
Here is a Apitrace under Win10 with 1080ti (just a couple seconds of moving around in starter town)
https://www.dropbox.com/s/x7u3mb2su8owiii/Gothic%20III%20Forsaken%20Gods.7z?dl=0


Should I also post a apitrace for d9vk? might be hard at 1fps but doable. 


**Update: Apparently this is a bad DLC which has allot of bugs and is basically abandon ware, people tell me to play the normal Gothic III game which is MUCH better. Thus closing.**
