### ISSUE TITLE
[regression?] Need for Speed: Hot Pursuit → glitches

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#335]
with d9vk #807
![20190826221302_1](https://user-images.githubusercontent.com/4572452/63729281-0bffa200-c867-11e9-8580-7e3a7835bf9d.jpg)
![20190826221342_1](https://user-images.githubusercontent.com/4572452/63729290-10c45600-c867-11e9-9951-8a29252107bc.jpg)

with d9vk 0.13f
![20190826220917_1](https://user-images.githubusercontent.com/4572452/63729309-1f127200-c867-11e9-9ec4-3c5e91aef5e8.jpg)
![20190826220959_1](https://user-images.githubusercontent.com/4572452/63729319-233e8f80-c867-11e9-9762-d4e9458aca1c.jpg)

### System information
- GPU: Nvidia GT 730M
- Driver: 435-17 (beta)
- Wine version: Proton 4.11
- DXVK version: #807 & 0.13f 

### Apitrace file(s)
https://mega.nz/#!n6w0zYxb!Q3CnPSZKZPZoUGgQewpMSq82VGVXtrcpLGd03LnL5YA

### Log files
[steam-47870-d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3543471/steam-47870-d3d9.log)
[steam-47870-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3543516/steam-47870-d9vk.log)

**Comment by Joshua-Ashton** [comment]
Hm, the issue is baked into the trace...
I spent way too long investigating this to find that out, doh!

Any chance you'd be able to bisect and find out what version broke it? You can use the builds on git.froggi.es

**Comment by NerosTie** [comment]
From #705 exactly (yes, it's old now!)

**Comment by Joshua-Ashton** [comment]
Can you rename this to dxvk.conf (Github is being an asshole) and see if that fixes the issue? Thanks.

[dxvk.conf.txt](https://github.com/Joshua-Ashton/d9vk/files/3602123/dxvk.conf.txt)

**Comment by NerosTie** [comment]
It has no effect (or maybe I'm doing something wrong)

**Comment by Joshua-Ashton** [comment]
Can you try this build?

[d3d9.zip](https://github.com/Joshua-Ashton/d9vk/files/3602206/d3d9.zip)

**Comment by NerosTie** [comment]
Yes, totally fixed! 
(and visibly I don't know how to use a dxvk.conf)

**Comment by Joshua-Ashton** [comment]
[d3d9_a.zip](https://github.com/Joshua-Ashton/d9vk/files/3602435/d3d9_a.zip)

**Comment by Joshua-Ashton** [comment]
Can you try this and see if it is still fixed?

**Comment by NerosTie** [comment]
No, the glitches are back.

**Comment by Joshua-Ashton** [comment]
blegh ok

**Comment by Joshua-Ashton** [comment]
[d3d9_b.zip](https://github.com/Joshua-Ashton/d9vk/files/3602497/d3d9_b.zip)

Does this fix the issue? Sorry to be a pita.

**Comment by NerosTie** [comment]
Nope, still here!

> Sorry to be a pita.

Don't worry (I just hate EA for this intro we can't skip :angry: )

**Comment by Joshua-Ashton** [comment]
Have you tried deleting the file for it -- that works in some games.

**Comment by NerosTie** [comment]
Only a partial fix: https://pcgamingwiki.com/wiki/Need_for_Speed:_Hot_Pursuit#Partial_skip_intro_fix

But it's not really useful.

**Comment by Joshua-Ashton** [comment]
[d3d9_c.zip](https://github.com/Joshua-Ashton/d9vk/files/3602523/d3d9_c.zip)

Can you try this change? 😄

**Comment by NerosTie** [comment]
Still here :/

**Comment by Joshua-Ashton** [comment]
Last thing I'll ask of you today:

[d3d9.zip](https://github.com/Joshua-Ashton/d9vk/files/3602866/d3d9.zip)

**Comment by NerosTie** [comment]
Still here, unfortunately :confused:

**Comment by NerosTie** [comment]
With #845, all the glitches are gone! :tada:
