### ISSUE TITLE
Rise of The Triad 2013 - graphical arifacts (sprites near to camera)

### ISSUE THREAD

**Issue by kwahoo2** [Joshua-Ashton/d9vk#336]
To reproduce: get an explosive weapon, shoot an enemy directly in his face, his face and eyes will be splashed on screen. This is correctly rendered with Wine D3D9, but causes artifacts with D9VK:

![RoTT2014eyes](https://raw.githubusercontent.com/kwahoo2/steamreports/master/rott2013/20190827091409_1.jpg)

Also, I spotted a very similar issue in Unreal Tournament 3.

### Software information
Rise of The Triad, 2013 release

### System information
- GPU: Radeon RX 580
- Driver: Mesa 19.3.0-devel (LLVM 8.0.0)
- Wine version: Proton 4.11-3
- DXVK version: Bundled with Proton 4.11-3

### Apitrace file(s)
- [Wine D3D9 trace](https://drive.google.com/file/d/1qPYguIE4sj1X8Ijsx1o6xeobqnXK1usR/view?usp=sharing)

### Log files
- [d3d9.log](https://github.com/kwahoo2/steamreports/blob/master/rott2013/ROTT_d3d9.log)
- [d3d11.log](https://github.com/kwahoo2/steamreports/blob/master/rott2013/ROTT_d3d11.log)
- [dxgi.log](https://github.com/kwahoo2/steamreports/blob/master/rott2013/ROTT_dxgi.log)

Note: to start RoTT at all you have to run ROTT.exe directly or replace it's launcher ROTTLauncher.exe eg. using this code:

```#include < stdlib.h > 
int main(int argc, char **argv) 
{ 
    return system("Win64\\ROTT.exe"); 
}```

**Comment by NerosTie** [comment]
> DXVK version: Bundled with Proton 4.11-3

It's an old version of d9vk now.

**Comment by kwahoo2** [comment]
> It's an old version of d9vk now.

Yes, very old,  1 commit behind master https://github.com/Joshua-Ashton/d9vk/releases/tag/0.20

**Comment by NerosTie** [comment]
Didn't noticed Proton was updated today.

**Comment by Joshua-Ashton** [comment]
Hey, this renders fine for me on the trace.

Can you re-test so this can *hopefully* be closed?

**Comment by kwahoo2** [comment]
Just tested, the issue is gone.
