### ISSUE TITLE
The Room → black bar at the bottom

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#337]
with d9vk
![20190827132755_1](https://user-images.githubusercontent.com/4572452/63770052-92060200-c8d4-11e9-8bda-41e0401d3594.jpg)

without d9vk
![20190827132839_1](https://user-images.githubusercontent.com/4572452/63770066-9a5e3d00-c8d4-11e9-9c24-fc3cb6ad0a25.jpg)

### System information
- GPU: Nvidia GT 730M
- Driver: 435-17 (beta)
- Wine version: Proton 4.11
- DXVK version: #807

### Apitrace file(s)
https://mega.nz/#!3mIRiA5Q!HlNck4vxHVYHtX2fEowW4W3XSkNcWtsc7oX11TFz_Yw

### Log files
[steam-288160-d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3545982/steam-288160-d3d9.log)
[steam-288160-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3545983/steam-288160-d9vk.log)

**Comment by Joshua-Ashton** [comment]
![image](https://user-images.githubusercontent.com/21316711/64717354-0daea400-d4bc-11e9-8266-c05a0e7731c7.png)

Looks correct on latest master,
can you verify on your end?

**Comment by Joshua-Ashton** [comment]
I'm playing back your trace, can you try doing the same?

**Comment by NerosTie** [comment]
After testing several versions of d9vk, I found the glitch was introduced with #797 and it was fine before.

**Comment by K0bin** [comment]
[That one](https://git.froggi.es/joshua/d9vk/-/jobs/797)? Because that doesn't change anything for games that aren't Dead Space.

**Comment by NerosTie** [comment]
Yes, that one:

#796:
![20190915190650_1](https://user-images.githubusercontent.com/4572452/64925107-2258a800-d7ec-11e9-8c40-bc30a0ab9e0c.jpg)

#797:
![20190911191449_1](https://user-images.githubusercontent.com/4572452/64925111-2a184c80-d7ec-11e9-84bd-b4042f4f00bd.jpg)

**Comment by Joshua-Ashton** [comment]
![image](https://user-images.githubusercontent.com/21316711/64925217-21704800-d7e5-11e9-85b2-27b198a79688.png)

Could be any one of these commits inbetween too :b

**Comment by K0bin** [comment]
Ah, there are multiple commits between those two builds. a83a45fa15a267d0a3c2cd7dfd46aa33c6d0a1da most likely caused the issue but that fixed other games.

**Comment by K0bin** [comment]
Could you try this build with at least DXVK_LOG_LEVEL=warn and post the logs?
[d3d9.zip](https://github.com/Joshua-Ashton/d9vk/files/3614046/d3d9.zip)

**Comment by K0bin** [comment]
Actually, scratch that, can you make an apitrace **with** D9VK?

**Comment by NerosTie** [comment]
@K0bin https://mega.nz/#!SqY3wYiA!MHfhib_aMvtxyHVv1Y8cs5eupqbOq6QoTITDpknHpH0

**Comment by K0bin** [comment]
I've found an issue but the game also uses a different code path with D9VK compared to what it does with the Nvidia D3D9 driver.

Can you try running the game with `d3d9.supportDFFormats = False` in your DXVK config file?

**Comment by NerosTie** [comment]
> Can you try running the game with d3d9.supportDFFormats = False in your DXVK config file?

How? My dxvk.conf is inside the game's folder but there is no effect, so I'm not sure if I'm doing it right.

**Comment by K0bin** [comment]
Sounds about right.

If you change your log level to info, the log should tell you if it found the file and applied the option.

**Comment by NerosTie** [comment]
```
info:  Found config file: dxvk.conf
info:  Effective configuration:
info:    d3d9.supportDFFormats = False
```
Thanks. But yes, ```d3d9.supportDFFormats = False``` has no effect.

**Comment by K0bin** [comment]
Thanks. I wonder why the Windows apitrace doesn't show the issue. Something makes the game do things differently with D9VK. Just to be sure, you did use the same settings for both traces, right?

**Comment by NerosTie** [comment]
> did use the same settings for both traces, right?

Yes, I think. I can make a new apitrace without d9vk if it helps.

**Comment by K0bin** [comment]
Should be fixed with that.

**Comment by NerosTie** [comment]
The glitch is gone with #838 (with #839, I just have a black screen).

BUT, there is an other issue: 

![20190915235408_1](https://user-images.githubusercontent.com/4572452/64928141-6c558400-d814-11e9-8bf9-477bbea596a8.jpg)

You can see a black bar at the bottom but it shouldn't be here. Because of that, the menus are shifted up (so the game is unplayable). A workaround is to alt+enter 2 times (disable fullscreen then enable fullscreen).

This is what we should have: 
![20190915235416_1](https://user-images.githubusercontent.com/4572452/64928197-0ddcd580-d815-11e9-9f48-389af2a49079.jpg)

**Comment by NerosTie** [comment]
There is a black bar with Oddworld New 'n' Tasty too:
![20191010100747_1](https://user-images.githubusercontent.com/4572452/66556366-5f485e00-eb50-11e9-9a50-cf89eb13ed5a.jpg)

Could be a bug with Unity 4 games.

**Comment by NerosTie** [comment]
Tested with #997 and now the black bar is wider:

![Screenshot_20191128_232505](https://user-images.githubusercontent.com/4572452/69833797-7fce9380-1236-11ea-9200-d7cd93b135fc.png)

With 0.30 for reference:

![Screenshot_20191128_232730](https://user-images.githubusercontent.com/4572452/69833835-ab517e00-1236-11ea-8871-70f84efb0d00.png)

**Comment by Joshua-Ashton** [comment]
Can this be re-tested?

**Comment by NerosTie** [comment]
Still here =/

**Comment by NerosTie** [comment]
The issue is gone! 🥳

Tested with DXVK 1.6.

**Comment by misyltoad** [comment]
Really? No idea how that got fixed. Cool!

**Comment by NerosTie** [comment]
Yes, really, tested 5 times to be sure.
