### ISSUE TITLE
TimeShift → no shadows

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#338]
with d9vk
![20190827150741_1](https://user-images.githubusercontent.com/4572452/63793680-84667180-c900-11e9-9b73-7e0fc219593f.jpg)

without d9vk
![20190827150554_1](https://user-images.githubusercontent.com/4572452/63793696-8a5c5280-c900-11e9-92bf-d5c41de520e3.jpg)

### System information
- GPU: Nvidia GT 730M
- Driver: 435-17 (beta)
- Wine version: Proton 4.11
- DXVK version: #807

### Apitrace file(s)
https://mega.nz/#!OzQSTIbR!wA1sbnkZoJR41cDU9ncEVOCgSm5I99jyFx2llrClDK8

### Log files
[steam-10130-d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3547389/steam-10130-d3d9.log)
[steam-10130-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3547390/steam-10130-d9vk.log)

**Comment by Joshua-Ashton** [comment]
![image](https://user-images.githubusercontent.com/21316711/64717165-a7c21c80-d4bb-11e9-8c96-c31c669a7d02.png)

Looks fine here!

**Comment by Joshua-Ashton** [comment]
I'm playing back your trace, can you try doing the same?

**Comment by NerosTie** [comment]
Yes. It works when we retrace it:
![Screenshot_20190917_143459](https://user-images.githubusercontent.com/4572452/65042403-14746580-d959-11e9-875c-0d1ced9ec656.png)

(note there are weird lines in the shadow)

But not with the real game.

Actually, now, this is what I have: https://imgur.com/Tw3LrG0

**Comment by K0bin** [comment]
Can you try disabling DF Formats like I asked you to in the other issue? This might be similar to what Dead Space does with its shadows.

**Comment by NerosTie** [comment]
It has no effect.

**Comment by Vencorr** [comment]
![image](https://user-images.githubusercontent.com/23224476/68359517-b7d43200-00e1-11ea-83aa-8ec19de7d823.png)
I get no shadows either and my shaders are messed up. Getting these lines. I can't even run the game without d9vk so I can't compare.
Also, probably unrelated but I get major stuttering issues on this game. Seems there are moments that it just stops doing any screen updates or something and can only be minimized by lowering to the lowest settings. Thought it was worth mentioning since I may have a borked setup.

**Comment by NerosTie** [comment]
On my side, I have shadows but they are not rendered well. Without D9VK, I know you can play this game, I finished it last year. I think it's because your GPU is AMD.

The stuttering is a known bug: 
https://www.pcgamingwiki.com/wiki/TimeShift#Microstuttering

I see there is a 1.2 patch (on Steam, the version of the game is 1.0):
https://community.pcgamingwiki.com/files/file/1026-timeshift-update-12-steam/

**Comment by Vencorr** [comment]
I have Patch 1.2, and I do not have the steam version.

**Comment by NerosTie** [comment]
Tested with DXVK 1094 and I can't access the main menu anymore. It hangs just after the logos.

**Comment by misyltoad** [comment]
@NerosTie Would you be able to bisect?

**Comment by NerosTie** [comment]
1093: same
1092: same
1091: same
1090: "Unhandled exception: Game crashed, 'timeshift_minidump.dmp' saved"
1089: "Unhandled exception: Game crashed, 'timeshift_minidump.dmp' saved"
1088: "Unhandled exception: Game crashed, 'timeshift_minidump.dmp' saved"
1086: "Unhandled exception: Game crashed, 'timeshift_minidump.dmp' saved"
1085: "Unhandled exception: Game crashed, 'timeshift_minidump.dmp' saved"
1084: "Unhandled exception: Game crashed, 'timeshift_minidump.dmp' saved"
1083: "Unhandled exception: Game crashed, 'timeshift_minidump.dmp' saved"
1082: It works!

edit: I have the same issue with Splinter Cell Chaos Theory: I can launch the game with 1082 but with 1083 and beyond it crashes at start.

**Comment by NerosTie** [comment]
Good news, it doesn't hang anymore with dxvk 1112 (and the issue with Splinter Cell is gone too).

**Comment by Riesi** [comment]
DXVK trace: https://drive.google.com/open?id=1cqTgeNwftgro1j3y-d-JaP0Y2LvbDEQD
windows trace: https://drive.google.com/open?id=1NclGHUcYVNrgSEhridWEjTtvjE-ewIvz
attaching some more traces, so they don't get lost.

**Comment by NerosTie** [comment]
With DXVK 1.7.1 there is still a remaining issue.

There is a ray of light that shouldn't be here (first door at the beginning of the game):
![Screenshot_20200813_201958](https://user-images.githubusercontent.com/4572452/90175297-804c9180-dda7-11ea-8fa0-a0082e8957d9.png)

https://imgur.com/03WlU58

(sorry for the blinking in the video)

**Comment by K0bin** [comment]
Is that in your apitrace?

**Comment by NerosTie** [comment]
Yes, it's the same scene.
