### ISSUE TITLE
Sudeki → no shadows

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#339]
with d9vk
![20190827193128_1](https://user-images.githubusercontent.com/4572452/63802625-4e7eb880-c913-11e9-90e6-c9e9991b2d55.jpg)

without d9vk
![20190827192935_1](https://user-images.githubusercontent.com/4572452/63802640-550d3000-c913-11e9-9489-184fd76f2c59.jpg)

### System information
- GPU: Nvidia GT 730M
- Driver: 435-17 (beta)
- Wine version: Proton 4.11
- DXVK version: #807

### Apitrace file(s)
https://mega.nz/#!DzJklagA!pnckNRbabWqltQHNXInw9bJEA1P5i-zET5CLC8wel7Y
(sorry, the FPS are very low, Sudeki doesn't like to be apitraced :disappointed: )

### Log files
[steam-233350-d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3547816/steam-233350-d3d9.log)
[steam-233350-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3547817/steam-233350-d9vk.log)

**Comment by Joshua-Ashton** [comment]
![image](https://user-images.githubusercontent.com/21316711/64715290-13a28600-d4b8-11e9-976b-500c9a4c4825.png)

I think your trace is just slightly broken, but yes I see the lack of shadows. I'll take a look 🐸

**Comment by NerosTie** [comment]
Regression: now it crashes during the loading screen (tested with DXVK 1084)

**Comment by NerosTie** [comment]
It looks like the shadows are back! 🎉

![Screenshot_20200121_014957](https://user-images.githubusercontent.com/4572452/72766491-763b2980-3bf0-11ea-9acc-d4a4ad363d8f.png)

(tested with dxvk 1094)

**Comment by misyltoad** [comment]
Awesome!
