### ISSUE TITLE
Ponds look too saturated in Sims 2

### ISSUE THREAD

**Issue by tannisroot** [Joshua-Ashton/d9vk#342]
Here's how the water in the ponds looks with WineD3D (native is the same, I checked):
![Screenshot from 2019-08-28 05-46-18](https://user-images.githubusercontent.com/10602045/63823471-a7bf0a00-c95c-11e9-821f-5fe556b16546.png)
And here's how it looks with D9VK:
![Screenshot from 2019-08-28 06-05-26](https://user-images.githubusercontent.com/10602045/63823505-c1605180-c95c-11e9-9958-6cde9ef8b05b.png)
As you can see, the color of the water with D9VK is too saturated.

### System information
- GPU: NVIDIA GTX 1070
- Driver: 430.40
- Wine version: 4.14
- D9VK version: 0.20

### Apitrace file(s)
Note: don't mind the color of the swimming pool, it looks different from the pictures because I disabled shaders in the game itself (to avoid crash during tracing).
https://drive.google.com/open?id=14gSqto2u7QOZOgEBDQZVD_e89B29MaZn

### Log files
- d3d9.log: [Sims2EP9_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3548978/Sims2EP9_d3d9.log)

**Comment by Joshua-Ashton** [comment]
Closed by https://github.com/Joshua-Ashton/d9vk/commit/56fcc19e20b110871c7ef87e1c7e4c541ab622b9 and https://github.com/Joshua-Ashton/d9vk/commit/717d9c48a16a4c680c213f109a5481d29cadb9b8
