### ISSUE TITLE
Just Cause → lighting issue

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#343]
with d9vk:
https://imgur.com/a/8ZOsyR0

### Software information
Name of the game, settings used etc.

### System information
- GPU: Nvidia GT 730M
- Driver: 435-17 (beta)
- Wine version: Proton 4.11
- DXVK version: #807

### Apitrace file(s)
https://mega.nz/#!Wu4lnSzD!jYRaKsjWx5MCyskUvd-aIBwcQzn6AJs5MaLeDJ15kEg

### Log files
[steam-6880-d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3550571/steam-6880-d3d9.log)
[steam-6880-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3550572/steam-6880-d9vk.log)

**Comment by Joshua-Ashton** [comment]
Closed by https://github.com/Joshua-Ashton/d9vk/commit/d5ebe85ac9436fdd3b66d0a077540e48ee527bb7

It still has a slight flicker on the edges of hands -- but that's also present on native and wined3d.

**Comment by NerosTie** [comment]
> It still has a slight flicker on the edges of hands

Yep, I noticed that too.

Thanks!
