### ISSUE TITLE
Collin Mac Rally 2005 show car paint issues

### ISSUE THREAD

**Issue by mrdeathjr28** [Joshua-Ashton/d9vk#345]
Collin Mac Rally 2005 show car paint issues

![a](https://user-images.githubusercontent.com/6601480/63880760-ee7c2680-c993-11e9-89ae-e722bfb8affd.png)

![b](https://user-images.githubusercontent.com/6601480/63881021-8aa62d80-c994-11e9-8122-ab90b88a5e76.png)

d9vk log:

https://mega.nz/#!6dFyAA4Z!ykitB18e54jJMBX-BwemE18zOqSQqxlql67OamIgoWo

Trace:

https://mega.nz/#!qddwkKqT!zFGURd-JyZsivQIFgWEbHSgkZ-U3NGcqCG2qYzmtaiw

Nvidia Drivers 418.52.18 (run package)

Xubuntu 18.04 x64 - Kernel 4.17.12 generic (ubuntu mainline) -

CPUFreq: Performance

CPU: Core i3 8350K Tri-Core (Coffelake 14nm) 5.0Ghz + Zalman CNPS 10x Performa+

MEMORY: 8GB DDR4 2400mhz (4x2) Mushkin (dual channel: 37.5 gb/s)

GPU: Gigabyte Nvidia Geforce GTX 1050 OC (GP107 14nm: 640 Shaders / 40 TMUS / 32 ROPS) Windforce 2GB DDR5 7000Mhz 128Bit (110Gb/s)

MAINBOARD: ASUS Z370-P

**Comment by Joshua-Ashton** [comment]
Looks to be a game bug, same happens on native when replaying the trace.

**Comment by K0bin** [comment]
> Looks to be a game bug, same happens on native when replaying the trace.

Could also be *sigh* another locking issue.

**Comment by Joshua-Ashton** [comment]
Definately not, the vertex data and texture data looks correct -- and afaik the trace was made with wined3d

**Comment by K0bin** [comment]
Well apitrace doesnt handle locking correctly either.

**Comment by Joshua-Ashton** [comment]
iirc he said on Discord it looks the same with wined3d, but I could be misremembering

**Comment by Joshua-Ashton** [comment]
See video of it on native: https://youtu.be/X6nXBUGmMb8?t=297

**Comment by mrdeathjr28** [comment]
Issue closed because is gamebug
