### ISSUE TITLE
Dungeons and Dragons Dragonshard have missing textures

### ISSUE THREAD

**Issue by mrdeathjr28** [Joshua-Ashton/d9vk#346]
Dungeons and Dragons Dragonshard have missing textures

![dda](https://user-images.githubusercontent.com/6601480/63881270-1029dd80-c995-11e9-8ed5-e79ef8441a3e.png)

![ddb](https://user-images.githubusercontent.com/6601480/63881273-1455fb00-c995-11e9-9088-0865961096c8.png)

d9vk log:

https://mega.nz/#!fJMQgILS!fGp7fzpUqO4K_FT32HnvG_t2jaFkImE7lCjdP1d-BbM

Trace:

https://mega.nz/#!rFdkFKja!5xkvILs271T2XYLeg2r3X3csu3giPhy1AQu7hsF6Ifo

Nvidia Drivers 418.52.18 (run package)

Xubuntu 18.04 x64 - Kernel 4.17.12 generic (ubuntu mainline) -

CPUFreq: Performance

CPU: Core i3 8350K Tri-Core (Coffelake 14nm) 5.0Ghz + Zalman CNPS 10x Performa+

MEMORY: 8GB DDR4 2400mhz (4x2) Mushkin (dual channel: 37.5 gb/s)

GPU: Gigabyte Nvidia Geforce GTX 1050 OC (GP107 14nm: 640 Shaders / 40 TMUS / 32 ROPS) Windforce 2GB DDR5 7000Mhz 128Bit (110Gb/s)

MAINBOARD: ASUS Z370-P

**Comment by K0bin** [comment]
Might be readonly locking
