### ISSUE TITLE
Burnout Paradise → the sky is not well rendered 

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#348]
with d9vk:
![20190829202821_1](https://user-images.githubusercontent.com/4572452/63982514-14541900-cac3-11e9-9f04-79d3aba1b4f3.jpg)
![20190829202842_1](https://user-images.githubusercontent.com/4572452/63982524-19b16380-cac3-11e9-9bf0-4b4c7e5a80e5.jpg)
![20190829202848_1](https://user-images.githubusercontent.com/4572452/63982526-1c13bd80-cac3-11e9-941c-bf3386f4eaa2.jpg)

without d9vk:
![20190829202631_1](https://user-images.githubusercontent.com/4572452/63982541-2930ac80-cac3-11e9-9820-fddf084d711c.jpg)
![20190829202654_1](https://user-images.githubusercontent.com/4572452/63982546-2b930680-cac3-11e9-8cee-3d2106fd6b41.jpg)
![20190829202701_1](https://user-images.githubusercontent.com/4572452/63982550-2df56080-cac3-11e9-8a9a-454fb231260f.jpg)

### System information
- GPU: Nvidia GT 730M
- Driver: 435-17 (beta)
- Wine version: Proton 4.11
- DXVK version: #807

### Apitrace file(s)
https://mega.nz/#!jzQ2XQJa!5XP-i6QaTUjWaLVRpSOE7pAZwyFawg7FnFcW9ikGh1s

### Log files
[steam-24740-d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3557618/steam-24740-d3d9.log)
[steam-24740-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3557619/steam-24740-d9vk.log)

**Comment by K0bin** [comment]
This might be a regression related to the fixed function fog. I remember I tried the game at some point and it was fine.

**Comment by NerosTie** [comment]
The issue about the sky was introduced with #705, so yes, it's a regression.

**Comment by K0bin** [comment]
I can reproduce it using the build 704.

**Comment by K0bin** [comment]
The sky issue is on master and #375 fixes the background on the main menu.

**Comment by NerosTie** [comment]
Tested with #845 and everything is perfect :+1:
