### ISSUE TITLE
The King of Fighters 98 Ultimate Match show intensive flickering

### ISSUE THREAD

**Issue by mrdeathjr28** [Joshua-Ashton/d9vk#349]
The King of Fighters 98 Ultimate Match show intensive flickering

![a](https://user-images.githubusercontent.com/6601480/63990839-0d211100-caab-11e9-8dda-84abf9e12867.png)

d9vk log:

https://mega.nz/#!iIMmTaBa!bzKl8kqee7EFyMD0QmJ69DwpLbAHsf_AUwYf-KRGnGk

Trace:

https://mega.nz/#!ScdSHSgI!BLKaz5szbLmoiS2H4fUN05940Sf42uj6En1UoEPjI5o

Nvidia Drivers 435.19.02 (run package)

Xubuntu 18.04 x64 - Kernel 4.17.12 generic (ubuntu mainline) -

CPUFreq: Performance

CPU: Core i3 8350K Tri-Core (Coffelake 14nm) 5.0Ghz + Zalman CNPS 10x Performa+

MEMORY: 8GB DDR4 2400mhz (4x2) Mushkin (dual channel: 37.5 gb/s)

GPU: Gigabyte Nvidia Geforce GTX 1050 OC (GP107 14nm: 640 Shaders / 40 TMUS / 32 ROPS) Windforce 2GB DDR5 7000Mhz 128Bit (110Gb/s)

MAINBOARD: ASUS Z370-P

**Comment by Joshua-Ashton** [comment]
Dupe
