### ISSUE TITLE
Override vendor/device id (probably) doesn't work

### ISSUE THREAD

**Issue by Kron4ek** [Joshua-Ashton/d9vk#35]
Hi. I'm trying to override vendor/device ID, I put this into dxvk.conf:

    d3d9.customVendorId = "10de"
    d3d9.customDeviceId = "402"

But game (Fallout 3 launcher, actually) still reports that i have Intel GPU. That's what i see in d3d9.log:

    info:  Effective configuration:
    info:    d3d9.customDeviceId = "402"
    info:    d3d9.customVendorId = "10de"

Can someone else test if vendor/device ID overriding works?

### System information
- GPU: Intel HD 630
- Driver: Mesa 19.0.1
- Wine version: 4.6
- DXVK version: 331d883

**Comment by Joshua-Ashton** [comment]
Firstly, your device ID is invalid.

Secondly, it does not spoof the name of the device, just the device id, vendor id and the driver dll reported to the game.

**Comment by Kron4ek** [comment]
> Firstly, your device ID is invalid.

How will be correct, 0402?

> it does not spoof the name of the device

Ok. I suppose this game (Fallout 3 launcher) reports device name according to its device ID. When i use WineD3D and spoof vendor/device ID through regedit the game reports that i have Nvidia GPU (GeForce 8600 GT in case of this device ID).

**Comment by Kron4ek** [comment]
I also tried dxdiag. Spoofing works with WineD3D but with D9VK nothing changes no matter if i change only vendor ID or both vendor and device ID. With D9VK DxDiag always reports:

        Vendor ID: 0x8086
        Device ID: 0x5912

**Comment by K0bin** [comment]
D9VK doesn't implement DXDiag, so if games query that you also need to setup the override in Wine.

**Comment by Kron4ek** [comment]
Well, i think Fallout 3 doesn't use dxdiag. Anyway, i tested 3 different games/apps: Fallout 3, Braid and DxDiag.exe, and in all of them overriding vendor/device ID doesn't work with D9VK. I don't know, maybe i'm doing something wrong.

**Comment by K0bin** [comment]
I don't think Dxdiag uses D3D9.

**Comment by Kron4ek** [comment]
It uses d3d9, because when i disable d3d9.dll it doesn't reports vendor ID at all.

**Comment by Joshua-Ashton** [comment]
> 
> 
> > Firstly, your device ID is invalid.
> 
> How is correct, 0402? I tried 0402 and still nothing changes.
> 
> > it does not spoof the name of the device
> 
> Ok. I suppose this game (Fallout 3 launcher) reports device name according to its device ID.
> 
> When i use WineD3D and spoof vendor/device ID through regedit the game reports that i have Nvidia GPU (GeForce 8600 GT in case of this device ID).

No, I stated the game stills hows the device name, but the device id, vendor and driver name are spoofed -- which is what the game actually checks to make decisions

**Comment by Kron4ek** [comment]
Fallout 3 always changes graphics settings when hardware changes. 

When i spoof vendor ID using WineD3D, F3 launcher changes graphics settings, and when i spoof it again to some different value and run launcher again then graphics settings changes again. But when i spoof vendor/device ID using D9VK nothing changes.

Same behavior in And as i said DxDiag.exe and Braid always shows the same IDs when i use D9VK. That's what DxDiag.exe (and Braid shows the same) reports:

    Vendor ID: 0x8086
    Device ID: 0x5912

What i'm trying to say is that spoofing works with WineD3D, but doesn't work with D9VK. At least doesn't work for me. What am I doing wrong?

**Comment by Kron4ek** [comment]
@Joshua-Ashton I was able to spoof vendor and device ID by manually replacing lines in src/d3d9/d3d9_interface.cpp:

    uint32_t vendorId = m_d3d9Options.customVendorId == -1 ? props.vendorID : uint32_t(m_d3d9Options.customVendorId);
    pIdentifier->DeviceId = m_d3d9Options.customDeviceId == -1 ? props.deviceID : uint32_t(m_d3d9Options.customDeviceId);

with

    uint32_t vendorId = 0x10de;
    pIdentifier->DeviceId = 0x0402;

After that Fallout 3 working and doesn't crashes (as it crashes on Intel GPUs without spoofing) and DxDiag.exe reports:

        Vendor ID: 0x10DE
        Device ID: 0x0402

So spoofing using dxvk.conf file is broken, options just ignored or handled incorrectly. Maybe parsePciId function is broken?

**Comment by Kron4ek** [comment]
@Joshua-Ashton I found out why spoofing doesn't works for me. The problem is in double quotes. This works:

    d3d9.customVendorId = 10de
    d3d9.customDeviceId = 0402

and this doesn't:

    d3d9.customVendorId = "10de"
    d3d9.customDeviceId = "0402"

**Comment by Joshua-Ashton** [comment]
Yeah, that'd cause it :P
