### ISSUE TITLE
Skullgirls → glitches

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#351]
with d9vk:
https://imgur.com/9UmW0Q9

### System information
- GPU: Nvidia GT 730M
- Driver: 435-17 (beta)
- Wine version: Proton 4.11
- DXVK version: #809

### Apitrace file(s)
https://mega.nz/#!a7QmRQRY!QY7l9q6TblGUCWODvDig1dqZ8K8YhmU0s33Nmedionc

### Log files
[steam-245170-d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3559705/steam-245170-d3d9.log)
[steam-245170-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3559706/steam-245170-d9vk.log)

**Comment by NerosTie** [comment]
Characters are not glitching anymore but they are still flickering.

**Comment by Joshua-Ashton** [comment]
Seems to be fixed as of https://github.com/Joshua-Ashton/d9vk/commit/4866e321f168acf0147fee52ed7adc9cd8e72598

Can you verify?

**Comment by NerosTie** [comment]
The issue is still here unfortunately.

**Comment by Joshua-Ashton** [comment]
Can you try on latest master? Sorry I don't own the game, but I made a change that may fix it.

**Comment by NerosTie** [comment]
Nothing has changed :man_shrugging:

**Comment by Joshua-Ashton** [comment]
Blegh

**Comment by Joshua-Ashton** [comment]
Can you try now on latest master?

**Comment by NerosTie** [comment]
Fixed! 🥳
