### ISSUE TITLE
Guild Wars 2 - some effects are missing in crowded area

### ISSUE THREAD

**Issue by logan001** [Joshua-Ashton/d9vk#355]
In world boss fight or crowded areas some skill effects won't render or just partial rendering.
An example is some lighting effects are rendering only the smoke on the ground but the lighting itself is missing completely. sometime the red circles on the ground are missing.
Unfortunately i can't create an api trace since this occurs in crowded places and ill have to on the map before the fight starts.

### Software information
Guildwars 2
### System information
- GPU: 970
- Driver: 435.19.02 (or previous)
- Wine 4.14 (or lower)
- D9VK 0.20 (or lower)

### Apitrace file(s)
impossible to trace due to huge  size. if there is a possibility to on/off with some shortcuts key that will be helpful

### Log files
i'll add them with next occasion

Strange nobody reported it so far. does it happen only to me

**Comment by DxCx** [comment]
It happens to me too
But as far as i can tell it happenes also without d9vk
I didnt really try windows on my PC only linux with pba gl or d9vk.
Anyway i think with d9vk its better then glx

**Comment by logan001** [comment]
@DxCx i also didn't try it with windows. Since d9vk stared to work so good i haven't play the game in windows except for some test of FPS (1 min) in different places all over the world

**Comment by logan001** [comment]
i've tried the game without d9vk and as DxCx said the game has the same issues. so its probably wine issue
