### ISSUE TITLE
Dark Souls 2 → windowed mode doesn't work anymore

### ISSUE THREAD

**Issue by OnikenX** [Joshua-Ashton/d9vk#358]
In the previous version (Version 0.13f - Hypnofrog) dark souls 2 worked in windowed mode now it is not as the game does not render the game showing a black window instead of the game.

### System information
- GPU: Intel HD Graphics 5500
- Driver: mesa 19.1.5-1 , vulkan-intel 19.1.5-1
- Wine version: wine 4.15-1
- DXVK version: d9vk 0.20

**Comment by Joshua-Ashton** [comment]
Please try latest master. There have been fixes for degenerate present regions there.

**Comment by OnikenX** [comment]
The bug was corrected in the master.
