### ISSUE TITLE
Winelib compilation failing

### ISSUE THREAD

**Issue by npour** [Joshua-Ashton/d9vk#360]
Essentially the same issue as this:

https://github.com/doitsujin/dxvk/issues/1179

https://bugs.winehq.org/show_bug.cgi?id=47710

Which dxvk managed to fix with these changes:

https://github.com/doitsujin/dxvk/commit/5ea5d2a81660480ba553b8b98e8682dfc0153d20

https://github.com/doitsujin/dxvk/commit/c57e63f7d297c3f29ca0b34d93960fb414cf633c

However, I tried applying the same changes to the d9vk project and didn't get it working, a good reason for this could be that I'm dumb though. 

[winebuild.patch.txt](https://github.com/Joshua-Ashton/d9vk/files/3586589/winebuild.patch.txt)

**Comment by Joshua-Ashton** [comment]
I rebased, can you try again?

**Comment by Kattus** [comment]
Had the same issue, works great now, thanks!
