### ISSUE TITLE
Halo Custom Edition → Game never gets to frame buffer.

### ISSUE THREAD

**Issue by gbMichelle** [Joshua-Ashton/d9vk#364]
~~When the game has loaded up all that renders is a single color. This color is accurate to what one pixel on the screen should be, as I recognize it as part of the skybox. If you wait long enough the color will change, as the camera moves to a point where the corner of the screen has different colors.~~

After inspection of an apitrace I have found that the game's texture never ends up in Framebuffer. This is why the loading screen stays stuck after the game has loaded. (See comment)

### Software information
Halo Custom Edition, version 1.10 (latest). Settings have no effect.

### System information
- GPU: Nvidia GTX 1060
- Driver: 435.21
- Wine version: 4.12 (Also tested on seperate Windows 7 PC, same problem)
- DXVK version: D9VK 0.20

### Apitrace file(s)
- ~~https://drive.google.com/open?id=1OthqOoPFd6qL-JLOtwmz4Ie62V8h9kVH~~
   (Small as the issue is right there when the game first starts.)
 - ~~New traces that hopefully aren't black. https://drive.google.com/open?id=1H8PTj9esFQolOZ461HMYK4KrImnw5Ap7~~

### Log files
- d3d9.log: https://pastebin.com/qfxFMiRy
- d3d11.log: https://pastebin.com/5TgPF0bi
- dxgi.log: empty

**Comment by Joshua-Ashton** [comment]
Trace renders black on d9vk and native for me

**Comment by DaRkL3AD3R** [comment]
I can confirm this too.

**Comment by gbMichelle** [comment]
Idk if I did the trace right, but if it helps at all, this is what I am supposed to see:
![intended image](https://i.imgur.com/7S8UY0R.png "Intended image")
What d9vk outputs.
![d9vk image](https://i.imgur.com/v7J5jkL.png "d9vk output")
From what it seems to me it only renders the bottom right point for the whole screen.

Keep in mind that the game also renders black for a little bit at 800x600 before the game changes resolution and this renders. (These screenshots were taken at a different resolution than the trace.)

**Comment by gbMichelle** [comment]
So, interesting detail. I just noticed that I have two more trace files with very similar timestamps on my desktop. One being bigger and one being really small. I've uploaded both so they can be examined. I hope it helps. I will also update the original issue.

https://drive.google.com/open?id=1H8PTj9esFQolOZ461HMYK4KrImnw5Ap7

**Comment by K0bin** [comment]
Does this still happen on master?

**Comment by gbMichelle** [comment]
I'll have to find some time to set up a compile to test that.

**Comment by gbMichelle** [comment]
Found out someone's been doing nightly's. Thanks @pchome.
Same result with current master. (23c1de19c45d36a8e432d98b08446f8be01b4844)

**Comment by Joshua-Ashton** [comment]
I do builds for every commit myself on https://git.froggi.es/joshua/d9vk/-/jobs :frog:
Is that what you're referring to?

And thanks for the info

**Comment by gbMichelle** [comment]
Uhh, yeah that's what I'm referring to. I got confused because @pchome linked it. And I was using the link before that automatically picks the newest one. So, I didn't see this page until later. :fox_face:

**Comment by Joshua-Ashton** [comment]
The traces are black

**Comment by gbMichelle** [comment]
Ok. So, I'm going to set up a windows machine and try to create some traces on there. How would I go about watching back the traces to see if it worked?

**Comment by Joshua-Ashton** [comment]
Drag and drop on d3dretrace.exe

**Comment by gbMichelle** [comment]
Sorry for waiting so long. I had a busy week. So, I got traces that aren't black, but they end after the loading screen is over, and only after the loading screen is where the rendering stops functioning properly.

https://drive.google.com/open?id=12jxSR4HzdBMBDRTnokJQa5ozJER1x0wT

I originally wasn't going to upload this, but then I realized that the end of this trace might tell us why this problem happens. So, here you go, it's just the loading screen, not the point where the actual "single color screen" bug happens yet.

**Comment by gbMichelle** [comment]
I got this peculiar trace. Idk if this is the memory size I gave my VM, but it starts spitting out memory errors.
![Screenshot_20190924_045628](https://user-images.githubusercontent.com/24233409/65477938-381f3a80-de88-11e9-91ff-5d9a46a5478d.png)

https://drive.google.com/open?id=1UPFgmf5JxV3W9a1HElsFdwOOkIIpILEs

**Comment by Joshua-Ashton** [comment]
That trace is fine, can you do one like that but past the loading screen? The other ones are just complete garbage (they're MBs in size :b)

**Comment by gbMichelle** [comment]
Is there a way to start a trace while the game is already running? I have not gotten a single trace that isn't the loading screen :/

**Comment by gbMichelle** [comment]
So, as an experiment I went into the game, changed the resolution. And while the trace only shows that loading screen, it does change resolution around the same time that I did...

**Comment by gbMichelle** [comment]
Sorry for posting three messages in a row.
Here is that trace.

https://drive.google.com/open?id=11bXOTJWhjdHg6zlK6iJUwiOjb5-igBFw

I just remembered an important detail about the game, I don't know if this matters. But the game hates native anti-aliasing. Apparently this is because of some render target thing. I don't know the specifics, but basically, if someone who tries to play the game has anti-aliasing enabled, the game will not render past the loading screen. I can see past the loading screen while doing a trace, but the trace might not see past that for similar reasons.

**Comment by gbMichelle** [comment]
![Screenshot_20191007_060508](https://user-images.githubusercontent.com/24233409/66284746-9eb14900-e8c9-11e9-9f66-4d016b4aa3ff.png)
New trace: https://drive.google.com/open?id=1R29HgEc11Vl8wkkoYkqKESZUBOv601u3

So, from tinkering around I have found that the game does actually render frames. But, the rendered frame never ends up in the framebuffer. As you can see from the screenshot the game frame can be found inside of PS_RESOURCE_0_LEVEL_0. Which then promptly is discarded by the next call. (Screenshot is of frame 324, was just a good frame with no loading screen plasted over it.)

I'll be playing with this a bit more, maybe change some calling args to see what it does. Tell me what you think though.

**Comment by Joshua-Ashton** [comment]
Got a friend to try out this game, and it works for them :-/

Does it work for you in Windows + D9VK (on master)

**Comment by gbMichelle** [comment]
I'll go test. Btw, I forgot to report this. But I had someone on an amd gpu and it worked for them, while the few that tested with nvidia it didn't work. Also, there is a few seperate rendering modes the game can be in, and while the worse ones work, the intended one didn't work for me on nvidia

**Comment by gbMichelle** [comment]
Perfect, this works. Thank you 🦊
