### ISSUE TITLE
[Question] What am I doing wrong? Shader glitches on native DirectX + D9VK (GTA IV)

### ISSUE THREAD

**Issue by lostinmymind** [Joshua-Ashton/d9vk#367]
This isn't a bug issue, I'm just kinda tempted to ask now because I have no clue what I'm doing wrong.
When I first installed d9vk, everything was working fine and it seemed to be using native DX9 for d3dx9 and d3dcompiler, there were no shader artifacts (apart from top of the screen like I mentioned in my different issue), but then I made a new Wineprefix (tried reinstalling games instead of copying them from old to new), installed DirectX from June 2010 Redist (bundled with GTA V) (I also tried installing d3dx9_?? libraries via Winetricks) and completed by replacing d3dcompiler_46 and 47 .dlls (not bundled with redistributables) in system32 and syswow64 with respectively 64-bit and 32-bit versions. SMAA injector was working while with wined3d it wouldn't, so I assumed everything is correct. Then I installed d9vk (this alone fixed shader glitches last time) and horrible shader glitches were still here in GTA IV. I tried overriding all d3dx9 and d3dcompiler libraries, I tried downgrading Wine, graphics drivers, d9vk (also using latest master), Vulkan loader, I tried installing Visual C++, even .NET framework or Mono... I made sure that all d3dx9 and d3dcompiler libraries are native (by filesize, native are few MB and Wine's fakedlls are just a few KB, right?) and I also tried reinstalling DirectX a lot of times. Nothing worked. Any hope?
Sorry for kind of offtopic issue, but I can't seem to find an answer to this.
**EDIT:** okay this is strange. Disabling d3dx9_31 (seemingly required for GTA IV to run, errors about d3dx9 are always about library number 31, but tried 37 too which was mentioned once as well) doesn't prevent game from running. Disabling d3dcompiler_43 on the other hand DOES prevent the game from loading
**EDIT 2:** nvm disabling d3dx9_43 also prevented game from running. Seems version of both matches. ;p Question still open though. Problem still not fixed, I deleted all GTAIV-dxvk.cache files as well

**Comment by Joshua-Ashton** [comment]
Can you show me what you mean?

**Comment by lostinmymind** [comment]
yes, sorry, what I wrote might've been a bit messy ^^' here https://imgur.com/a/R6i5UMh there is a screenshot that more or less shows what I mean, these black rectangles on TV screen and literally transparent ones on lamp (like square holes), when I installed d9vk for the first time it disappeared but when I restarted wineprefix, installed MS DirectX from redist bundled with GTA V (tried with one bundled with GTA IV too as well as via Winetricks) and d9vk it appeared again. No clue what I did wrong :/

**Comment by lostinmymind** [comment]
I just checked without d9vk and the type of glitches like on floor and outside on parking place happen only on d9vk (these on lamps and intro texts happen on builtin d3d9 too) but as I said it could possibly be something wrong with my configuration but idk what... that's why I'm asking, maybe anyone knows what could have caused these glitches on d9vk? anything I have yet to install? thanks in advanceee

**Comment by lostinmymind** [comment]
okay I am sorry for a reply after such a long time but I was off for 3 weeks, I just downgraded whole OS and confirmed what was mentioned in a different issue, this is a problem with Nvidia 435 driver. They need to fix it ASAP, it drives me crazy. I had some crazy glitches in Assassin's Creed IV as well, I'll check if it's also problem of 435 driver. For now I think this is to be closed. Thank you :)

**Comment by Joshua-Ashton** [comment]
So the problem doesn't happen on older drivers?

**Comment by lostinmymind** [comment]
No, the problem doesn't appear on driver 430, only on 435. Out of curiousity I checked AC4 too but the issue is still here so it is more about DXVK probably and not driver so I'll file a bug report to Doitsujin about it. Meanwhile I am wondering how can I possibly install LTS Nvidia 430 driver on Arch because there's no package for it and it would be very useful at the moment cause driver 435 just introduces problems, it seems :/

**Comment by Tk-Glitch** [comment]
May I? https://github.com/Tk-Glitch/PKGBUILDS/tree/master/nvidia-all :frog:

**Comment by Joshua-Ashton** [comment]
Should be fixed in ``master``, feel free to re-open if you can still repro it.
