### ISSUE TITLE
bns

### ISSUE THREAD

**Issue by wqy0916** [Joshua-Ashton/d9vk#368]
info:  Game: Client.exe
info:  DXVK: d9vk-0.20-frogcookie
warn:  OpenVR: Failed to locate module

It can still be used before reinstalling the system. It will not work after reinstalling the system. It used to be the home version. It is now the professional version. win10

**Comment by K0bin** [comment]
Client.exe is my favorite game

**Comment by shijiediyo** [comment]
兄弟你是笔记本吗

**Comment by shijiediyo** [comment]
Are you a laptop computer?

**Comment by K0bin** [comment]
> bns
What is bns?

> It can still be used before reinstalling the system. It will not work after reinstalling the system. 
So the game doesnt start? Or does it start without D9VK?

Please attach D9VK logs.

> It used to be the home version. It is now the professional version. win10
Home/Professional has 0 impact on D9VK.

**Comment by Joshua-Ashton** [comment]
Feel free to re-open if you can actually provide some info/an apitrace/tell us the game 🐸
