### ISSUE TITLE
Metin2 Portugal Zooming floor textures.

### ISSUE THREAD

**Issue by MortalisPT** [Joshua-Ashton/d9vk#371]
### Software information

**Name of the game, settings used etc.**
Metin2, Settings don't matter.

**System information**

    GPU: Nvidia GT 1030
    Driver: 435.21
    Wine version: 4.11-3 (Proton)
    DXVK version: D9VK 0.20 (d3d8to9>D9VK because the game is d3d8.)

### Apitrace file(s):

    https://cloud.mail.ru/public/5raQ/2QjV2ovGA

### Log files:

   Proton's D9VK didn't produce logs.

### Videos:

   Video showing the bug: https://cloud.mail.ru/public/2ZQY/46T7fGLxF

**Comment by Joshua-Ashton** [comment]
Closed by https://github.com/Joshua-Ashton/d9vk/commit/b385e24b0645d3c371b534583cc0a8eae2084190
