### ISSUE TITLE
fr-025 missing graphics due to unhandled render state

### ISSUE THREAD

**Issue by arabek** [Joshua-Ashton/d9vk#373]
https://www.pouet.net/prod.php?which=9450
This demo is free to download from scene.org servers.

When running under latest wine-staging with dx9vk enabled the graphics are looking wrong.

### Console output

```
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_CLIPPING
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:    Buffer size:  1024x768
info:    Image count:  3
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_SPECULARENABLE
```

### System information
- GPU: Nvidia 1080
- Driver: Nvidia binary 435.21
- Wine version: wine-4.14 (Staging)
- DXVK version: info:  DXVK: v1.3.2

### Apitrace file(s)
- not provided

### Log files
- d3d9.log: [fr-025-final2_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3613626/fr-025-final2_d3d9.log)

**Comment by K0bin** [comment]
What does 'graphics are looking wrong' mean exactly?

Please attach screenshots and an apitrace.

**Comment by CME42** [comment]
Your 32bit d3d9.dll is out of date, D3DRS_SPECULARENABLE is already implemented and the demo is working just fine on the latest master.

Here you can find the latest build: https://git.froggi.es/joshua/d9vk/-/jobs

**Comment by Joshua-Ashton** [comment]
I've already debugged this demo and know it works fine on latest master. If you still have an issue feel free to re-open.

**Comment by arabek** [comment]
Indeed. I didn't notice that my winetricks was out of date. Thanks for your amazing work!
