### ISSUE TITLE
[Regression] Missing text in Divinity II Deverloper's Cut

### ISSUE THREAD

**Issue by SDN-Arkhen** [Joshua-Ashton/d9vk#374]
### Software information
Divinity II Developer's Cut at default settings.

### System information
- GPU: GTX 1050 Ti
- Driver: 435.21
- Wine version: 4.15
- DXVK version: Job #837 (latest master) and #836

### Apitrace file(s)
- The game crash when using apitrace's d3d9.dll with native,build-in Wine setup. Only a small 500kb trace file rendered.

### Log files
- d3d9.log #837: 
[Divinity2_d3d9_837.log](https://github.com/Joshua-Ashton/d9vk/files/3613633/Divinity2_d3d9_837.log)

- d3d9.log #836:
[Divinity2_d3d9_836.log](https://github.com/Joshua-Ashton/d9vk/files/3613645/Divinity2_d3d9_836.log)

- dxgi.log: None

### Issue
All in-game text is missing with the latest commit (#837), but it's working with the previous job (#836).

D9VK job #837
![divinity2_notext](https://user-images.githubusercontent.com/12013166/64920094-61cbc800-d7dd-11e9-8d68-11a265940a24.jpg)

D9VK job #836
![divinty2_text](https://user-images.githubusercontent.com/12013166/64920096-67c1a900-d7dd-11e9-8c3e-1840701eb89a.jpg)

**Comment by jrugia** [comment]
In a related note, this commit fixes Legend of Grimrock 2 and Race Driver GRID 1. I'll create separate reports if the fix for this game breaks the other 2 again.

**Comment by NerosTie** [comment]
![20190915173256_1](https://user-images.githubusercontent.com/4572452/64923901-eff47e00-d7de-11e9-84d9-39709ce1b717.jpg)

On my side, I don't have this issue with #837.

**Comment by SDN-Arkhen** [comment]
> On my side, I don't have this issue with #837.

Hmm, that's odd. I already try switching from those two commits few times and the result is just the same, all text is gone without any error. I'll try making a fresh new wine prefix then, to see if the problem is in my wine configuration or not.

I don't know if it's help, but I've made a debug log. I still can't get apitrace working on wine 4.15 though. 
[Divinity2_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3614357/Divinity2_d3d9.log)

**Comment by K0bin** [comment]
Please retest with master.

**Comment by SDN-Arkhen** [comment]
> Please retest with master.

I see the latest master have failed status and I don't know how myself before. So, I'll just wait for the next commit. In the meantime I'll try running this game on a new wine prefix first.

**Comment by SDN-Arkhen** [comment]
Testing with new wine prefix with only d3dx9 and d3dcompilers installed give the same result. I'll try with the latest master later when it successfully compiled.

**Comment by Joshua-Ashton** [comment]
Can you re-test with latest master? Should fix it.

**Comment by SDN-Arkhen** [comment]
Awesome! Yes, the latest master fix it. Thanks.
I'm closing this issue.
