### ISSUE TITLE
Regression at commit f1dfe727966f42d6e4a2aa3e6304a4817444f3a7.

### ISSUE THREAD

**Issue by l12436** [Joshua-Ashton/d9vk#376]
Commit f1dfe727966f42d6e4a2aa3e6304a4817444f3a7 cause skyrim main menu show like following.
![image](https://user-images.githubusercontent.com/2596649/64934997-e4f22a00-d880-11e9-8340-0b12a8bdc2a2.png)

Revert that commit will return to normal.
![image](https://user-images.githubusercontent.com/2596649/64934999-e91e4780-d880-11e9-9597-fb9b57a6a6fe.png)

**Comment by Joshua-Ashton** [comment]
Thanks for the clear report. Was looking for some regression testing for that change. I will fix this today.

**Comment by Joshua-Ashton** [comment]
hm, I was not able to replicate, might be related to the other language you are using however
