### ISSUE TITLE
Dungeon Siege II Broken World - Objects / Meshes wrong position.

### ISSUE THREAD

**Issue by dlshinobi** [Joshua-Ashton/d9vk#379]
### Software information
Dungeon Siege 2 Broken World

### System information
- GPU: nVidia GTX 960
- Driver: 435.27.02
- Wine version: 4.18
- DXVK version: #957 master (3deda2a0)

### Apitrace file(s)
https://drive.google.com/file/d/1LKBPM9euB56nVmqYpbYAplCpx77OFgGs/view?usp=sharing

### Log files
https://drive.google.com/file/d/1boUYmAV85Z4LsiHO7ZUPoJinIYYXQ76J/view?usp=sharing

---

Dungeon Siege II Broken World with d9vk renders all objects in the world (npc, rocks, grass, etc.) in wrong position. Moving main character or rotating camera all objects jumping all over the screen. Probably the problem is with calculation of transformations.
P.S. Wined3d renders everything fine except the performance is abysmal (30-40 fps) compared with d9vk (const 60 fps). 

Few shots and video below shows the problem better.

---

**Video example:**
https://drive.google.com/file/d/11oiS28cxbRDZcTDMEld2aVEOTbfAwC-G/view?usp=sharing

- Windows (d3d9):
![d3d9-screen-01](https://user-images.githubusercontent.com/7222444/65048704-38da3d00-d96d-11e9-8d11-73a7f0b704c5.jpeg)
![d3d9-screen-02](https://user-images.githubusercontent.com/7222444/65048715-3c6dc400-d96d-11e9-9072-d7734a0c25f0.jpeg)

- Wine (d9vk):
![d9vk-screen-01](https://user-images.githubusercontent.com/7222444/65048752-498ab300-d96d-11e9-92f5-d2b4d1fa1e1a.jpeg)
![d9vk-screen-02](https://user-images.githubusercontent.com/7222444/65048762-4c85a380-d96d-11e9-86ac-0852e65ea56f.jpeg)

**Comment by NerosTie** [comment]
![Screenshot_20200222_125941](https://user-images.githubusercontent.com/4572452/75091963-51c9c880-5573-11ea-8c45-a8581e15fcf6.png)

Well, the world is not broken anymore! It can be closed.

Tested with DXVK 1168.

**Comment by dlshinobi** [comment]
Yep, fixed in master.
