### ISSUE TITLE
Torchlight II → everything is too bright

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#380]
with d9vk:
![20190915214431_1](https://user-images.githubusercontent.com/4572452/65346819-eb183b80-dbdd-11e9-9c87-6870dd2fb278.jpg)

without d9vk:
![20190915214358_1](https://user-images.githubusercontent.com/4572452/65346828-f1a6b300-dbdd-11e9-995a-8a18685339eb.jpg)

### System information
- GPU: Nvidia GT 730M
- Driver: 435.21
- Wine version: Proton 4.11
- DXVK version: #850

### Apitrace file(s)
https://mega.nz/#!OzwRGALK!gdsSZTDLNLo4NuAd7xO3mh62XUpB6ffH_ruv2FZYpU4

### Log files
[steam-200710-d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3637114/steam-200710-d3d9.log)
[steam-200710-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3637115/steam-200710-d9vk.log)

**Comment by Joshua-Ashton** [comment]
Looks fine on the trace to me: 
![image](https://user-images.githubusercontent.com/21316711/65347297-a046f580-dbd6-11e9-841d-82deaa2a2a52.png)

Can you try replaying it yourself?

**Comment by Joshua-Ashton** [comment]
![image](https://user-images.githubusercontent.com/21316711/65347680-6aeed780-dbd7-11e9-8761-7c528271aa80.png)

Nvm, only happens on Nvidia

**Comment by NerosTie** [comment]
![Screenshot_20190920_194948](https://user-images.githubusercontent.com/4572452/65347698-d472e400-dbdf-11e9-98ae-0062e6fc2b58.png)

**Comment by Joshua-Ashton** [comment]
This was an Nvidia driver bug worked around with

https://github.com/Joshua-Ashton/d9vk/commit/4ab98e8babe239cce8aa3f2b728ce5767509d007
