### ISSUE TITLE
borderlands 2 crashes after traveling to another location

### ISSUE THREAD

**Issue by barfin** [Joshua-Ashton/d9vk#383]
borderlands 2 crashes after traveling to another location
only with d9vk when using wined3d it's fine

### Software information
Borderlands 2

### System information
- GPU: GTX 970
- Driver: 435.24.02
- Proton version: 4.11-5
- D9VK version: 0.21-rc-p

**Comment by telans** [comment]
https://github.com/Joshua-Ashton/d9vk/issues/170

https://github.com/doitsujin/dxvk/issues/1100

These?

**Comment by K0bin** [comment]
Please at least add logs.

**Comment by Joshua-Ashton** [comment]
Please test with https://git.froggi.es/joshua/d9vk/-/jobs/954

**Comment by barfin** [comment]
> Please test with https://git.froggi.es/joshua/d9vk/-/jobs/954

i did this ( i'm not sure if i did everything right )

barfin@linux-qhzf:~> WINEPREFIX=/mnt/332e336f-675d-46a3-98dc-194f1992e576/SteamLibrary/steamapps/compatdata/49520/pfx Downloads/build/d9vk-release/setup_dxvk.sh

and now it crashes at startup
[steam-49520.log](https://github.com/Joshua-Ashton/d9vk/files/3788506/steam-49520.log)

**Comment by Joshua-Ashton** [comment]
So I've played for about 45 minutes going to different places on max settings with the high resolution texture pack with the release in DXVK 1.5

Can anyone repro this bug there? (using DXVK 1.5's d3d9)
