### ISSUE TITLE
SpellForce: Platinum Edition → crash at launch

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#384]
When I launch the game, I have a black screen then it crashes.

### System information
- GPU: Nvidia GT 730M
- Driver: 435.21
- Wine version: Proton 4.11
- DXVK version: #852

### Apitrace file(s)

I can't apitrace the game. It just ignores the d3d9.dll, I think. Probably related to the issue.

### Log files
[steam-39540-d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3638614/steam-39540-d3d9.log)
[steam-39540-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3638615/steam-39540-d9vk.log)

**Comment by NerosTie** [comment]
It doesn't crash in windowed mode (use the command line parameter `-window`)

**Comment by K0bin** [comment]
Does eadde9dd10bf52ab5531413b46e58503813e21d3 help here too?

**Comment by NerosTie** [comment]
No, nothing has changed.

**Comment by NerosTie** [comment]
I can launch the game in windowed mode. The issue is something about fullscreen, I guess...

**Comment by NerosTie** [comment]
For a weird reason, I can launch the game with my external 16:10 monitor, but not with my other monitor with 16:9 ratio and not with the laptop's monitor alone.

Tested with DXVK v1317.

**Comment by NerosTie** [comment]
It doesn't crash with Proton-5.9-GE-3-ST. I don't know why, but it's not DXVK's fault.

**Comment by NerosTie** [comment]
Retested with Proton-5.9-GE-6-ST and Proton-tkg 5.18 and it crashes with both. Maybe my previous comment was wrong... I reopen it.

**Comment by NerosTie** [comment]
A solution has been found here: 

https://github.com/ValveSoftware/Proton/issues/686#issuecomment-715441869

**Comment by NerosTie** [comment]
Fixed with Proton 5.13-2 RC (I hope Wine will add this fix too)

https://github.com/ValveSoftware/Proton/issues/4360
