### ISSUE TITLE
Intrusion 2 → crash at launch

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#386]
I have a black square, then it crashes.

### System information
- GPU: Nvidia GT 730M
- Driver: 435.21
- Wine version: Proton 4.11
- DXVK version: #852

### Apitrace file(s)
The game doesn't want to be apitraced. I just have a 2o file and nothing more.

### Log files

[steam-214970-d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3638641/steam-214970-d3d9.log)
[steam-214970-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3638642/steam-214970-d9vk.log)

**Comment by Joshua-Ashton** [comment]
`75672.341:002f:0030:fixme:vulkan:X11DRV_vkCreateWin32SurfaceKHR Application requires child window rendering, which is not implemented yet!`

Use the WineVulkan patch for child window rendering.
