### ISSUE TITLE
World in Conflict → crash at launch: "update the drivers of your graphics card"

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#387]
When I launch the game, it crashes and I have this error:

![Screenshot_20190921_140115](https://user-images.githubusercontent.com/4572452/65374171-1440d680-dc87-11e9-96c2-2706d50a9582.png)

In english, it asks to update the driver for the GPU.

### System information
- GPU: Nvidia GT 730M
- Driver: 435.21
- Wine version: Proton 4.11
- DXVK version: #852: 

### Apitrace file(s)
https://mega.nz/#!jzgxwAhR!y2pcNm6B4u5xe2f2rzipWkAQKs4kKwL4oZkxihrz_1w

### Log files
[WorldInConflict-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3638729/WorldInConflict-d9vk.log)

**Comment by Berobad** [comment]
Isn't it the same bug as on windows were you just press cancel and the game loads?

**Comment by NerosTie** [comment]
Ho wow, I didn't even try that :man_facepalming: and yes, it works!
But I don't have this error without d9vk, so maybe something can be fixed somewhere?

**Comment by Joshua-Ashton** [comment]
I'm guessing this is a 32-bit game? If so, can you try this:
[d3d9.zip](https://github.com/Joshua-Ashton/d9vk/files/3663914/d3d9.zip)

**Comment by NerosTie** [comment]
Yes, it works :)
