### ISSUE TITLE
Halo: Combat Evolved → crash at launch: "you need to have DirectX 9.0b installed"

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#388]
When I launch the game, it crashes and I have this error:
![Screenshot_20190921_155216](https://user-images.githubusercontent.com/4572452/65374240-f162f200-dc87-11e9-9c99-ef4efabb8dad.png)

### System information
- GPU: Nvidia GT 730M
- Driver: 435.21
- Wine version: Proton 4.11
- DXVK version: #852

### Apitrace file(s)
Unfortunately the game doesn't want to be apitraced, I get the same error as above.

### Log files
[halo-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3638734/halo-d9vk.log)

**Comment by TheArchKnight** [comment]
This is really weird. I tried Halo CE with D9VK (i normally use Gallium Nine) and it worked at the first time, only with some artifacts, but at even it launch

**Comment by TheArchKnight** [comment]
Maybe proton is giving you trouble?

**Comment by NerosTie** [comment]
It's the same issue with Wine 4.16.
Maybe I should try with Halo Custom Edition.

**Comment by TheArchKnight** [comment]
It should be the same result. What distro are you using?

**Comment by NerosTie** [comment]
Arch, why?

**Comment by TheArchKnight** [comment]
> Arch, why?

Cuz you could have some necessary software not installed by default. Normally on a fresh installation of Arch it works

**Comment by TheArchKnight** [comment]
How did you installed the game?

**Comment by Joshua-Ashton** [comment]
Figured I should add, this works on Windows now.

If this still occurs for you it is another bug which is not mine.

**Comment by NerosTie** [comment]
Yes, it still occurs. No idea how to fix that :(

**Comment by NerosTie** [comment]
Tested with #949 and it works very well now 🥳
Thanks!
