### ISSUE TITLE
Halo 2 → glitches

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#389]
It's also an issue without d9vk. So maybe it's related to wine or wined3d. But maybe something can be done with Vulkan+d9vk?

with d9vk:
![Screenshot_20190921_160216](https://user-images.githubusercontent.com/4572452/65374430-08a2df00-dc8a-11e9-915b-84dcc67e2e79.png)
Better view:
https://imgur.com/WK8qV4s

### System information
- GPU: Nvidia GT 730M
- Driver: 435.21
- Wine version: Proton 4.11
- DXVK version: #852

### Apitrace file(s)
https://mega.nz/#!irpxlaSb!zzw99TP5EHwky0i0zwJGj2fVk_kopH7nGfEUerii454

### Log files
[halo2-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3638746/halo2-d9vk.log)

**Comment by TheArchKnight** [comment]
I used the master version from winetricks, it works just fine. Try to use that version

**Comment by NerosTie** [comment]
I have the last master (#859) and the glitches are still here.

**Comment by TheArchKnight** [comment]
> I have the last master (#859) and the glitches are still here.

That's weird. I can run into some maps, and even play at a decent performance. Other maps will crash.

**Comment by TheArchKnight** [comment]
Did you install mfc40, and mfc42?

**Comment by NerosTie** [comment]
Yes, both.

**Comment by TheArchKnight** [comment]
> Yes, both.

Have you tried using wine-staging instead of Proton?

**Comment by NerosTie** [comment]
With wine and wine-staging, it hangs on the first logo :/

**Comment by TheArchKnight** [comment]
> With wine and wine-staging, it hangs on the first logo :/ Ok, so i know what you have to do. Create another 32 bit prefix, install all the prerequisites, and copy and paste your Halo 2 installation into the new prefix. Then, just run it and it should be all good

**Comment by TheArchKnight** [comment]
> > With wine and wine-staging, it hangs on the first logo :/.

Ok, so i know what you have to do. Create another 32 bit prefix, install all the prerequisites, and copy and paste your Halo 2 installation into the new prefix. Then, just run it and it should be all good

**Comment by NerosTie** [comment]
Can you send me your wine prefix? It would be faster (for Halo 1 too if you can).

**Comment by TheArchKnight** [comment]
Yep, but only with the condition that you will play with me

**Comment by money123451** [comment]
try with the latest release 0.21 if it still has a issue it might be a nvidia issue since the game renders fine for me with proton 4.11 audio can be fixed with a 32 bit prefix and installing wmp9 (you can even do this with proton since stock wine hangs as startup it seem)

**Comment by NerosTie** [comment]
Already tested with 0.21 + proton 4.11. I have the same issue with my Intel GPU + native d3d9, but I can't test with d9vk unfortunately.

Maybe it's Nvidia, maybe not. I can't verify myself =/

I think it will be easier with the upcoming remastered bundle (you can switch to the non-remaster game)

**Comment by TheArchKnight** [comment]
I highly think it's an Nvidia issue. For me, using and AMD APU just renders fine

**Comment by money123451** [comment]
amd apu club also yap it renders fine here but crashes on arbiter missions

**Comment by money123451** [comment]
also can some of you Nvidia users or anyone with buggy graphics try dxvk.conf with
`d3d9.customVendorId = 1002`
`d3d9.customDeviceId = 687f`
`d3d9.customDeviceDesc = AMD RADV RAVEN`
which will lie to the game about you having a amd card in place of nvidia

**Comment by NerosTie** [comment]
It looks like it has no effect.
The log file if it can helps:

[halo2-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3673149/halo2-d9vk.log)

**Comment by money123451** [comment]
yap the custom options loaded it didn't fix the issue then  its not the game doing something stupid its a driver issue

**Comment by NerosTie** [comment]
Wow, you just solved a 10 years old issue! Thanks!
(but I will have to open a new one because it hangs when you enter in a zone)

**Comment by Joshua-Ashton** [comment]
Working on a fix for that right now, actually 😄

**Comment by NerosTie** [comment]
Can you ping me when the fix will be released? I want to play this game in 1080p for the first time :p

**Comment by Joshua-Ashton** [comment]
Oh that should already be in master...

**Comment by NerosTie** [comment]
It looks like the issue is still. After a certain amount of time, it freezes.

**Comment by Joshua-Ashton** [comment]
Log?
