### ISSUE TITLE
Tropico 4 - cascaded shadow maps corruption

### ISSUE THREAD

**Issue by aufkrawall** [Joshua-Ashton/d9vk#390]
The shadow maps show artifacts in shape of sharply disappearing shadows at some distances instead of switching to the next lower-res cascade (at least that's my cheap guess).

Screenshot:
![tropico](https://user-images.githubusercontent.com/13510490/65386137-eb2c4e80-dd37-11e9-93c9-d216cc2651c2.png)

### Software information
Tropico 4 Steam maxed out visuals

### System information
- GPU: RX 570 8GB
- Driver: radv-aco b738bf069172ba08a087735061570ade4415041a
- Wine version: Proton 4.11-5
- DXVK version: d9vk 515643f2c097068ee93faccbeacd59f6dda6d53a

### Apitrace file(s)
Created on Windows with D3D9:
https://drive.google.com/open?id=1KxM2le4QnC7_HYj2S5nKDNRtI4dpMNjd

### Log files
[Tropico4_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3639648/Tropico4_d3d9.log)
[Tropico4_dxgi.log](https://github.com/Joshua-Ashton/d9vk/files/3639650/Tropico4_dxgi.log)

As a side note: I've observed artifacts in Crysis 1 which look exactly the same.

**Comment by Joshua-Ashton** [comment]
Can this be re-tested?

**Comment by aufkrawall** [comment]
Fixed. :)
I suppose D9VK is now close to what everybody has hoped for (or already there), great job!
