### ISSUE TITLE
Full Spectrum Warrior: Ten Hammers → white glitch arround words + crash

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#392]
with d9vk:
![20190922164539_1](https://user-images.githubusercontent.com/4572452/65391556-e59c2c00-dd6a-11e9-8d00-84269a8e6171.jpg)

without d9vk:
![20190922165014_1](https://user-images.githubusercontent.com/4572452/65391562-ec2aa380-dd6a-11e9-81a9-8e7ca29f89cb.jpg)

Then it crashes if I launch a new game.

### System information
- GPU: Nvidia GT 730M
- Driver: 435.21
- Wine version: Proton 4.11
- DXVK version: #859

### Apitrace file(s)
https://mega.nz/#!qzgVzKoJ!xPju_-SzaZlShHT1I403yiubPDL6wI42n5B0fD0eDDU

### Log files
[steam-4530-d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3639985/steam-4530-d3d9.log)
[steam-4530-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3639986/steam-4530-d9vk.log)

**Comment by NerosTie** [comment]
Thanks it works, but it shouldn't be closed because it still crashes when I launch a new game.

**Comment by Joshua-Ashton** [comment]
Can you open another issue and provide a trace for that

**Comment by NerosTie** [comment]
Done!
