### ISSUE TITLE
Full Spectrum Warrior: Ten Hammers → crash when starting a new game

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#393]
Click on play → select difficulty → crash

### System information
- GPU: Nvidia GT 730M
- Driver: 435.21
- Wine version: Proton 4.11
- DXVK version: #859

### Apitrace file(s)
https://mega.nz/#!qzgVzKoJ!xPju_-SzaZlShHT1I403yiubPDL6wI42n5B0fD0eDDU

### Log files
[steam-4530-d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3639985/steam-4530-d3d9.log)
[steam-4530-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3639986/steam-4530-d9vk.log)

**Comment by Joshua-Ashton** [comment]
Can you try running with Large Address Aware?

**Comment by NerosTie** [comment]
Yes, it works with that.

**Comment by Joshua-Ashton** [comment]
Does it crash at all when running with that?

**Comment by NerosTie** [comment]
It doesn't crash at all with that. Tested for about 10min.

**Comment by NerosTie** [comment]
It's not an issue with d9vk when we need to add Large Address Aware?

**Comment by Joshua-Ashton** [comment]
There isn't really a solution other than that at the moment. We can always come back to this later. The issue is not unique to this game.

**Comment by NerosTie** [comment]
In this case, I should test with other games.
