### ISSUE TITLE
Witcher 2 doesn't start

### ISSUE THREAD

**Issue by shmerl** [Joshua-Ashton/d9vk#395]
Just tested latest d9vk master with The Witcher 2 in Wine, and strangely it fails to start with such errors:

```
info:  Required Vulkan extension VK_KHR_get_physical_device_properties2 not supported
info:  Required Vulkan extension VK_KHR_surface not supported
info:  Required Vulkan extension VK_KHR_win32_surface not supported
terminate called after throwing an instance of 'dxvk::DxvkError'
```
That's with Mesa 19.2.0 rc3, so I think those extensions should be supported. I have these installed: `libvulkan1:i386`, `mesa-vulkan-drivers:i386`.

**Comment by Joshua-Ashton** [comment]
You need an x32 vulkan loader.

**Comment by shmerl** [comment]
I have it installed as I said: `libvulkan1:i386`. Something else is off.

**Comment by Joshua-Ashton** [comment]
Yeah I deleted that comment already 🐸

This isn't a D9VK bug, but rather a setup issue.

I'm not too familiar with using Vulkan on Debian/Ubuntu so I'm not sure. Definately not on my end though.

**Comment by Joshua-Ashton** [comment]
Can you install ``vulkanutils:i386`` and see if 32-bit vkcube or vulkaninfo work?

**Comment by shmerl** [comment]
I just tested running TW1 with d9vk which is also 32-bit. It started fine, so 32-bit Vulkan in general is OK. But something got messed up with TW2 somehow.

**Comment by Joshua-Ashton** [comment]
Are you doing this in the same prefix?

**Comment by shmerl** [comment]
No, separate prefixes.

**Comment by shmerl** [comment]
For a test, I can try copying one to another, and see what's going to happen

**Comment by shmerl** [comment]
This is already interesting. I made a copy of TW1 prefix for a test, and also copied TW2 game directory in it. From that prefix, TW1 starts OK with d9vk. TW2 fails like before with same errors.

**Comment by Joshua-Ashton** [comment]
It's not x64 is it? 🐸

**Comment by shmerl** [comment]
Nope, it shouldn't be.

**Comment by Joshua-Ashton** [comment]
Are you using winelib builds btw?

**Comment by Joshua-Ashton** [comment]
Right, can you try using a normal mingw build?

https://git.froggi.es/joshua/d9vk/-/jobs

Just to rule that out.

**Comment by shmerl** [comment]
Let me try with 64-bit one, and then I'll try mingw build.

**Comment by shmerl** [comment]
With 64-bit prefix + winelib build, same errors as before. Trying now 64-bit prefix + mingw build.

**Comment by shmerl** [comment]
Same error with 64-bit + mingw build. Game is quite unlikely 64-bit though.  I'm going to try now 32-bit + mingw.

**Comment by shmerl** [comment]
Oh, I think I know what's going on. Let me check something.

**Comment by shmerl** [comment]
Yep, that was my misconfig. In the startup script it tried to use non existing Mesa. I managed to start it now, though it hangs on the loading screen (not the whole computer, just the game gets stuck). But that would be a separate bug if anything. Closing.
