### ISSUE TITLE
Darksiders II Deathinitive Edition : big perormance issue

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [Joshua-Ashton/d9vk#396]
The game runs fine, but the difference between running it with wined3d, and d9vk is big in favour of wined3d.

**With d9vk (14 fps!)**

![Screenshot from 2019-09-24 19-54-52](https://user-images.githubusercontent.com/29783425/65538330-6001b300-df07-11e9-863d-0935cd7a424a.png)

**With wined3d (25 fps, and it goes up to 50+ fps in closed areas)**

![Screenshot from 2019-09-24 19-56-29](https://user-images.githubusercontent.com/29783425/65538335-655efd80-df07-11e9-8875-1a3fc6bfa030.png)

### Software information
Darksiders II Deathinitive Edition, everything is maxed, and antialiasing is turned off.

### System information
- GPU: AMD HD 8750M
- Driver: Mesa (Obiaf PPA)
- Wine version: Wine-staging 4.16
- D9VK version: 0.21 - Lollihop

### Log files
- d3d9.log: [Darksiders2_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3648773/Darksiders2_d3d9.log)
- dxgi.log: [Darksiders2_dxgi.log](https://github.com/Joshua-Ashton/d9vk/files/3648774/Darksiders2_dxgi.log)

**Comment by K0bin** [comment]
Please add an apitrace.

**Comment by jrugia** [comment]
If it helps

I Tested the game under Nvidia (drivers 435.24.02) with D9VK 0.21. This issue is not present for me and it runs faster and smoother than WineD3D.

**Comment by Joshua-Ashton** [comment]
Unfortunately the issue is that you are playing on a GCN 1.0 APU, which is *not the fastest* and not *really* supported by AMDGPU and RADV anyway.

There's nothing I can really do about this -- sorry.

**Comment by ahmed-elsayed2017** [comment]
It is supported by RadonSI which is a part of MESA. It is a Laptop! I can't upgrade the external graphic card.
