### ISSUE TITLE
Can't determine git version

### ISSUE THREAD

**Issue by Kerrung** [Joshua-Ashton/d9vk#4]
### System information
- OS: Arch Linux
- D9VK version: 246c6cd

### Terminal output:
![screenshot from 2019-03-02 15-37-48](https://user-images.githubusercontent.com/36989404/53680722-2a923f80-3d01-11e9-9677-3de0cfb4d393.png)

**Comment by Joshua-Ashton** [comment]
And?

**Comment by Joshua-Ashton** [comment]
Going to close this as it seems like a non-issue.

I just haven't marked any tags yet.
