### ISSUE TITLE
FlatOut 2 - Entirely black but the game itself works

### ISSUE THREAD

**Issue by Medath** [Joshua-Ashton/d9vk#40]
The game loads absolutely fine but is entirely black from start to finish. Judging from the sound the entire game logic works as intended but absolutely nothing is displayed.

### Software information
FlatOut 2 on lowest settings (higher settings have the same symptoms)

### System information
- GPU: Radeon R9 290X
- Driver: amdgpu
- Wine version: 4.6 from (latest from the Arch repos)
- DXVK version: a262dcd

### Apitrace file(s)
- https://mega.nz/#!8XIhlapI!mM5nnm_SwankdjtnwWit8bAjZXRp8B6nlLoJyMXqp_Y

### Log files
- [d3dretrace_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3109259/d3dretrace_d3d9.log)

**Comment by Joshua-Ashton** [comment]
Flatout 2 uses SM1 which has some dumb ops I have not currently implemented

**Comment by ReaperOfSouls1909** [comment]
Same issue with medal of Honor modern warfare as i call it

**Comment by Joshua-Ashton** [comment]
Fixed with

https://github.com/Joshua-Ashton/d9vk/commit/8a5039a0b26544794537ab47799bdf1ee8054db8
