### ISSUE TITLE
Dll files not found at installation

### ISSUE THREAD

**Issue by arabcian** [Joshua-Ashton/d9vk#400]
When i issue WINEPREFIX=/home/cian/.wine/ ./setup_dxvk.sh install --without-dxgi  command
i get this

/home/cian/Desktop/d9vk-master/x32/d3d9.dll: File not found. Skipping.
/home/cian/Desktop/d9vk-master/x64/d3d9.dll: File not found. Skipping.
/home/cian/Desktop/d9vk-master/x32/d3d10.dll: File not found. Skipping.
/home/cian/Desktop/d9vk-master/x64/d3d10.dll: File not found. Skipping.
/home/cian/Desktop/d9vk-master/x32/d3d10_1.dll: File not found. Skipping.
/home/cian/Desktop/d9vk-master/x64/d3d10_1.dll: File not found. Skipping.
/home/cian/Desktop/d9vk-master/x32/d3d10core.dll: File not found. Skipping.
/home/cian/Desktop/d9vk-master/x64/d3d10core.dll: File not found. Skipping.
/home/cian/Desktop/d9vk-master/x32/d3d11.dll: File not found. Skipping.
/home/cian/Desktop/d9vk-master/x64/d3d11.dll: File not found. Skipping.

d9vk cannot set up correctly

**Comment by Joshua-Ashton** [comment]
Do those files exist?

**Comment by arabcian** [comment]
Im doing it using by a clone which i download from here. those files do not exist not even those x32 and x64 directories.

**Comment by Joshua-Ashton** [comment]
That's not how you install D9VK.

Use a release or follow the build instructions in the readme.
