### ISSUE TITLE
different cpu load with older game and much older game

### ISSUE THREAD

**Issue by andysendo** [Joshua-Ashton/d9vk#401]
the old game old Titan Quest - Immortal Throne,  released 2007, using d3dcompiler_47,d3dx9_27. play with wine+d9vk the cpu load larger than play with wine over 20%.

the old game Trine 2, released 2011, using d3dcompiler_47.dll d3dx9_38.dll. play with wine+d9vk the cpu load smaller than play with wine ~20%.

play with wine+d9vk two games works fine, but why Titan Quest - Immortal Throne cpu load much larger than plain wine? is about vulkan driver or d9vk?

intel i5-8300H  d9vk 0.21  mesa-vulkan-drivers 18.3.6-2  libvulkan1 1.1.97-2  wine4.14

Regards.

**Comment by Joshua-Ashton** [comment]
What framerates are you getting with these games in comparison?

**Comment by andysendo** [comment]
fps almost same both of wine+d9vk and wine.

Titan Quest - Immortal Throne: with vertical synchronization 50~60, no vsync 80~99.
Trine 2: no vsync 90~99

also tested Age of Empires II HD, Star Craft I windowed version, cpu load same with  Titan Quest.

**Comment by Joshua-Ashton** [comment]
This isn't a bug so I'm just going to close this.

If there are specific performance issues in certain games feel free to open issues for them individually and follow the template.
