### ISSUE TITLE
[regression] Glitches in some videos since #878

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#403]
Example: 

Sudeki:
![20191001170120_1](https://user-images.githubusercontent.com/4572452/65974369-23850880-e46d-11e9-8d30-e00f105a29b1.jpg)

Forgotten Realms:
![Screenshot_20191001_170253](https://user-images.githubusercontent.com/4572452/65974548-6515b380-e46d-11e9-8727-67a30d2274b0.png)

**Comment by K0bin** [comment]
I cant find build 878? https://git.froggi.es/joshua/d9vk/pipelines

**Comment by K0bin** [comment]
Of course it's the locking changes...

0f54e1923a8ee996987282791dcfe2dea72232cb

**Comment by NerosTie** [comment]
From "jobs" ;)

**Comment by NerosTie** [comment]
https://github.com/Joshua-Ashton/d9vk/issues/339
https://github.com/Joshua-Ashton/d9vk/issues/321

**Comment by Joshua-Ashton** [comment]
Do you know of any other games where this happens?

**Comment by NerosTie** [comment]
I'm trying random games but nothing yet =/

**Comment by Joshua-Ashton** [comment]
Does replaying the traces show the issue for you?

**Comment by NerosTie** [comment]
No, nothing on the trace.

I also sent a new trace to see a longer version of the first logo:
https://mega.nz/#!DqokXY7L!aVtisHkYOyMiHuJI8yEVYzPsrM9Y_RBbrIQJ-LinDxk

**Comment by Joshua-Ashton** [comment]
Closed by https://github.com/Joshua-Ashton/d9vk/commit/afd549ce2155092d447e8c0b13175476d64e6b8e
