### ISSUE TITLE
CS:GO still detects my GPU as NVIDIA

### ISSUE THREAD

**Issue by guixxx** [Joshua-Ashton/d9vk#404]
I'm not sure if I should post this here or in the Proton tracker, but in my (limited) understanding, the driver workarounds, such as NVAPI, are applied by DXVK/D9VK, right? If I'm wrong, feel free to close this anytime.

tl;dr: While the CS:GO window does open in Proton (all black, but still), the game instantly throws this error:

![image](https://user-images.githubusercontent.com/27077338/66066594-34db1d00-e520-11e9-807d-94e6e917129d.png)

And clicking "Ok" closes the game window.

### Software information
[Counter-Strike: Global Offensive](https://store.steampowered.com/app/730/CounterStrike_Global_Offensive/)

### System information
- GPU: NVIDIA GTX 660
- Driver: 435.21
- Wine version: Proton 4.11-6
- DXVK version: 0.21-rc-p (?)

**Comment by Joshua-Ashton** [comment]
D9VK doesn't actually spoof driver vendor, DXVK does however.

**Comment by guixxx** [comment]
Do you think I should post it there, then?

**Comment by Joshua-Ashton** [comment]
No
