### ISSUE TITLE
Medal of Honor: Pacific Assault → the world is a box

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#406]
with d9vk:
![Screenshot_20191002_232343](https://user-images.githubusercontent.com/4572452/66084911-13a21d00-e570-11e9-8b3a-b5d63095744c.png)

### System information
- GPU: Nvidia GT 730M
- Driver: 435.21
- Wine version: Proton 4.11
- DXVK version: #886

### Apitrace file(s)
https://mega.nz/#!jr4HjKgL!S71xsKJ01qJkzW1p9BxhX0Oigow4YDcytN8FIqysjRI

### Log files
[MedalOfHonorPacificAssault-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3683507/MedalOfHonorPacificAssault-d9vk.log)

**Comment by SDN-Arkhen** [comment]
There is also a regression in Need For Speed Carbon (demo) with job #886, I think its the same problem. But I'll wait for this to get fixed and see if its also affect nfs carbon.

**Comment by Joshua-Ashton** [comment]
Trace plays fine for me.

**Comment by NerosTie** [comment]
Fixed. 
Tested with #888
