### ISSUE TITLE
Need for Speed: Carbon → everything is black

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#407]
with d9vk:
![Screenshot_20191003_004009](https://user-images.githubusercontent.com/4572452/66088256-c11a2e00-e57a-11e9-8a24-2454dd3c5231.png)

### System information
- GPU: Nvidia GT 730M
- Driver: 435.21
- Wine version: Proton 4.11
- DXVK version: #886

### Apitrace file(s)
https://mega.nz/#!mqoFQCZJ!eH2IxGr0m__FRJawvfgh-uJbE-O2qiobKQIsrsy3uL4

### Log files
[nfs-carbon.log](https://github.com/Joshua-Ashton/d9vk/files/3683758/nfs-carbon.log)

**Comment by SDN-Arkhen** [comment]
I think it fixed with the latest job. Try it.

**Comment by Joshua-Ashton** [comment]
Trace plays fine for me.

**Comment by NerosTie** [comment]
Fixed.
Tested with #888
