### ISSUE TITLE
[Regression] Broken rendering on Need For Speed Carbon (demo)

### ISSUE THREAD

**Issue by SDN-Arkhen** [Joshua-Ashton/d9vk#408]
### Software information
Need For Speed Carbon demo version (also affect Street Racing Syndicate) at default settings.

### System information
- GPU: GTX 1050 Ti
- Driver: 435.21
- Wine version: 4.16-Staging
- DXVK version: Job #893

### Apitrace file(s)
- Can't render apitrace on wine 4.16. But you can download NFS Carbon demo anywhere.

### Log files
- d3d9.log: 
[nfsc_demo_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3692869/nfsc_demo_d3d9.log)

- dxgi.log: None

### Issue
Need For Speed Carbon (tested on demo version) 3D rendering is broken with job #893. It's perfectly fine with job #891. This broken rendering is also happen in Street Racing Syndicate.
![Screenshot_2019-10-05_11-19-40](https://user-images.githubusercontent.com/12013166/66249940-94763a00-e765-11e9-92ca-44b8dc61c489.png)
![Screenshot_2019-10-05_11-19-55](https://user-images.githubusercontent.com/12013166/66249942-96d89400-e765-11e9-931b-8691dde4e859.png)

**Comment by Joshua-Ashton** [comment]
Please re-test.

**Comment by NerosTie** [comment]
It looks fine now.
![Screenshot_20191005_172300](https://user-images.githubusercontent.com/4572452/66257068-ec786500-e794-11e9-828d-5376ebcbbe57.png)
![Screenshot_20191005_172331](https://user-images.githubusercontent.com/4572452/66257071-f0a48280-e794-11e9-9719-240e0582354c.png)

**Comment by SDN-Arkhen** [comment]
Thanks.
