### ISSUE TITLE
Witcher 2 rendering issue

### ISSUE THREAD

**Issue by John-Gee** [Joshua-Ashton/d9vk#409]
Hello,

The game works globally well, but when drinking a cat potion which allows seeing in the dark. Then some artifacts appear here and there. These appear whether using d9vk with llvm or aco, but do not appear when using wined3d. This could mean the issue is in radv of course, if so please tell me and I'll open the bug over there.

### Software information
The Witcher 2 from GoG, Ultra settings minus Ubersampling

### System information
- GPU: 580X
- Driver: radv-aco from commit d0ed7ce952c
- Wine version: wine-tkg-staging-fsync-vkd3d-faudio-git 4.17.r0.g9fe5cabf-206
- DXVK version: master at this time so commit adc2d84

### Screenshot
![witcher2](https://user-images.githubusercontent.com/1646210/66250334-35c5a780-e6f6-11e9-9c46-40e9491cff8e.png)

### Apitrace file(s)
- https://mega.nz/#!xxxwEKgQ!euU21zZnhLHTlJTmvOjid3pUpCPJ82QeEATRZsopzvY
As the issue does not constantly appear, this is a trace done with D9VK. If that is a problem I can do another one with wined3d.

### Log files
- d3d9.log: https://gist.github.com/John-Gee/5a78192b66e0987acad719ebfe151b8a
I suspect the line "GetShaderModule: Bytecode does not match shader stage" is relevant. Am I missing one d3d winetrick? I have these d3dx9_36 d3dx9_39 d3dx9 d3dcompiler_47 d3dxof d3dcompiler_43 d3dcompiler, not sure which is useful. Here's the winecfg for this profile in case it helps

![winecfg1](https://user-images.githubusercontent.com/1646210/66250380-d6b46280-e6f6-11e9-8abc-150875be1848.png)
![winecfg2](https://user-images.githubusercontent.com/1646210/66250381-d6b46280-e6f6-11e9-91cd-3ce520c6fa52.png)
![winecfg3](https://user-images.githubusercontent.com/1646210/66250382-d6b46280-e6f6-11e9-887b-2be552e5d3f5.png)

Thank you!

**Comment by Joshua-Ashton** [comment]
Can you verify if this is an issue on latest master with this?

Although looking at the images, it looks like a render hazard, but I'd like to be sure.

If that doesn't work please try adding
`d3d9.hasHazards = True` to your dxvk.conf

**Comment by John-Gee** [comment]
The latest commit did not help but hasHazards fixes the issue. I used the conf on top of latest master.

The line "err:   GetShaderModule: Bytecode does not match shader stage" still appears so I guess it was unrelated.

Should I keep this conf and close this bug or is there more needed than this workaround?

Thank you!

**Comment by Joshua-Ashton** [comment]
Thats a known game bug

**Comment by John-Gee** [comment]
Oh I see.

**Comment by Joshua-Ashton** [comment]
Can you try with this branch https://github.com/Joshua-Ashton/d9vk/tree/d3d9-new-hazards

**Comment by John-Gee** [comment]
That looked good to me.
I tried with the conf and the value set to False and without it and it's all fine.

Thank you!
