### ISSUE TITLE
Guild Wars 2 texture bug

### ISSUE THREAD

**Issue by logan001** [Joshua-Ashton/d9vk#410]
There are some parallel white lines on the water in the background and triangle texture of the sky has different color/contrast with a7fa5e5

![gw460](https://user-images.githubusercontent.com/6472378/66251008-45270e00-e753-11e9-87e7-e484ff154370.jpg)
![gw459](https://user-images.githubusercontent.com/6472378/66251009-45bfa480-e753-11e9-8ad7-962086779b12.jpg)

This does not happen with f945fb0

### Software information
Guild Wars 2

### System information
- GPU: 970
- Driver: 435.24.02
- Wine version:  4.1x (i'm in windows right now)
- DXVK version:  a7fa5e5

### Apitrace file(s)
- [here](https://drive.google.com/open?id=0B21AKedF-JpVb2lHdEtLSWY4a2c)

**Comment by Joshua-Ashton** [comment]
Please re-test.

**Comment by logan001** [comment]
yeap, everything is back to normal
