### ISSUE TITLE
Splinter Cell: Double Agent → hang when I want to launch a new game

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#412]
Click on new game, then choose the difficulty, then it hangs before the loading page.

### Software information
Name of the game, settings used etc.

### System information
- GPU: Nvidia GT 730M
- Driver: 435.21
- Wine version: Proton 4.11
- DXVK version: #891

### Apitrace file(s)
https://mega.nz/#!6yo3CICJ!DL9Dz7i2RRavPNWlnfBUJiuR2ftft-_sins9g3TmDe4

### Log files
[steam-13580-d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3693388/steam-13580-d3d9.log)
[steam-13580-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3693389/steam-13580-d9vk.log)

**Comment by Joshua-Ashton** [comment]
Requires weird d3d9 predication

https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/setp-comp---ps

**Comment by Joshua-Ashton** [comment]
Can you try now?

**Comment by NerosTie** [comment]
With #895, the issue is still here.

**Comment by Joshua-Ashton** [comment]
Does playing the trace back also hang for you?

**Comment by Joshua-Ashton** [comment]
> 149032.109:0055:0056:fixme:d3dx:D3DXCreateTextureFromFileInMemoryEx Generation of mipmaps for compressed pixel formats is not implemented yet.
> 149032.111:0055:0056:fixme:d3dx:D3DXCreateTextureFromFileInMemoryEx Generation of mipmaps for compressed pixel formats is not implemented yet.

Please also use native D3D9X

**Comment by NerosTie** [comment]
> Does playing the trace back also hang for you?

No, everything is ok.

> Please also use native D3D9X

It's weird, it should have been native d3d9... But I reinstalled it and the issue is still here.

New log:
[steam-13580-d9vk-2.log](https://github.com/Joshua-Ashton/d9vk/files/3694880/steam-13580-d9vk-2.log)

**Comment by NerosTie** [comment]
It doesn't hang anymore 🥳
