### ISSUE TITLE
Halo 2 → broken background when you configure your profile

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#413]
with d9vk:
![Screenshot_20191006_022651](https://user-images.githubusercontent.com/4572452/66262474-325b1a80-e7e1-11e9-84e4-6621f65e55b9.png)

without d9vk:
![Screenshot_20191006_022616](https://user-images.githubusercontent.com/4572452/66262476-371fce80-e7e1-11e9-97d9-4cca56c14db2.png)

### System information
- GPU: Nvidia GT 730M
- Driver: 435.21
- Wine version: Proton 4.11
- DXVK version: #894

### Apitrace file(s)
https://mega.nz/#!S2oTDKwI!ehkZCErens75VqWKav_sSSI__XairItq8G6XqtQmIUM

### Log files
[halo2-option.log](https://github.com/Joshua-Ashton/d9vk/files/3693828/halo2-option.log)

**Comment by Joshua-Ashton** [comment]
StretchRect from 1 sample -> 2 samples

**Comment by money123451** [comment]
works for me just fine for me I blame novideo same with the other issue about crashing
![Screenshot_20191007_121513](https://user-images.githubusercontent.com/12605368/66329243-ba463f00-e91d-11e9-9278-1de65dd7c91b.png)

**Comment by Joshua-Ashton** [comment]
Well, it's still a spec violation what is happening now, and I should fix it.

**Comment by Joshua-Ashton** [comment]
Please try with https://git.froggi.es/joshua/d9vk/-/jobs/934

**Comment by NerosTie** [comment]
Fixed! 🥳
