### ISSUE TITLE
Halo 2 → hangs after a certain amount of time

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#414]
Play for a few minutes then it will hang.

### System information
- GPU: Nvidia GT 730M
- Driver: 435.21
- Wine version: Proton 4.11
- DXVK version: #894

### Apitrace file(s)
https://mega.nz/#!qzwU1AZB!MOCRRQXeBVvhJiu-AYw8Uyg58S5PVvRtTruL6O2SmuA

### Log files
[halo2-lutis.txt](https://github.com/Joshua-Ashton/d9vk/files/3694892/halo2-lutis.txt)

**Comment by Joshua-Ashton** [comment]
Please try with https://git.froggi.es/joshua/d9vk/-/jobs/934

**Comment by NerosTie** [comment]
The issue is still here =/

**Comment by NerosTie** [comment]
It's not about time actually. It hangs in a specific room.

Here:
![Screenshot_20191018_103411](https://user-images.githubusercontent.com/4572452/67079116-e3bf6000-f192-11e9-993a-47b0dccb4dbf.png)

**Comment by K0bin** [comment]
Can you run the game with validation layers and write stdout to a file. Then after it hangs, check that file.

**Comment by NerosTie** [comment]
Can you tell me how to do that please?

**Comment by K0bin** [comment]
First you make sure you have the Vulkan validation layers installed.
To use them you need to set the following environment variable: VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation

I think you cando that in lutris. Then it should be the same file you already posted.

If that doesnt work try using Wine directly:
`VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation wine halo2.exe > halo2validation.txt`

**Comment by NerosTie** [comment]
[halo2_vklayer.log](https://github.com/Joshua-Ashton/d9vk/files/3744448/halo2_vklayer.log)

Is that ok?

**Comment by K0bin** [comment]
Yup, that looks useful. Thank you.

`UNASSIGNED-CoreValidation-Shader-PushConstantOutOfRange(ERROR / SPEC): msgNum: 0 - Push constant range covering variable starting at offset 40 not declared in layout`

`VUID-VkImageBlit-srcOffset-00244(ERROR / SPEC): msgNum: 0 - vkCmdBlitImage(): region [0] srcOffset[].y values (-47, 60) exceed srcSubresource height extent (1080). The Vulkan spec states: srcOffset[0].y and srcOffset[1].y must both be greater than or equal to 0 and less than or equal to the source image subresource height (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkImageBlit-srcOffset-00244)`

`VUID-vkCmdBlitImage-pRegions-00215(ERROR / SPEC): msgNum: 0 - vkCmdBlitImage(): region [0] source image blit region exceeds image dimensions. The Vulkan spec states: The source region specified by each element of pRegions must be a region that is contained within srcImage (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdBlitImage-pRegions-00215)
`

**Comment by money123451** [comment]
can you retry with the latest master since on windows with a amd gpu I no longer seem to get random crashes.

**Comment by NerosTie** [comment]
Nope, the issue is still here.

**Comment by NerosTie** [comment]
Just noticed a difference between 2 Nvidia drivers:

With Nvidia Vulkan dev 435.27.03 with Vulkan 1.1.126:
- textures are not flickering
- it hangs

With Nvidia 435.21 with Vulkan 1.1.109:
- textures are flickering
- it doesn't hang

**Comment by K0bin** [comment]
Those issues you found earlier still exist. Fixing them will hopefully also fix the hangs.

**Comment by NerosTie** [comment]
Fixed with nvidia-beta 440.31 / vulkan 1.1.119

**Comment by K0bin** [comment]
@Joshua-Ashton You should fix the validation errors anyway.

**Comment by NerosTie** [comment]
Regression? 

I hangs at the exact the same place as before. Tested with DXVK 1082.

**Comment by mcKFAQ** [comment]
well not the best solution, i've been using d9vk version 0.21 on lutris no problem playing 2 games of halo 2's multiplayer.

**Comment by NerosTie** [comment]
Probably because this bug doesn't occur on multiplayer maps.

**Comment by mcKFAQ** [comment]
> Probably because this bug doesn't occur on multiplayer maps.

I've got halo 2 hangups in multiplayer seems to happen at random in newer versions of d9vk

**Comment by NerosTie** [comment]
Tested 3 times with DXVK 1137 and it doesn't crash anymore :)
