### ISSUE TITLE
Crysis → broken shadows

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#416]
with d9vk:
https://imgur.com/7wfDdXY

### System information
- GPU: Nvidia GT 730M
- Driver: 435.21
- Wine version: Proton 4.11
- DXVK version: #894

### Apitrace file(s)
https://mega.nz/#!azwUTQyC!Qan44Knwk9K-zO-UEVu5BxUTH8z_Dbeha1vqExMZWyo

### Log files
[steam-17300-d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3694895/steam-17300-d3d9.log)
[steam-17300-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3694896/steam-17300-d9vk.log)

**Comment by Joshua-Ashton** [comment]
For me...

![image](https://user-images.githubusercontent.com/21316711/66360728-01f7b580-e974-11e9-83f2-9a25eaf0322e.png)

Does this happen for you too?
I kinda like those stars tho...

**Comment by NerosTie** [comment]
No, I don't have those stars. Can you screenshot your parameters?

**Comment by Joshua-Ashton** [comment]
It's an AMDVLK bug

**Comment by DaRkL3AD3R** [comment]
I can't even get Crysis to run with D9VK it just crashes on initialization.

**Comment by Joshua-Ashton** [comment]
On Linux/Wine/...

**Comment by NerosTie** [comment]
@DaRkL3AD3R You need the 64 bits binaries : https://pcgamingwiki.com/wiki/Crysis#64-bit_binaries

Anyway, it's not related to shadows...

**Comment by NerosTie** [comment]
Well, I think you broke something:

![Screenshot_20191129_001150](https://user-images.githubusercontent.com/4572452/69834788-f1a9db80-123c-11ea-9f22-50a46c7fdb93.png)

**Comment by Joshua-Ashton** [comment]
What does it look like if you retrace the trace you provided?

**Comment by Joshua-Ashton** [comment]
While you're at it, can you try with 4caa51ff3cf0ac2da64c7d69855346b8031630d1 (before the fix)?

**Comment by NerosTie** [comment]
With #997, it's exactly like 0.30. I'll test to retrace it in a minute.

**Comment by Joshua-Ashton** [comment]
Ne bother with that then if thats the case...

**Comment by Joshua-Ashton** [comment]
[d3d9.zip](https://github.com/Joshua-Ashton/d9vk/files/3903211/d3d9.zip)

For my sanity, can you try this? Same as master (with some unrelated crap on-top) but compiled with MSVC.

**Comment by NerosTie** [comment]
The bug is gone with this one :)

**Comment by Joshua-Ashton** [comment]
Try with the latest https://git.froggi.es/joshua/d9vk/-/jobs?

**Comment by NerosTie** [comment]
Definitely fixed :-)

![Screenshot_20191129_012419](https://user-images.githubusercontent.com/4572452/69836147-17d47900-1247-11ea-86e5-d47c7959918b.png)

**Comment by Joshua-Ashton** [comment]
Yeah, nothing changed. Must be a fluke
