### ISSUE TITLE
C&C 3 Tiberium Wars - rendering issues

### ISSUE THREAD

**Issue by Yardanico** [Joshua-Ashton/d9vk#418]
There are graphical glitches in C&C 3 Tiberium Wars, most units are partially or fully invisible, also static props on the map flicker (as well as shadows), also the MCV doesn't fully render, example of how it should look (taken from Google images):
![image](https://user-images.githubusercontent.com/21169548/66491762-f8796500-eabb-11e9-907b-2333f0386fb0.png)

### Software information
Command & Conquer 3 Tiberium Wars v1.9 (latest released version)

### System information
- GPU: RX 570
- Driver: Mesa 19.3.0-devel (git-030e67fac3)
- Wine version: wine-4.17.r8.ga246130f ( TkG Staging Esync Fsync )
- D9VK version: d9vk-mingw-git-0.21.r1243.bb8ce4288-1

### Apitrace file(s)
- https://drive.google.com/open?id=1If9MJJInLoPdH6aEYA59MO1GipYw2p0-

### Log files
- https://drive.google.com/open?id=1lEiJpfI6NaF6N6uc8WSWUXCRwYmLpyOT

**Comment by Riesi** [comment]
Did you record the trace with d9vk enabled? Because it renders the same with wined3d and d9vk on my end. If you recorded the trace with d9vk, please record one with wined3d instead.

Also how did you get the game working in wine? It refuses to start for me.... (maybe due to the fact that I own the combo version with KW included...)

**Comment by Yardanico** [comment]
@Riesi I don't know, it just works for me in Wine. And I think I recorded the trace without d9vk, since I explicitly disabled it in winecfg and ran setup_d9vk uninstall before trying the game.
And yeah, I know that it renders the same with wined3d and d9vk, but I hope d9vk can fix this

**Comment by Joshua-Ashton** [comment]
Can you try with `d3d9.allowLockFlagReadonly = False`?

**Comment by Yardanico** [comment]
@Joshua-Ashton It's still the same, d9vk log - https://paste.debian.net/1105614
Wine itself also outputs a lot of stuff like this in terminal (although I don't know if it's related):
```
002a:fixme:d3dx:d3dx_effect_SetRawValue iface 1C3BC570, parameter 1C3BD2A8, data 00C05DB8, byte_offset 0, bytes 1024 stub!
002a:fixme:d3dx:d3dx_effect_SetRawValue iface 1C3BC570, parameter 1C3BD2A8, data 00C05DB8, byte_offset 0, bytes 1024 stub!
002a:fixme:d3dx:d3dx_effect_SetRawValue iface 1C3BC570, parameter 1C3BD2A8, data 00C05DB8, byte_offset 0, bytes 672 stub!
002a:fixme:d3dx:d3dx_effect_SetRawValue iface 1488A1E8, parameter 14893C98, data 00C05DB8, byte_offset 0, bytes 128 stub!
002a:fixme:d3dx:d3dx_effect_SetRawValue iface 1C2C5AC8, parameter 1C2C6EC0, data 00C05DB8, byte_offset 0, bytes 608 stub!
002a:fixme:d3dx:d3dx_effect_SetRawValue iface 1488A1E8, parameter 14893C98, data 00C05DB8, byte_offset 0, bytes 96 stub!
002a:fixme:d3dx:d3dx_effect_SetRawValue iface 1C2C5AC8, parameter 1C2C6EC0, data 00C05DB8, byte_offset 0, bytes 64 stub!
002a:fixme:d3dx:d3dx_effect_SetRawValue iface 1C2C5AC8, parameter 1C2C6EC0, data 00C05DB8, byte_offset 0, bytes 128 stub!
002a:fixme:d3dx:d3dx_effect_SetRawValue iface 1488A1E8, parameter 14893C98, data 00C05DB8, byte_offset 0, bytes 96 stub!
002a:fixme:d3dx:d3dx_effect_SetRawValue iface 17A10668, parameter 17A11510, data 00C05DB8, byte_offset 0, bytes 160 stub!
002a:fixme:d3dx:d3dx_effect_SetRawValue iface 17A10668, parameter 17A11510, data 00C05DB8, byte_offset 0, bytes 160 stub!
002a:fixme:d3dx:d3dx_effect_SetRawValue iface 1C3BC570, parameter 1C3BD2A8, data 00C05DB8, byte_offset 0, bytes 1024 stub!
```

**Comment by Yardanico** [comment]
Ah, nvm, I think this can be closed since it works with native d3dx9 installed via "winetricks d3dx9"
![image](https://user-images.githubusercontent.com/21169548/66519684-722b4600-eaf0-11e9-9da6-52875d8265d8.png)
