### ISSUE TITLE
Oddworld: New 'n' Tasty → hangs after a certain amount of time

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#419]
Launch a new game then wait not even a minute.

### System information
- GPU: Nvidia GT 730M
- Driver: 435.27.00
- Wine version: Proton 4.11
- DXVK version: #906

### Apitrace file(s)
From the previous issue:
https://mega.nz/#!jqIyBapC!tOLVmuK9Mw5BmTPHx-lMBupuRWd9HSZLg_Vt5HD3q0A

### Log files
[steam-314660-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3708898/steam-314660-d9vk.log)

**Comment by Joshua-Ashton** [comment]
Can you reproduce the hang on the trace you sent?

**Comment by NerosTie** [comment]
No issue with the trace =/

**Comment by Joshua-Ashton** [comment]
Would you able to do a longer trace, lets say a few minutes of gameplay -- and play it back and see if it hangs?

**Comment by NerosTie** [comment]
Well, it's also an issue with WineD3D... So, can it be fixed with d9vk, or it's something else?

**Comment by Joshua-Ashton** [comment]
Can you test it on Windows? If it doesn't happen there with D9VK then it isn't my bug.

**Comment by NerosTie** [comment]
> Can you test it on Windows?

Not here. And in the other hand, nobody tests the windows version on linux because there is a native port (which works well but the cutscenes are jerky).

Are you sure nothing can be done with d9vk? (if not, feel free to close this issue)

**Comment by Joshua-Ashton** [comment]
Do you mean you don't have Windows or it doesn't happen on Windows.

**Comment by NerosTie** [comment]
I don't have a computer with Windows at home.

**Comment by CartoonFan** [comment]
If it's helpful, I have the game on Windows and can probably test it when I have time.

**Comment by NerosTie** [comment]
Fixed by adding `PROTON_NO_ESYNC=1` as a parameter.

Also notice there is a black bar at the bottom:
![20191010100747_1](https://user-images.githubusercontent.com/4572452/66556089-ecd77e00-eb4f-11e9-8bb7-cdc8bf3dfd0e.jpg)

And switching between fullscreen and windowed makes it disappear.

It the exact same behavior as https://github.com/Joshua-Ashton/d9vk/issues/337

Could be a bug with Unity 4 games.
