### ISSUE TITLE
Q - Can d9vk support SweetFX in the future?

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [Joshua-Ashton/d9vk#42]
My dx9 game collections runs well with d9vk, but there is no options for antialiasing in these games, so I really need to use SweetFX to inject SMAA or FXAA, so is there any chance that d9vk will support SweetFX in the future or is that impossible?

**Comment by Joshua-Ashton** [comment]
I don't see any reason why it shouldn't work. I'll try it after I've finished my compiler rewrite

**Comment by ahmed-elsayed2017** [comment]
OMG! Thanks man. That is really appreciated.

**Comment by NightSprinter** [comment]
Not trying to necro this thread, but I can confidently say that neither SweetFX or ReShade work well at best with D9VK.  Some games like The King of Fighters 98 Ultimate Match either give an all-black game screen (not counting the borders), or give strange artifacts.
![Screenshot_20190630_171137-1](https://user-images.githubusercontent.com/52381903/60402649-624eae00-9b60-11e9-87c2-f8790a1569d2.png)

Some commercial D3D9EX games like Undertale and Mushihimesama, and free ones like Make a Good Mega Man Level 2 just flat out crash when using it with D9VK.  If you need someone to test things with these once the compiler rewrite's done, I'll be glad to.

**Comment by Joshua-Ashton** [comment]
Oh that rewrite happened ages ago.

Can you send me an apitrace of things you find? Cheers.

**Comment by NightSprinter** [comment]
Ah, how would you suggest I do so?  Am a bit new to this, and if needed, I can compile from your github and install.

**Comment by Joshua-Ashton** [comment]
https://tracehub.froggi.es has instructions

**Comment by NightSprinter** [comment]
I think I managed to get it..  Though both Mushihimesama and Make a Good Mega Man Level 1 Remastered crashes unless I disable everything regarding D3D9 (and I have a log of that).  Undertale just gives a repeated D3D9ex stub message unless D3D9 is set to built-in.  KoF98UM still has the issue shown in the earlier screencap, but CRT effects (same with all DX9 games ReShade worked with in D9VK) resorts to a black screen for many shaders.  Still working on how to get apitrace working with proton.  I'll try to provide more apitraces once I've read up on how to actually do so in Proton.

[MaGMML1-Crash.txt](https://github.com/Joshua-Ashton/d9vk/files/3343916/MaGMML1-Crash.txt)


[Undertale.trace.tar.gz](https://github.com/Joshua-Ashton/d9vk/files/3343976/Undertale.trace.tar.gz)

**Comment by Joshua-Ashton** [comment]
Reshade works fine with D9VK so I'm gonna assume SweetFX does and close this.

The KoF98UM issue was a different thing entirely and was fixed ages ago.
