### ISSUE TITLE
Crysis → missing texture of bullet impact on objects

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#420]
with d9vk:
![20191009203357_1](https://user-images.githubusercontent.com/4572452/66520690-ef9f8800-eae9-11e9-9a11-ca46d34f18d8.jpg)

### System information
- GPU: Nvidia GT 730M
- Driver: 435.27.00
- Wine version: Proton 4.11
- DXVK version: #906

### Apitrace file(s)
https://mega.nz/#!yzIjEIYT!Zn6DSap_PkZtojWzE3Ntp-K_Vw_crxuNhlDnuG1ZP3E

### Log files
[steam-17300-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3709443/steam-17300-d9vk.log)

**Comment by Joshua-Ashton** [comment]
Can you try with #905 and #908?

**Comment by NerosTie** [comment]
There is no difference with 905 or 908.

**Comment by Joshua-Ashton** [comment]
Border color

**Comment by NerosTie** [comment]
I want to add that this issue doesn't exist with d3d10/dxvk.

Tested with DXVK 1.6.

**Comment by misyltoad** [comment]
I know, waiting for border color ext

**Comment by NerosTie** [comment]
>VK_EXT_custom_border_color is now used to support for arbitrary sampler border colors, which fixes issues in many Direct3D 9 games including Crysis and Halo 2 Vista

Is this issue related to this line in the changelog of 1.7?

Because I have the driver Nvidia Vulkan 440.66.14 which is supposed to have `VK_EXT_custom_border_color` but the issue is still here:

![Screenshot_20200519_145420](https://user-images.githubusercontent.com/4572452/82329116-1f4c3200-99e1-11ea-86aa-c34d92d7b60a.png)

**Comment by K0bin** [comment]
![grafik](https://user-images.githubusercontent.com/1131720/90188969-a892bb00-ddbc-11ea-8d6b-4c4dda137df3.png)

Works for me.

**Comment by NerosTie** [comment]
![Screenshot_20200813_233457](https://user-images.githubusercontent.com/4572452/90189570-b72da200-ddbd-11ea-9d0d-ebacbc61b79f.png)

Not for me...

**Comment by K0bin** [comment]
Might be a driver issue. Or your WineVulkan doesnt support the extension.
Do the logs (with log level: info) mention the VK_EXT_custom_border_color extension?

**Comment by NerosTie** [comment]
```
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 0
info:    customBorderColorWithoutFormat         : 0
```

I guess not. It's with Proton 5.0-9 and Nvidia 450.57

**Comment by NerosTie** [comment]
With Proton 5.9-GE-4-ST:
```
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 1
info:    customBorderColorWithoutFormat         : 1
```

![Screenshot_20200814_000011](https://user-images.githubusercontent.com/4572452/90191701-a4b56780-ddc1-11ea-8145-01047599fbc3.png)

Clearly, `VK_EXT_custom_border_color extension` is not yet supported with the official release of Proton (5.0-9) at this moment.

I think I can close this issue! :)
