### ISSUE TITLE
[Nvidia?] Artifact on DreadOut demo

### ISSUE THREAD

**Issue by SDN-Arkhen** [Joshua-Ashton/d9vk#421]
### Software information
DreadOut demo version at all settings.

### System information
- GPU: GTX 1050 Ti
- Driver: 435.21
- Wine version: 4.17 Staging
- DXVK version: Job #905

### Apitrace file(s)
https://www.dropbox.com/s/kh9c6fyeengg95v/dreadoutdemo.7z?dl=0

### Log files
- d3d9.log: 
[DreadOutDemo_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3709751/DreadOutDemo_d3d9.log)
- dxgi.log: 
[DreadOutDemo_dxgi.log](https://github.com/Joshua-Ashton/d9vk/files/3709752/DreadOutDemo_dxgi.log)

### Issue
As you can see below there are grey lines on the screen. They are slimmer and more transparent at low setting. It was fine with old d9vk version. I don't know which job causing this artifact, because I just found it yesterday. But it happen most likely after version 0.20. 

DreadOut was made with early version of Unity, so I suspect it may affect other games with the same engine and rendering method as well. Although I haven't verified that behavior myself, someone might want to check their games.

![Screenshot_2019-10-09_18-02-47](https://user-images.githubusercontent.com/12013166/66526901-5fcaff80-eb24-11e9-8c50-783bdb77cad7.png)

**Comment by Joshua-Ashton** [comment]
Would you be able to bisect to the exact commit?

Builds are here: https://git.froggi.es/joshua/d9vk/-/jobs

**Comment by SDN-Arkhen** [comment]
I did try all the way to d9vk 0.11 and the problem persist. But I've found out what may causing the problem. It's nVidia 435 driver (vulkan v.1.1.109). I downgraded my driver to nVidia 430 (vulkan v.1.1.99) and the game works as it should.

PS: One little problem, the game is always in windowed mode with the latest d9vk.

**Comment by Joshua-Ashton** [comment]
Can you try with https://github.com/Joshua-Ashton/d9vk/tree/d3d9-new-hazards

**Comment by SDN-Arkhen** [comment]
Great! That one fix the problem. Thanks.
I hope that can get in to the master builds.
