### ISSUE TITLE
Manhunt

### ISSUE THREAD

**Issue by ByCybernetik** [Joshua-Ashton/d9vk#422]
In the beginning, the game works well, but then
- Main menu is not displayed, black screen
- Special effects don't work
- No HUD displayed
- UI invisible
- A black square is displayed around the player on the road

![20191010122042_1](https://user-images.githubusercontent.com/45942960/66566836-9ded1100-eb6e-11e9-86ee-b7d975fc99dc.jpg)
Was so

![20191010122217_1](https://user-images.githubusercontent.com/45942960/66566852-a8a7a600-eb6e-11e9-90b9-9e1de19eb41c.jpg)
Became so

### Software information
Manhunt, high setting

### System information
- GPU: Radeon RX 590
- Driver: Mesa 19.3.0 dev
- Wine version: Proton 4.11-7
- DXVK version: d3d8to9 1.9.2 + D9VK Master 09.10.19 

### Apitrace file(s)
- https://drive.google.com/open?id=1WqNOl0y_WDkUjQAnZyjg7YKhZQNUTqhX

### Log files
- [manhunt_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3712003/manhunt_d3d9.log)

**Comment by ByCybernetik** [comment]
Now works, truth in some places not work noise effect

**Comment by Joshua-Ashton** [comment]
Please show me what you mean

**Comment by ByCybernetik** [comment]
For example, no noise effects are displayed at this location
![20191018115543_1](https://user-images.githubusercontent.com/45942960/67088042-d6af6a80-f1ac-11e9-9fd5-43e055f83178.jpg)
Here are displayed
![20191018115551_1](https://user-images.githubusercontent.com/45942960/67088418-c51a9280-f1ad-11e9-8862-822a5a329177.jpg)
log
[manhunt_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3743518/manhunt_d3d9.log)
apitrace
https://drive.google.com/open?id=1chQxvCKVZABSOCbD8QuAKLgzgnSnBOU7

**Comment by Joshua-Ashton** [comment]
Your trace is shared privately.

**Comment by ByCybernetik** [comment]
yes

**Comment by ByCybernetik** [comment]
https://drive.google.com/file/d/1chQxvCKVZABSOCbD8QuAKLgzgnSnBOU7/view?usp=sharing

**Comment by ByCybernetik** [comment]
Is trace now available?

**Comment by Joshua-Ashton** [comment]
Should be fixed now.

**Comment by ByCybernetik** [comment]
It works now

**Comment by ByCybernetik** [comment]
There was a problem with the windows in the car.

**Comment by ByCybernetik** [comment]
![20191021025006_1](https://user-images.githubusercontent.com/45942960/67168472-923eed00-f3ad-11e9-9725-0cb92028de13.jpg)

**Comment by ByCybernetik** [comment]
Through gallium nine are displayed normally.

**Comment by Joshua-Ashton** [comment]
Is that in the trace? If not can you make a new one thanks

**Comment by ByCybernetik** [comment]
It's in the new trace

**Comment by Joshua-Ashton** [comment]
![image](https://user-images.githubusercontent.com/21316711/67168788-703e6e00-f39f-11e9-814c-8a4b03ee5d9b.png)

![image](https://user-images.githubusercontent.com/21316711/67168789-72083180-f39f-11e9-9746-203cadb79891.png)

The cars I can see seem to render fine here?
I am not sure I see the car you took the picture in the trace though.

**Comment by ByCybernetik** [comment]
I haven’t uploaded this trace yet.

**Comment by Joshua-Ashton** [comment]
Oh, right

**Comment by ByCybernetik** [comment]
Trace ready.
https://drive.google.com/file/d/11G_1LUn3xzV2l2iLCxIz-DqdciAFNVmL/view?usp=sharing

**Comment by Joshua-Ashton** [comment]
Was this trace recorded with D9VK?

**Comment by ByCybernetik** [comment]
Trace done in Gallium Nine.

**Comment by Joshua-Ashton** [comment]
Issue occurs in native D3D9 too. I think it not being red may be a Gallium bug?

Can you test the game + the trace you made on native D3D9?

**Comment by ByCybernetik** [comment]
Tested with D3D Native, WineD3D, dgVoodoo, a bug is present.

**Comment by ByCybernetik** [comment]
In gallium nine, windows are displayed normally
![Без имени](https://user-images.githubusercontent.com/45942960/67205706-efbc5380-f418-11e9-8ad4-83bec03993bd.jpg)

**Comment by ByCybernetik** [comment]
If you reproduce the trace through gallium nine, the bug will not be visible.

**Comment by ByCybernetik** [comment]
Strange, reproduced the trace, d3d native and d9vk through gallium nine, windows are fine.

**Comment by ByCybernetik** [comment]
D3D Native trace
https://drive.google.com/file/d/1EtPMNKtXhzqgz_AuewyuMW-IVK3LSOhq/view?usp=sharing
