### ISSUE TITLE
Alan Wake - green flash

### ISSUE THREAD

**Issue by ByCybernetik** [Joshua-Ashton/d9vk#424]
A green flash appears before playing back movies.
![Снимок экрана_2019-10-19_18-59-57](https://user-images.githubusercontent.com/45942960/67148035-66cfdb80-f2a3-11e9-98d9-1b248e26c06e.jpg)
![Снимок экрана_2019-10-19_19-04-00](https://user-images.githubusercontent.com/45942960/67148042-6df6e980-f2a3-11e9-9025-49b0c82fd413.jpg)

### Software information
Alan Wake, High settings.

### System information
- GPU: Radeon RX 590
- Driver: RADV 19.2.99
- Wine version: Proton 4.11-7
- DXVK version: Master 19.10.19 

### Apitrace file(s)
https://drive.google.com/file/d/1vAYcQI_nXzEH5xSnXBBvY5OYCbHgFGo2/view?usp=sharing

**Comment by Joshua-Ashton** [comment]
This issue is baked into the trace and happens when playing back with Windows' Native D3D9 too - does it happen when you play the game with with WineD3D?

If so, I'd be fairly confident in saying that it's not my bug and it's some other dependency the game replies on.

**Comment by ByCybernetik** [comment]
I tested this game on D3D Native, dgVoodoo+DXVK, Gallium Nine, WineD3D, I did not find any green flashes.

**Comment by Joshua-Ashton** [comment]
Was the trace made with D9VK?

**Comment by ByCybernetik** [comment]
D3D Native

**Comment by ByCybernetik** [comment]
I noticed that the trace shows this problem even on other wrappers.

**Comment by Joshua-Ashton** [comment]
Does this DLL change the color at all?

[d3d9.zip](https://github.com/Joshua-Ashton/d9vk/files/3747087/d3d9.zip)

**Comment by ByCybernetik** [comment]
Yes, the color is pink

**Comment by Joshua-Ashton** [comment]
Can you let me know if either of these DLLs resolve your issues?

[d3d9_yuy2.zip](https://github.com/Joshua-Ashton/d9vk/files/3747149/d3d9_yuy2.zip)

[d3d9_uyvy.zip](https://github.com/Joshua-Ashton/d9vk/files/3747150/d3d9_uyvy.zip)

**Comment by ByCybernetik** [comment]
None of these libraries solved the problem.

**Comment by Joshua-Ashton** [comment]
What colours though?

**Comment by ByCybernetik** [comment]
Green

**Comment by misyltoad** [comment]
Can you re-rest the flicker on DXVK master? I think it should be fixed now.

**Comment by ByCybernetik** [comment]
Great. The green flashes disappeared.
