### ISSUE TITLE
Need for Speed: Carbon → Autosculpt not working

### ISSUE THREAD

**Issue by hazelnot** [Joshua-Ashton/d9vk#426]
In Need for Speed: Carbon, attempting to use Autosculpt only makes the glowing outline change, not the model itself. 

A [possibly-related issue](https://bugs.winehq.org/show_bug.cgi?id=47880) was present in Wine pre-4.17, in which the geometry of the part would become corrupted with the message `005f:err:d3d:wined3d_debug_callback 0x21c778: "GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.".`

#### D9VK off
![image](https://i.imgur.com/ONUJ1U3.png)

#### D9VK on
![image](https://i.imgur.com/l6nRc2r.png)

### Software information
Need for Speed: Carbon, maxed out, using AGThirteen's widescreen mod (although the issue happens regardless of the mod being present).

### System information
- GPU: NVIDIA GTX 1080
- Driver: 435.21
- Wine version: 4.17
- D9VK version: 0.22

### Apitrace file(s)
https://mega.nz/#!UyYCRYDT!rsoCwrK_P_oAsu5bbRe7Xq31Y2Sb1sDdwNrVxZcWAro

**Comment by NerosTie** [comment]
Can you try with Wine 4.18?

There is something about that:
`47880 Need for Speed: Carbon - Autosculpt causes geometry corruption and GL_INVALID_OPERATION error`

https://www.winehq.org/announce/4.18

**Comment by hazelnot** [comment]
Oh, the *original* issue got fixed with 4.17, but the D9VK one persists.

**Comment by Joshua-Ashton** [comment]
Log?

**Comment by hazelnot** [comment]
I don't actually know how to get that

**Comment by NerosTie** [comment]
[NFSC_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3771776/NFSC_d3d9.log)
Is that ok?

**Comment by Joshua-Ashton** [comment]
Hello! Can this be re-tested on the game?
Changes have been made since which I think should resolve this issue, but I cannot test it myself as it is unreproducable on the trace.

Cheers!

**Comment by NerosTie** [comment]
Still here:

![Screenshot_20191202_162959](https://user-images.githubusercontent.com/4572452/69972066-37a6be00-1521-11ea-9a3a-9625de314ef6.png)

**Comment by Joshua-Ashton** [comment]
Can you try with this?

[d3d9.zip](https://github.com/Joshua-Ashton/d9vk/files/3912620/d3d9.zip)

**Comment by NerosTie** [comment]
It fixes the issue :)

![Screenshot_20191202_190548](https://user-images.githubusercontent.com/4572452/69983361-cd007d00-1536-11ea-84db-8c821ac4a6e5.png)

**Comment by Joshua-Ashton** [comment]
Nice. I'll do some more native testing to verify stuff here and hopefully push to master soon.
