### ISSUE TITLE
[Feature Request] Allow forcing MSAA

### ISSUE THREAD

**Issue by TRPB** [Joshua-Ashton/d9vk#43]
Several older games do not allow setting MSAA in the in-game options. It would be nice if there was a D9VK_MSAA=8 option which forced the sample count to 8x.

**Comment by skeevy420** [comment]
If you have an AMD based GPU, there is an environment variable to control the MSAA level and to enable EQAA.  A game or program has to use MSAA for these to work.  All the values and names are from a tech manual describing AMD's MSAA modes for DX9/10/11.

## MSAA>EQAA Modes
#No MSAA
#export EQAA=0,0,0

#2x MSAA 
#export EQAA=2,2,2

#2f4x EQAA
#export EQAA=4,2,2

#4x MSAA
export EQAA=4,4,4

#2f8x EQAA
#export EQAA=8,2,2

#4f8x EQAA
#export EQAA=8,4,4

#4f16x EQAA
#export EQAA=16,4,4

#8x MSAA
#export EQAA=8,8,8

#8f16x EQAA
#export EQAA=16,8,8

**Comment by Joshua-Ashton** [comment]
This'd be really cool, but this isn't possible without app profiles per-game.

You can force it on the swapchain or only regular RTs that aren't lockable/textures but then you also have to do that for depth stencils which could be re-used all over for a texture or a regular RT which breaks this.

Maybe try some DSR or something similar.
