### ISSUE TITLE
Max Payne 2

### ISSUE THREAD

**Issue by ByCybernetik** [Joshua-Ashton/d9vk#430]
1. Windows are not transparent
D3D Native
![20191022120634_1](https://user-images.githubusercontent.com/45942960/67273175-a0346100-f4c6-11e9-880a-6c211103bbe6.jpg)
D9VK
![20191022120336_1](https://user-images.githubusercontent.com/45942960/67273222-b2ae9a80-f4c6-11e9-832f-380762f6c430.jpg)

2. Mirror is not displayed
D3D Native
![20191022120622_1](https://user-images.githubusercontent.com/45942960/67273370-f99c9000-f4c6-11e9-9379-033c1da99b73.jpg)
D9VK
![20191022120329_1](https://user-images.githubusercontent.com/45942960/67273410-0a4d0600-f4c7-11e9-9423-c465fa7c2279.jpg)

### Software information
Max Payne, high settings.

### System information
- GPU: Radeon RX 590
- Driver: RADV 19.2.99
- Wine version: Proton 4.11-7
- DXVK version: d3d8to9 1.9.2 + D9VK Master 22.10.19 

### Apitrace file(s)
D3D Native
https://drive.google.com/file/d/1FtdEx-s2BP9mthIltlTA_t7rYYTFk7Om/view?usp=sharing

**Comment by CartoonFan** [comment]
I was going to create a bug for this game too, but I'm not sure if my problems are on the D3D8 side...I couldn't get a trace at all with just d3d9.dll. My issues are largely with the floor/wall textures: Last I checked, everything was white and changed when the character moved.

![20191020-221451](https://user-images.githubusercontent.com/29664894/67274956-68053200-f476-11e9-8fd1-c2f8ffa3b062.png)


GPU: Nvidia GeForce GTX 960
Driver: 435.27.0

Native Windows trace:
 https://drive.google.com/file/d/1ZIXHG1PTQO_aVSx8stDTLmsP_7oN7y9g/view?usp=sharing

D3D9 Log:
[maxpayne2_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3754814/maxpayne2_d3d9.log)

**Comment by NerosTie** [comment]
I don't understand, Max Payne 2 is a Directx 8 game, no?

**Comment by NerosTie** [comment]
Sorry, but I see nowhere that Max Payne 2 is a DirectX 9 game.

https://www.pcgamingwiki.com/wiki/Max_Payne_2:_The_Fall_of_Max_Payne#API

I really don't know how do you run this game in d3d9 mode...

**Comment by ByCybernetik** [comment]
Through the wrapper d3d8to9.

**Comment by CartoonFan** [comment]
> Sorry, but I see nowhere that Max Payne 2 is a DirectX 9 game.
> 
> https://www.pcgamingwiki.com/wiki/Max_Payne_2:_The_Fall_of_Max_Payne#API
> 
> I really don't know how do you run this game in d3d9 mode...

@NerosTie I agree, but the game is also producing d3d9 logs for me that are not 0kb. Maybe there are small d3d9 assets or portions of code? I don't know at all how these things work, but it looks like D9VK is reacting to something there, no? I've heard of, but haven't tried d3d8to9. I'll see if that helps my problems.
