### ISSUE TITLE
Bayonetta graphical artifacts

### ISSUE THREAD

**Issue by Vthyarilops** [Joshua-Ashton/d9vk#431]
Bayonetta displays strange graphical glitches with D9VK, WINED3D doesn't have this issue. Basically some colors will displays as multicolored glitched sections, mostly on gold items. 

### Software information

Bayonetta steam - Max settings, 1680x1050 @ 60hz

### System information
- GPU: AMD RX580 (Polaris)
- Driver: Mesa 19.3.0 devel 
- Wine version: Proton 4.11-7

With D9VK

![460790_screenshots_20191022143935_1](https://user-images.githubusercontent.com/32111041/67320310-0bd4f900-f4dc-11e9-8551-23d0cd6467e8.jpg)

With WineD3D

![460790_screenshots_20191022144606_1](https://user-images.githubusercontent.com/32111041/67320368-2018f600-f4dc-11e9-8ce4-288bfc1b6400.jpg)

I was unsure of how to make a trace, sorry

**Comment by Joshua-Ashton** [comment]
Can't fix it without a trace.

**Comment by Vthyarilops** [comment]
This is the first time I made a trace so I hope I did it right, but I had to do it with D9VK enabled (and it made the game run really slow which I guess is probably normal), with WineD3D the game crashed at start trying to make a trace.

Here is the trace: https://mega.nz/#!orxHEABB!5HNULSdhtdtWsQRZv6DvE6cbEEG2A3beg9GazThMVX8

**Comment by Vthyarilops** [comment]
Fixed in the newest master, closing.
