### ISSUE TITLE
Not able to work with Antialising 16x

### ISSUE THREAD

**Issue by vinifmor** [Joshua-Ashton/d9vk#432]
Hi,

I just want to report that it seems D9VK is currently not able to work with **Antialising 16x** in some of my games ( **Ultra Street Fighter IV** / **Street Fighter x Tekken** ). With the default WIneD3D compiler the option is displayed ( picture below ). The game performance with D9VK is outstanding ( it doubles the framerate ). Thank you for this great software.

### System information
- GPU: GTX 970
- Driver: Nvidia 435.21
- Wine version: Proton 4.11-7
- D9VK version: 0.22

![45760_20191022233932_1](https://user-images.githubusercontent.com/4312414/67353190-672cd880-f528-11e9-9d10-a96c3f38a062.png)
[ Antialising option using default WIneD3D compiler ]

**Comment by Joshua-Ashton** [comment]
Your graphics card does not support it. WineD3D exposing that is a bug.
