### ISSUE TITLE
Dead space is too bright

### ISSUE THREAD

**Issue by monterrr** [Joshua-Ashton/d9vk#434]
### Software information 
Dead Space is too bright and washed.

### System information
- GPU: Nvidia 1080 ti
- Driver: 430.40
- Wine version: Proton 4.11-7
- DXVK version: D9VK 0.22

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:

**Comment by K0bin** [comment]
No it's not. It looks exactly like it does on Windows.
