### ISSUE TITLE
Castlevania - Lords of Shadow 2 → some shadows are not rendered well

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#435]
with d9vk:
![20191023223023_1](https://user-images.githubusercontent.com/4572452/67484434-6c913c80-f668-11e9-808f-1945364136f0.jpg)

in action:
https://imgur.com/7kZ1yOG

### System information
- GPU: Nvidia GT 730M
- Driver: 435.27.01
- Wine version: Proton 4.11
- DXVK version: #949

### Apitrace file(s)
https://mega.nz/#!q6phAABb!tQm-vWmeocmIr3fuf8NSrtJlmrB-NW5M7hq-7K0JF-k

### Log files
[steam-239250-d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3767407/steam-239250-d3d9.log)
[steam-239250-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3767408/steam-239250-d9vk.log)

**Comment by DanMan** [comment]
That might actually be the depth of field, which is still completely broken with this game.

**Comment by DanMan** [comment]
I don't have that issue over here. Shadows seem to work fine on Ubuntu 18.04, Kernel 5.3, GTX 970 w/ 440.44 driver, Proton 4.11-11.

**Comment by NerosTie** [comment]
It looks like it fixed with DXVK 1.5.1.
