### ISSUE TITLE
Battlefield 2 crash

### ISSUE THREAD

**Issue by 10010101001** [Joshua-Ashton/d9vk#436]
I have all vulkan libs installed. vulkancube and vulkaninfo works, Urban Terror, Quake and Quake 3 all work with vulkan enabled (native linux x64s).

`info:  Game: BF2.exe
info:  DXVK: d9vk-0.22-kerokero
warn:  OpenVR: Failed to locate module
info:  Required Vulkan extension VK_KHR_get_physical_device_properties2 not supported
info:  Required Vulkan extension VK_KHR_surface not supported
info:  Required Vulkan extension VK_KHR_win32_surface not supported
terminate called after throwing an instance of 'dxvk::DxvkError'

abnormal program termination`

**Comment by K0bin** [comment]
> I have all vulkan libs installed. vulkancube and vulkaninfo works, Urban Terror, Quake and Quake 3 all work with vulkan enabled (native linux x64s).

You're missing 32bit Vulkan drivers.
