### ISSUE TITLE
Guild Wars 2 – graphics pipelines generation completely stalls the render process

### ISSUE THREAD

**Issue by n1trux** [Joshua-Ashton/d9vk#437]
With 0.22, I got low FPS when generating the graphics pipelines.

On 0.30 however, the FPS drop to literally zero. Maybe the generation takes longer for some reason?

Idk how to diagnose this other than that I saw a regression from 0.22→0.30. Appreciate all hints.

**Comment by tannisroot** [comment]
Can you try bisecting?
If you don't know how, join the VKx (or Lutris) server and I will help you with that.

**Comment by Joshua-Ashton** [comment]
Can this be re-tested on `master`?

**Comment by n1trux** [comment]
I'll test this ASAP – excuse my silence, I have a lot of other work with higher priorities atm.

GW2 is free to play btw if any of you wants to test it themselves.

**Comment by n1trux** [comment]
couldn't compile current master as described in #473, but managed to compile 7126fd47e.

Sadly I get `EE ../src/gallium/drivers/radeonsi/si_state_shaders.c:2109 si_build_shader_variant - Failed to build shader variant (type=1)` currently.

**Comment by n1trux** [comment]
OK I could also compile 6a0113887 and GW2 doesn't crash. The shader generation process doesn't completely stall the render process anymore, but it's still worse then in 0.22. I'll try uploading a video with enabled graphs soon™.

**Comment by n1trux** [comment]
nevermind, I don't care if you fix this.
