### ISSUE TITLE
Vampire The Masquerade - Bloodlines

### ISSUE THREAD

**Issue by ByCybernetik** [Joshua-Ashton/d9vk#438]
The game runs fine through D9VK on Windows, but only bink videos are displayed on Linux, and then a black screen.

### Software information
Vampire The Masquerade - Bloodlines, high settings.

### System information
- GPU: Radeon RX 590
- Driver:RADV 19.2.99
- Wine version: Proton 4.11-7
- DXVK version: Master 29.10.19

### Apitrace file(s)
D3D Native
https://drive.google.com/file/d/1DzDkdkqNliCsxpQGmiOE9HpWNzkn5tx3/view?usp=sharing

### Log files
[vampire_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3783907/vampire_d3d9.log)

**Comment by Joshua-Ashton** [comment]
Please ensure you're using native d3dx9 and d3dcompilers.

**Comment by ByCybernetik** [comment]
The game uses only D3D9.

**Comment by ByCybernetik** [comment]
The game works well in WineD3D and Gallium Nine.

**Comment by Joshua-Ashton** [comment]
Please test with https://git.froggi.es/joshua/d9vk/-/jobs/954

**Comment by ByCybernetik** [comment]
But this version has the ability to reproduce trace.

**Comment by ByCybernetik** [comment]
Patch did not work without msvcrt.dll and dbghelp.dll.

**Comment by Joshua-Ashton** [comment]
I mean to say that I can't even get it working on Windows... heh I'll try on Linux/Proton later today.

**Comment by ByCybernetik** [comment]
The game stopped launching after removing the '-game Unofficial_Patch' launch line, restoring the launch line or disabling Steam Overlay solves the problem.

**Comment by ByCybernetik** [comment]
After new commits, the game stopped launching on both Windows and Linux.

**Comment by ByCybernetik** [comment]
I managed to run the game on Linux using the options 
d3d9.deferSurfaceCreation = True
d3d9.maxAvailableMemory = 536870912

**Comment by ByCybernetik** [comment]
True, in some places the game slows down.
