### ISSUE TITLE
Secret Files: Tunguska → it crashes after the intro and before the main menu

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#439]
When it crashes, there is this error message:

![Screenshot_20191029_175411](https://user-images.githubusercontent.com/4572452/67789942-23c8f180-fa75-11e9-8625-852d08f3498f.png)

### System information
- GPU: Nvidia GT 730M
- Driver: 435.27.01
- Wine version: Proton 4.11
- DXVK version: #949

### Apitrace file(s)
https://mega.nz/#!nm5XxYbB!qI56F02y0ZkdZTL0YJGwMrM7eITEwArTxaysFDsrscQ

### Log files
[steam-40330-d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3784766/steam-40330-d3d9.log)
[steam-40330-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3784767/steam-40330-d9vk.log)

**Comment by Joshua-Ashton** [comment]
Can you try with this?

[d3d9.zip](https://github.com/Joshua-Ashton/d9vk/files/3829779/d3d9.zip)

**Comment by NerosTie** [comment]
It has no effect, unfortunately.

**Comment by Joshua-Ashton** [comment]
Hm, that is peculiar then, as that fixes the only issues/differences in the trace.

**Comment by NerosTie** [comment]
Maybe there is an other issue?

**Comment by Joshua-Ashton** [comment]
Idea: Would you be able to apitrace it with that dll also?

**Comment by NerosTie** [comment]
https://mega.nz/#!LnwGTSaZ!BbHrWpeQDEJJFzdP2rH3tZHS81PeF5rCNVC2hA0V4LE

**Comment by Joshua-Ashton** [comment]
Thanks! I'll take a look in just one moment.

**Comment by NerosTie** [comment]
I want to add that if you disable the option "Software Cursor" ([pic](https://images.pcgamingwiki.com/e/ee/Secret_Files_Tunguska_-_configuration_tool_settings.png)), the game hangs when you launch it. It doesn't happen with wined3d.

**Comment by Mephistople** [comment]
Not sure if anyone has tested this game in a while, but seems to be mostly working now.
Manage to reach the main menu after the intro, and is able to play normally in-game.
Only issue left seems to be when you disable  "software cursor" option you talked about @NerosTie.
Once disabled I'm able to reach the main menu, but then the cursor won't appear and I can't proceed.

![Menu](https://user-images.githubusercontent.com/53997310/116788073-34598e00-aa97-11eb-8371-14d5e8a907f5.png)
![Gameplay](https://user-images.githubusercontent.com/53997310/116788106-5226f300-aa97-11eb-96db-2403748e23a4.png)

### **System information**

- GPU: GeForce RTX 2080 Ti
- Driver: 460.73.01
- Wine Version: 6.7 TKG
- DXVK version: commit 4a4b966

**Comment by NerosTie** [comment]
I still have the same issue with "GDIFont.cpp"...

@Mephistople how did you solve this?

**Comment by NerosTie** [comment]
The issue is fixed with Proton Experimental 2021/05/21 but still present with Proton 6.3-4.

I'll wait the next update of Proton to close this issue.

**Comment by NerosTie** [comment]
With Proton 6.3-5-rc1 + DXVK 1.9.0, everything is working now.
