### ISSUE TITLE
X-Men Origins Wolverine

### ISSUE THREAD

**Issue by legluondunet** [Joshua-Ashton/d9vk#44]
Hello,

on X-Men Origins Wolverine, the main menu miss light with d9vk.

without d9vk (wine 4.6 staging)
![Capture d’écran de 2019-04-26 21-39-16](https://user-images.githubusercontent.com/325405/56832515-87772580-686c-11e9-9f4b-0a246e4a1939.jpg)

with d9vk (wine 4.6 staging)
![Capture d’écran de 2019-04-26 21-38-31](https://user-images.githubusercontent.com/325405/56832531-8c3bd980-686c-11e9-83ca-3419826e6fab.jpg)

d3d9.log
[Wolverine_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3122780/Wolverine_d3d9.log)

Config: Ubuntu 19.04 Disco Dingo 64 bits - NVIDIA GeForce GTX 770 - Nvidia drivers 418.56 - 1920x1080 - Processor Intel i5-3570 3,4 Ghz - 16 Go RAM

Do you need apitrace?

**Comment by mrdeathjr28** [comment]
> Hello,
> 
> on X-Men Origins Wolverine, the main menu miss light with d9vk.
> 
> without d9vk
> ![Capture d’écran de 2019-04-26 21-39-16](https://user-images.githubusercontent.com/325405/56832515-87772580-686c-11e9-9f4b-0a246e4a1939.jpg)
> 
> with d9vk
> ![Capture d’écran de 2019-04-26 21-38-31](https://user-images.githubusercontent.com/325405/56832531-8c3bd980-686c-11e9-83ca-3419826e6fab.jpg)
> 
> d3d9.log
> [Wolverine_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3122780/Wolverine_d3d9.log)
> 
> Config: Ubuntu 19.04 Disco Dingo 64 bits - NVIDIA GeForce GTX 770 - Nvidia drivers 418.56 - 1920x1080 - Processor Intel i5-3570 3,4 Ghz - 16 Go RAM
> 
> Do you need apitrace?

Rare in my case menu light works ok

**Comment by arzardk** [comment]
https://github.com/doitsujin/dxvk/issues/1011#issuecomment-482781793
Maybe that will help.

**Comment by legluondunet** [comment]
@arzardk The issue you referred to is about the directx11 mode of this game, not the directx9. The screen capture I posted here came from the directx9 version.

**Comment by mrdeathjr28** [comment]
> @arzardk The issue you referred to is about the directx10 mode of this game, not the directx9. The screen capture I posted here came from the directx9 mode.
> @mrdeathjr28 did you install some dll or program (nvidia? directx?)? What is your GPU model?

Hi this is my system specs used in test

System Specs Used in Test

Nvidia Drivers 418.52.03 (run package from nvidia drivers homepage)

Xubuntu 18.04 x64 - Kernel 4.17.12 generic (ubuntu mainline) -

CPUFreq: Performance

CPU: Core i3 8350K Tri-Core (Coffelake 14nm) 5.0Ghz + Zalman CNPS 10x Performa+

MEMORY: 8GB DDR4 2400mhz (4x2) Mushkin (dual channel: 37.5 gb/s)

GPU: Gigabyte Nvidia Geforce GTX 1050 OC (GP107 14nm: 640 Shaders / 40 TMUS / 32 ROPS) Windforce 2GB DDR5 7000Mhz 128Bit (110Gb/s)

MAINBOARD: ASUS Z370-P

**Comment by legluondunet** [comment]
I reinstall today the game without modify anything, no directx, no dll, nothing else than install the game and launch it with Dd9vk enable.
I obtained this result (d9vk on):
![Capture d’écran de 2019-05-02 08-50-29](https://user-images.githubusercontent.com/325405/57059946-cddae300-6cb7-11e9-9846-ec32b771a236.jpg)
Compare it to the first screen capture of this discussion (d9vk off).

Config: 
Ubuntu 19.04
Wine tkg-4.6
d9vk d9vk-master.98a24c890803333359efc45c747361728d8d4859 01/05/2019 revision 365

**Comment by legluondunet** [comment]
Hello,
I tested the d9vk #455 master 24938a0c and the game seems to run as it should now.

![Capture d’écran de 2019-05-17 23-52-44](https://user-images.githubusercontent.com/325405/57958445-2210d480-7900-11e9-8142-782dcaabca8e.jpg)

![Capture d’écran de 2019-05-18 00-08-13](https://user-images.githubusercontent.com/325405/57958762-31dce880-7901-11e9-8964-76d428c5b76e.jpg)

Very nice work, thanks.
