### ISSUE TITLE
Lens flares aren't rendered in GTA San Andreas

### ISSUE THREAD

**Issue by tannisroot** [Joshua-Ashton/d9vk#441]
D9VK:
![Screenshot from 2019-10-28 04-05-10](https://user-images.githubusercontent.com/10602045/67997368-f478d700-fc64-11e9-919c-dff478bf17b7.png)
WineD3D (Native DX9 with Nvidia GT9800 looks identical):
![Screenshot from 2019-10-28 04-01-42](https://user-images.githubusercontent.com/10602045/67997371-f93d8b00-fc64-11e9-86dc-660be737a464.png)

### System information
- GPU: GTX 1070
- Driver: 435.27.02
- Wine version: 4.18
- D9VK version: 0.30

### Apitrace file(s)
Recorded under native D3D9:
https://drive.google.com/open?id=1nc3V_CZxJRQeA6qWn3WvSL0xShP-ZjRB

### Log files
- d3d9.log: [gta_sa_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3796409/gta_sa_d3d9.log)

**Comment by Joshua-Ashton** [comment]
The flares don't render on native AMD fwiw, I need to test playing back that trace on NV though.

**Comment by CME42** [comment]
The flares are rendered on native nv.
