### ISSUE TITLE
Risen 1 - high frametimes and black flickering

### ISSUE THREAD

**Issue by DadSchoorse** [Joshua-Ashton/d9vk#443]
~During the the attack of the final boss fps are basically 0 (trace 1). Extremely high frame times in some areas when rotating the character, sometimes up to 5s (trace 2).~  In some Areas the trees flicker black (trace 3). These Problems do not happen with wined3d.
The performance issue is fixed.

### Software information
Risen 1680x1050 

### System information
- GPU:gtx 1060 6 gb
- Driver:440.26
- Wine version: Proton 4.11-7
- D9VK version: 0.30

### Apitrace file(s)
https://drive.google.com/open?id=1evdD8EzDm8bhstlfdLkN0CJRalsP3ekV
Hopefully these are not useless because the game did not respond at time where d9vk has issues.

### Log files
- proton log: [risen.log](https://github.com/Joshua-Ashton/d9vk/files/3800672/risen.log)

**Comment by K0bin** [comment]
Unfortunately your traces are borked. I also can't reproduce any of the issues.

**Comment by DadSchoorse** [comment]
@K0bin do you own the game? Should I give you the save files?

**Comment by K0bin** [comment]
I do own the game, so I guess we could try that.

**Comment by DadSchoorse** [comment]
The first one is during the final boss, wait until he attacks.
Just rotate the character in the second .
Go forward in the third.
[Risen saves.tar.gz](https://github.com/Joshua-Ashton/d9vk/files/3801706/Risen.saves.tar.gz)

**Comment by DadSchoorse** [comment]
I am pretty sure that this is a d9vk issue because it happens on windows, too. 
@K0bin could you reproduce my issues and if not do you have a AMD card?

**Comment by K0bin** [comment]
I can reproduce the issue and we know what causes the problem. We're still unsure about how to fix it though.

**Comment by Joshua-Ashton** [comment]
Can you try on latest master?
