### ISSUE TITLE
subcommand failed build failure since aa39387

### ISSUE THREAD

**Issue by Kattus** [Joshua-Ashton/d9vk#444]
Ignoring template as it's targeted to problems with games.

Trying to compile winelib version of aa39387a6c1c603e2a4028fb04b6522cb1fec2de or later results in `ninja: build stopped: subcommand failed.`, compiling 33d2041b0b513f383ef8f51723a75fb03139b5cc works just fine.
Full log: [buildlog.log](https://github.com/Joshua-Ashton/d9vk/files/3800787/buildlog.log)

Using this AUR package: https://aur.archlinux.org/packages/d9vk-winelib-git/

Linux 5.3.8-arch1-1-fsync + wine-4.19

**Comment by Joshua-Ashton** [comment]
Can you try now?

**Comment by Kattus** [comment]
That did the trick, thanks!
