### ISSUE TITLE
In game custom video playback reading issues

### ISSUE THREAD

**Issue by SKULLWORTH** [Joshua-Ashton/d9vk#447]
Hopefully i can explain as much as i can in this post.
The game is The Sims 2, disk version.

The GPU is Nvidia 1070 GTX TI

---------------------------------------------

Overall the game runs with no problem with d9VK, however the issue begins when you use in game TV. Just to be brief if you haven't played sims 2 before, there is a custom option to add your own videos to play on the TV. The only format the game reads for custom videos is AVI. The directory would be like this C:\Documents\EA Games\The Sims 2\Movies\Broadcast\TvSBN. 

----------------------------------------------------------------------------------------------------
From what i've gathered, the videos built into the game run on a unique codec created by Electronic arts. These run properly with no interference from d9vk.

![Screen_Shot_2019-11-10_at_7 38 01_AM](https://user-images.githubusercontent.com/57593112/68547506-337ff880-03da-11ea-9a4e-2f413adfbd6a.png)

Here is a typical custom video format.

![321312](https://user-images.githubusercontent.com/57593112/68547870-c02cb580-03de-11ea-9474-22845c8a5c28.PNG)

---------------------------------------------

In the past, these videos used to work on my older Gpu which was a 1gb 6800 ATI radeon HD.
For about a week i had been experimenting with the codecs, and i can confirm this is not a codec issue. Simply put, d9VK which doesn't fully acknowledge AVI videos.

---------------------------------------------

This is what the videos look like with d9vk installed. Although there's a black screen, i could still hear the video. So the video was playing but only from an audio perspective.

![snapshot_6aca6692_8ad43f5c](https://user-images.githubusercontent.com/57593112/68548217-4696c680-03e2-11ea-85fd-f725ead6ec5a.jpg)

-----------------------------------------

These pics were taken without d9vk, as you can see the custom Avi videos work.

![snapshot_6aca6692_4ad44ecd](https://user-images.githubusercontent.com/57593112/68548163-c2dcda00-03e1-11ea-9ed5-87a7a7b89755.jpg)
![snapshot_6aca6692_6ad44efa](https://user-images.githubusercontent.com/57593112/68548165-c83a2480-03e1-11ea-8246-82195d90b4b0.jpg)

----------------------------------------

Here is the d3d9 report.

[Sims2EP9_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3828770/Sims2EP9_d3d9.log)

**Comment by Joshua-Ashton** [comment]
I'll need an apitrace to debug this -- preferably one recorded where it works, and one where it doesn't (ie. w and w/o d9vk)

A copy of a working video would also be nice.

@tannisroot can probably help you or provide these.

**Comment by Joshua-Ashton** [comment]
When you say `without d9vk` do you mean native D3D or WineD3D?

**Comment by Joshua-Ashton** [comment]
Please try with this build. It probably won't render the videos *correctly* but it should hopefully render something (albeit very green)

[d3d9.zip](https://github.com/Joshua-Ashton/d9vk/files/3828906/d3d9.zip)

**Comment by SKULLWORTH** [comment]
> 
> 
> I'll need an apitrace to debug this -- preferably one recorded where it works, and one where it doesn't (ie. w and w/o d9vk)
> 
> A copy of a working video would also be nice.
> 
> @tannisroot can probably help you or provide these.

Just out of curiosity would that be the dxvk-cache? Either way, i'll speak with Tannis have those sent to you shortly.


------------------------------------------




> 
> 
> When you say `without d9vk` do you mean native D3D or WineD3D?

Wine3D code name - Loli-Hop.   

---------------------------------------------






> 
> 
> Please try with this build. It probably won't render the videos _correctly_ but it should hopefully render something (albeit very green)
> 
> Please provide a picture if anything changes.
> 
> [d3d9.zip](https://github.com/Joshua-Ashton/d9vk/files/3828906/d3d9.zip)

Thank you i will report back shortly.

**Comment by Joshua-Ashton** [comment]
> Just out of curiosity would that be the dxvk-cache

no

> Wine3D code name - Loli-Hop.

I think you're getting confused with the different things here.

**Comment by nelsonjchen** [comment]
I managed to trace it. There may be lots of pink flashing but I'm able to get a trace of the "gameplay" where the video from the reporter is being played.

https://drive.google.com/open?id=1RrDlbMVaGssmQHzYaWoHhTGE34MB9vhG
