### ISSUE TITLE
Guild Wars 2 crash/freeze 

### ISSUE THREAD

**Issue by logan001** [Joshua-Ashton/d9vk#449]
GW2 started to freeze desktop on minimize or sometimes if im lucky it won't go back in full screen. i can see a black screen and the hand cursor of the game but thats it. the game itself doesn't seem to freeze cause the sound it keeps going.

If desktop freeze i can still here youtube but there is no response from keyboard/mouse or power button. i have to hard reset the computer

I'm not sure when it started. it might be around [this](a70b703f311304226d7ded0864acd7ab33df2a42) or newer. 
I can't make a trace since i have no clue when it will crash.

### Software information
Name of the game, settings used etc.

### System information
- GPU: nvidia 970
- Driver: 435.27.03
- Wine version: wine-4.19.r0.g1f775840 ( TkG Staging Esync Fsync )
- DXVK version: 334fa6dc1365ea6720dd6166e615a7fef03e466f

### Log files 
- [d3d9.log](https://drive.google.com/open?id=1Oml_MHt7yaG_h6qn3Vt0AcqJtjqdOPvj)
This log is from when game didn't crash but i got only a black window with game cursor when click on it on taskbar.

I keep the game in windowed fullscreen.

**Comment by Joshua-Ashton** [comment]
Would you be able to bisect the issue?

**Comment by logan001** [comment]
for now i recompiled wine from Tk-Glitch and see if it still happens

**Comment by logan001** [comment]
ive recompile wine
still same problem
i've recreated a new profile in lutris
nothing changed.

the only good think is that today i didn't had to hard reset computer. today i only got the game to freeze (sound still working)

i can't access [froggi](https://git.froggi.es/joshua/d9vk/-/jobs) to download previous version. does it work for you?

**Comment by jrugia** [comment]
I play GW2 regularly with D9VK currently using the 0.30 release. Haven't encountered any issues.

My Setup:
Debian 9 - Kernel 5.3.11
Desktop Environment: Mate
Wine Version: 4.6 with eSync enabled

Hardware:
GPU / Driver: GTX 1060 6GB (435.27.03)
CPU: Ryzen 1700X
RAM: 16GB

**Comment by logan001** [comment]
@jrugia 
i think its a problem with cinnamon
i get this messages in .xession-erros
```
Cinnamon warning: Window 0x9800009 (Untitled) sets an MWM hint indicating it isn't resizable, but sets min size 1 x 1 and max size 2147483647 x 2147483647; this doesn't make much sense.
Cjs-Message: 15:50:32.738: JS LOG: pushModal: invocation of begin_modal failed
```

i don't have time to try now older version since its not always a sure hit on minimize.

for anybody else willing to give it a try a play the game in windowed fullscreen and when i minimize the game from button inside the game (when for example option window is open you can see all 3 buttons in the right upper corner)
alt+tab its not as much of a problem with windows mode but if i don't minimize the game than the video card will keep going on full power. thats why i choose miminize

**Comment by jrugia** [comment]
@logan001  Good find, for confirmation you could try to run the game in a different desktop environment. I think Openbox would make a good test base as it's lightweight and even doesn't require many packages.

**Comment by logan001** [comment]
@jrugia just as info: i reinstalled the previous version and everything works so far without any problem. i still get those messages in xseesion-errors. but nothing freeze anymore. the game has a 0.5-1 sec freeze period when it is restore from minimize status but it does not freeze at all. been using this version for a few hours now without any issues on minimize. 
so it might not necessary be cinnamon.

**Comment by logan001** [comment]
@Joshua-Ashton [this](d96d4c85ed406efc0cd7b9cdd5e9c663c590b998) is the last that build that does not freeze the game.

**Comment by Joshua-Ashton** [comment]
So https://git.froggi.es/joshua/d9vk/commit/5e686484eec269ffd6f32210db492396f7b59b43 (async present) causes the issues for you?

**Comment by logan001** [comment]
i don't know. i just tried the builds that are available on froggi.es. i didn't build manually every commit. So judging by froggi.es available downloads the build that started to freeze is https://git.froggi.es/joshua/d9vk/commit/a013f1e09f80841f2f4208ef5212deda82786e7e

**Comment by Joshua-Ashton** [comment]
Can you try using this build please? https://git.froggi.es/joshua/d9vk/-/jobs/974

**Comment by logan001** [comment]
i did. it still freeze

**Comment by Joshua-Ashton** [comment]
@logan001 Can you see if this freezes or not? Will help me to determine the problem exactly.

[dxvk-gw2.tar.gz](https://github.com/Joshua-Ashton/d9vk/files/3855982/dxvk-gw2.tar.gz)

**Comment by logan001** [comment]
just did and yes it freeze.

**Comment by Joshua-Ashton** [comment]
Async present it is then.

**Comment by Joshua-Ashton** [comment]
Just to triple check, can we try this?

[dxvk-gw2-new.tar.gz](https://github.com/Joshua-Ashton/d9vk/files/3856051/dxvk-gw2-new.tar.gz)

**Comment by logan001** [comment]
the "new" one does not freeze. at least so far after 4 hours of playing its still ok

**Comment by Joshua-Ashton** [comment]
Can you try this?

[dxvk-gw2-test-fix.tar.gz](https://github.com/Joshua-Ashton/d9vk/files/3859940/dxvk-gw2-test-fix.tar.gz)

**Comment by logan001** [comment]
no problem with test-fix either so far after 3 hours of using it

**Comment by Joshua-Ashton** [comment]
Can you try with the latest stuff i just pushed? Builds should be on git.froggi.es

**Comment by logan001** [comment]
i've installed 4f0edd27 and no problem after 4 hours of playing

**Comment by logan001** [comment]
i'm guessing there's nothing to test anymore since its working so i'm closing the issue :)
