### ISSUE TITLE
[Question] Will D9VK support DXVK_ASYNC patchset?

### ISSUE THREAD

**Issue by t14462** [Joshua-Ashton/d9vk#45]
I have noticed that D9VK with low CPU overhead completely get rid of Fallout New Vegas stuttering (wich exist on Gallium-Nine).

Also, D9VK supports DX9 for WPF as Nine

Will be DXVK_ASYNC=1 ported to D9VK?

**Comment by Guy1524** [comment]
The async patchset has the flaw that, DXVK can't guarantee something will be rendered.  This can be interpreted as a cheating mechanism, so it will never be merged.

Even if it was a good idea to merge, that decision is entirely up to doitsujin as the patch only affects the backend, DXVK.  Merging into D9VK would be useless.

**Comment by Joshua-Ashton** [comment]
Officially, no.
However the patchset for DXVK should apply just the same, use at your own peril.
Don't blame me if your cat gives birth or your frog dies.
