### ISSUE TITLE
guild wars 2 : mouse disapear in fullscreen if f.lux running

### ISSUE THREAD

**Issue by nykoo** [Joshua-Ashton/d9vk#453]
mouse cursor disapear in guild wars 2 (gw2.exe x64) if f.lux application is running (f.lux v.4.111)

https://justgetflux.com/$

d9vk version: d9vk-master.9195847768a74767f0ae57e3b2749a0c586805e6  - Nov 17, 2019 5:58pm

** @Joshua-Ashton i would like to thank you for your so great job with d9vk that save my game after a computer upgrade with an AMD RT 5700 XT that cause gw2 to be completly unplayable. Thank you very much  **

**Comment by K0bin** [comment]
> d9vk version: d912_pxy_1.9h2_r454 - Nov 17, 2019 5:58pm

d912pxy is not d9vk

It's a totally different project.

**Comment by nykoo** [comment]
> > d9vk version: d912_pxy_1.9h2_r454 - Nov 17, 2019 5:58pm
> 
> d912pxy is not d9vk
> 
> It's a totally different project.

sry my mistake, i correct the d9vk version in first post, i use d9vk (and not d912pxy that was not working for me)

**Comment by Joshua-Ashton** [comment]
Are you playing in full screen or windowed?

Can you tell me if one of these works?

**Comment by nykoo** [comment]
in fullscreen and windowed-fullscreen cursor disapeared
in windowed mode cursor is present.

Not so annoying anyway as i simply exit f.lux and maybe it's a problem to f.lux side. But just want to let you know and let know this issue to users if they encouter this cursor disapear problem :)

**Comment by Joshua-Ashton** [comment]
Looks like a problem with compositor bypass + f.lux.

You should report the issue there.

**Comment by nykoo** [comment]
Thank you, i will report it to f.lux 👍
