### ISSUE TITLE
Gothic / Gothic II: Gold Edition Crash on Startup

### ISSUE THREAD

**Issue by shoober420** [Joshua-Ashton/d9vk#454]
### Software information
Gothic and Gothic II: Gold Edition crash on startup, whether D9VK is used or not.

### System information
- GPU: GTX 760
- Driver: 440.31
- Wine version: Proton 4.11-8
- D9VK version: 0.30

**Comment by Joshua-Ashton** [comment]
Logs? Apitrace?

**Comment by K0bin** [comment]
If it crashes **without** D9VK then it's not a D9VK issue.

Gothic 1 uses Direct3D7.
Gothic 2 used Direct3D8.1.

So this has nothing to do with D9VK.

**Comment by shoober420** [comment]
Sorry for the confusion. Gothic 2 still crashes at startup even when d3d8to9 is installed, so it’s an issue with Wine/Proton.

**Comment by neVERberleRfellerER** [comment]
FYI both Gothics are DX7. They only use ddraw, so d3d8to9 is of no use. dgVoodoo2 works, but it's slower than wind3d. Crashes are caused by dmusic.

**Comment by shoober420** [comment]
@neVERberleRfellerER 
PCGamingWiki says it’s DX8 (https://www.pcgamingwiki.com/wiki/List_of_DirectX_8_games), but it crashes whether or not d9vk or wined3d is used, so I think it’s an issue with Wine/Proton.

There’s a DX11 mod for Gothic 1/2 I’m going to try when I get home from work to see if it launches with DX11.

https://github.com/ataulien/GD3D11

**Comment by shoober420** [comment]
@neVERberleRfellerER 

More info on my progress getting Gothic and Gothic II to work here.

https://github.com/Joshua-Ashton/d9vk/issues/454
