### ISSUE TITLE
S.T.A.L.K.E.R: Call of Pripyat performance regression

### ISSUE THREAD

**Issue by shoober420** [Joshua-Ashton/d9vk#455]
# Software information
S.T.A.L.K.E.R: Call of Pripyat

### System information
- GPU: GTX 760
- Driver: 440.31
- Wine version: Proton 4.11-8
- D9VK version: 0.30

S.T.A.L.K.E.R.: Call of Pripyat has encountered a serious performance regression. My FPS will be constantly what looks like literal 5 FPS.

https://github.com/ValveSoftware/Proton/issues/3229

**Comment by Joshua-Ashton** [comment]
Logs/Apitrace?

**Comment by shoober420** [comment]
Here goes the logs. I'm on Proton, so installing apitrace would be weeeeeeird.

[xrEngine_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3862336/xrEngine_d3d9.log)

[xrEngine_d3d11.log](https://github.com/Joshua-Ashton/d9vk/files/3862337/xrEngine_d3d11.log)

**Comment by Joshua-Ashton** [comment]
If you can't trace it can you at least bisect?

**Comment by Joshua-Ashton** [comment]
https://git.froggi.es/joshua/d9vk/-/jobs

**Comment by Joshua-Ashton** [comment]
> S.T.A.L.K.E.R.: Call of Pripyat has encountered a serious performance regression. My FPS will be constantly be what looks like literal 5 FPS.

Are you sure that's not because you're using debug logging?

**Comment by shoober420** [comment]
@Joshua-Ashton 
The performance was that way before I put the log commands launch options.

**Comment by axredneck** [comment]
There were an apitrace of Stalker CoP somewhere in bug reports.
