### ISSUE TITLE
Grand Theft Auto: Vice City Long Load Screens

### ISSUE THREAD

**Issue by shoober420** [Joshua-Ashton/d9vk#456]
### Software information
Grand Theft Auto: Vice City has very long load times than normal.

### System information
- GPU: GTX 760
- Driver: 440.31
- Wine version: Proton 4.11-8
- D9VK version: 0.30

**Comment by Joshua-Ashton** [comment]
Please stop making garbage issues where you provide no apitrace/logs every few minutes.

If you're going to write issues, at least make an effort dude. I can't do **anything** with just ``has very long load times than normal``.

**Comment by shoober420** [comment]
What directory is the "d3d9.log" file generated?

**Comment by Joshua-Ashton** [comment]
You'll need to enable that with ``DXVK_LOG_LEVEL=info`` if you're on Proton I think and it should be dumped in the game dir.

**Comment by Leopard1907** [comment]
> What directory is the "d3d9.log" file generated?

This game is not dx9. It utilizes 8.

**Comment by ByCybernetik** [comment]
Launched game, works well, only swathe of the bottom should not be.
![20191118172816_1](https://user-images.githubusercontent.com/45942960/69064846-d3b7cc00-0a2f-11ea-8cd9-a3ab7e1e77b9.jpg)

Log: [gta-vc_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3859287/gta-vc_d3d9.log)

WineD3D Trace: https://drive.google.com/file/d/19xJkbI0bM1sKZ-tfmjH1y3hdbusHb1Zp/view?usp=sharing

### System information
- GPU: Radeon RX 590 8GB
- Driver: RADV 19.99.99
- Wine version: Proton 4.11-8
- DXVK version: Master 18-11-2019

**Comment by shoober420** [comment]
I’ll try again with that wrapper you used. I was just thinking that d9vk should have a wrapper to convert DX3-8 calls to D3D9, then to Vulkan

**Comment by shoober420** [comment]
Upon installing d3d8to9 (https://github.com/crosire/d3d8to9/) into the GTA:VC directory, the load time bug is gone. It runs a lot better and looks a lot better, considering it’s now using Vulkan. Don't forget to add ```WINEDLLOVERRIDES="d3d8=n" PROTON_USE_D9VK=1``` to launch options.

https://github.com/ValveSoftware/Proton/issues/291
