### ISSUE TITLE
Grand Theft Auto IV appears to crash with Unhandled render state D3DRS_ADAPTIVETESS_{Z,W}

### ISSUE THREAD

**Issue by telans** [Joshua-Ashton/d9vk#458]
GTA IV Crashes during the benchmark where it hangs until manually killed. Repeatable on the third benchmark scene when the moped spins around.

### Software information
Grand Theft Auto IV
```
Command: ['/home/telans/.local/share/Steam/steamapps/common/Grand Theft Auto IV/GTAIV/LaunchGTAIV.exe', '-width', '1920', '-height', '1080', '-nomemrestrict', '-norestrictions', '-percentvidmem', '100', '-availablevidmem', '6144', '-noprecache', '-novblank']
Options: {'forcelgadd', 'winetricks', 'nowinedbg', 'pulselowlat', 'nonvapi', 'logcommandtoprefix'}
```

### System information
- GPU: 980Ti
- Driver: 435.27.07
- Wine version:  proton-tkg-4.20.r4.ga9639c41 (Same issue with Proton 4.11)
- D9VK version: 55cb30c (Same with 0.30)

### Apitrace file(s)
With D9VK:
https://mega.nz/#!YFwn2AJA!98HX-Y5IH9sq7-dwoeISmYLrH4CVd5c7pLTZBJV_k2I

Can't get a trace with wined3d as GTA IV fails to load with it.

### Log files
[GTAIV_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3871994/GTAIV_d3d9.log)
dxgi.log (empty)
[steam-12210.log](https://github.com/Joshua-Ashton/d9vk/files/3872033/steam-12210.log)

Note that the log files & trace aren't from the same run, but I can do it again if needed.

**Comment by Joshua-Ashton** [comment]
Works fine for me...

**Comment by telans** [comment]
Just tested again, still crashing with proton_tkg_4.20.r8.g7e4e8088 & Proton 4.11-8 - both with clean prefixes.

Proton 4.11-8:
[steam-12210.log](https://github.com/Joshua-Ashton/d9vk/files/3881717/steam-12210.log)
[GTAIV_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3881718/GTAIV_d3d9.log)

proton_tkg_4.20.r8.g7e4e8088:
[steam-12210.log](https://github.com/Joshua-Ashton/d9vk/files/3881723/steam-12210.log)
[GTAIV_d3d9.log (more info in this log)](https://github.com/Joshua-Ashton/d9vk/files/3881728/GTAIV_d3d9.log)

**Comment by Joshua-Ashton** [comment]
Would you be able to get a screenshot with DXVK_HUD=full ?

**Comment by telans** [comment]
Fixed. Probably due to driver upgrade.
