### ISSUE TITLE
Mass Effect 2: Very slow rendering on D9VK

### ISSUE THREAD

**Issue by XXXBold** [Joshua-Ashton/d9vk#459]
I'm having issues with Mass Effec 2 using D9VK.

On startup, the intro Videos play fine. However, on the menu the framerate drops down to 0.5 FPS and doesn't go up anymore. After some idle time on initial menu screen without interaction, some cinematics start playing, for this, FPS go up again, but fall back to 0.5 when done.

When using Wined3d9, this problem doesn't occur, however, general performance isn't very good.

### Software information
Mass Effect 2 Steam version

### System information
- GPU: Sapphire Radeon R9 290X Tri-X OC
- Driver: mesa 20.0-git (oibaf ppa)
- Wine version: 4.11 (Proton 4.11.8)
- DXVK version: 0.90 (Default, bundled with proton)
- OS: Linux Mint 19.2 Cinnamon

### Apitrace file(s)
- https://drive.google.com/file/d/1AtLKtsxjx9AnTk4p2btrX9Kpz2NLQe3z/view?usp=sharing

### Log files
- d3d9.log: 
[MassEffect2_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3883601/MassEffect2_d3d9.log)

**Comment by Joshua-Ashton** [comment]
This is a known bug in the current Proton build due to a dodgy mingw

**Comment by XXXBold** [comment]
Interesting. So, is this already addressed then, or should I open an issue for Proton? Do you have information when this will be fixed?

**Comment by Joshua-Ashton** [comment]
Discussion is happening here: https://github.com/ValveSoftware/Proton/issues/3198

**Comment by XXXBold** [comment]
I've installed D9VK v0.30 from releases here now in proton, and can confirm that this issue is gone. Will keep this issue open until a proton update fixes that officially, if that's okay for you. BTW why does proton has D9VK version 0.90, but here you're on 0.30?

**Comment by Joshua-Ashton** [comment]
Just a quirk of tags
