### ISSUE TITLE
Cant launch WPF apps

### ISSUE THREAD

**Issue by t14462** [Joshua-Ashton/d9vk#46]
.NET WPF depending on DX9 + D3Dcompiler_47

With gallium-nine everything OK, almost.

**Comment by Joshua-Ashton** [comment]
Thank you for deleting every part of the issue template and writing perhaps the most unhelpful pair of sentences known to man.

**Comment by t14462** [comment]
Problem in shader compiling, or in compatibility with D3Dcompiler, because D3DCompiler is a critical part of WPF.

It need to be investigated later, when D9VK will be ready

**Comment by Joshua-Ashton** [comment]
I don't provide d3dcompiler.

**Comment by Joshua-Ashton** [comment]
Additionally, wine's d3dcompiler is pretty crap and generates absolute garbage that won't be parsed properly. Please use a Windows d3dcompiler.

Additionally, please use the `wip-shader-compiler` branch.

**Comment by t14462** [comment]
So, how it works? It translating regular DX9 shaders to SPIR-V, right?..

**Comment by Joshua-Ashton** [comment]
Yeah? The already compiled ones.

d3dcompiler -> shader bytecode -> spirv
[                     not me                   ][     me      ]

**Comment by t14462** [comment]
OK, I'll try to figure out with workarounds.

By the way, i installed D3Dcompiler_47 but program still crashes on D9VK. On nine it works OK.

**Comment by Joshua-Ashton** [comment]
You still haven't told me the name of whatever it is you are trying to run 🐸

**Comment by t14462** [comment]
Frosty Mod Manager, program for modding Frostbite games (Mass Effect Andromeda, Dragon Age Inquisition and others) - nobody knows how to launch it on linux... except me.

**Comment by Joshua-Ashton** [comment]
> nobody knows how to launch it on linux... except me.

Then what do you expect me to do about that? If
 - I don't own a single Frostbite game
 - I have never heard of this application
 - I wouldn't be able to launch it because I am not you

?????

**Comment by t14462** [comment]
Just for note:

1.WPF apps depending on DX9
2.You doing DX9
3.Something, little bit, not OK
4.Compatibility with many programs - cool thing
5.You must be FROGGING

**Comment by Joshua-Ashton** [comment]
Either way, if you'd like to provide logs or an apitrace or investigate the issue yourself, you are more than welcome.

🐸

**Comment by Glog78** [comment]
A small comment:

“PATIENCE YOU MUST HAVE my young padawan”
– Yoda

D9vk is in very early stages comparing it to nine is not helpfull currently. Also if you want to help please don't remove stuff from the templates but try to fill the requested informations.

**Comment by t14462** [comment]
OK, I will try all doing nice next time

**Comment by K0bin** [comment]
Here are some logs at the very least: https://pastebin.com/Njm4xAD1
Looks like it's using fixed function stuff.
