### ISSUE TITLE
Senran Kagura Shinovi Versus: Letterboxed Fullscreen

### ISSUE THREAD

**Issue by ryester27** [Joshua-Ashton/d9vk#460]
### Software information
Senran Kagura Shinovi Versus
Arch Linux

### System information
- GPU: AMD RX 560
- Driver: Mesa 19.2.6/LLVM 9.0.0
- Wine version: Proton 4.11-8
- DXVK version: d9vk-v0.90-2288-g1c550035d-froglet

### Apitrace file(s)
https://mega.nz/#!qpxy1IYa!GXJJI5t8-5IApIsjJ6pQRTH0837GyZNpqohykTgdLX4

### Log files
[steam-411830.log](https://github.com/Joshua-Ashton/d9vk/files/3885026/steam-411830.log)

There appears to be a letterbox effect going on with the game, despite the monitor being 1080p 16:9, and the game resolution set correctly

D9VK
![Screenshot_20191124_232341](https://user-images.githubusercontent.com/17807258/69516315-4e488600-0f1f-11ea-8593-27d8faf09cb0.jpg)

WineD3D
![Screenshot_20191124_232738](https://user-images.githubusercontent.com/17807258/69516402-8354d880-0f1f-11ea-827d-eaec31449d6c.jpg)

**Comment by K0bin** [comment]
Probably related to #337

**Comment by Joshua-Ashton** [comment]
Can't repro on the trace, could you provide a trace made with d9vk?

**Comment by Joshua-Ashton** [comment]
So I've tested this with the actual game, and the same behaviour is present when using native d3d9.

**Comment by ryester27** [comment]
> So I've tested this with the actual game, and the same behaviour is present when using native d3d9.

So that means this is a mesa issue?

**Comment by Joshua-Ashton** [comment]
No, I mean it happens in Windows d3d9 too for me... (I have the game)

I'm using a 4K monitor, and disabling certain modes caused it to pick the right ones. I think this might be a game bug.


Can possibly work around it though.

**Comment by Joshua-Ashton** [comment]
Yeah this is technically a game bug.

**Comment by ryester27** [comment]
> No, I mean it happens in Windows d3d9 too for me... (I have the game)
> 
> I'm using a 4K monitor, and disabling certain modes caused it to pick the right ones. I think this might be a game bug.
> 
> Can possibly work around it though.

Strange. Guess I never thought about it being a game issue because the last time I played on Windows was with a 16:10 monitor, and top-bottom letterboxing is just a part of life when playing console ports made for 16:9 TVs. Sounds like Wine must have patched in a workaround at some point

I'll get you a d9vk trace this evening

**Comment by Joshua-Ashton** [comment]
I dont need a d9vk trace anymore its fine

**Comment by Joshua-Ashton** [comment]
Can you try with this build to see if it fixes it?

[d3d9.zip](https://github.com/Joshua-Ashton/d9vk/files/3893357/d3d9.zip)

**Comment by ryester27** [comment]
> Can you try with this build to see if it fixes it?
> 
> [d3d9.zip](https://github.com/Joshua-Ashton/d9vk/files/3893357/d3d9.zip)

I will let you know this evening 👍

**Comment by Joshua-Ashton** [comment]
Feel free to re-open if it persists...

**Comment by ryester27** [comment]
> Can you try with this build to see if it fixes it?
> 
> [d3d9.zip](https://github.com/Joshua-Ashton/d9vk/files/3893357/d3d9.zip)

Just gave it a try. I didn't see any changes.

I'm assuming the instructions for installing this test DLL are the exact same as setting up for a trace?

**Comment by Joshua-Ashton** [comment]
Well yeah, I also pushed the changes to latest, which fix the issue for me.

**Comment by Joshua-Ashton** [comment]
If that doesn't work then please trace...

**Comment by ryester27** [comment]
okay got a new d9vk trace for you

https://mega.nz/#!f1BwzKwQ!u4i03_PvNln-zNSnDus2U0hKRugUpEZkqAIQplx3DAU

**Comment by Joshua-Ashton** [comment]
I didn't mean to re-close this sorry

**Comment by Joshua-Ashton** [comment]
Can you try with 4caa51ff3cf0ac2da64c7d69855346b8031630d1

**Comment by ryester27** [comment]
Looks like you got it. Thanks for the fix!

![Screenshot_20191127_185233](https://user-images.githubusercontent.com/17807258/69766768-75819c00-1147-11ea-8183-f2e3falkon:startd4b8d703.jpg)
