### ISSUE TITLE
increasing number of black objects in CS:GO when playing longer or after settings switch

### ISSUE THREAD

**Issue by aufkrawall** [Joshua-Ashton/d9vk#462]
Getting this when just starting a bot match and playing for a few seconds:

![Screenshot_20191128_130352](https://user-images.githubusercontent.com/13510490/69811474-6efa2f80-11ee-11ea-8313-12e9e03bfe20.png)
It gets worse the longer I play.

It gets really bad when changing graphics settings (e.g. MSAA) while playing:

![Screenshot_20191128_141420](https://user-images.githubusercontent.com/13510490/69811521-846f5980-11ee-11ea-8a92-fbbe50a62581.png)

Edit: This is with native d3dx9 and d3dcompiler.

Not sure if related, but after playing TESIV Oblivion a little a few weeks back, I got the same artifacts in Shivering Isles town area. They disappeared after restarting the game.

### Software information
CS:GO, maxed out visuals, 1440p

### System information
- GPU: 6700k
- Driver: mesa-git 20, radv
- Wine version: Proton 4.11-9
- D9VK version:  4caa51ff3cf0ac2da64c7d69855346b8031630d1

### Apitrace file(s)
https://drive.google.com/open?id=1JcfKxDzcEGkZxq2BDU3xX3dcF8aIwO5S
WineD3D and native Windows D3D9 don't work, so it's with D9VK.

### Log files
[csgo_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3901965/csgo_d3d9.log)

**Comment by K0bin** [comment]
That's a game bug. I've had this happen countless times over the years on Windows.

**Comment by aufkrawall** [comment]
I don't have this issue on Windows with native D3D9.

**Comment by K0bin** [comment]
Happened a lot on the old cache for me. Alt-Tab or chaning graphics settings would trigger it.

**Comment by Joshua-Ashton** [comment]
@aufkrawall Can you please take a screenshot of the full DXVK hud when you are ingame?

This shouldn't be an issue if the game is using D3D9Ex...

**Comment by aufkrawall** [comment]
@Joshua-Ashton 
![Screenshot_20191129_100453](https://user-images.githubusercontent.com/13510490/69857265-d74d1d80-128f-11ea-9c7d-44d49083efb2.png)

**Comment by Joshua-Ashton** [comment]
This is my bug.

**Comment by Joshua-Ashton** [comment]
This is an exclusive bug to D3D9Ex + D9VK. Hmmm

**Comment by Joshua-Ashton** [comment]
Turns out it's a race condition in the game, it's unlocking the buffer then continuing to write.

**Comment by aufkrawall** [comment]
Thanks. Though it crashes after a few seconds now with git-master 0c84d72941f8798770a6dec54fa7e57a711f5e8d.

**Comment by Joshua-Ashton** [comment]
Works fine here 🤷‍♂

**Comment by aufkrawall** [comment]
Stupid me, it was mesa-layer-mango. CS:GO works fine now, thanks.

Too bad it isn't whitelisted with Proton + D9VK in VAC, as D9VK likely kills the official OGL wrapper renderer of the Linux version in terms of CPU performance (and perhaps even native D3D9). The Danger Zone map Scirocco is a mess with OGL. :(

**Comment by K0bin** [comment]
Danger Zone performance is shit on Windows too and CSGO doesn't seem to be bottlenecked by draw calls.

**Comment by aufkrawall** [comment]
The other game modes might not, but Danger Zone maps have a several times higher object count and don't seem to have a LOD system for it either. Also the native D3D9 renderer runs at least 20-30% faster than the OGL crap, so not seeing any gains with D9VK should be very unlikely.

The OGL renderer also has crap frame time consistency in Danger Zone mode, even after caching all shaders.
