### ISSUE TITLE
Spintires don't work in Fullscreen using D9VK

### ISSUE THREAD

**Issue by leillo1975** [Joshua-Ashton/d9vk#463]
Is not possible to use the menu using D9VK in FullScreen Mode (as described [here](https://github.com/ValveSoftware/Proton/issues/777#issuecomment-559504000)). If I use the gam in a Window it works

### Software information
Spintires

### System information
- GPU: NVIDIA GeForce GTX-1060-6GB
- Driver: 430.50
- Wine version: Proton 4.11-9
- DXVK version: 0.30

### Apitrace file(s)
-I can't generate an apitrace

### Log files
- d3d9.log:
[SpinTires_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3903019/SpinTires_d3d9.log)
- d3d11.log:
- dxgi.log: 0 bytes

**Comment by leillo1975** [comment]
Now the apitrace woked. Here is it:
https://mega.nz/#!BcRRhYgI!fXwydGk7R2qZYI3NSej3-dbJ_FO8ma6Ox3siTEljyYY

The game has the same problem that Mudrunner in certain moments:
![Captura de pantalla de 2019-11-28 23-37-57](https://user-images.githubusercontent.com/551821/69834163-06847000-1239-11ea-9a13-9201cf36dc5f.png)

**Comment by Joshua-Ashton** [comment]
> Is not possible to use the menu using D9VK in FullScreen Mode

Works fine here.

**Comment by Joshua-Ashton** [comment]
This isn't my bug, use a native d3dcompiler/d3dx9.

Fullscreen with D9VK works fine on Windows too, so it's a Wine bug causing that.
