### ISSUE TITLE
Mudrunner only works in a Window and has rendering problems

### ISSUE THREAD

**Issue by leillo1975** [Joshua-Ashton/d9vk#464]
Is not possible to use the menu using D9VK in FullScreen Mode . If I use the game in a Window it works, but it has rendering problems as you can see in the following screenshot:
![Captura de pantalla de 2019-11-28 22-17-29](https://user-images.githubusercontent.com/551821/69832186-45142d80-122d-11ea-8525-55617d60c128.png) (is a dark screenshot because is night in game)

### Software information
Mudrunner

### System information
- GPU: NVIDIA GeForce GTX-1060-6GB
- Driver: 430.50
- Wine version: Proton 4.11-9
- DXVK version: 0.30

### Apitrace file(s)
-I can't generate an apitrace

### Log files
- d3d9.log:
[MudRunner_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3903030/MudRunner_d3d9.log)
- d3d11.log:
- dxgi.log: 0 bytes

**Comment by Joshua-Ashton** [comment]
> I can't generate an apitrace

Please try and do this.

**Comment by Joshua-Ashton** [comment]
I don't know why you couldn't. Works fine for me. Got a trace.

**Comment by leillo1975** [comment]
It's OK?
https://mega.nz/#!FdBjFAqQ!hAIhT4iz0m52bIfYbkQuf2pl6noVlqaTEIz2r2wu27o

**Comment by Joshua-Ashton** [comment]
It's OK I have one now

**Comment by leillo1975** [comment]
With Spintires I made the same and don't work

**Comment by Joshua-Ashton** [comment]
Fullscreen works for me in Mudrunner fine on Windows with D9VK. This might be a Proton/Wine-exclusive bug. I'll try that out later.

I do have a bug with the bloom though, going to look into that now.

**Comment by leillo1975** [comment]
I finally managed to create an apitrace of [Spintires](https://github.com/Joshua-Ashton/d9vk/issues/463#issuecomment-559614442), and the game seems to have the same problem.

**Comment by Joshua-Ashton** [comment]
Can you try now?

**Comment by Joshua-Ashton** [comment]
> Is not possible to use the menu using D9VK in FullScreen Mode

Works fine here.

**Comment by leillo1975** [comment]
> Can you try now?

What do you want me to try again? I think nothing has changed

**Comment by Joshua-Ashton** [comment]
Well, the rendering bugs are because you aren't using native d3dx9 and/or d3dcompiler, and the fullscreen bug is Wine-exclusive so I'm not entirely sure what to do.

**Comment by Joshua-Ashton** [comment]
Closing this as it isn't my bug.
