### ISSUE TITLE
Metal Gear Rising: Low framerate when moving mouse

### ISSUE THREAD

**Issue by Mar2ck** [Joshua-Ashton/d9vk#465]
Game runs fine and smooth but fps drops to single digits whenever the mouse is being moved. Doesn't happen with WINED3D

### Software information
METAL GEAR RISING

### System information
- GPU: GTX 760
- Driver: NVIDIA 430.50
- Wine version: Proton 4.11-9
- D9VK version: 0.30

### Apitrace file(s)
https://drive.google.com/file/d/14HlG-88hXCJhmv7r4B7epJ_LRI-GDjlF/view?usp=sharing

### Log files
- d3d9.log:
Don't know how to produce
- d3d11.log:
- dxgi.log:

**Comment by Joshua-Ashton** [comment]
I can't really tell issues like this from a trace. Can you try master?

**Comment by Mar2ck** [comment]
Ill try to compile and see

**Comment by Joshua-Ashton** [comment]
Just use the builds: https://git.froggi.es/joshua/d9vk/-/jobs

**Comment by Mar2ck** [comment]
With the lastest build the fps only drops to about 20-30 fps but it still drops. Moving the camera using a controller instead doesn't have any impact on the fps

**Comment by Mar2ck** [comment]
It looks like not moving the mouse for a few seconds then moving it quickly mostly consistently causes an fps drop

**Comment by Joshua-Ashton** [comment]
The game never calls any cursor code in D3D9 so this isn't my bug.

This sounds like the mouse polling rate bug present in Wine/something.

**Comment by Joshua-Ashton** [comment]
Actually I'm gonna keep this open just to make sure, going to get some people to see if they can test/find the cause.

**Comment by Mar2ck** [comment]
Strange that it only happens with d9vk then. Ill have to make a bug report with the wine devs then

**Comment by Joshua-Ashton** [comment]
Yeah this isn't my bug and just looks to be mouse polling. Please make an issue on Wine.
