### ISSUE TITLE
LOTR War in North show severe flickering

### ISSUE THREAD

**Issue by mrdeathjr28** [Joshua-Ashton/d9vk#467]
LOTR War in North show severe flickering and dont allow pass to main game screen

### Software information

LOTR War in North

### System information

Nvidia Drivers 435.27.08 (run package)

Lubuntu 20.04 x64 - Kernel 5.3.0-18 generic (ubuntu mainline) -

CPUFreq: Performance

CPU: Core i3 8350K Tri-Core (Coffelake 14nm) 5.0Ghz - Zalman CNPS 10x Performa+ - CoolerMaster MasterFan Pro Air Balance (83 CFM)

MEMORY: 12GB DDR4 2400mhz (8x1 - 4x1) Mushkin (dual channel: 37.5 gb/s - Flex Mode)

GPU: Gigabyte Nvidia Geforce GTX 1050 OC (GP107 14nm: 640 Shaders / 40 TMUS / 32 ROPS) Windforce 2GB DDR5 7000Mhz 128Bit (110Gb/s)

MAINBOARD: ASUS Z370-P

### Apitrace file(s)

https://mega.nz/#!nAMQSCSS!gqmF77CbvLnfxOjmTFY-Y3M-fXyRWSzYTXw_dyFCwCw

### Log files

[witn_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3930275/witn_d3d9.log)

**Comment by Joshua-Ashton** [comment]
I can't do much given you've only recorded the loading screen.

**Comment by mrdeathjr28** [comment]
> I can't do much given you've only recorded the loading screen.

dont leave pass from here in my case

**Comment by Joshua-Ashton** [comment]
??????????????????

**Comment by felipe19930** [comment]
I think he meant the game doesn't get past the loading screen, for him.

**Comment by mrdeathjr28** [comment]
Actually game runs fine
