### ISSUE TITLE
The Witcher 2 doesn't start when `PROTON_USE_D9VK=1 %command%` is set

### ISSUE THREAD

**Issue by jqadev** [Joshua-Ashton/d9vk#468]
### Software information
The game doesn't start when `PROTON_USE_D9VK=1 %command%` is set.
Without this command it works.

To reproduce this issue the config files need to be copied like below to run the launcher:
```sh
cp -r ~/.steam/steam/steamapps/common/the\ witcher\ 2/bin/config/* ~/.steam/steam/steamapps/compatdata/20920/pfx/drive_c/users/steamuser/My\ Documents/Witcher\ 2/Config/
```
I already reported the issue with not starting launcher without above workaround here https://github.com/ValveSoftware/Proton/issues/2309#issuecomment-560487551

### [System information](https://gist.github.com/jqadev/8a892c8f8b5145169b4d5ae8c142c7c9)
- GPU: GeForce 930MX
- Driver: NVIDIA 435.21
- Proton version: 4.11-9

### Log files
- d3d9.log: [steam-20920.log](https://github.com/Joshua-Ashton/d9vk/files/3933120/steam-20920.log)

**Comment by K0bin** [comment]
Pls post the actual D9VK logs instead of that steam log.

**Comment by Joshua-Ashton** [comment]
[d3d9.zip](https://github.com/Joshua-Ashton/d9vk/files/3933409/d3d9.zip)

Please try with this dll and provide logs if it doesn't work.

**Comment by jqadev** [comment]
@Joshua-Ashton 
What I did:
1. worked around the launcher issue
```sh
cp -r ~/.steam/steam/steamapps/common/the\ witcher\ 2/bin/config/* ~/.steam/steam/steamapps/compatdata/20920/pfx/drive_c/users/steamuser/My\ Documents/Witcher\ 2/Config/
```
2. extracted and copied `d3d9.dll` file to:
`~/.steam/steam/steamapps/common/the\ witcher\ 2` (here is Launcher.exe)
`~/.steam/steam/steamapps/common/the witcher 2/bin` (here is witcher2.exe)
3. set launch options:
`PROTON_LOG=1 WINEDLLOVERRIDES="d3d9=n" %command%`

The game starts now but there is only a black screen.
Here is the log file: [steam-20920.log](https://github.com/Joshua-Ashton/d9vk/files/3934371/steam-20920.log)

**Comment by Joshua-Ashton** [comment]
Looks like it might be some form of setup issue on your end if you're getting that...

Can you try with the latest from here? https://git.froggi.es/joshua/d9vk/-/jobs and if that doesn't work try adding a dxvk.conf with `d3d9.deferSurfaceCreation = True`?

**Comment by jqadev** [comment]
When I test using [6ab4ba92](https://git.froggi.es/joshua/d9vk/commit/6ab4ba9262e7c8bfc680b0307d15abd27e6a1aa9)
there appears 
![Screenshot from 2019-12-07 02-16-54](https://user-images.githubusercontent.com/20422423/70366451-ba1fdc80-1897-11ea-9323-d97ec98f4d2b.png)
Here is the log file 
[steam-20920.log](https://github.com/Joshua-Ashton/d9vk/files/3934556/steam-20920.log)

As a next test I created `dxvk.conf` file in the directory
`~/.steam/steam/steamapps/common/the\ witcher\ 2/bin`  (here is the `witcher2.exe` file):
```ini
[witcher2.exe]
d3d9.deferSurfaceCreation = True
```
The error from the attacked screenshot didn't appeared.
There is still black screen but the sound is playing.
Here is the log file:

**Comment by NerosTie** [comment]
It's an issue with the configuration files.

Do that:

> Before first launch you need to cp -r ~/.steam/steam/steamapps/common/the\ witcher\ 2/bin/config/* ~/.steam/steam/steamapps/compatdata/20920/pfx/drive_c/users/steamuser/My\ Documents/Witcher\ 2/Config/ or else the game simply crashes on launch. You only need to do this once.

https://www.protondb.com/app/20920

Tested on my own with #1011 and it works very well. It's not a d9vk's bug.

**Comment by jqadev** [comment]
@NerosTie please read my previous comments. I already did it. The game works for me but only when D9VK is not used.

**Comment by NerosTie** [comment]
Sorry, I missed this part.

But it works for me with d9vk activated. I don't understand why it doesn't work for you...

(you should update your Nvidia driver btw, 435.21 is a little bit old now)

**Comment by jqadev** [comment]
@NerosTie you are right. It's not the D9VK bug
`vulkaninfo` output contains:
```
WARNING: [Loader Message] Code 0 : loader_icd_scan: Can not find 'ICD' object in ICD JSON file /usr/share/vulkan/icd.d/nvidia_layers.json.  Skipping ICD JSON
/build/vulkan-tools-IZAxVX/vulkan-tools-1.1.114.0+dfsg1/vulkaninfo/vulkaninfo.c:1528: failed with VK_ERROR_INITIALIZATION_FAILED
```
Here is the full output: [vulkaninfo.txt](https://github.com/Joshua-Ashton/d9vk/files/3940378/vulkaninfo.txt)

@Joshua-Ashton the output from the `vulkaninfo` should be required in the bug report

**Comment by jqadev** [comment]
@Joshua-Ashton thank you for your time and help. Should this issue be closed? If yes, please do it.

**Comment by jqadev** [comment]
I found the solution here https://github.com/ValveSoftware/Dota-Underlords/issues/1#issuecomment-515776293
It is enough to run `sudo vulkaninfo` instead of `vulkaninfo` before running games and games using DXVK/D9VK start working.
`vulkaninfo` is not installed by default on Ubuntu so I needed to install it using `apt install vulkan-utils`.

**Comment by NerosTie** [comment]
Uh? Where do you put that? I don't think you can do that with Steam.
