### ISSUE TITLE
Spellforce: Platinum Edition → transparent textures

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#470]
with d9vk:
![Screenshot_20191209_103344](https://user-images.githubusercontent.com/4572452/70427227-a087bc00-1a74-11ea-8372-497b4fb819c9.png)

without d9vk:
![Screenshot_20191209_103245](https://user-images.githubusercontent.com/4572452/70427239-a8476080-1a74-11ea-860d-5985a1746584.png)

### System information
- GPU: Nvidia GT 730M
- Driver: 440.36
- Wine version: Proton 4.11
- DXVK version: #1013

### Apitrace file(s)
Like https://github.com/Joshua-Ashton/d9vk/issues/384, I can't apitrace it...

### Log files
[spellforce_d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3939068/spellforce_d9vk.log)
[spellforce_wined3d.log](https://github.com/Joshua-Ashton/d9vk/files/3939069/spellforce_wined3d.log)

**Comment by Joshua-Ashton** [comment]
Need a trace to even attempt that

**Comment by NerosTie** [comment]
I really really can't. I don't know why but there is no apitrace when I attempt to make one. I tried many things with no success...

**Comment by Joshua-Ashton** [comment]
Love this game's 9 year long unskipable cutscene when I specifically said Skip Prologue...

**Comment by Joshua-Ashton** [comment]
Ok I ran around a bit and couldn't find any houses like this, but all the other buildings/towers looked fine. Then a guy turned me into ice for some reason and then I met up with this purple dude.

Can you send me a savegame where you can repro the issue on `master`? (and please double check with native d3dx9 and d3dcompiler)

**Comment by NerosTie** [comment]
It's not only this house, there is also this stone: 

with d9vk:
![Screenshot_20200105_214717](https://user-images.githubusercontent.com/4572452/71785907-6ffc5900-3005-11ea-9242-39557a9f0fe1.png)

with wined3d:
![Screenshot_20200105_214810](https://user-images.githubusercontent.com/4572452/71785912-7a1e5780-3005-11ea-8456-4e13328aa0a7.png)

Also, notice the missing dark-transparent background for the text box.

The savegame you ask (it's the beginning of the tutorial)
[SpellForce.tar.gz](https://github.com/Joshua-Ashton/d9vk/files/4024009/SpellForce.tar.gz)

**Comment by Joshua-Ashton** [comment]
What's the easiest way I can get a box like that? It looks nice to debug :)

**Comment by NerosTie** [comment]
It's at the beginning of the campaign, during the tutorial.

**Comment by NerosTie** [comment]
There are no transparent textures anymore with DXVK 1.5.1 :)
The only remaining issue is the background for the textbox.

![Screenshot_20200110_000247](https://user-images.githubusercontent.com/4572452/72112087-e4eccd00-333c-11ea-9506-05289f0fc923.png)

**Comment by NerosTie** [comment]
![Screenshot_20200207_085957](https://user-images.githubusercontent.com/4572452/74011506-534a9c80-4988-11ea-9ee0-f452609ae74b.png)

Fixed! :)
