### ISSUE TITLE
AquaNox 2 → EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#471]
When I want to change the resolution, I have this error:
![Screenshot_20191209_111433](https://user-images.githubusercontent.com/4572452/70427767-a4680e00-1a75-11ea-8d72-2a3906fd38e2.png)

### System information
- GPU: Nvidia GT 730M
- Driver: 440.36
- Wine version: Proton 4.11
- DXVK version: #1013

### Log files
[aquanox2-d9vk.log](https://github.com/Joshua-Ashton/d9vk/files/3939090/aquanox2-d9vk.log)
[aquanox2-wined3d.log](https://github.com/Joshua-Ashton/d9vk/files/3939091/aquanox2-wined3d.log)

**Comment by SDN-Arkhen** [comment]
Changing resolution in Aquanox 2 demo is working just fine with wine-staging 4.21 on my PC. Maybe it's just proton 4.11 problem? Or perhaps you need to disable hyperthreading support in the game options. I can't test it because I don't have intel processor.

**Comment by NerosTie** [comment]
Tested with Proton 4.21-GE and I have the same result.

**Comment by SDN-Arkhen** [comment]
Hmm, probably that crash only happen in the full version. Anyway, have you tried disabling/enabling hyperthreading support in the options menu?

**Comment by NerosTie** [comment]
I can't modify this option it's grey. So, no.

**Comment by NerosTie** [comment]
I can't launch the game anymore. I'm stuck on a black screen.

Tested with DXVK 1316.

[steam-39640.tar.gz](https://github.com/Joshua-Ashton/d9vk/files/4779079/steam-39640.tar.gz)

**Comment by Blisto91** [comment]
@NerosTie If this is this is still an issue with latest dxvk then please move the issue to that repo. 🙂

**Comment by NerosTie** [comment]
Duplicate with https://github.com/doitsujin/dxvk/issues/3255

I close this one.
