### ISSUE TITLE
GW2 with d3d9 can't have a window/software in "front"/"always on top"

### ISSUE THREAD

**Issue by nykoo** [Joshua-Ashton/d9vk#475]
Hi,

Not sure if it's an issue but with d3d9.dll in gw2 x64 i can't have a window/software in top of the game in fullscreen windowed mode. Even if the software is tagged as "always in front".

This is is a bit annonying for some hardware monitor soft i use.

If it's a know issue and if someone know a solution, that will be great as without d3d9 guild wars 2 is unplayable :(

GPU: RX 5700 XT (last AMD driver 19.12.2)
gw2.exe in x64
d3d9 last version from d9vk jobs -> https://git.froggi.es/joshua/d9vk/-/jobs (was the same problem with some previous version)

Thank you.

**Comment by logan001** [comment]
Do you mean TacO or the likes?

**Comment by nykoo** [comment]
No not TacO (i haven't tried with TacO) some hardware monitoring like CPU/GPU temp, GPU/CPU usage or ispy with a cctv monitor in a small bottom window (foced in always on top).

**Comment by Joshua-Ashton** [comment]
Hi,
Borderless Vulkan windows by default that encompass the screen will steal exclusive fullscreen rights.

I'll add a config option to disable this behaviour.

**Comment by nykoo** [comment]
:D :D thank you very much :D :D

**Comment by nykoo** [comment]
Thank you for the option... but i certainly did something wrong as this don't seems to work :(

- copy dxvk.conf to my game directory where d3d9.dll is (C:\Guild Wars 2\bin64\)
- i set de dxvk.conf directory in variables (C:\Guild Wars 2\bin64\dxvk.conf)
- i passed d3d9.enableDialogMode to True
- i uncheck d3d9.enableDialogMode in dxvk.conf

But not working for me :( game still in exclusive top

Here is a part of my d3d9 debug log, if you know what i missed. Thank you very much

> info:  Game: Gw2-64.exe
> info:  DXVK: v1.4.6
> info:  Found config file: C:\Guild Wars 2\bin64\dxvk.conf
> info:  Effective configuration:
> info:    d3d9.enableDialogMode = True
> info:  Built-in extension providers:
> info:    Win32 WSI
> info:    OpenVR
> warn:  OpenVR: Failed to locate module
> info:  Enabled instance extensions:
> info:    VK_KHR_get_physical_device_properties2
> info:    VK_KHR_get_surface_capabilities2
> info:    VK_KHR_surface
> info:    VK_KHR_win32_surface
> warn:  D3D9: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
> info:  AMD Radeon RX 5700 XT:
> info:    Driver: 2.0.116
> info:    Vulkan: 1.1.125

**Comment by Joshua-Ashton** [comment]
Can you send the full log?

**Comment by nykoo** [comment]
Here it is

[Gw2-64_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3964264/Gw2-64_d3d9.log)

**Comment by nykoo** [comment]
Still don't work with last Version 0.40.1 - Croakacola Zero 🥤0️⃣🐸  :D 
i'd remove d3dcompiler_43.dll but it went recreat as soon i launch game, don't know if it can be part of my problem.
i certainly did something wrong :( if have any idea, will be great :) :)

Thank you very much and sorry for my english (and my inexistant coding skills)

**Comment by Joshua-Ashton** [comment]
Hm, it's working fine here.

Perhaps your issue is just that the game is flagging the window as always on top, in which there isn't really anything I can do about that 🤷‍♀️

**Comment by Joshua-Ashton** [comment]
Is GW2 x64 or x86? I have something for you to try.

**Comment by nykoo** [comment]
x64
Will check and try tomorrow as it's 2:24am here and time to sleep :)

Thank you for your answer

**Comment by nykoo** [comment]
I test again this morning, this have definitly something to do with d3d9.dll as when i remove it i can have somthing in front of the game (always on top) without problem.

- gw2 is in x64
- i tried disable fullscreen optimization of the exe fils without any improvement
- i checked again and my dxvk.conf as d3d9.enableDialogMode = True and uncomment

Really don't know what the problem is... anyway can still play the game with your d3d9.dll so really thank you for that and too bad if i can't have soft in front but not so vital anyway :)
