### ISSUE TITLE
About setting dialog mode

### ISSUE THREAD

**Issue by shijiediyo** [Joshua-Ashton/d9vk#477]
A new warning appeared in the Journal
[client64_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3967442/client64_d3d9.log)
If this problem only appears in win10 system, I give up, I also found a solution

**Comment by K0bin** [comment]
What exactly is the problem?

**Comment by shijiediyo** [comment]
After using d9vk, you will change the display Settings of the game and will not be able to use the full-screen window, but after creating your own desktop display resolution and reducing the horizontal resolution, there will be no problem

**Comment by shijiediyo** [comment]
Use d9vk, in win10 system will change the display Settings of the game, will not be able to use the full screen window, but in their own creation of a desktop display resolution, reduce the horizontal resolution, there will not be a problem

**Comment by Joshua-Ashton** [comment]
This should be fixed now (builds moved to https://git.froggi.es/doitsujin/dxvk/-/jobs)

**Comment by shijiediyo** [comment]
I try to run on win10, the game will collapse, delete this option, because the problem only appears in win10

**Comment by Joshua-Ashton** [comment]
I'm sorry, I don't understand what you're saying.

Can you post in your native language?

**Comment by shijiediyo** [comment]
我在win10用了dxvk，但是游戏里输入文字，游戏会停止运行，建议还是删除掉对话框模式吧

**Comment by Joshua-Ashton** [comment]
> I used dxvk in win10, but if I enter text in the game, the game will stop running. It is recommended to delete the dialog mode.

from: Google Translate

You're saying that entering text in the IME overlay since I added Dialog Mode crashes the game?

**Comment by shijiediyo** [comment]
是最近修改过的dxvk，前期的版本是没有问题
[client64_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/4029232/client64_d3d9.log)

**Comment by shijiediyo** [comment]
> > I used dxvk in win10, but if I enter text in the game, the game will stop running. It is recommended to delete the dialog mode.
> 
> from: Google Translate
> 
> You're saying that entering text in the IME overlay since I added Dialog Mode crashes the game?
> 
> I don't understand how dialog mode causes that, all it does is disable exclusive fullscreen...

哥们，经过1个月的学习，发现对话框模式在全屏模式无法使用。。。。对你造成了的困扰，不好意思！！！
