### ISSUE TITLE
The Sims 4 crashes right at intro

### ISSUE THREAD

**Issue by Zemogiter** [Joshua-Ashton/d9vk#478]
[wine.log](https://github.com/Joshua-Ashton/d9vk/files/3997868/wine.log)

### Software information
The Sims 4, 64bit wineprefix with vcrun2010, 2015, and 2017, set `msvcr120` and `api-ms-win-core-path-l1-1-0` to Native (based on https://bugs.winehq.org/show_bug.cgi?id=44999 ) but that did not solve the problem
### System information
- GPU: GTX 1080ti
- Driver: 440.44
- Wine version: 4.21
- DXVK version: 0.40.1

### Apitrace file(s)
[TS4_x64.zip](https://github.com/Joshua-Ashton/d9vk/files/3988161/TS4_x64.zip)

### Log files
- d3d9.log:
[Origin_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3988109/Origin_d3d9.log)
[igoproxy_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3988114/igoproxy_d3d9.log)
[IGOProxy64_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3988115/IGOProxy64_d3d9.log)
[TS4_x64_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3988116/TS4_x64_d3d9.log)
- d3d11.log:
[Origin_d3d11.log](https://github.com/Joshua-Ashton/d9vk/files/3988119/Origin_d3d11.log)
[igoproxy_d3d11.log](https://github.com/Joshua-Ashton/d9vk/files/3988120/igoproxy_d3d11.log)
[IGOProxy64_d3d11.log](https://github.com/Joshua-Ashton/d9vk/files/3988121/IGOProxy64_d3d11.log)
- dxgi.log (the log file for TS4_x64.exe is empty so I did not upload it):
[Origin_dxgi.log](https://github.com/Joshua-Ashton/d9vk/files/3988126/Origin_dxgi.log)
[igoproxy_dxgi.log](https://github.com/Joshua-Ashton/d9vk/files/3988127/igoproxy_dxgi.log)
[IGOProxy64_dxgi.log](https://github.com/Joshua-Ashton/d9vk/files/3988128/IGOProxy64_dxgi.log)

**Comment by tannisroot** [comment]
I've tested it with DXVK 1.5 and it works perfectly fine.

**Comment by Zemogiter** [comment]
Retested with DXVK 1.5, crashes with the exact same error.

**Comment by tannisroot** [comment]
What error?

**Comment by Zemogiter** [comment]
The one in wine.log

**Comment by tannisroot** [comment]
That's not a crash or even a real error, that just says that you disabled winemenubuilder.
Please retest with a new fresh prefix without any workarounds.

**Comment by Zemogiter** [comment]
Oh wait that's not the right log file here is the correct one:
[wine.log](https://github.com/Joshua-Ashton/d9vk/files/3997873/wine.log)

**Comment by lieff** [comment]
```

**Comment by Zemogiter** [comment]
```
ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63648
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63648
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by lieff** [comment]
```

**Comment by lieff** [comment]
@Zemogiter Can you re-check with ulimit -aH, I forgot we need look at hard limit.

**Comment by Zemogiter** [comment]
```
ulimit -aH
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63648
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63648
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by lieff** [comment]
Then it can be file-system issue and python file/module name collision. Is it located on ntfs or ext4 etc?

**Comment by Zemogiter** [comment]
It's on ext4 partition.

**Comment by lieff** [comment]
Weird, https://github.com/supernova-project/GNU-Linux/blob/4513da25dbb059209daa28d04e6bc295515d813b/core/Python-3.7.4/Python/pylifecycle.c#L1830
it's just loads few modules and wraps stdin/stdout/stderr. It looks like limit/file-system issue, or may be python interpreter dll depends on some other dll which broken in prefix. You can add +loaddll to WINEDEBUG to see all loaded dlls in wine log.

**Comment by Zemogiter** [comment]
log file with fixme-all,+loaddll
[wine.log](https://github.com/Joshua-Ashton/d9vk/files/3998751/wine.log)

**Comment by lieff** [comment]
```
0009:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\msvcr120.dll" at 0x7d3a0000: builtin
```
Probably this. python37_x64.dll depends on MSVCR120.dll, and wine version of MSVCR120.dll are used. So setting msvcr120 to native do not works for some reason.
