### ISSUE TITLE
[question] how to apitrace for D9VK?

### ISSUE THREAD

**Issue by axredneck** [Joshua-Ashton/d9vk#48]
I try to apitrace Stalker Shadows of Chernobyl (D3D9 game).
DXVK suggests to do this: `wine apitrace.exe trace -a dxgi YOURGAME.exe`
But apitrace says this:
`warning: Z:\home\redneck\programs\apitrace-msvc\x86\bin\..\lib\wrappers\dxgitrace.dll was never used: application probably does not use this API`
and doesn't produce .trace file, while the game works while being apitraced.

**Comment by tannisroot** [comment]
It's not being apitraced. You need to use `d3d9` instead of `dxgi`.
It's all in the apitrace manual btw: https://github.com/apitrace/apitrace/blob/master/docs/USAGE.markdown

**Comment by axredneck** [comment]
> https://github.com/apitrace/apitrace/blob/master/docs/USAGE.markdown

Better https://tracehub.froggi.es/
