### ISSUE TITLE
[Question] Which version of d3d9.dll is more appropriate for GW2?

### ISSUE THREAD

**Issue by guidomedina** [Joshua-Ashton/d9vk#480]
Which version of d3d9.dll is more appropriate for GW2, the official release hosted here on Github or the one you regularly build on https://git.froggi.es/joshua/d9vk/-/jobs ?

It seems that the ones you build on Froggi are more recent?

**Comment by Joshua-Ashton** [comment]
Use this now: https://git.froggi.es/doitsujin/dxvk/-/jobs

The project got merged upstream.
