### ISSUE TITLE
lutris league of legends not works with d9vk

### ISSUE THREAD

**Issue by BLOODYCOOT** [Joshua-Ashton/d9vk#481]
### Software information
Lutris Vsyscall32 override w/d9vk version

### System information
- GPU: sapphire r9 270 2gb 256 bit
- Driver: radeon
- Wine version: wine-4.18 (Staging) main, in lutris Wine Lol 4.20

https://ibb.co/CWZpbSV

**Comment by K0bin** [comment]
> Vulkan is not installed [...] on your system

That's the problem. Please make sure you have both 64 bit 32 bit Vulkan drivers installed.
https://github.com/doitsujin/dxvk/wiki/Common-issues#vulkan-errors

**Comment by BLOODYCOOT** [comment]
ı have dxvk drivers https://ibb.co/XkFCFym

**Comment by K0bin** [comment]
First of all: both the driver (Mesa) and DXVK shown in that screenshot are super outdated and will cause lots of issues.

Second: this doesn't prove that you have a **32 bit** Vulkan driver installed or that your driver is working correctly.
