### ISSUE TITLE
Alt+Tab not working after d9vk

### ISSUE THREAD

**Issue by nasiftanjim** [Joshua-Ashton/d9vk#484]
I tried GTA 4 & San Andreas with d9vk but after that can't alt+tab nor take screenshot as it comes black.

**Comment by K0bin** [comment]
#482

The alt tabbing is a known issue. No one is really interested in fixing that.

>  nor take screenshot as it comes black.

That's a Windows problem. Nothing we can do on that. Use something that can take screenshots in Vulkan fullscreen applications.

**Comment by misyltoad** [comment]
D9VK dead use dxvk
