### ISSUE TITLE
[Question] Is the D9VK ready for testing?

### ISSUE THREAD

**Issue by Kerrung** [Joshua-Ashton/d9vk#5]
@Joshua-Ashton Hi! Thank you for your great work!
Sorry, but I just want to ask you, what the current readiness of your project? How much is it currently ready? Can I just now try to test it with a few games that I usually play or it will be better if I will wait some more time?

**Comment by Tk-Glitch** [comment]
As of right now it's still a bit too early. Also it will currently fail to build on Linux. Soon™
![Screenshot_20190327_011336](https://user-images.githubusercontent.com/741977/55169071-68557d00-5174-11e9-8ac6-f0b98e788cb4.png)

**Comment by Kerrung** [comment]
@Tk-Glitch thank you!
And how can I find out about when it will be possible to try it?

**Comment by TedsterTech** [comment]
Because it's in development, it's inherent that it'll improve with time. I would suggest waiting a while before sinking your time into it, but what Josh has shown me is very, very promising.

**Comment by TedsterTech** [comment]
> @Tk-Glitch thank you!
> And how can I find out about when it will be possible to try it?

Just keep paying attention. Josh is busy and is doing this in his free time (:

**Comment by ronoverdrive** [comment]
@Kerrung when you hear the frog chirping uncontrollably in the swamp. ;P

**Comment by Kerrung** [comment]
Okay. I am very interested to test, whether D9VK will work faster than Gallium Nine Standalone?

**Comment by TedsterTech** [comment]
> Okay. I am very interested to test, whether D9VK will work faster than Gallium Nine Standalone?

It looks like you're asking questions about indeterminate thing that will change over time; you'd best try for yourself if you want to see.

**Comment by Joshua-Ashton** [comment]
Soon

**Comment by jp7677** [comment]
@Kerrung I'm certainly not in the position to answer for Joshua, though while your enthusiasm is appreciated, I would suggest to refrain yourself from opening (for now useless) issues until there is at least a tagged version of v9dk that is targeted for broader usage.

**Comment by ahmed-elsayed2017** [comment]
It will be interesting to see SweetFX running with D9VK.

**Comment by TedsterTech** [comment]
> @Kerrung I'm certainly not in the position to answer for Joshua, though while your enthusiasm is appreciated, I would suggest to refrain yourself from opening (for now useless) issues until there is at least a tagged version of v9dk that is targeted for broader usage.

Useless? Wasteful, I'd say

**Comment by Joshua-Ashton** [comment]
Closing this issue as I think the question has been answered.
