### ISSUE TITLE
Trine 2 - The main menu is rotated and there is no text

### ISSUE THREAD

**Issue by Ahmed-E-86** [Joshua-Ashton/d9vk#50]
### Software information
![Screenshot from 2019-04-29 02-46-54](https://user-images.githubusercontent.com/29783425/56872421-221c6380-6a29-11e9-9a1e-2be1b0337c85.png)

### System information
- GPU: HD 8750M
- Driver: Mesa 19.0.2
- Wine version: 4.7
- D9VK version: e1886cc8

### Log files
- d3d9.log: 
[trine2_32bit_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3125716/trine2_32bit_d3d9.log)

### The main menu is rotated to the right direction and there is no text
![Screenshot from 2019-04-29 02-26-10](https://user-images.githubusercontent.com/29783425/56872547-796f0380-6a2a-11e9-8d5c-05d61f6dc74f.png)

### That is how it looks with wined3d
![Screenshot from 2019-04-29 02-23-41](https://user-images.githubusercontent.com/29783425/56872553-97d4ff00-6a2a-11e9-8c26-4796c21a48d7.png)

### The loading screen is rotated also with d9vk
![Screenshot from 2019-04-29 02-25-29](https://user-images.githubusercontent.com/29783425/56872580-d5d22300-6a2a-11e9-8fc1-cd4b5c7a2f5d.png)

**Sorry for not recording apitrace, if you need it, please tell me, and I will record it.**

**Comment by Kron4ek** [comment]
The same issue in Flatout 2.

![Снимок экрана от 2019-04-29 13-21-45](https://user-images.githubusercontent.com/13851877/56883998-d1852480-6a81-11e9-8dd4-6d4565de9703.png)

**Comment by LeJimster** [comment]
Have you guys tried a recent build?  I was experiencing a similar bug in Borderlands and had created an apitrace, screenshots, etc.  I decided to try a recent build of d9vk first and found it had already been fixed!
I was using `98a24c89`

**Comment by Joshua-Ashton** [comment]
> 
> 
> The same issue in Flatout 2.
> 
> ![Снимок экрана от 2019-04-29 13-21-45](https://user-images.githubusercontent.com/13851877/56883998-d1852480-6a81-11e9-8dd4-6d4565de9703.png)

works fine here

**Comment by Joshua-Ashton** [comment]
Regarding flatout 2, please use a REAL d3d9x and d3dcompiler (ie not a broken crappy Wine one)

**Comment by ahmed-elsayed2017** [comment]
> Have you guys tried a recent build? I was experiencing a similar bug in Borderlands and had created an apitrace, screenshots, etc. I decided to try a recent build of d9vk first and found it had already been fixed!
> I was using `98a24c89`

That commit fixed the issue of loading screen, and the main menu, but still there is no text in the main menu

![Screenshot from 2019-05-02 03-54-29](https://user-images.githubusercontent.com/29783425/57053453-72482f80-6c8e-11e9-9496-2efe4af3fbfc.png)

**Comment by Kron4ek** [comment]
Yup, Flatout 2 works fine now.

**Comment by LeJimster** [comment]
I just tested Trine 2 and I also noticed no text for the menus and some graphical corruption/flickering in the background.  I've created a trace.  I would suggest anyone posting bug reports always create a trace, especially if you want somebody to spend time fixing it, it's the least you can do =).

Strangely the game crashes for me on subsequent attempts to launch with an unhandled acception.

![Trine2-unhandled-error](https://user-images.githubusercontent.com/35663469/57074794-dc87c100-6cdc-11e9-9971-4da90570ff63.jpg)

### System information
GPU: RX Vega 56
Driver: Mesa 19.1-git (git-07745f9494)
Wine version: Proton 4.2-3
D9VK version: 98a24c89

### Log files
- d3d9.log: [trine2_32bit_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3137911/trine2_32bit_d3d9.log)
- [trine2.log](https://github.com/Joshua-Ashton/d9vk/files/3137930/trine2.log)
- [trine2_32bit.exe_3d529d38.dmp.zip](https://github.com/Joshua-Ashton/d9vk/files/3137934/trine2_32bit.exe_3d529d38.dmp.zip)

### Apitrace
- https://drive.google.com/open?id=1abDFf7RPOju5kZ_eZ2zq_kpGWK0GB0X5

**Comment by ahmed-elsayed2017** [comment]
@LeJimster I am sorry about that. I tried to do it before, but it always fails to record. Do you record apitrace with d3d9.dll native or builtin?

**Comment by LeJimster** [comment]
@ahmed-elsayed2017 to be fair I tend to run into trouble creating traces on linux.  I have done them before, but they often fail.  I'm definitely no expert, lol!

I have a separate windows 10 drive that I plug into a usb hdd dock when I need to test something out on windows.  I use valves apitrace  and just drop it into the games folder and then run the game.

I need to have another go at making traces on linux, maybe follow Joshua's guide?  https://tracehub.froggi.es/

**Comment by BLaDZer** [comment]
@ahmed-elsayed2017 use native(windows, apitrace) instead of builtin(wine implementation). 

For quick trace and don't change global wine config use something like this:
`WINEDLLOVERRIDES="d3d9=n" wine /path_to/apitrace.exe trace -a d3d9 /path_to/game_dx9.exe`
then I found `game.trace` file in my Desktop folder(idk why there).

**Comment by LeJimster** [comment]
Just had a quick test with a recent build: a0bfc932
Seems fine now, no bugs that I saw from a quick run through.

**Comment by ahmed-elsayed2017** [comment]
@LeJimster Yeah it runs without any problems so far with latest d9vk build.

**Comment by Ahmed-E-86** [comment]
The issue with no text for the menu happens again with DXVK 1.5.5
