### ISSUE TITLE
ReShade doesn't work

### ISSUE THREAD

**Issue by Sporif** [Joshua-Ashton/d9vk#52]
https://reshade.me/

Tried it with Arkham Asylum and the game just hangs on launch. Portal 2 shows the same error but ReShade doesn't show up. Black Ops launches but has a second screen in the top left.
All these games work fine before adding the ReShade d3d9.dll to the game folder. 

Here's the d3d9.log from ReShade for Arkham Asylum:

```
13:34:02:095 [00065] | INFO  | Initializing crosire's ReShade version '4.2.1.542' (32-bit) built on '2019-03-04 22:32:13' loaded from "Z:\mnt\storage2\SteamLibrary\SteamApps\common\Batman Arkham Asylum GOTY\Binaries\d3d9.dll" to "Z:\mnt\storage2\SteamLibrary\SteamApps\common\Batman Arkham Asylum GOTY\Binaries\ShippingPC-BmGame.exe" ...
13:34:02:109 [00065] | INFO  | Registering hooks for "user32.dll" ...
13:34:02:109 [00065] | INFO  | > Libraries loaded.
13:34:02:110 [00065] | INFO  | > Found 13 match(es). Installing ...
13:34:02:114 [00065] | INFO  | Registering hooks for "ws2_32.dll" ...
13:34:02:114 [00065] | INFO  | > Libraries loaded.
13:34:02:114 [00065] | INFO  | > Found 8 match(es). Installing ...
13:34:02:117 [00065] | INFO  | Registering hooks for "C:\windows\system32\d3d9.dll" ...
13:34:02:117 [00065] | INFO  | > Delayed until first call to an exported function.
13:34:02:118 [00065] | INFO  | Registering hooks for "C:\windows\system32\d3d10.dll" ...
13:34:02:118 [00065] | INFO  | > Delayed.
13:34:02:118 [00065] | INFO  | Registering hooks for "C:\windows\system32\d3d10_1.dll" ...
13:34:02:119 [00065] | INFO  | > Delayed.
13:34:02:119 [00065] | INFO  | Registering hooks for "C:\windows\system32\d3d11.dll" ...
13:34:02:121 [00065] | INFO  | > Delayed.
13:34:02:121 [00065] | INFO  | Registering hooks for "C:\windows\system32\dxgi.dll" ...
13:34:02:122 [00065] | INFO  | > Delayed.
13:34:02:122 [00065] | INFO  | Registering hooks for "C:\windows\system32\opengl32.dll" ...
13:34:02:122 [00065] | INFO  | > Delayed.
13:34:02:122 [00065] | INFO  | Initialized.
13:34:02:728 [00065] | INFO  | Redirecting Direct3DCreate9(32) ...
13:34:02:742 [00065] | INFO  | Installing export hooks for "C:\windows\system32\d3d9.dll" ...
13:34:02:742 [00065] | INFO  | > Found 9 match(es). Installing ...
13:34:02:857 [00065] | INFO  | Installing delayed hooks for "C:\windows\system32\opengl32.dll" (Just loaded via LoadLibrary("ddraw.dll")) ...
13:34:02:857 [00065] | INFO  | > Found 359 match(es). Installing ...
13:34:02:924 [00065] | INFO  | Redirecting wglChoosePixelFormat(00260049, 02F8DE14) ...
13:34:02:925 [00065] | INFO  | > Dumping pixel format descriptor:
13:34:02:925 [00065] | INFO  |   +-----------------------------------------+-----------------------------------------+
13:34:02:925 [00065] | INFO  |   | Name                                    | Value                                   |
13:34:02:925 [00065] | INFO  |   +-----------------------------------------+-----------------------------------------+
13:34:02:925 [00065] | INFO  |   | Flags                                   | 0x25                                    |
13:34:02:925 [00065] | INFO  |   | ColorBits                               | 32                                      |
13:34:02:925 [00065] | INFO  |   | DepthBits                               | 0                                       |
13:34:02:925 [00065] | INFO  |   | StencilBits                             | 0                                       |
13:34:02:925 [00065] | INFO  |   +-----------------------------------------+-----------------------------------------+
13:34:02:926 [00065] | INFO  | > Returned format: 3
13:34:02:926 [00065] | INFO  | Redirecting wglSetPixelFormat(00260049, 3, 02F8DE14) ...
13:34:02:926 [00065] | INFO  | Redirecting wglCreateContext(00260049) ...
13:34:02:926 [00065] | INFO  | > Passing on to 'wglCreateLayerContext' ...
13:34:02:926 [00065] | INFO  | Redirecting wglCreateLayerContext(00260049, 0) ...
13:34:02:926 [00065] | INFO  | Redirecting wglCreateContext(00260049) ...
13:34:02:926 [00065] | INFO  | > Passing on to 'wglCreateLayerContext' ...
13:34:02:926 [00065] | INFO  | Redirecting wglCreateLayerContext(00260049, 0) ...
13:34:02:926 [00065] | INFO  | Redirecting wglCreateContext(00260049) ...
13:34:02:927 [00065] | INFO  | > Passing on to 'wglCreateLayerContext' ...
13:34:02:927 [00065] | INFO  | Redirecting wglCreateLayerContext(00260049, 0) ...
13:34:02:927 [00065] | INFO  | Redirecting wglCreateContext(00260049) ...
13:34:02:927 [00065] | INFO  | > Passing on to 'wglCreateLayerContext' ...
...
```
The log goes on but just keeps repeating these lines
```
Redirecting wglCreateLayerContext(00260049, 0) ...
Redirecting wglCreateContext(00260049) ...
 > Passing on to 'wglCreateLayerContext' ...
```

**Comment by Riesi** [comment]
This is not a d9vk issue. You can clearly see that its failing at the opengl hook in the log.
What wine version are you using? This should be fixed in >=4.3.
But even with new wine versions d9vk wont work, if the opengl hook succeeds. It will crash in some wine code iirc. I will take a look at Reshade and nag Josh when the project is more major, but for now it does not make sense at all.
Also Reshade 4.2 and newer are more broken than 4.1 on wine.

**Comment by Sporif** [comment]
I tried with both wine 4.6 and 4.7 and tested both ReShade 4.1 and 4.2. But why is there an opengl hook failing with d9vk when it doesn't with dxvk?

**Comment by Joshua-Ashton** [comment]
Does the same issue occur with WineD3D/G9? I'm guessing it does. If so, it's not my issue.

**Comment by Eignar17** [comment]
@Riesi  @Joshua-Ashton  reshade work fine 
22:05:29:513 [00009] | INFO  | Initializing crosire's ReShade version '4.1.1.495' (32-bit) built on '2019-01-23 23:34:27' loaded from "C:\\Program Files\\EA GAMES\\Need for Speed Most Wanted\\d3d9.dll" to "C:\\Program Files\\EA GAMES\\Need for Speed Most Wanted\\speed.exe" ...
22:05:29:519 [00009] | INFO  | Registering hooks for "user32.dll" ...
22:05:29:519 [00009] | INFO  | > Libraries loaded.
22:05:29:519 [00009] | INFO  | > Found 13 match(es). Installing ...
22:05:29:521 [00009] | INFO  | Registering hooks for "ws2_32.dll" ...
22:05:29:521 [00009] | INFO  | > Libraries loaded.
22:05:29:521 [00009] | INFO  | > Found 8 match(es). Installing ...
22:05:29:522 [00009] | INFO  | Registering hooks for "C:\\windows\\system32\\d3d9.dll" ...
22:05:29:522 [00009] | INFO  | > Delayed until first call to an exported function.
22:05:29:522 [00009] | INFO  | Registering hooks for "C:\\windows\\system32\\d3d10.dll" ...
22:05:29:523 [00009] | INFO  | > Delayed.
22:05:29:523 [00009] | INFO  | Registering hooks for "C:\\windows\\system32\\d3d10_1.dll" ...
22:05:29:523 [00009] | INFO  | > Delayed.
22:05:29:523 [00009] | INFO  | Registering hooks for "C:\\windows\\system32\\d3d11.dll" ...
22:05:29:525 [00009] | INFO  | > Delayed.
22:05:29:525 [00009] | INFO  | Registering hooks for "C:\\windows\\system32\\dxgi.dll" ...
22:05:29:526 [00009] | INFO  | > Delayed.
22:05:29:526 [00009] | INFO  | Registering hooks for "C:\\windows\\system32\\opengl32.dll" ...
22:05:29:526 [00009] | INFO  | > Delayed.
22:05:29:526 [00009] | INFO  | Initialized.
22:05:29:793 [00009] | INFO  | Redirecting 'Direct3DCreate9(32)' ...
22:05:29:805 [00009] | INFO  | Installing export hooks for "C:\\windows\\system32\\d3d9.dll" ...
22:05:29:805 [00009] | INFO  | > Found 9 match(es). Installing ...
22:05:29:934 [00009] | INFO  | Redirecting 'RegisterClassExA(0033FD98)' ...
22:05:29:934 [00009] | INFO  | > Adding 'CS_OWNDC' window class style flag to 'GameFrame'.
22:05:29:954 [00009] | INFO  | Redirecting 'IDirect3D9::CreateDevice(00DE13F8, 0, 1, 00010054, 0x40, 0093E82C, 00982BDC)' ...
22:05:29:955 [00009] | INFO  | > Dumping presentation parameters:
22:05:29:955 [00009] | INFO  |   +-----------------------------------------+-----------------------------------------+
22:05:29:955 [00009] | INFO  |   | Parameter                               | Value                                   |
22:05:29:955 [00009] | INFO  |   +-----------------------------------------+-----------------------------------------+
22:05:29:955 [00009] | INFO  |   | BackBufferWidth                         | 1280                                    |
22:05:29:955 [00009] | INFO  |   | BackBufferHeight                        | 1024                                    |
22:05:29:955 [00009] | INFO  |   | BackBufferFormat                        | 21                                      |
22:05:29:955 [00009] | INFO  |   | BackBufferCount                         | 0                                       |
22:05:29:955 [00009] | INFO  |   | MultiSampleType                         | 1                                       |
22:05:29:955 [00009] | INFO  |   | MultiSampleQuality                      | 3                                       |
22:05:29:955 [00009] | INFO  |   | SwapEffect                              | 1                                       |
22:05:29:955 [00009] | INFO  |   | DeviceWindow                            | 00010054                                |
22:05:29:955 [00009] | INFO  |   | Windowed                                | FALSE                                   |
22:05:29:955 [00009] | INFO  |   | EnableAutoDepthStencil                  | TRUE                                    |
22:05:29:955 [00009] | INFO  |   | AutoDepthStencilFormat                  | 75                                      |
22:05:29:955 [00009] | INFO  |   | Flags                                   | 0                                       |
22:05:29:955 [00009] | INFO  |   | FullScreen_RefreshRateInHz              | 0                                       |
22:05:29:955 [00009] | INFO  |   | PresentationInterval                    | 0x80000000                              |
22:05:29:955 [00009] | INFO  |   +-----------------------------------------+-----------------------------------------+
22:05:29:955 [00009] | WARN  | > Multisampling is enabled. This is not compatible with depth buffer access, which was therefore disabled.
22:05:30:875 [00009] | INFO  | Recreated runtime environment on runtime 0019CDB8.
22:05:35:203 [00009] | INFO  | Loading image files for textures ...
22:09:21:240 [00009] | INFO  | Destroyed runtime environment on runtime 0019CDB8.
22:09:21:242 [00009] | WARN  | Reference count for 'IDirect3DDevice9' object 001F0100 is inconsistent: 4294967295, but expected 0.
22:09:21:243 [00009] | INFO  | Exiting ...
22:09:21:243 [00009] | INFO  | Uninstalling 35 hook(s) ...
22:09:21:245 [00009] | INFO  | Exited.

**Comment by Eignar17** [comment]
![Captura de pantalla -2019-04-29 22-44-19](https://user-images.githubusercontent.com/8561550/56939923-eccb5080-6ad0-11e9-922d-84dbb13ff4f4.png)

**Comment by ahmed-elsayed2017** [comment]
> Does the same issue occur with WineD3D/G9? I'm guessing it does. If so, it's not my issue.

Reshade has never worked with wined3d, and it didn't even work with DXVK until someone stepped and fix that. This was his post in reddit after his first attempt to get Reshade working with DXVK (It was 5 months ago)

https://www.reddit.com/r/linux_gaming/comments/a2d7xv/reshade_is_now_working_with_latest_dxvk_master/

**Comment by ahmed-elsayed2017** [comment]
`ReShade_Setup_4.2.1.exe` doesn't work when `d3d9` set to native, so I had to go to winecfg and add `ReShade_Setup_4.2.1.exe` and set `d3d9` to `builtin` to be able to launch it, otherwise the main screen of Reshade will be completely black.

**Comment by aqxa1** [comment]
Just tested Reshade 4.1.1 with Proton (D9VK 0.20) and wine-staging-4.15 with D9VK git, and it's working for me with Arkham Asylum, Grand Theft Auto IV, and Mirror's Edge.

Tested SMAA and adaptive sharpening, without any obvious issues. 

GPU: 5700 XT
Driver: RADV git (LLVM 10)

**Comment by ahmed-elsayed2017** [comment]
> Just tested Reshade 4.1.1 with Proton (D9VK 0.20) and wine-staging-4.15 with D9VK git, and it's working for me with Arkham Asylum, Grand Theft Auto IV, and Mirror's Edge.
> 
> Tested SMAA and adaptive sharpening, without any obvious issues.
> 
> GPU: 5700 XT
> Driver: RADV git (LLVM 10)

Good to know that it is working with D9VK, but when I tested it with DXVK, I didn't notice any difference with SMAA turned on or off. I tried to raise all settings to the maximum, and still didn't feel any difference at all.
