### ISSUE TITLE
Shader compiler fails to parse some shaders

### ISSUE THREAD

**Issue by geneishouko** [Joshua-Ashton/d9vk#53]
The d9vk shader compiler fails to parse some shaders with invalid opcodes and out of range source registers

```
err:   DxsoDecodeContext::decodeSourceRegister: source register out of range.
err:   DxsoDecodeContext::decodeSourceRegister: source register out of range.
err:   DxsoDecodeContext::decodeSourceRegister: source register out of range.
err:   DxsoDecodeContext::decodeSourceRegister: source register out of range.
err:   DxsoDecodeContext::decodeSourceRegister: source register out of range.
err:   DxsoDecodeContext::decodeSourceRegister: source register out of range.
err:   DxsoDecodeContext::decodeSourceRegister: source register out of range.
err:   DxsoDecodeContext::decodeSourceRegister: source register out of range.
err:   DxsoDecodeContext::decodeSourceRegister: source register out of range.
err:   DxsoDecodeContext::decodeSourceRegister: source register out of range.
err:   DxsoDecodeContext::decodeSourceRegister: source register out of range.
warn:  DxsoCompiler::processInstruction: unhandled opcode: Invalid Opcode (2337)
warn:  DxsoCompiler::processInstruction: unhandled opcode: Invalid Opcode (21062)
warn:  DxsoCompiler::processInstruction: unhandled opcode: Invalid Opcode (248)
```

### Software information
Game is Artificial Academy 2. Default dxvk settings.

### System information
- GPU: Nvidia GTX 1050
- Driver: 418.56
- Wine version: 4.0
- DXVK version: d9vk master

### Apitrace files
https://mega.nz/#F!wYRXAYia!FQjOZi69z0sLf921baRw5g

### Shader dumps
~~[aa2edit-shadersv1.zip](https://github.com/Joshua-Ashton/d9vk/files/3133367/aa2edit-shadersv1.zip)~~
~~[aa2edit-shadersv2.zip](https://github.com/Joshua-Ashton/d9vk/files/3133368/aa2edit-shadersv2.zip)~~

### Log files
- d3d9.log:
~~[AA2Edit_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3133373/AA2Edit_d3d9.log)~~
[AA2Edit_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3402043/AA2Edit_d3d9.log)

**Comment by geneishouko** [comment]
Newest generated shaders https://mega.nz/#!pFoznIwL!WowM2gBOGuaDa0gLHX-IpU6udRlb-IVfz6xynpVRIRs

**Comment by K0bin** [comment]
Did you have Microsoft's d3dcompiler installed in your prefix when those errors appeared?

**Comment by geneishouko** [comment]
@K0bin 
Yes, I have all d3dcompiler 42 43 & 47 native overrides installed. Check out the most recent logs as of commit cb420d2976
https://github.com/Joshua-Ashton/d9vk/files/3402043/AA2Edit_d3d9.log

**Comment by geneishouko** [comment]
This issue has been fixed.
