### ISSUE TITLE
Endless Battle opens and closes or hangs in the startup logo

### ISSUE THREAD

**Issue by RivelinoDomingo** [Joshua-Ashton/d9vk#55]
" " 002b:fixme:vulkan:X11DRV_vkCreateWin32SurfaceKHR Application requires child window rendering, which is not implemented yet!
terminate called after throwing an instance of 'dxvk::DxvkError'
" "
[cos_l_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3135157/cos_l_d3d9.log)
Kde Neon
Wine staging 4.7

**Comment by Joshua-Ashton** [comment]
Not my bug. This is a WineVulkan issue.
