### ISSUE TITLE
Example Issue

### ISSUE THREAD

**Issue by StinkyAnimeGirl** [Joshua-Ashton/d9vk#58]
Here is an example issue for other peple to base theirs on:

Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Name of the game, settings used etc.

### System information
- GPU:
- Driver:
- Wine version: 
- DXVK version: 

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
- dxgi.log:

**Comment by rphsoftware** [comment]
***E X A M P L E    I S S U E***

**Comment by StinkyAnimeGirl** [comment]
remember to use d3d9 in apitrace and not dxgi

**Comment by StinkyAnimeGirl** [comment]
i will add more to this later

**Comment by rphsoftware** [comment]
remember to exist

**Comment by Joshua-Ashton** [comment]
> i will add more to this later
No, you won't.

**Comment by StinkyAnimeGirl** [comment]
Fuck you. I was trying to help.

**Comment by rphsoftware** [comment]
:frog:

**Comment by StinkyAnimeGirl** [comment]
I was only trying to help

**Comment by Joshua-Ashton** [comment]
> 
> 
> I was only trying to help

Yeah, well try harder next time 🐸

**Comment by Joshua-Ashton** [comment]
You just reposted the issue template, this is completely unnecessary.
