### ISSUE TITLE
The Guild 2 - rendering issues

### ISSUE THREAD

**Issue by Riesi** [Joshua-Ashton/d9vk#59]
The initial loading screen of the game renders black. The main menu UI isn't rendered, but the ingame background renders ok except for the npcs that move around.

The log file contains some unhandled op-codes and grows extremely fast due to a spam of `warn:  D3D9DeviceEx::SetMaterial: Stub`.

### System information
- GPU: GTX 970
- Driver: 418.52.05
- Wine version: 4.5 
- DXVK version: 4957fecd303b38f46fe67742c2c0fdea79861792

### Apitrace file(s)
https://git.froggi.es/Riesi/tracehub/raw/master/traces/d3d9/Guild%202%20%20%5Bnative%5D.tar.xz?inline=false

### Log files
[GuildII_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3137528/GuildII_d3d9.log)

**Comment by Joshua-Ashton** [comment]
Moving to global issue: #60
