### ISSUE TITLE
Fixed Function Implementation

### ISSUE THREAD

**Issue by Joshua-Ashton** [Joshua-Ashton/d9vk#60]
Title.

**Comment by Managor** [comment]
Oblivion works now at least.

**Comment by jtrees** [comment]
> Oblivion works now at least.

With Hypnofrog? I still got a black screen on that.

**Comment by Joshua-Ashton** [comment]
> > Oblivion works now at least.
> 
> With Hypnofrog? I still got a black screen on that.

Works fine for me

**Comment by jtrees** [comment]
My bad. I forgot to re-build after pulling. :see_no_evil: 

Performance is pretty low for me though (lower than stock proton). Is that normal? Or will it sort itself out once the shader cache has been generated?

**Comment by Joshua-Ashton** [comment]
np
