### ISSUE TITLE
Guild Wars 2 has lower fps with d9vk than normal wine

### ISSUE THREAD

**Issue by logan001** [Joshua-Ashton/d9vk#65]
The game seems to work pretty good for some users.
For me the game is working below wine staging.
The `DXVK_LOG_LEVEL=none` seems to have no effect on fps.
The details for the game are set at best appearance without depth blur and my fps is about 30-35 in normal (not reach in details) maps.
on a world boss  kill when lots of players are in the same place i had about 5-7 fps.
I've tried the game both on arch (kernet 5.0.11) and on linuxmint (kernel 4.15.0-48). both has the same low fps.

System information
- GPU: 970 GTX
- Driver: 418.56 (i also tried beta drivers)
- Wine version: 4.7 staging
- D9VK version: ab57adc

Log files
[Gw2-64_d3d9.log.zip](https://github.com/Joshua-Ashton/d9vk/files/3143684/Gw2-64_d3d9.log.zip)

**Comment by Joshua-Ashton** [comment]
Can you please try using a TKG wine build and see if that improves performance?

**Comment by ReaperOfSouls1909** [comment]
using lutris is the best way to test that out

**Comment by logan001** [comment]
with a new TKG prefix (lutris) I get about 10 fps more than wine (TKG) in that HoT map.
So the stats are like this wine staging with d9vk (no TKG) = 15fp < wine (TKG) no d9vk = 25 fps < wine (TKG) with d9vk=35fps
on another map i have 65-70 fps with tkg and d9vk compared to 45-48 with just TKG
definitely better than wine.
well im far from 140 fps as ReaperOfSouls1909 but at least im getting ~70 fps in the same place as that screenshot.

**Comment by michalszajnecki** [comment]
Please try 430.09 drivers. They do improve performance in Guild Wars 2.

![gw_2_nvidia_430](https://user-images.githubusercontent.com/5558640/57176116-2b0b9b80-6e54-11e9-9582-044af1ff25f8.png)

**Comment by logan001** [comment]
@michalszajnecki same performance with 430.09.
Well, even though i dont have such a huge fps in same place i'm still getting better performance than i'd get without d9vk.
seems that i TKG wine is needed.

**Comment by ronoverdrive** [comment]
After installing to a new prefix with DXVK_LOG_LEVEL=none and installing the latest git master I finally started to get decent FPS. Before I was getting around 20 - 25 FPS and now I'm getting between 55 - 85 which is much more playable. Still not getting 100+ like others, but this is a big improvement.

**Comment by logan001** [comment]
i've made a few tests windows 10 vs wine with d9vk with 18c78ce
some maps has about same fps and some has 20 lower fps than w10. at least on my setup
seems that PoF and HoT maps are slower on wine than windows.
[here](https://drive.google.com/open?id=1IkipGsIYn5Pu-cRVTwJxVTao78qO9HkB) are some screenshots

**Comment by logan001** [comment]
question: what should be the settings in lutris for DX/9VK?
i don't know what else to put in there other then DXVK_HUD=whatever you like  DXVK_LOG_LEVEL=none and STAGING_SHARED_MEMORY=1 (i have no clue what it does but sound interesting :) ).
