### ISSUE TITLE
Dark Messiah of Might and Magic crash on start

### ISSUE THREAD

**Issue by cyro666** [Joshua-Ashton/d9vk#67]
### Software information
Tried with a few Proton releases and also wine 4.7

### System information
- GPU: AMD RX 590
- Driver: Mesa 19.0.3
- Wine version: 4.7, also Proton 3.16.9 (and lots of others)
- D9VK version: commit 18c78ce3, the latest master as of writing this

So essentially the game gives a black screen on starting. Loads for a really long time, then crashes. From what I could tell, it fills up all the RAM and then gets killed by the OOM killer. If not using address extension in wine, it crashes by itself a bit sooner. This does NOT happen with wined3d or Gallium Nine.

Here's `mm_d3d9.log`:

> info:  Game: mm.exe
> info:  DXVK: v1.1.1
> warn:  OpenVR: Failed to locate module
> info:  Enabled instance extensions:
> info:    VK_KHR_get_physical_device_properties2
> info:    VK_KHR_surface
> info:    VK_KHR_win32_surface
> info:  AMD RADV POLARIS10 (LLVM 8.0.0):
> info:    Driver: 19.0.3
> info:    Vulkan: 1.1.90
> info:    Memory Heap[0]: 
> info:      Size: 7936 MiB
> info:      Flags: 0x1
> info:      Memory Type[0]: Property Flags = 0x1
> info:    Memory Heap[1]: 
> info:      Size: 256 MiB
> info:      Flags: 0x1
> info:      Memory Type[2]: Property Flags = 0x7
> info:    Memory Heap[2]: 
> info:      Size: 8192 MiB
> info:      Flags: 0x0
> info:      Memory Type[1]: Property Flags = 0x6
> info:      Memory Type[3]: Property Flags = 0xe
> info:  AMD RADV POLARIS10 (LLVM 8.0.0):
> info:    Driver: 19.0.3
> info:    Vulkan: 1.1.90
> info:    Memory Heap[0]: 
> info:      Size: 7936 MiB
> info:      Flags: 0x1
> info:      Memory Type[0]: Property Flags = 0x1
> info:    Memory Heap[1]: 
> info:      Size: 256 MiB
> info:      Flags: 0x1
> info:      Memory Type[2]: Property Flags = 0x7
> info:    Memory Heap[2]: 
> info:      Size: 8192 MiB
> info:      Flags: 0x0
> info:      Memory Type[1]: Property Flags = 0x6
> info:      Memory Type[3]: Property Flags = 0xe
> info:  Process set as DPI aware
> info:  Game: mm.exe
> info:  DXVK: v1.1.1
> warn:  OpenVR: Failed to locate module
> info:  Enabled instance extensions:
> info:    VK_KHR_get_physical_device_properties2
> info:    VK_KHR_surface
> info:    VK_KHR_win32_surface
> info:  AMD RADV POLARIS10 (LLVM 8.0.0):
> info:    Driver: 19.0.3
> info:    Vulkan: 1.1.90
> info:    Memory Heap[0]: 
> info:      Size: 7936 MiB
> info:      Flags: 0x1
> info:      Memory Type[0]: Property Flags = 0x1
> info:    Memory Heap[1]: 
> info:      Size: 256 MiB
> info:      Flags: 0x1
> info:      Memory Type[2]: Property Flags = 0x7
> info:    Memory Heap[2]: 
> info:      Size: 8192 MiB
> info:      Flags: 0x0
> info:      Memory Type[1]: Property Flags = 0x6
> info:      Memory Type[3]: Property Flags = 0xe
> info:  AMD RADV POLARIS10 (LLVM 8.0.0):
> info:    Driver: 19.0.3
> info:    Vulkan: 1.1.90
> info:    Memory Heap[0]: 
> info:      Size: 7936 MiB
> info:      Flags: 0x1
> info:      Memory Type[0]: Property Flags = 0x1
> info:    Memory Heap[1]: 
> info:      Size: 256 MiB
> info:      Flags: 0x1
> info:      Memory Type[2]: Property Flags = 0x7
> info:    Memory Heap[2]: 
> info:      Size: 8192 MiB
> info:      Flags: 0x0
> info:      Memory Type[1]: Property Flags = 0x6
> info:      Memory Type[3]: Property Flags = 0xe
> info:  Process set as DPI aware
> info:  Game: mm.exe
> info:  DXVK: v1.1.1
> warn:  OpenVR: Failed to locate module
> info:  Enabled instance extensions:
> info:    VK_KHR_get_physical_device_properties2
> info:    VK_KHR_surface
> info:    VK_KHR_win32_surface
> info:  AMD RADV POLARIS10 (LLVM 8.0.0):
> info:    Driver: 19.0.3
> info:    Vulkan: 1.1.90
> info:    Memory Heap[0]: 
> info:      Size: 7936 MiB
> info:      Flags: 0x1
> info:      Memory Type[0]: Property Flags = 0x1
> info:    Memory Heap[1]: 
> info:      Size: 256 MiB
> info:      Flags: 0x1
> info:      Memory Type[2]: Property Flags = 0x7
> info:    Memory Heap[2]: 
> info:      Size: 8192 MiB
> info:      Flags: 0x0
> info:      Memory Type[1]: Property Flags = 0x6
> info:      Memory Type[3]: Property Flags = 0xe
> info:  AMD RADV POLARIS10 (LLVM 8.0.0):
> info:    Driver: 19.0.3
> info:    Vulkan: 1.1.90
> info:    Memory Heap[0]: 
> info:      Size: 7936 MiB
> info:      Flags: 0x1
> info:      Memory Type[0]: Property Flags = 0x1
> info:    Memory Heap[1]: 
> info:      Size: 256 MiB
> info:      Flags: 0x1
> info:      Memory Type[2]: Property Flags = 0x7
> info:    Memory Heap[2]: 
> info:      Size: 8192 MiB
> info:      Flags: 0x0
> info:      Memory Type[1]: Property Flags = 0x6
> info:      Memory Type[3]: Property Flags = 0xe
> info:  Process set as DPI aware
> info:  Enabled device extensions:
> info:    VK_EXT_conditional_rendering
> info:    VK_EXT_memory_priority
> info:    VK_EXT_shader_viewport_index_layer
> info:    VK_EXT_transform_feedback
> info:    VK_EXT_vertex_attribute_divisor
> info:    VK_KHR_dedicated_allocation
> info:    VK_KHR_descriptor_update_template
> info:    VK_KHR_driver_properties
> info:    VK_KHR_get_memory_requirements2
> info:    VK_KHR_image_format_list
> info:    VK_KHR_maintenance1
> info:    VK_KHR_maintenance2
> info:    VK_KHR_sampler_mirror_clamp_to_edge
> info:    VK_KHR_shader_draw_parameters
> info:    VK_KHR_swapchain
> info:  DXVK: Read 0 valid state cache entries
> info:  DXVK: Using 3 compiler threads
> warn:  D3D9: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 9
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 16
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 37
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 38
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 60
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 136
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 137
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 141
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 142
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 145
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 146
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 154
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 155
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 158
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 161
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 166
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 172
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 173
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 178
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 179
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 182
> warn:  D3D9DeviceEx::SetTextureStageState: Stub
> info:  Presenter: Actual swap chain properties:
>   Format:       VK_FORMAT_B8G8R8A8_UNORM
>   Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
>   Buffer size:  1920x1080
>   Image count:  2

I presume it's because of unimplemented things? If not, I can provide API traces.

EDIT: fix typo

**Comment by NerosTie** [comment]
On my side, Dark Messiah doesn't crash on start. I can play the game perfectly fine.
However, there is an issue when you are underwater: 
![20190719001443_1](https://user-images.githubusercontent.com/4572452/61495959-f91dc600-a9ba-11e9-9133-5bc6c938aee1.jpg)

I would like to apitrace it but I can't with wined3d, I only have the sound...

Is an apitrace with d9vk worth it?

**Comment by cyro666** [comment]
This bug report was a long time ago, I have to re-check myself if it works or not. Will do when I have time.

**Comment by NerosTie** [comment]
My bug is gone (tested with #784). I think we can close this issue.
