### ISSUE TITLE
Guild Wars 2 - Character Portraits Disappearing in Party List.

### ISSUE THREAD

**Issue by Jrugia** [Joshua-Ashton/d9vk#68]
If you join a party and click on their portrait or clicking on their character, the portrait disappears from the party list leaving a blank box. Furthermore this issue also seems to happen only when that character is in range. Clicking on the portrait when the character is out of range doesn't disappear.

For easier understanding I recorded a video showing the issue at this link: https://drive.google.com/file/d/1ineKvNmMOAG8EvppVuJlOxMbXyP7ZaNQ

The blue flashing cursor represents mouse clicking.

Can confirm the issue isn't present using WineD3D.

### Software information
Guild Wars 2

### System information
- GPU: GTX 1060 6GB
- Driver: 418.52.05
- Wine version: 4.6 Staging (with Esync)
- DXVK version: commit 18c78ce3c17e69c485515fe96980567722f3a91a

### Log files
d3d9.log: [GW2_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3145459/GW2_d3d9.log)
dxgi.log: File remains empty during testing.

**Comment by logan001** [comment]
i can confirm the bug

**Comment by arzardk** [comment]
More like unimplemented function(s) rather than a bug.
`D3D9DeviceEx::SetTextureStageState: Stub`
`D3D9DeviceEx::SetMaterial: Stub`

**Comment by logan001** [comment]
seems that the issue is fixed with da392277550446f2d037a3dcfd6fb15e59654daf

**Comment by Jrugia** [comment]
> seems that the issue is fixed with [da39227](https://github.com/Joshua-Ashton/d9vk/commit/da392277550446f2d037a3dcfd6fb15e59654daf)

Just tested it and can confirmed it is indeed fixed. Closing ticket.
