### ISSUE TITLE
GTA IV – black patches on faces

### ISSUE THREAD

**Issue by AlexeyProkhin** [Joshua-Ashton/d9vk#69]
Faces are covered in black patches in cut scenes.
![GTAIV 0030497316](https://user-images.githubusercontent.com/615489/57194920-48745e80-6f55-11e9-8c13-ed5f64fa03f8.jpg)

### Software information
Steam version of Grand Theft Auto IV

### System information
- GPU: GeForce GTX 1070
- Driver: 430.09
- Wine version: Proton 4.2
- D9VK version: commit 18c78ce3c17e69c485515fe96980567722f3a91a

### Apitrace file(s)
- [GTAIV.trace.tar.gz](https://www.dropbox.com/s/0niq4pwnuv3b3wr/GTAIV.trace.tar.gz?dl=0)

### Log files
- d3d9.log: [GTAIV_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3145578/GTAIV_d3d9.log)

**Comment by AlexeyProkhin** [comment]
Fixed in 1566ca3bc098a805a3edebaef861c51ca201592 . Thank you for your work!

**Comment by Joshua-Ashton** [comment]
Nice, I wasn't even trying to fix that bug
