### ISSUE TITLE
Darksiders II Deathinitive Edition : Renderer Issue in game

### ISSUE THREAD

**Issue by Odelpasso** [Joshua-Ashton/d9vk#70]
Old issue : Initially, the game crashed at launch with an error about display format. Since the latest commits from Joshua, the game still crashes at launch but with a new error.

New issue : Since more commits ago, the game no crashes at launch but have now differents issue : 
- Intro videos + game videos are black, only the sound works. 
- There are renderer issues in game like on this screenshot.

![Capture du 2019-06-21 14-03-25](https://user-images.githubusercontent.com/3606036/59921405-d76a0700-942d-11e9-90ea-02d7e8779c1c.png)

### Software information
Darksiders II Deathinitive Edition from GoG. The game is downloaded from Galaxy but launched without it.

### System information
- GPU: AMD RX580 8Gb
- Driver: 19.2 Git version + LLVM 9.0.0
- Wine version: 4.10-staging
- D9VK version: "Master" git commit at b787cf0 or "d3d9-fixed-function" git commit at 0e6e448

### Apitrace file(s)
- https://drive.google.com/open?id=1p2ejkoCiAAWIDXhdpGR78XhYJ-vDPuKY

**Comment by phush0** [comment]
For me is working with Steam Version, though I use Proton for this purpose and Vega M. Performance is over double compared with Wine D3D. Game is 64bit.

**Comment by Odelpasso** [comment]
Which GPU do you have ?
With Proton it does not work for me. Maybe because i have a fucking AMD GPU ...

**Comment by phush0** [comment]
Vega M

**Comment by Odelpasso** [comment]
Well i don't know ...

**Comment by phush0** [comment]
What I have done was to use proton dxvk and just put direct3d9.dll inside

**Comment by Joshua-Ashton** [comment]
Your trace was really short, but it now plays back on latest master fine for me.

You can get the latest build here: https://git.froggi.es/joshua/d9vk/-/jobs
Does it fix more of the game than just the menu you showcased?

**Comment by LeJimster** [comment]
Hmmm, the latest build a750df75 is exactly the same for me.  It launches, but all the issues persist. No bink videos, the early menus do display properly for the most part, although there is some kind of issue with alignment and elements not being drawn properly starting from the initial screen, into later menus.  It creates a line across the center as seen below:
Proton:
![DSII_proton_mainscreen](https://user-images.githubusercontent.com/35663469/57415765-2993f780-71f5-11e9-9765-6eef6e89d913.jpg)
D9VK:
![DSII_d9vk_tophalf](https://user-images.githubusercontent.com/35663469/57415770-31ec3280-71f5-11e9-8b44-dd6d7d3041e3.jpg)

It's when you get to the continue screen and ingame where it's all messed up.

I've created a trace, with a little bit of in game movement.  Hopefully it's enough to help show the problems.

### Apitrace
- https://drive.google.com/open?id=1tOk5zGzxq3jOz8T1hwGXi_sBBY7sd7qd

**Comment by Odelpasso** [comment]
Josh, i tried the game with AMDVLK :
Bad screen without sound.

Si there is an issue with D9VK like there is the same issue for NVIDIA and AMD (RADV) users.

**Comment by Odelpasso** [comment]
Update title + Initial message for the new issue.
Link for the apitrace updated.
