### ISSUE TITLE
Call of Duty 2: Skybox missing on open menu, fog effect is dark on edges 

### ISSUE THREAD

**Issue by Riesi** [Joshua-Ashton/d9vk#73]
As already mentioned in the title the skybox is missing when the menu or the "click to continue" screen is open, but the most annoying thing is the dark fog. Other than that the game looks correct.
I attached two screenshots so you get what I mean by those issues and an apitrace, which contains both problems.

missing skybox (should have the skybox of the 2nd picture):
![May08::205716](https://user-images.githubusercontent.com/27691485/57400559-0a38a280-71d4-11e9-9f61-85431041674e.png)
dark fog:
![May08::205734](https://user-images.githubusercontent.com/27691485/57400565-0b69cf80-71d4-11e9-8fca-7142cd1153ea.png)

### System information
- GPU: GTX 970
- Driver: 418.52.05
- Wine version: 4.7
- D9VK version: 0.1

### Apitrace file(s)
https://git.froggi.es/Riesi/tracehub/raw/master/traces/d3d9/Call%20of%20Duty%202%20%5Bnative%5D.tar.xz?inline=false

### Log files
[CoD2MP_s_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3158895/CoD2MP_s_d3d9.log)

:frog:

**Comment by K0bin** [comment]
The game uses shader model < 1.4 and thus doesnt have explicit sampler declarations. D9VK just generates a 2D sampler. The game wants to bind a cubemap to that though, which doesn't work.

**Comment by Joshua-Ashton** [comment]
Should be fixed as of ae2805cea77ed3dc61139bb43aab190c4fe89a1a, can you verify on your end?

**Comment by Riesi** [comment]
Sorry for the long wait... the issue is fixed on latest master! 
Thanks! :heart::frog:
