### ISSUE TITLE
Call of Duty 2 crashes when loading map

### ISSUE THREAD

**Issue by nicocarbone** [Joshua-Ashton/d9vk#75]
Call of Duty 2 crashes when loading a map using d9vk 0.10, on a Intel Kaby Lake Laptop.  
In previous development versions of d9vk, COD2 loaded the map, albeit with heavy artifacts.

Name of the game, settings used etc.

### System information
- GPU: Intel HD620
- Driver: Mesa 19.0
- Wine version: Proton 4.2
- DXVK version: D9VK 0.10

### Crash log:
Unhandled exception: page fault on read access to 0x0000000c in 32-bit code (0x757631cd).
0046:fixme:dbghelp:elf_search_auxv can't find symbol in module
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:757631cd ESP:18a31b28 EBP:70dccb70 EFLAGS:00010206(  R- --  I   - -P- )
 EAX:00000000 EBX:75b33000 ECX:00000002 EDX:70d33428
 ESI:00000101 EDI:00000101
Stack dump:
0x18a31b28:  70d32a98 18a31cb0 70d3a480 70d0fe78
0x18a31b38:  18a3a8e0 7b9b5510 00000004 00000007
0x18a31b48:  70dccbe0 1ad1b930 625d2340 70d356a0
0x18a31b58:  7b97a9d0 7cf18b98 75a41000 70d356b8
0x18a31b68:  0000001c 70dccb70 62c08828 18a31ba8
0x18a31b78:  00000001 01010100 00000001 01010001
Backtrace:
=>0 0x757631cd in libvulkan_intel.so (+0x4d1cd) (0x70dccb70)
0x757631cd: movl	0xc(%eax),%esi
Modules:
Module	Address			Debug info	Name (167 modules)
PE	  380000-  3f9000	Deferred        openvr_api_dxvk
PE	  400000- 1cca000	Deferred        cod2sp_s
PE	 1df0000- 1e1b000	Deferred        msseax.m3d
PE	 eef0000- f653000	Deferred        gfx_d3d_x86_s
PE	10000000-1013d000	Deferred        steam
PE	21100000-21164000	Deferred        mss32
PE	22100000-22122000	Deferred        mssa3d.m3d
PE	22300000-2231b000	Deferred        mssds3d.m3d
PE	22400000-22419000	Deferred        msssoft.m3d
PE	22600000-2261f000	Deferred        mssdx7.m3d
PE	22700000-22768000	Deferred        mssrsx.m3d
PE	24100000-24121000	Deferred        mssdsp.flt
PE	26400000-26439000	Deferred        mssvoice.asi
PE	26f00000-26f2c000	Deferred        mssmp3.asi
ELF	5e1df000-5e26c000	Deferred        libvorbisenc.so.2
ELF	5e26c000-5e2ce000	Deferred        libflac.so.8
ELF	5e2ce000-5e3b1000	Deferred        libgcrypt.so.20
ELF	5e3b1000-5e440000	Deferred        libsndfile.so.1
PE	62440000-62678000	Deferred        d3d9
ELF	62683000-626a8000	Deferred        libgpg-error.so.0
ELF	626a8000-626d4000	Deferred        libvorbis.so.0
ELF	626d4000-62700000	Deferred        liblzma.so.5
ELF	62700000-627aa000	Deferred        libsystemd.so.0
ELF	62b03000-62b29000	Deferred        liblz4.so.1
ELF	62b29000-62b73000	Deferred        libdbus-1.so.3
ELF	62b73000-62c00000	Deferred        libpulsecommon-12.2.so
ELF	62f11000-62f6c000	Deferred        libpulse.so.0
ELF	638ae000-64408000	Deferred        i965_dri.so
ELF	75716000-75b36000	Export          libvulkan_intel.so
ELF	76337000-79b19000	Deferred        libllvm-8.so.1
ELF	79b19000-7b400000	Deferred        steamclient.so
ELF	7b400000-7b7fc000	Deferred        kernel32<elf>
  \-PE	7b420000-7b7fc000	\               kernel32
ELF	7b7ff000-7b818000	Deferred        libresolv.so.2
ELF	7b818000-7b821000	Deferred        libogg.so.0
ELF	7b821000-7b828000	Deferred        libasyncns.so.0
ELF	7b828000-7b851000	Deferred        winepulse<elf>
  \-PE	7b830000-7b851000	\               winepulse
ELF	7b851000-7b874000	Deferred        mmdevapi<elf>
  \-PE	7b860000-7b874000	\               mmdevapi
ELF	7b874000-7b8bf000	Deferred        dsound<elf>
  \-PE	7b880000-7b8bf000	\               dsound
ELF	7bc00000-7bd1c000	Deferred        ntdll<elf>
  \-PE	7bc10000-7bd1c000	\               ntdll
ELF	7bd1d000-7bd29000	Deferred        libwrap.so.0
ELF	7bdb5000-7bdc1000	Deferred        libpciaccess.so.0
ELF	7bdc1000-7bdcb000	Deferred        libdrm_nouveau.so.2
ELF	7bdcb000-7bdd9000	Deferred        libdrm_radeon.so.1
ELF	7bdd9000-7be00000	Deferred        libdrm_intel.so.1
ELF	7c000000-7c004000	Deferred        <wine-loader>
ELF	7c004000-7c00b000	Deferred        libxcb-dri2.so.0
ELF	7c00b000-7c029000	Deferred        libxcb-glx.so.0
ELF	7c029000-7c048000	Deferred        libglapi.so.0
ELF	7c048000-7c0c0000	Deferred        libglx_mesa.so.0
ELF	7c404000-7c408000	Deferred        libxdamage.so.1
ELF	7c4d1000-7c50f000	Deferred        libvklayer_steam_fossilize.so
ELF	7c50f000-7c7da000	Deferred        libvulkan_radeon.so
ELF	7c7da000-7c91c000	Deferred        opengl32<elf>
  \-PE	7c800000-7c91c000	\               opengl32
ELF	7c91c000-7c943000	Deferred        libtinfo.so.6
ELF	7c943000-7c97a000	Deferred        libedit.so.2
ELF	7c97a000-7c984000	Deferred        libffi.so.6
ELF	7c984000-7c98e000	Deferred        libatomic.so.1
ELF	7c995000-7c9ad000	Deferred        steamoverlayvulkanlayer.so
ELF	7c9ad000-7c9c2000	Deferred        libdrm.so.2
ELF	7c9c2000-7c9c5000	Deferred        libxshmfence.so.1
ELF	7c9c5000-7c9ce000	Deferred        libxcb-sync.so.1
ELF	7c9ce000-7c9d3000	Deferred        libxcb-present.so.0
ELF	7c9d3000-7c9e7000	Deferred        libxcb-randr.so.0
ELF	7c9e7000-7c9f6000	Deferred        libwayland-client.so.0
ELF	7c9f6000-7ca14000	Deferred        libelf.so.1
ELF	7ca14000-7ca21000	Deferred        libdrm_amdgpu.so.1
ELF	7ca21000-7cb74000	Deferred        wined3d<elf>
  \-PE	7ca30000-7cb74000	\               wined3d
ELF	7cb74000-7cbea000	Deferred        ddraw<elf>
  \-PE	7cb80000-7cbea000	\               ddraw
ELF	7cd87000-7cd9b000	Deferred        api-ms-win-core-localization-l1-2-1<elf>
  \-PE	7cd90000-7cd9b000	\               api-ms-win-core-localization-l1-2-1
ELF	7cd9b000-7cdaf000	Deferred        api-ms-win-core-fibers-l1-1-1<elf>
  \-PE	7cda0000-7cdaf000	\               api-ms-win-core-fibers-l1-1-1
ELF	7cdaf000-7cdc3000	Deferred        api-ms-win-core-synch-l1-2-0<elf>
  \-PE	7cdb0000-7cdc3000	\               api-ms-win-core-synch-l1-2-0
ELF	7cdfa000-7ce3f000	Deferred        usp10<elf>
  \-PE	7ce00000-7ce3f000	\               usp10
ELF	7ce3f000-7ce69000	Deferred        libpng12.so.0
ELF	7cfaf000-7d282000	Deferred        lsteamclient<elf>
  \-PE	7d0b0000-7d282000	\               lsteamclient
ELF	7d282000-7d296000	Deferred        psapi<elf>
  \-PE	7d290000-7d296000	\               psapi
ELF	7d296000-7d3be000	Deferred        oleaut32<elf>
  \-PE	7d2b0000-7d3be000	\               oleaut32
ELF	7d3be000-7d479000	Deferred        msvcrt<elf>
  \-PE	7d3d0000-7d479000	\               msvcrt
ELF	7d479000-7d4d1000	Deferred        libvulkan.so.1
ELF	7d4d1000-7d566000	Deferred        winex11<elf>
  \-PE	7d4e0000-7d566000	\               winex11
ELF	7d566000-7df25000	Deferred        shell32<elf>
  \-PE	7d570000-7df25000	\               shell32
ELF	7dfc7000-7dfcc000	Deferred        libx11-xcb.so.1
ELF	7dfcc000-7dfd2000	Deferred        libxcb-dri3.so.0
ELF	7dfd4000-7dfdb000	Deferred        libxfixes.so.3
ELF	7dfdb000-7dfe8000	Deferred        libxcursor.so.1
ELF	7dfe8000-7dff4000	Deferred        libxrender.so.1
ELF	7dff4000-7e007000	Deferred        libxi.so.6
ELF	7e007000-7e00b000	Deferred        libxcomposite.so.1
ELF	7e00b000-7e012000	Deferred        libxxf86vm.so.1
ELF	7e012000-7e017000	Deferred        libxinerama.so.1
ELF	7e017000-7e02c000	Deferred        libxext.so.6
ELF	7e02c000-7e072000	Deferred        winevulkan<elf>
  \-PE	7e040000-7e072000	\               winevulkan
ELF	7e072000-7e08a000	Deferred        vulkan-1<elf>
  \-PE	7e080000-7e08a000	\               vulkan-1
ELF	7e0b5000-7e0df000	Deferred        iphlpapi<elf>
  \-PE	7e0c0000-7e0df000	\               iphlpapi
ELF	7e0df000-7e116000	Deferred        ws2_32<elf>
  \-PE	7e0f0000-7e116000	\               ws2_32
ELF	7e116000-7e130000	Deferred        wsock32<elf>
  \-PE	7e120000-7e130000	\               wsock32
ELF	7e130000-7e15c000	Deferred        msacm32<elf>
  \-PE	7e140000-7e15c000	\               msacm32
ELF	7e15c000-7e215000	Deferred        winmm<elf>
  \-PE	7e160000-7e215000	\               winmm
ELF	7e215000-7e239000	Deferred        shcore<elf>
  \-PE	7e220000-7e239000	\               shcore
ELF	7e239000-7e2a7000	Deferred        shlwapi<elf>
  \-PE	7e250000-7e2a7000	\               shlwapi
ELF	7e2a7000-7e32c000	Deferred        rpcrt4<elf>
  \-PE	7e2b0000-7e32c000	\               rpcrt4
ELF	7e32c000-7e485000	Deferred        ole32<elf>
  \-PE	7e340000-7e485000	\               ole32
ELF	7e485000-7e4aa000	Deferred        imm32<elf>
  \-PE	7e490000-7e4aa000	\               imm32
ELF	7e5d7000-7e5e1000	Deferred        libuuid.so.1
ELF	7e5e1000-7e61c000	Deferred        libexpat.so.1
ELF	7e61c000-7e669000	Deferred        libfontconfig.so.1
ELF	7e669000-7e686000	Deferred        libz.so.1
ELF	7e686000-7e6c4000	Deferred        libpng16.so.16
ELF	7e6c4000-7e785000	Deferred        libfreetype.so.6
ELF	7e785000-7e79f000	Deferred        version<elf>
  \-PE	7e790000-7e79f000	\               version
ELF	7e79f000-7e817000	Deferred        advapi32<elf>
  \-PE	7e7b0000-7e817000	\               advapi32
ELF	7e817000-7e946000	Deferred        gdi32<elf>
  \-PE	7e820000-7e946000	\               gdi32
ELF	7e946000-7eb48000	Deferred        user32<elf>
  \-PE	7e960000-7eb48000	\               user32
ELF	7eb48000-7eb5c000	Deferred        libnss_files.so.2
ELF	7eb5c000-7eb78000	Deferred        libnsl.so.1
ELF	7eb78000-7eb87000	Deferred        libnss_nis.so.2
ELF	f6072000-f607c000	Deferred        libnss_compat.so.2
ELF	f755a000-f7579000	Deferred        libbsd.so.0
ELF	f7579000-f7580000	Deferred        libxdmcp.so.6
ELF	f7582000-f7586000	Deferred        libxau.so.6
ELF	f7586000-f75b4000	Deferred        libxcb.so.1
ELF	f75b4000-f7700000	Deferred        libx11.so.6
ELF	f7700000-f771e000	Deferred        libgcc_s.so.1
ELF	f771e000-f7780000	Deferred        libgldispatch.so.0
ELF	f7780000-f77a4000	Deferred        libglx.so.0
ELF	f77a4000-f78a8000	Deferred        libm.so.6
ELF	f7a85000-f7a8b000	Deferred        libdl.so.2
ELF	f7a8b000-f7a95000	Deferred        librt.so.1
ELF	f7a97000-f7afd000	Deferred        libgl.so.1
ELF	f7afd000-f7cdd000	Deferred        libc.so.6
ELF	f7cdd000-f7cfd000	Deferred        libpthread.so.0
ELF	f7cfd000-f7eb8000	Export          libwine.so.1
ELF	f7eb8000-f7ef5000	Deferred        gameoverlayrenderer.so
ELF	f7ef7000-f7f21000	Deferred        ld-linux.so.2
Threads:
process  tid      prio (all id:s are in hex)
00000008 steam.exe
	00000025    0
	00000009    0
0000000e services.exe
	00000021    0
	0000001c    0
	00000018    0
	00000013    0
	00000010    0
	0000000f    0
00000011 winedevice.exe
	00000019    0
	00000017    0
	00000016    0
	00000012    0
0000001a plugplay.exe
	0000001e    0
	0000001d    0
	0000001b    0
0000001f winedevice.exe
	00000024    0
	00000023    0
	00000022    0
	00000020    0
00000026 explorer.exe
	0000002c    0
	0000002b    0
	0000002a    0
	00000027    0
00000028 (D) Z:\home\nicolas\.local\share\Steam\steamapps\common\Call of Duty 2\CoD2SP_s.exe
	00000042    0
	00000041    0
	00000040    0
	0000003f    0
	0000003e   -2
	0000003d   -2 <==
	0000003c    0
	0000003b   15
	0000003a   15
	00000039    0
	00000036   15
	00000035    0
	00000032    0
	00000031    0
	00000030    0
	0000002f   -2
	0000002e   -2
	0000002d    0
	00000029    0
System information:
    Wine build: wine-4.2
    Platform: i386 (WOW64)
    Version: Windows 7
    Host system: Linux
    Host version: 5.0.0-13-generic
pid 5516 != 5515, skipping destruction (fork without exec?)
Game removed: AppID 2630 "", ProcID 5548 
Exiting app 2630

**Comment by Joshua-Ashton** [comment]
Looks like the issue is in your driver based on the Stack Trace.

**Comment by nicocarbone** [comment]
Ok. If it matters, I don't have problems with Vulkan or OpenGl games. And previous dev versions of d9vk (around two weeks ago) did not crash the game in the same laptop with the same distro.
They did have several artifacts, but they got in-game.

Is there anything else I can do to help debugging the issue?

**Comment by nicocarbone** [comment]
As another data point: Rocket League (Win DX9 version, of course) works perfectly with d9vk 0.10 in the very same laptop. And it runs better than both the OpenGL and the WineD3D version!

**Comment by Joshua-Ashton** [comment]
While it is cool -- this is not the best place to post this. 😛

**Comment by nicocarbone** [comment]
Yeah, you're right.
I just though it may help you diagnose the problem with COD2 by comparison. And, at the same time, saying that you are doing a great job! :)

**Comment by neVERberleRfellerER** [comment]
This is the same bug I found here:
https://github.com/Joshua-Ashton/d9vk/issues/64#issuecomment-491488934
Just whatever compiler version was used, it used ESI instead of EBX, but it's the same code - EBX and ESI both contain 101, and offet is 0xc and so on. The source code confirms that they do the same thing as RADV.

**Comment by NerosTie** [comment]
@Joshua-Ashton 
It's an old issue and I think it can be closed now.

**Comment by Joshua-Ashton** [comment]
This works now?

**Comment by telans** [comment]
> This works now?

https://github.com/Joshua-Ashton/d9vk/issues/267#issuecomment-534816241
