### ISSUE TITLE
Shift 2 Unleashed run but not load race and others problems

### ISSUE THREAD

**Issue by games4tux** [Joshua-Ashton/d9vk#79]
### Software information
Shift2 Unleashed 
shift2u.exe

### System information
- GPU: radeon HD7770
- Driver: radv
- Wine version: 4.1 staging
- DXVK version: 0.10

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log
info:  Game: shift2u.exe
info:  DXVK: d9vk-0.10
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD RADV CAPE VERDE (LLVM 7.0.1):
info:    Driver: 19.0.3
info:    Vulkan: 1.1.90
info:    Memory Heap[0]: 
info:      Size: 768 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[2]: Property Flags = 0x7
info:    Memory Heap[2]: 
info:      Size: 3072 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:  Process set as DPI aware
info:  Game: shift2u.exe
info:  DXVK: d9vk-0.10
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD RADV CAPE VERDE (LLVM 7.0.1):
info:    Driver: 19.0.3
info:    Vulkan: 1.1.90
info:    Memory Heap[0]: 
info:      Size: 768 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[2]: Property Flags = 0x7
info:    Memory Heap[2]: 
info:      Size: 3072 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:  Process set as DPI aware
info:  Enabled device extensions:
info:    VK_EXT_conditional_rendering
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  DXVK: Read 205 valid state cache entries
info:  DXVK: Using 2 compiler threads
warn:  D3D9: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  D3D9DeviceEx::ResetEx:
  Requested Presentation Parameters
    - Width:              1440
    - Height:             900
    - Format:             A8R8G8B8
    - Auto Depth Stencil: true
    - Windowed:           false

warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 9
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 16
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 37
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 38
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 60
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 136
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 137
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 141
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 142
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 145
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 146
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 154
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 155
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 158
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 161
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 166
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 172
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 173
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 178
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 179
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 182
warn:  D3D9DeviceEx::SetTextureStageState: Stub
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_FIFO_KHR
  Buffer size:  1440x900
  Image count:  3
warn:  D3D9DeviceEx::ColorFill: Stub
warn:  D3D9DeviceEx::ColorFill: Stub
warn:  D3D9DeviceEx::ColorFill: Stub
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_FIFO_KHR
  Buffer size:  1x1
  Image count:  3

- d3d11.log:
- dxgi.log:

**Comment by Joshua-Ashton** [comment]
> Apitrace file(s)
    Put a link here

please do

**Comment by mozo78** [comment]
It seems I can't get a proper apitrace. Will this do the work?

[shift2u.trace.zip](https://github.com/Joshua-Ashton/d9vk/files/3161260/shift2u.trace.zip)

**Comment by mozo78** [comment]
Here is the proper apitrace 1.7GB:
https://my.pcloud.com/publink/show?code=XZIEdU7ZMH4OLGBeBXhuReJz3Re0HfUsHtcX

**Comment by neVERberleRfellerER** [comment]
For me on RADV 19.0.4, d3dretrace crashes in same place as Alan Wake.
Do you also get crash during (probably at the end) of loading?

**Comment by mozo78** [comment]
For me on Nvidia 418.74 it actaully starts and loads the race but it has severe graphical problems:
![Shift 2](https://user-images.githubusercontent.com/38666396/57572619-8d9d0280-7425-11e9-9cab-5bd7e1f0cbc2.png)
- d3d9 log:
https://pastebin.com/an2PTVVR

**Comment by neVERberleRfellerER** [comment]
My problem was RADV bug. On AMDVLK I get the same thing as you.

**Comment by mozo78** [comment]
It seems this issue is invisible for Joshua :(

**Comment by mozo78** [comment]
D9VK 0.11:
![1](https://user-images.githubusercontent.com/38666396/57603491-8d5a4f80-756a-11e9-99df-ead3cdeb03da.png)
![2](https://user-images.githubusercontent.com/38666396/57603506-95b28a80-756a-11e9-8d50-44f992a7697e.png)

**Comment by neVERberleRfellerER** [comment]
Looks good to me (not sure how the game is supposed to look like) on RADV git, D9VK c8fb2d569675cd7ef37712b0b2d4efe53db752c6 (it's 0.11) .
![Screenshot_20190513_131350 png](https://user-images.githubusercontent.com/11160972/57617506-43c92f00-7581-11e9-9b53-0f091a64a8e3.jpg)

**Comment by mozo78** [comment]
What are these d3dx9_00.dll and d3dcompiler_00.dll? From winetricks?

**Comment by neVERberleRfellerER** [comment]
I don't use winetricks personally, but I think it's what everybody use and it allegedly works, so yes. I think it can install all of them somehow, or you can go to directory where exe files are and use this
`strings *.exe *.dll | grep -i '\.dll$' | sort -fu | grep -i d3dx9_` to find wha d3dx9_00.dll game uses and `strings *.exe *.dll | grep -i '\.dll$' | sort -fu | grep -i d3dcompiler_` to get list of necessary d3dcompilers.
Then it seems that `winetricks d3dx9_34` (for exmaple; replace with what long commands gave you) should do the trick. Juding from some *verb files* in winetricks sources, `winetricks d3dx9` could install everything, but I don't know.

**Comment by mozo78** [comment]
Thank you :)
It seems the game use d3dx9_42.dll, d3dx9_43.dll and d3dcompiler_43.dll. I installed them via winetricks and now the game doesn't start anymore.

https://pastebin.com/AhgjnB7M

Then again I tried with the latest master 2a0c153b but the game looks like in the screenshots I posted previously even with 2a0c153b.

**Comment by neVERberleRfellerER** [comment]
Interesting.
What does backtrace in console output of wine say?
It might also be worth to try my procedure again - adding d3dx9_ that d3dx9_ installed in first step depend on

**Comment by mozo78** [comment]
The output is in my previous post :)
I tried to install the whole dx9 from winetricks and from the Microsoft's exe always with the same result as in the log.

https://pastebin.com/AhgjnB7M

In the meantime the game starts without any directx9 libraries, only with D9VK but with the artefacts I show in the screenshots. With vanilla Wine the game also works but has the infamous big black squares bug.

**Comment by neVERberleRfellerER** [comment]
That out of bound error might be related to the one in https://github.com/Joshua-Ashton/d9vk/issues/92 . Indices are not that different, which is... surprising. But it could be product of random chance, of course. I don't have the game and apitrace replays correctly, so I can't do anything here and it probably isn't problem with D9Vk. Maybe one last thing: does the game start with native d3dx9 and d3dcompilers without D9VK?

**Comment by mozo78** [comment]
No it's problem with D9VK. With vanilla Wine I don't observe such graphical problems at all and this error isn't present.
Yes, the game starts without problems with d3dx9 and d3dcompilers without D9VK, installed via winetricks or Microsoft's exe.

**Comment by mozo78** [comment]
I don't think using Wine d3dx9 and d3dcompilers is a good idea:

> Please do not use wine's d3d9x or d3dcompiler with d9vk. They make invalid API calls and generate bad shaders. I cannot stress this enough.

**Comment by neVERberleRfellerER** [comment]
> installed via winetricks or **Microsoft's exe**

> Microsoft's exe

this would require you to add all the DLLs as native manually in winecfg. Maybe, just to be sure, you can check if native versions get loaded correctly with  `WINEDEBUG=+loaddll`. BBut it should be safe with winetricks.

> I don't think using Wine d3dx9 and d3dcompilers is a good idea:

Indeed.

**Comment by mozo78** [comment]
Yes I know. Installing DX form exe requires manual overriding. With winetricks the overriding is made automatically. I just tried both variants of DX installation to try different methods.

>Indeed. Always use native ones with D9VK.

Which are the native ones? From the Microsoft's exe?

**Comment by neVERberleRfellerER** [comment]
> Which are the native ones? From the Microsoft's exe?

Yes, the ones from Microsoft are native.

**Comment by mozo78** [comment]
Thank you :)

**Comment by mozo78** [comment]
@Joshua-Ashton 
With latest master the game has severe problems:
![Screenshot_20190516_134441](https://user-images.githubusercontent.com/38666396/57848140-e3d0c380-77e0-11e9-8637-cb38a0a840ef.png)

**Comment by mozo78** [comment]
@Joshua-Ashton 
Is there any reason to ignore this issue? You asked for an apitrace and I provided it. Then the issue was doomed to oblivion. Why?

**Comment by neVERberleRfellerER** [comment]
Does game still crash(/not start) with native d3dx9? If so, maybe you could try shader validation thing as described here: https://github.com/Joshua-Ashton/d9vk/issues/16

**Comment by mozo78** [comment]
I'm not a developer and this seem too complicated for me. I'm at work now but when I get home I'll try latest master with Microsoft's d3dx9. When I tried two days ago it still crashed with DX9.

**Comment by mozo78** [comment]
The game with latest 35a94236 it getting worse:
![1](https://user-images.githubusercontent.com/38666396/58039274-f0d01880-7b3a-11e9-8953-8fe312863bf7.png)
With just installed Microsoft's DX9 the game crashes with even no dll overrides.

**Comment by mozo78** [comment]
I made and shader validations. There aren't errors at all:
https://pastebin.com/dcB56daW

**Comment by yagomont** [comment]
@Joshua-Ashton

Please get on this. This a game I am interested to see running on this.

**Comment by mozo78** [comment]
The game finally runs fine but have problems with menu background:
![Screenshot_20190622_003413](https://user-images.githubusercontent.com/38666396/59952713-e1b7ef80-9485-11e9-82d5-8cac96a44357.png)
![Screenshot_20190622_003605](https://user-images.githubusercontent.com/38666396/59952718-e41a4980-9485-11e9-82ea-215dcc560e2a.png)
I tried both Wine's and Microsoft's d3dcompiler_47 set to native to no avail.

**Comment by mozo78** [comment]
Can we receive some attention?

**Comment by K0bin** [comment]
As you can see the list of issues is quite long and Josh is currently busy with getting some fixed function functionality in.

**Comment by mozo78** [comment]
This isn't the case here. He must have something personal. He answers to the newer threads but never here.

**Comment by Joshua-Ashton** [comment]
You must be cuckoo 🐤 

It's on my todo list, chill out 🐸

**Comment by mozo78** [comment]
Ah, hello finally :)

**Comment by CME42** [comment]
Can you guys try this game with the latest master? Both the apitrace and the game are working fine for me on my 1060 with driver version 430.26.

And please double check that you're using the native d3dcompiler and d3d9x dlls.

**Comment by mozo78** [comment]
Yes, all the graphical glitches are fixed but the game stutters like hell. On my previous try there isn't any stuttering. One more problem - you can't turn off vsync and the framerate is always 60. With previous builds I can see higher fps like 150 or so.

**Comment by Joshua-Ashton** [comment]
No vsync changes have occured

**Comment by mozo78** [comment]
I may be wrong for I tested the game with dgvodoo also. Anyway, the game stutters very bad.

**Comment by Joshua-Ashton** [comment]
@mozo78 And you're sure you're not using dgVoodoo here? 🐸 

I don't own the game but things seemed fine in the trace I have of it...
Can you give me some system information (gpu, driver, wine/windows version, etc)

@CME42 owns it I believe, can you confirm a stutter?

**Comment by CME42** [comment]
Just did a quick test but i can't see any stutter, there is no frametime variation, both with and without vsync that would indicate any stutter.

**Comment by mozo78** [comment]
> @mozo78 And you're sure you're not using dgVoodoo here? frog
> 
> I don't own the game but things seemed fine in the trace I have of it...
> Can you give me some system information (gpu, driver, wine/windows version, etc)
> 
> @CME42 owns it I believe, can you confirm a stutter?

Excuse me for the false alarm, my bad. I use isolated prefixes and the version of Wine in the Shift 2 prefix was 4.8 Staging. I updated it to 4.11 vanilla and now everything is working fine and there isn't FPS cap. The game runs with ~200 FPS on my side.

Arch Linx
Nvidia GTX 1080 Ti 
Video driver 430.26
Intel 9900K

Thank you!!!

**Comment by Joshua-Ashton** [comment]
No problem!
