### ISSUE TITLE
How is this to be installed with DXVK?

### ISSUE THREAD

**Issue by greencopper** [Joshua-Ashton/d9vk#80]
I don't understand how to install this while also running the latest DXVK?

Or what DXVK version is it based upon? The file sizes from this project doesn't match the ones in DXVK 1.1.1.

**Comment by pchome** [comment]
> how to install this while also running the latest DXVK?

https://youtu.be/4NCRsjrqco8?t=25

... just grab `d3d9.dll`s ...

**Comment by mozo78** [comment]
Will you tell me where d3d9.dll can be downloaded from? I want to use it just like DXVK - drop the dll in the .exe directory rather compiling or using setup_dxvk.sh. Thank you :)

**Comment by loathingKernel** [comment]
@mozo78 Read the instructions, there is a conveniently named file README which explains where to find the binary package here https://github.com/Joshua-Ashton/d9vk/blob/release-0.10/README.md

**Comment by mozo78** [comment]
Forgive me but english isn't my native language. I read it hard but can find such explanation. According to the readme the only way obtaining the dlls is compiling and getting them from /your/d9vk/directory/bin. There isn't a link for downloading the precompiled dlls like in DXVK's page.

**Comment by Riesi** [comment]
Maybe take a look at the releases page? No?
https://github.com/Joshua-Ashton/d9vk/releases
Or download a latest hot master potato from here:
https://git.froggi.es/joshua/d9vk/-/jobs

**Comment by mozo78** [comment]
I jusd found it for myself. Thank toy:

https://github.com/Joshua-Ashton/d9vk/releases/download/0.10/d9vk-0.10.tar.gz

**Comment by loathingKernel** [comment]
> In order to install a D9VK package obtained from the release page (or build page which will give you the latest version from master) into a given wine prefix, run the following commands from within the D9VK directory

English is not my native language either but I think the sentence above is clear enough for anyone with basic knowledge.
