### ISSUE TITLE
Star Wars: The Old Republic black screen on start

### ISSUE THREAD

**Issue by Monsterovich** [Joshua-Ashton/d9vk#81]
### Software information

The game works fine under wine and normal wine's d3d9.

### System information
- GPU: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2)
- Driver: Mesa 19.1.0-devel - padoka PPA
- Wine version: Wine Staging 4.7
- DXVK version: 0.10

### Log files
[swtor_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3161910/swtor_d3d9.log)
[swtor_dxgi.log](https://github.com/Joshua-Ashton/d9vk/files/3161911/swtor_dxgi.log)

**Comment by kassindornelles** [comment]
Try to apitrace the game, that could be really helpful. 
apitrace dll [here](https://drive.google.com/open?id=1By-5qUdVsz_xJozRDJ-LHnkfXo_VhtA-)

**Comment by Monsterovich** [comment]
>Try to apitrace the game, that could be really helpful.

I can't. The game is run through launcher which runs the actual game exe.

**Comment by varris1** [comment]
You don't have to start through apitrace.exe.

put the d3d9.dll in the wrapper folder next to the .exe and set d3d9 to native,builtin

**Comment by Monsterovich** [comment]
>put the d3d9.dll in the wrapper folder next to the .exe and set d3d9 to native,builtin

I didn't know that output files will appear on my desktop. I expected it appear in the game folder.
[swtor.1.trace.zip](https://github.com/Joshua-Ashton/d9vk/files/3162502/swtor.1.trace.zip)

**Comment by K0bin** [comment]
That file is way too small. You still did something wrong.

**Comment by Monsterovich** [comment]
>That file is way too small. You still did something wrong.

I waited for over 2 mins and got the same file with size of 16396290 bytes.
I have black screen and d9vk just stuck on the CreatePixelShader.

**Comment by tannisroot** [comment]
Are you trying to apitrace it with d9vk? Because that is really not preferred and could cause issues. Use wined3d or better, native D3D on Windows instead.

**Comment by Monsterovich** [comment]
>Are you trying to apitrace it with d9vk?

Yes.

>Because that is really not preferred and could cause issues.

Okay, I run it with wined3d9. Here's .trace file.
https://drive.google.com/open?id=1gJA9vY-tYNVHXBZ4yrao9vZnp6C4_97Z

**Comment by fls2018** [comment]
I have the same issue, here's my trace: 

https://drive.google.com/file/d/1jT3oTXEyG1Z07JjoPKK0pZGYSJXWq_aF/view

**Comment by Monsterovich** [comment]
>I have the same issue with latest master & release, here's my trace:

Your trace is working for me.

![изображение](https://user-images.githubusercontent.com/3750982/58060457-d5cccb00-7b71-11e9-98b6-4c2e98ab8fdc.png)

**Comment by fls2018** [comment]
> > I have the same issue with latest master & release, here's my trace:
> 
> Your trace is working for me. What specs do you have in this trace? Is it wined3d or what? Also, can you give me your swtor config?

Because the trace was done under wined3d it doesn't have the issue, however they can still look at the api calls to figure out why d9vk wouldn't work.

**Comment by Monsterovich** [comment]
Fixed in Version 0.13f - Hypnofrog.

![cb_2019-07-15_Jul-17-26-1366x768](https://user-images.githubusercontent.com/3750982/61247120-bbb60000-a750-11e9-8b4d-ca06c27a3e91.png)
![cb_2019-07-15_Jul-26-43-1366x768](https://user-images.githubusercontent.com/3750982/61247119-b8bb0f80-a750-11e9-9097-e266588bbf13.png)

**Comment by Monsterovich** [comment]
[swtor_dxgi.log](https://github.com/Joshua-Ashton/d9vk/files/3394118/swtor_dxgi.log)
[swtor_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3394119/swtor_d3d9.log)

**Comment by K0bin** [comment]
Why are you posting logs if the issue is fixed?

**Comment by fls2018** [comment]
It's not fixed here, splash screen starts but crashes thereafter.

**Comment by K0bin** [comment]
Then post an apitrace so we can actually debug this

**Comment by fls2018** [comment]
@K0bin 

Here's an apitrace, as you see it just hangs at the splash screen. I also used native d3d_compiler & d3dx9 as suggested in the release notes.

https://drive.google.com/file/d/1uDsT16FPVBVPCfUhC9rf24RWKbi_QSKI/view

**Comment by Monsterovich** [comment]
![cb_2019-07-21_Jul-14-35-1366x768](https://user-images.githubusercontent.com/3750982/61590585-dc041580-abbb-11e9-826d-522300f0cdf5.png)

I noticed graphical artifacts in the main menu. This happens only when anti-aliasing is above medium.

**Comment by fls2018** [comment]
Haven't tried this since my last post but it appears to be working now since 0.20 at least.

![Screenshot from 2019-08-27 01-41-06](https://user-images.githubusercontent.com/43592670/63732374-e6c16280-c86b-11e9-9ae4-4e0b7dc573bd.png)
