### ISSUE TITLE
SH3 black screen

### ISSUE THREAD

**Issue by bohbisgfy** [Joshua-Ashton/d9vk#83]
Silent Hunter 3: black screen, mouse cursor visible.
Witness: Works great, huge improvement to frame rate.

**Comment by ByCybernetik** [comment]
SH3 uses D3D8

**Comment by bohbisgfy** [comment]
Hmm.., there comes dx9 in support material with the game (uplay version), so..?

**Comment by tsalwierz** [comment]
> Hmm.., there comes dx9 in support material with the game (uplay version), so..?

Uplay lists DX9 as a requirement and also lists the supported video cards as follows:

**Comment by tsalwierz** [comment]
> Hmm.., there comes dx9 in support material with the game (uplay version), so..?

Uplay lists DX9 as a requirement and also lists the supported video cards as follows:

ADDITIONAL NOTES:Currently Supported Video Cards: NVIDIA Geforce 3/4/FX

Geforce 3 and 4 are DX8 cards.

**Comment by NerosTie** [comment]
Silent Hunter 3 is not a D3D8 game, otherwise I would not have the DXVK HUD.

On my side, with 0.21, it crashes during the first loading screen (without, I have the main menu but it hangs when I launch a new mission)

But it should be tested with the Steam version because *cough* I don't really own the game *cough*. It's Platinum: https://www.protondb.com/app/15210

**Comment by ByCybernetik** [comment]
I thought you mean the game Silent Hill 3.

**Comment by DustyCrumpet** [comment]
Game appears to work fine here, only issue that I noticed while playing is the sky being rendered incorrectly.

**WineD3D:**
![wined3d](https://user-images.githubusercontent.com/58010930/69284424-83cf3580-0be6-11ea-8aab-66a8e91714b2.jpg)

**D9VK:**
![d9vk](https://user-images.githubusercontent.com/58010930/69284448-8d589d80-0be6-11ea-95f7-a399f88f6ae8.jpg)


**System information**

    GPU: Vega 56
    Driver: Mesa / RADV 19.2.4
    Wine version: Proton 4.11-8
DXVK version: 1.4.5
D9VK version: 55cb30c47f5c158afa159dde12ff9e8f8749bf55

**Apitrace file(s)**

[WineD3D trace](https://drive.google.com/open?id=1bN7oAmvDdgci2Bi3sCS-vJQBhHr2URtc)

**Log files**

[sh3_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3871843/sh3_d3d9.log)
