### ISSUE TITLE
Sonic Generations configuration tool white screen

### ISSUE THREAD

**Issue by BlazeKl** [Joshua-Ashton/d9vk#84]
The game's configuration tool uses d3d9 for rendering and it's completely white with d9vk, the windows is still clickeable and it creates the configs correctly for the game to run but it is impossible to change game settings, with Gallium 9 and WineD3D it renders properly, recorded an apitrace of the application using Gallium 9

### Software information
Sonic Generations

### System information
- GPU: AMD RX 470 4GB
- Driver: Mesa-git 19.2.0
- Wine version: Proton-tkg 4.7
- D9VK version: 43e5332f2a8cd5036664b9690ce7dbb8c31ca42b

### Apitrace file(s)
- https://drive.google.com/open?id=14WlzxMujqXITOUWb-27WOk5MAnO_K5HR

### Log files
- d3d9.log: [ConfigurationTool_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3162863/ConfigurationTool_d3d9.log)

**Comment by corvusd** [comment]
Do you can run the main game? For me crash before start whit small windows whit one botton "OK". Very weird.

**Comment by BlazeKl** [comment]
@corvusd you have to delete the GraphicsConfig.cfg file and then run the configuration tool with d9vk enabled and click where the "Save & Quit" button should be, the small windows that you get is empty because you are probably using a language different to english

**Comment by corvusd** [comment]
Okey, work. But freeze totally in the level. I try chemical level, very overhead in this for me.

My Hardware:
AMD Phenom(tm) II X6 1055T
8GB RAM DDR3-1333
SSD Sata3 KINGSTON 120Gb / Seagate Sata3 HDD 1TB
Nvidia GeForce GTX 1060 OC 3072MB VRAM DDR5
Ubuntu 16.04 LTS (Last updated) / Unity 7
Driver Nvidia: 418.56 official graphics ppa
Gamepad Xbox360 Wired USB

**Comment by BlazeKl** [comment]
are you using 0.10? that also happened to me before but it is fixed now on latest master

**Comment by corvusd** [comment]
Yes. Also in this game the e-sync also not working well. But still I have a lot of slowdowns, I think the same performance that in wined3d. This game show more than 2500 draw calls, I think this is a totally madness in Chemical Plant Level, arrive to low until 20 or less FPS constantly... :(

**Comment by BlazeKl** [comment]
this is partially fixed on master
![imagen](https://user-images.githubusercontent.com/17534468/60476319-2e02ec80-9c49-11e9-9127-3caf555f17e7.png)

**Comment by BlazeKl** [comment]
the issue seems to be fixed on master, closing

**Comment by NerosTie** [comment]
I think there is a regression here. I can't launch the configuration tool, it just crashes without anything on screen.

It works without d9vk.

**Comment by K0bin** [comment]
In that case we might actually need an WineD3D apitrace of the configuration tool.

**Comment by NerosTie** [comment]
Well, there it is:
https://mega.nz/#!Oih22CyT!C3_QawbsIgYa0FVGtPX0Cjz1y4NGR1w35Xq8Hoqsk-s

And the log (made with d9vk):
[steam-71340.log](https://github.com/Joshua-Ashton/d9vk/files/3541871/steam-71340.log)

**Comment by NerosTie** [comment]
I don't know why, but it looks like it's fixed. :man_shrugging:
