### ISSUE TITLE
Starcraft 2 bugs

### ISSUE THREAD

**Issue by LeJimster** [Joshua-Ashton/d9vk#85]
### Software information
Starcraft 2 Extreme (max) settings

### System information
- GPU: RX Vega 56
- Driver: Mesa 19.3.0-devel (git-0142dcb990) + RADV + LLVM 10.0.0
- Wine version: ge-protonified-nofshack-4.9 (Lutris)
- D9VK version: 0.20-frogcookie

- [x] When setting Post-processing to Ultra (it enables Depth of Field effect) I experience a strange effect.   See this video: https://youtu.be/YKQ9JByuivs : **Fixed with [b738c422](https://git.froggi.es/doitsujin/dxvk/commit/b738c4220b7f2ea71cf2f1f61521a08606ee7022)**
- [x] When setting shadows to Ultra, they aren't being shown correctly or at all.  Also I notice a black square with what looks like some of the shadows, but scaled really small, see last image. : **Fixed with [b738c422](https://git.froggi.es/doitsujin/dxvk/commit/b738c4220b7f2ea71cf2f1f61521a08606ee7022)**
- [x] When switching from Ultra to High shaders, game crashes with `e_gfxErrorShaderCompilerFailed`  See video: https://youtu.be/k94a-S6Wkzk : **Fixed with [b738c422](https://git.froggi.es/doitsujin/dxvk/commit/b738c4220b7f2ea71cf2f1f61521a08606ee7022)**

**Native**:
![SC2_Native_shadows](https://user-images.githubusercontent.com/35663469/57468959-715e6180-727d-11e9-9162-b34c91669999.jpg)
**D9VK**:
![SC2_D9VK_shadows](https://user-images.githubusercontent.com/35663469/57468995-7cb18d00-727d-11e9-9115-12a489d316fd.jpg)
**D9VK**:
![SC2_D9VK_shadows2](https://user-images.githubusercontent.com/35663469/57469070-a9fe3b00-727d-11e9-8e26-663a4eccb19d.jpg)

### Apitrace file(s)
- [Depth of Field trace](https://drive.google.com/open?id=1U9u-orROyO3BxGPyCWHsrndsy-fw3j9P)
- [Shadows trace](https://drive.google.com/open?id=1SRKd0vUjKyp-j6Y55Vcoy3n3I1w-Rolo)

### Log files
- d3d9.log: [SC2_x64_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3561607/SC2_x64_d3d9.log) << **new 30/8/19**
- dxgi.log: [SC2_x64_dxgi.log](https://github.com/Joshua-Ashton/d9vk/files/3561608/SC2_x64_dxgi.log) << **new 30/8/19**

**Comment by IngeniousDox** [comment]
I don't see the "Depth of Field" issue on Nvidia.

The shadows issue is known, with Low Shaders you have small circular shadows (Low Shadows) below the units, anything above it doesn't work yet. But should get implemented once Josh finds the time.

Awesome bug report btw, and thank you for the traces,

**Comment by Venemo** [comment]
On my machine, I see the same problem, but not just on ultra settings. The shadows do not show up on medium, either.

**Comment by LeJimster** [comment]
> On my machine, I see the same problem, but not just on ultra settings. The shadows do not show up on medium, either.

Yes you're correct, I should have said shadows are broken on anything above Low settings.  I was just testing with Extreme settings with all features on.

**Comment by LiamDawe** [comment]
Just here to confirm on NVIDIA I also see no Shadows.

**Comment by LinLo** [comment]
> Just here to confirm on NVIDIA I also see no Shadows.

Same here, tested for each graphic level settings.
If I'm right, shadows implementation is not done yet.

**Comment by LeJimster** [comment]
Any update on these issues?  I was also wondering if we knew whether the 1st bug was a d9vk issue or a mesa driver issue?  I notice nvidia users don't experience this problem and it could be reported on the mesa bug tracker if it's not a d9vk problem.

**Comment by v21cesc** [comment]
> Any update on these issues? I was also wondering if we knew whether the 1st bug was a d9vk issue or a mesa driver issue? I notice nvidia users don't experience this problem and it could be reported on the mesa bug tracker if it's not a d9vk problem.
> 
> For the last few months I was experiencing a crash, that I thought was due to an old LLVM, but I'm getting it with LLVM 10 and I've figure out how to replicate it. It could be related the first bug.
> 
> By switching from Ultra shaders > Medium the game crashes with `e_gfxErrorShaderCompilerFailed`
> 
> The last things in the log file:
> 
> > warn:  ConvertFormat: Unknown format encountered: D3D9Format::AL16
> > warn:  ConvertFormat: Unknown format encountered: D3D9Format::R16
> 
> Video showing the crash: https://youtu.be/k94a-S6Wkzk
> [SC2_x64_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3561586/SC2_x64_d3d9.log)

Only the 2nd issue happens with nvidia proprietary driver.
No shadows at all with any graphic level. This issue can also be found in other games like half-life blackmesa

**Comment by Joshua-Ashton** [comment]
Can you test with: https://github.com/doitsujin/dxvk/commit/b738c4220b7f2ea71cf2f1f61521a08606ee7022

**Comment by duramuss** [comment]
I can test it but I cannot produce the dlls.

**Comment by Joshua-Ashton** [comment]
https://git.froggi.es/doitsujin/dxvk/-/jobs

**Comment by LeJimster** [comment]
The first 2 bugs are fixed for me now.  I need further testing for the 3rd bug as I've experienced random crashes in previous builds with the same error message.  Thanks!  Will do some more testing =)

**Comment by duramuss** [comment]
The game definitely looks better now and the improvement does not seem to cost any fps.
b738c42:
![gb738c42](https://user-images.githubusercontent.com/36989579/72102923-60904f00-3328-11ea-89b5-af676ad998b0.png)
DXVK 1.5:
![dxvk1 5](https://user-images.githubusercontent.com/36989579/72102961-7bfb5a00-3328-11ea-9af3-641047cc53a8.png)

**Comment by LeJimster** [comment]
All 3 of the original bugs I found appear to be fixed, however I've experienced some random crashes with older builds resulting in the familiar `e_gfxErrorShaderCompilerFailed` message, and also had the same message when trying to load certain custom games.  It appears to happen a lot less with this new build so far, and some games that crashed before now work....  However I'm still experiencing a crash with a Tower Defense map.  It either hangs or crashes on the loading screen with that error message `e_gfxErrorShaderCompilerFailed`. 
I've created a trace.
[Tower Defense trace](https://drive.google.com/open?id=1h_ryixliY_mHj6te6fEXpruoCB5i3bo3)
[SC2_x64_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/4043278/SC2_x64_d3d9.log)

**Comment by LeJimster** [comment]
Here are two more maps that crash on the loading screen with the same error message as above.   Hopefully it's all the same issue causing the crashes.
[Direct Strike trace](https://drive.google.com/open?id=13m7VARhotqKeQ_PJUaZr-NysCcf37V8W)
[Hero Line Wars Starlight trace](https://drive.google.com/open?id=1s5u_XQtcsl2BHWkHhVjEBSLjbVs_2iS8)

FYI these crashes have been happening since early d9vk builds, I just didn't bother reporting as I thought they were related to bug #3.

**Comment by EldarAgalarov** [comment]
Tested with DXVK 1.5.1 - it works great now. Shadows are present at 60 fps. Great job!

**Comment by misyltoad** [comment]
@LeJimster You'll need to use native `d3dx9` and `d3dcompiler` as Wine's impls make invalid calls/shaders.

If it still happens can you open an issue about it on the main DXVK tracker? Cheers.
