### ISSUE TITLE
Error installing D9VK on custom Proton Prefix.

### ISSUE THREAD

**Issue by Orochikyocr** [Joshua-Ashton/d9vk#86]
I really excited about this release since most of the games I play are DX9 games and I want to test how these games could benefit with D9VK. Im trying to install D9VK on the custom proton prefixes Steam creates for every game on the Steamapps folder. 
Still, When I try to install the files using the setup_dxvk.sh file I receive a message telling me the installer  "Failed to resolve C:\windows\system32"
Dropping the D9VK files on the folder causes the game not launching from Steam, So I think maybe there is something on the installer that is just beyond copying and pasting but cant install from there.
Any advice?
Thanks in advanced.

**Comment by LeJimster** [comment]
I only know how to do it per game if thats any use for you?

Drop the `d3d9.dll` next to the games executable.  Find the prefix for that game then add a dll override for `d3d9` set to `native` with `winecfg`

I don't know if it's easier to see how I do, but I made a video using Borderlands as an example.  Sorry no talking =P

https://youtu.be/lbBH01UAKPQ

The only other thing I would say is know whether you need the 32-bit or 64-bit `d3d9.dll`
If your not sure you can use `file /path/to/game.exe` to check 
For 32bit executables you should get: `PE32 executable (GUI) Intel 80386, for MS Windows`
For 64bit executables you should get: `PE32+ executable (GUI) x86-64, for MS Windows`

**Comment by Arucard1983** [comment]
On Steam use the variable WINEDLLOVERRIDES="d3d9.dll=n" before everything else.

**Comment by LeJimster** [comment]
> On Steam use the variable WINEDLLOVERRIDES="d3d9.dll=n" before everything else.

Doh, thats much easier that how I normally do it.  I didn't realise that could be set from the Launch Properties. very good =).

So now I have in my borderlands launch properties:
`WINEDLLOVERRIDES="d3d9=n" DXVK_HUD=full %command%`

**Comment by Orochikyocr** [comment]
Thank you both, for the advices, I was about to give up but gonna try.

**Comment by pchome** [comment]
Also for your custom Proton you can use something like this:
<details>
  <summary>Proton 4.2 D9VK Patch</summary>

```patch
--- a/proton
+++ b/proton
@@ -268,6 +268,7 @@
 check_environment("PROTON_NO_ESYNC", "noesync")
 check_environment("PROTON_FORCE_LARGE_ADDRESS_AWARE", "forcelgadd")
 check_environment("PROTON_OLD_GL_STRING", "oldglstr")
+check_environment("PROTON_NO_D9VK", "nod9vk")
 
 if not "noesync" in config_opts:
     env["WINEESYNC"] = "1"
@@ -449,6 +450,13 @@
                 os.remove(dst)
             os.symlink(src, dst)
 
+    def make_d9vk_links(dll_dir, link_dir):
+        dst = link_dir + "/d3d9.dll"
+        src = dll_dir + "/d3d9.dll"
+        if os.path.lexists(dst):
+            os.remove(dst)
+        os.symlink(src, dst)
+
     if "wined3d" in config_opts:
         #use gl-based wined3d for d3d11 and d3d10
         make_dxvk_links(basedir + "/dist/lib64/wine/fakedlls/",
@@ -464,6 +472,20 @@
         for f in dxvkfiles:
             dlloverrides[f] = "n"
 
+    if "nod9vk" in config_opts:
+        #use gl-based wined3d for d3d9
+        make_d9vk_links(basedir + "/dist/lib64/wine/fakedlls/",
+            prefix + "drive_c/windows/system32")
+        make_d9vk_links(basedir + "/dist/lib/wine/fakedlls/",
+            prefix + "drive_c/windows/syswow64")
+    else:
+        #use vulkan-based d9vk for d3d9
+        make_d9vk_links(basedir + "/dist/lib64/wine/d9vk/",
+            prefix + "drive_c/windows/system32")
+        make_d9vk_links(basedir + "/dist/lib/wine/d9vk/",
+            prefix + "drive_c/windows/syswow64")
+        dlloverrides["d3d9"] = "n"
+
 if "nod3d11" in config_opts:
     dlloverrides["d3d11"] = ""
     if "dxgi" in dlloverrides:
```
[proton-4.2-d9vk.patch.txt](https://github.com/Joshua-Ashton/d9vk/files/3164526/proton-4.2-d9vk.patch.txt)
Copy to Proton's directory and execute `patch -p1 < proton-4.2-d9vk.patch.txt`
</details>

Then copy `d3d9.dll`s into `dist/lib64/wine/d9vk/` and `dist/lib/wine/d9vk/`.
Proton will use D9VK same way as DXVK, `PROTON_NO_D9VK=1` variable to use WINE's `d3d9`.

**Comment by Orochikyocr** [comment]
Used both methods, first dropping D3d9 individually and using command to  override Wine default D3D9,
then patching proton and copying the files to their respective folder Pchome.
In some games I can see the Vulkan Hud working but blackscreen, then other games just goes blackscreen, then other games doesnt even launch. 
Command PROTON_NO_D9VK=1 makes the games to work again. Im guess if D9VK needs some minimal requirements. Im stil with Linux 4.19, Mesa 18.2.10, using AMDGPU driver.

**Comment by LeJimster** [comment]
Yeah.  Some games work really well, others with minor bugs, some have black screen, some won't even launch.  It's still early days.
For example, we noticed that Starcraft 2 wouldn't even launch on stable mesa (19.0) for AMDGPU.  I'm running mesa-git (19.1-devel) LLVM 9.0.0 and RADV.  I'm pretty sure there has been some Vulkan updates since 18.2, so it might be worth upgrading.

**Comment by Orochikyocr** [comment]
> Yeah. Some games work really well, others with minor bugs, some have black screen, some won't even launch. It's still early days.
> For example, we noticed that Starcraft 2 wouldn't even launch on stable mesa (19.0) for AMDGPU. I'm running mesa-git (19.1-devel) LLVM 9.0.0 and RADV. I'm pretty sure there has been some Vulkan updates since 18.2, so it might be worth upgrading.

Actually Im aware of this, just guessing if I done all the steps correctly. In Lutris I was able to run two games, a Mugen game and Starcraft with D9VK, so I think my system is fine.
Testing more, I get sound but black screen on another. I would like to post game bugs but I dont even know if I running D9VK correctly. Ill wait for some sort of official integration with Steamplay to start reporting bugs.
Thanks to everyone.

**Comment by codeman101** [comment]
@LeJimster 
> > On Steam use the variable WINEDLLOVERRIDES="d3d9.dll=n" before everything else.
> 
> Doh, thats much easier that how I normally do it. I didn't realise that could be set from the Launch Properties. very good =).
> 
> So now I have in my borderlands launch properties:
> `WINEDLLOVERRIDES="d3d9=n" DXVK_HUD=full %command%`

Can this be done without adding the dll from this repo because I can find it even after doing `grep -r ".dll" ` on the downloaded repo. Do you have build the source files to get the dll? How is that possible on a Linux machine?

**Comment by LeJimster** [comment]
> @LeJimster
> 
> > > On Steam use the variable WINEDLLOVERRIDES="d3d9.dll=n" before everything else.
> > 
> > 
> > Doh, thats much easier that how I normally do it. I didn't realise that could be set from the Launch Properties. very good =).
> > So now I have in my borderlands launch properties:
> > `WINEDLLOVERRIDES="d3d9=n" DXVK_HUD=full %command%`
> 
> Can this be done without adding the dll from this repo because I can find it even after doing `grep -r ".dll" ` on the downloaded repo. Do you have build the source files to get the dll? How is that possible on a Linux machine?

If you want pre-compiled dll's you can either download them from the [Releases](https://github.com/Joshua-Ashton/d9vk/releases) page or you can get more recent development builds [here](https://git.froggi.es/joshua/d9vk/-/jobs).

**Comment by codeman101** [comment]
@LeJimster 

Thanks for the help unfortunately I still couldn't get it working. I didn't make a custom proton version like the guy in the video. I just wanted to edit the specific game so it would work with d9vk but adding the dll to the game's binaries/win32 directory doesn't do anything and add DXVK_HUD=full causes the game to not launch.

**Comment by LeJimster** [comment]
You need to tell the game to use d9vk, basically setting d3d9 to "native" in winecfg.

I believe its something like this should work..

'WINEDLLOVERRIDES="d3d9=n" DXVK_HUD=full %command%'

**Comment by codeman101** [comment]
@LeJimster 

It still didn't work. I even tried pasting all the dlls from the 32 folder into win32 of the game's binary directory.

**Comment by LeJimster** [comment]
Its possible that the game you're testing doesnt work with d9vk.  Have you seen anyone else running the same title on d9vk?

**Comment by codeman101** [comment]
@LeJimster 

Yes it's how I found out about the repo in the first place. https://www.protondb.com/app/288470 Maybe I need to run the setup.sh file?

**Comment by LeJimster** [comment]
@codeman101 did you install dotnet40 to the games prefix using protontricks? Also make sure d3d9.DLL is in the same folder as the games executable, win32 sounds right but some games use launchers and the actual executable might be in a separate folder.

**Comment by codeman101** [comment]
@LeJimster 

dotnet40 used to be required to get the game running at all but not anymore because wine-mono has caught up to it. To clarify I'm not trying to use d9vk to get the game running just to fix graphical issues. Also I verified that the game's exe launcher is in the same directory.

**Comment by codeman101** [comment]
@LeJimster 

I got it to work. The solution was to do this. ```
export WINEPREFIX=~/.steam/steam/steamapps/compatdata/288470/pfx
./setup_dxvk.sh install
```
