### ISSUE TITLE
Scribblenauts Unlimited fails to launch with D9VK

### ISSUE THREAD

**Issue by Managor** [Joshua-Ashton/d9vk#87]
[Scribble_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3164801/Scribble_d3d9.log)

[steam-218680.log](https://github.com/Joshua-Ashton/d9vk/files/3164806/steam-218680.log)

[Scribble.trace.zip](https://github.com/Joshua-Ashton/d9vk/files/3164818/Scribble.trace.zip)

The game launches fine without D9VK enabled

### Software information
Scribblenauts unlimited

### System information
- GPU: Nvidia 1060 6G
- Driver: 430.09 
- Wine version: 4.3
- D9VK version: 0.10 (43e5332)

### Apitrace file(s)
[Scribble.trace.zip](https://github.com/Joshua-Ashton/d9vk/files/3164818/Scribble.trace.zip)

**Comment by Managor** [comment]
Well the game exits almost immediately after launch so there's not much to record.

**Comment by neVERberleRfellerER** [comment]
Do the apitrace without D9VK.

**Comment by Managor** [comment]
[Scribble.trace.zip](https://github.com/Joshua-Ashton/d9vk/files/3174239/Scribble.trace.zip)
Here you go.

**Comment by neVERberleRfellerER** [comment]
Do you have native d3dx9_something.dll? 
It seems that game loads builtin (wine) versions of these:
```
56762.327:0036:0037:trace:module:load_builtin_dll Trying built-in L"d3dx9_43.dll"
```
Use native versions. Same for d3dcompiler_something.dll:
```
56762.328:0036:0037:trace:module:load_dll L"\\??\\C:\\windows\\system32\\d3dcompiler_47.dll" is a fake Wine dll
56762.328:0036:0037:trace:module:load_builtin_dll Trying built-in L"d3dcompiler_47.dll"
```
It renders this way for me:
![Screenshot_20190513_205452 png](https://user-images.githubusercontent.com/11160972/57646739-8a3e7e00-75c1-11e9-8d46-7e305833d4b8.jpg)

**Comment by Managor** [comment]
Yeah, it launches for me now.
