### ISSUE TITLE
Batman Arkham Asylum GOTY - Mapping memory failed

### ISSUE THREAD

**Issue by aqxa1** [Joshua-Ashton/d9vk#90]
Game randomly crashes, then reliably crashes at a certain point in the game, with:

```err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED
err:   DxvkMemoryAllocator: Memory allocation failed
```

Bug doesn't occur with Gallium Nine, or wined3d. It's likely related to the 32-bit issues that DXVK also has. Executable appears to already have the LARGE_ADDRESS_AWARE flag set, so that can't be used as a workaround.

### Software information
Batman Arkham Asylum GOTY, 2560x1440, high settings, 2xMSAA

### System information
- GPU: RX Vega 56
- Driver: mesa-git/LLVM git
- Wine version: 4.7-staging
- D9VK version: git

### Apitrace file(s)
Was unable to obtain a trace (copied lib/wrappers/d3d9.dll from current apitrace release into game directory, but no trace was generated)

### Log files
- d3d9.log: https://pastebin.com/qiVgYfL0

Screenshot of error message that the game outputs:
https://imgur.com/a/yNTDerE

**Comment by Joshua-Ashton** [comment]
Hi, can you try adding

d3d9.trustEvictions=True

In dxvk.conf

**Comment by aqxa1** [comment]
@Joshua-Ashton No change, unfortunately. I've added a screenshot of the error message to the report, which I forgot to add earlier.

**Comment by Jrugia** [comment]
@aqxa1  If you have a secondary display you can monitor the game's Virtual Memory consumption, that will give you a better idea when the crash is about to occur.

**Comment by Joshua-Ashton** [comment]
Hi, can you try latest master?

Specifically https://github.com/Joshua-Ashton/d9vk/commit/9373a3917ffdb2c712626f4859b5ae1d719e831b may have an effect.

**Comment by aqxa1** [comment]
Hi, latest master didn't help. I looked at virtual memory and it's around 2800M before the crash, and jumps to around 3450M when the game crashes. 

Whereas, with Gallium Nine, virtual memory hovers around 2200M before and after the period where the game would crash with D9VK.

I also tried the AMDVLK driver, and the game still crashes.

**Comment by Joshua-Ashton** [comment]
Can you try on latest master now please? Cheers.

**Comment by aqxa1** [comment]
Problem remains, and virtual memory looks to be the same as before (2800-3400M).

**Comment by pchome** [comment]
The problem likely in `nvapi`™, since the game using PhysX and 4.7-staging provides `nvapi` libraries.
So let me guess what going on:
1. the game trying to load `nvapi`, and succeeded
2. `nvapi` from staging depend on `wined3d` and `d3d11`
3. `d3d11` depend on `dxgi`
4. now (depending on your settings) you have "full house" -- running `opengl`, `dxvk` and `d9vk` (`cuda`, for Nvidia users, also some games can load `ddraw` in addition)

:smile: 

Sure, maybe I'm wrong, so better check your wine output with `WINEDEBUG="+loaddll"`.

I just faced similar issue in GTA EFLC, where in addition to usually disabled d3d11, d3d10 and nvapi (just to be sure) I also disabled `wined3d`. This likely will break things, like `gta4Browser.exe` now don't loading, but the game itself became a bit smoother.

**Comment by aqxa1** [comment]
@pchrome - no change from disabling nvapi, wined3d, d3d11, and nvcuda (maybe very slight lowering of virt memory, but not enough to prevent the bug). Bug still occurs with vanilla wine 4.8, so the issue isn't staging specific either.

**Comment by Joshua-Ashton** [comment]
Are you on latest master? I made some memory changes recently

**Comment by aqxa1** [comment]
@Joshua-Ashton Yep, none of the changes seem to have had an effect. Anyone else own the game? It might be something specific to my system.

**Comment by pchome** [comment]
@aqxa1 
I have the game in my Steam library, and last time I checked it with D9VK (a month ago or so) it works more or less OK. But, TBH, I tested only for a few minutes.

> Was unable to obtain a trace (copied lib/wrappers/d3d9.dll from current apitrace release into game directory, but no trace was generated)

Sometimes you should set dll-overrides to `d3d9=n,b`, not just `d3d9=n`.

> It might be something specific to my system.

Could you share your log (`${HOME}/steam-35140.log` file, if Proton) with `WINEDEBUG="+loaddll"` enabled?

<hr/>

_I found my old log file, dated exactly this day month ago._
<details>
  <summary>exactly as I guessed</summary>

```buld
Accessibility.dll native
actxprxy.dll builtin
advapi32.dll builtin
APEX_Destructible.dll native
APEX_Particles.dll native
APEX_release.dll native
APEX_RRB.dll native
avrt.dll builtin
bcrypt.dll builtin
binkw32.dll native
BmLauncherUtils.dll native
comctl32.dll builtin
comdlg32.dll builtin
crypt32.dll builtin
cudart32_60.dll native
d3d9.dll builtin
d3dx9_43.dll native
dbghelp.dll builtin
ddraw.dll builtin
dinput8.dll builtin
dsound.dll builtin
faultrep.dll builtin
fusion.dll builtin
gameux.dll builtin
gdi32.dll builtin
gdiplus.dll builtin
hid.dll builtin
imm32.dll builtin
iphlpapi.dll builtin
KERNEL32.dll builtin
libmono-2.0-x86.dll native
libresample.dll native
lsteamclient.dll builtin
Microsoft.DirectX.Direct3D.dll native
Microsoft.DirectX.dll native
mmdevapi.dll builtin
Mono.Posix.dll native
Mono.Security.dll native
msacm32.dll builtin
mscoree.dll builtin
mscorlib.dll native
msvcm80.dll builtin
msvcp80.dll builtin
msvcr80.dll builtin
msvcr90.dll builtin
msvcrt.dll builtin
nvapi.dll builtin
nvcuda.dll builtin
NxCooking.dll native
ole32.dll builtin
oleaut32.dll builtin
opengl32.dll builtin
PhysXCooking.dll native
PhysXCore.dll native
PhysXDevice.dll native
PhysXExtensions.dll native
PhysXLoader.dll native
powrprof.dll builtin
propsys.dll builtin
psapi.dll builtin
rpcrt4.dll builtin
setupapi.dll builtin
shcore.dll builtin
shell32.dll builtin
shlwapi.dll builtin
steam_api.dll native
steam.dll native
System.Configuration.dll native
System.dll native
System.Drawing.dll native
System.Management.dll native
System.Windows.Forms.dll native
System.Xml.dll native
user32.dll builtin
userenv.dll builtin
usp10.dll builtin
uxtheme.dll builtin
version.dll builtin
windowscodecs.dll builtin
wined3d.dll builtin
winevulkan.dll builtin
winmm.dll builtin
ws2_32.dll builtin
wsock32.dll builtin
wtsapi32.dll builtin
wxmsw28u_adv_vc_custom.dll native
wxmsw28u_aui_vc_custom.dll native
wxmsw28u_core_vc_custom.dll native
wxmsw28u_html_vc_custom.dll native
wxmsw28u_vc_custom.dll native
wxmsw28u_xml_vc_custom.dll native
wxmsw28u_xrc_vc_custom.dll native
xinput1_3.dll builtin
```
</details>

_Exept `dxgi/d3d11` still disabled, but `nvapi` enabled for testing purposes. Also my custom `nvapi` w/o d3d11 support, so loaded._

_The game currently uninstalled._

**Comment by pchome** [comment]
I created two scripts, which help me detect such situations.

[Informs if DXVK/D9VK/OpenGL/NvAPI/... used at the same time.](https://github.com/pchome/dumb-game-mode/blob/2cca345a52f796da1b89ed027bb41892b6653e83/dumb-game-mode.sh#L130:L163)
[Informs if Wine builtin d3d9x\_\*.dll.so or d3dcompiler\_\*.dll.so used.](https://github.com/pchome/dumb-game-mode/blob/2cca345a52f796da1b89ed027bb41892b6653e83/dumb-game-mode.sh#L180:L205)
###### _Copy/paste lines from `lsof -nPT ...` to `... END { report() }'` directly in terminal emulator when game already running. It's a `awk` scripts to parse `lsof` output. Silent if nothing was found._

###### _(or try [the whole thing](https://github.com/pchome/dumb-game-mode))_

**Comment by aqxa1** [comment]
Not sure what caused it to start working properly but it looks to be fixed now. Around 1100mb RAM allocated at the particular scene, and no crash. Big improvement, thanks!
