### ISSUE TITLE
Issue using rthdribl 2.0 benchmark..

### ISSUE THREAD

**Issue by oscarbg** [Joshua-Ashton/d9vk#91]
### Software information

I use Wine staging 4.7, radv 19.2dev latest on Vega 56..

Using rthdribl 2.0 from (site doesn't render correctly):
http://www.daionet.gr.jp/~masa/rthdribl/
link:
http://www.daionet.gr.jp/~masa/archives/rthdribl_2_0.zip
doesn't work correctly with d9vk 0.10 even it works with wined3d default d3d9 support or https://github.com/iXit/wine-nine-standalone ..
for getting working this program needs Win DLLs mfc71.dll and (d3dx9_35.dll  or d3dx9_37.dll I copied both from Win partition)

log below..

### System information
- GPU: Vega
- Driver: RADV
- Wine version: 4.7 stating
- DXVK version: 

### Log files
- d3d11.log: 
[rthdribl_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3166846/rthdribl_d3d9.log)

- dxgi.log:

**Comment by oscarbg** [comment]
just tested with 0.12 and same issues..
noted all warnings are D3D9DeviceEx .. 
I think this is a good app to support as uses D3D9Ex..
so D3D9Ex is supported or planned to?
thanks..

**Comment by K0bin** [comment]
D3D9Ex is supported. The issue is probably ColorFill (which is being worked on) and those two render states at the bottom.

**Comment by oscarbg** [comment]
just tested with 0.13:
updated log:
[rthdribl_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3373821/rthdribl_d3d9.log)
doesn't work yet.. but great progress..
only warnings due to D3D9DeviceEx::SetRenderState Unhandled render state X..
all stub warnings disappeared:
D3D9DeviceEx::SetTextureStageState: Stub
D3D9DeviceEx::SetMaterial: Stub
and also:
warn:  DxsoCompiler::emitTextureSample: Adding implicit 2D sampler
due to commits:
[dxvk] Add support for implicit samplers
https://github.com/Joshua-Ashton/d9vk/commit/7fa0016ba7d468b2012c7739f3a1956f993c5c06
[d3d9] Implement Get/SetTextureStageState
https://github.com/Joshua-Ashton/d9vk/commit/6dd81f1ded6704f9f01b991e1c55e67f71604b6e
[d3d9] Implement state tracking for materials
https://github.com/Joshua-Ashton/d9vk/commit/6a1167fb586e5c17cc33481d80b1e9ff262f2e87#diff-bf29a83eb73ce6d6e38dc1ed9e7f6551

**Comment by oscarbg** [comment]
there is progress here with 0.20rc1
https://git.froggi.es/joshua/d9vk/commit/da8c8370ee6945002b9f56a36df16101630bf4f1
only two warnings left:
```
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_SPECULARENABLE
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_DITHERENABLE
```
still can't see nothing as not responding on loading.. please wait..
curious if some AAA D3D9 games depending also on:
D3DRS_SPECULARENABLE
D3DRS_DITHERENABLE

**Comment by oscarbg** [comment]
forgot to say maybe an issue with D3D9 rendering inside a classic Win app with menu,etc..
might be a "child window rendering" issue? or some interop issue with GDI library or something?
no idea.. just saying because similarly Cemu Vulkan has problems running on Wine:
https://bugs.winehq.org/show_bug.cgi?id=45277
```
0235:fixme:vulkan:X11DRV_vkCreateWin32SurfaceKHR Application 
requires child window rendering, which is not implemented yet!
```

**Comment by Joshua-Ashton** [comment]
re. child window rendering, that's a WineVulkan bug.
