### ISSUE TITLE
Prototype -  auto close

### ISSUE THREAD

**Issue by Eignar17** [Joshua-Ashton/d9vk#92]
prototype close and generates this code in wine

terminate called after throwing an instance of 'std::out_of_range'
  what():  array::at: __n (which is 1188) >= _Nm (which is 17)
0030:fixme:msvcrt:__clean_type_info_names_internal (0x1131fe54) stub

### Software information
Prototype,800x600, all low, no Antialiasing

### System information
- GPU:nvidia 1050 oc
- Driver:430.09
- Wine version: 4.7
- DXVK version: git

### Apitrace file(s)
https://mega.nz/#!LxcQWQhI!jZ0g5mSavRv2MHeFQBJweSmLk_LOiLaFu-sayNCC9MU

### Log files
- d3d9.log:[prototypef_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3168610/prototypef_d3d9.log)

**Comment by qsniyg** [comment]
Does it work without D9VK though? Apparently the game doesn't work at all for modern CPUs. It didn't work for me either under windows, or under vanilla wine.

**Comment by Joshua-Ashton** [comment]
Can you please provide a trace? It may be on your desktop.

I can't fix an issue like this without either owning the game or having a trace.

**Comment by Eignar17** [comment]
@Joshua-Ashton  upload apitrace

**Comment by bugandy** [comment]
Same issue for me.

> Does it work without D9VK though?

Prototype work without d9vk, but is limited to 20fps.
Disabling csmt patch is 30min-90max fps, but graphics glitch.

**Comment by Yardanico** [comment]
Prototype works for me as of latest d9vk with latest nvidia vulkan drivers. Didn't play enough to thoroughly check for any bugs (expect for like 10ms green-color background at the game menu loading after the copyright) 
I'm also using a full-hd patch

**Comment by Yardanico** [comment]
I played for around 30 mins (with low/mid/max settings at FullHD), riding tanks, helicopters, doing explosions, etc, didn't notice a single bug :D

**Comment by bugandy** [comment]
Thank-you. Solved for me too.
Min 45, max 60 fps at max settings.

**Comment by Joshua-Ashton** [comment]
Can this be closed then?

**Comment by Eignar17** [comment]
fix problem :3rd_place_medal:
