### ISSUE TITLE
Bloodstained: Curse of the moon - Black screen with sound

### ISSUE THREAD

**Issue by Zeioth** [Joshua-Ashton/d9vk#97]
When I open the game, I see a black screen. Pressing some random keys I start to listen the game's music. 

![cast](https://user-images.githubusercontent.com/3357792/57571651-0cd40b80-7411-11e9-904b-c45a845d8cc0.png)

### Log files
- [d3d9.log](https://pastebin.com/raw/vmxr6eRV)

### More info:

* Lutris + Proton 4.2
* d9vk-7a9e9fb6
* Nvidia 1070
* Ryzen 1700
* GPU driver: 430.09

### More info:
Even without d9vk the issue remains. So maybe this is not a d9vk issue. Needs confirmation.

**Comment by Joshua-Ashton** [comment]
Trace?

**Comment by NerosTie** [comment]
It's not related to d9vk, it's a missing dll (I installed d3dx9 from winetricks).
It works fine:
![Screenshot_20190920_180830](https://user-images.githubusercontent.com/4572452/65341964-fbc2b480-dbd1-11e9-860f-82fd7b557c56.png)

**Comment by Zeioth** [comment]
I still get the black screen after installing d3dx9 from winetricks. But thank you for your comment @NerosTie

**Comment by NerosTie** [comment]
Are you sure d3dx9 was installed in the right prefix? (with Steam, don't forget the "/pfx" at the end or try protontricks, it's easier). I played 1 hour, so it should works for you too.

**Comment by aidinzolghadr** [comment]
> I still get the black screen after installing d3dx9 from winetricks. But thank you for your comment @NerosTie

Did you ever solve this? I also installed d3dx9 from Protontricks, but still have the same issue.
