### ISSUE TITLE
Assassin's Creed II hangs with DXVK state cache enabled

### ISSUE THREAD

**Issue by AccountOneOff** [Joshua-Ashton/d9vk#98]
Game menu works and the Desmond loading screen works but as soon as the screen turns white to load in it crashes.

### Software information
Also tried all low settings. No difference.

![Screenshot from 2019-05-11 19-06-30](https://user-images.githubusercontent.com/15083452/57576890-f97c6c80-741f-11e9-9c3d-1055a6b6f5c5.png)

### System information
- GPU: GTX 960
- Driver: 418.56
- Wine version: Wine Staging 4.6
- DXVK version: ca3c81c1

### Apitrace file(s)
- https://drive.google.com/open?id=1qavOf6brbxieRQQl747rK08cuU63XSiA

### Log files
- [AssassinsCreedIIGame_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3169637/AssassinsCreedIIGame_d3d9.log)

**Comment by neVERberleRfellerER** [comment]
It does not crash with latest RADV, but I doubt this is what the game is supposed to look like:
![Screenshot_20190512_152134 png](https://user-images.githubusercontent.com/11160972/57582830-df976400-74c9-11e9-8b76-3671a640029d.jpg)

**Comment by neVERberleRfellerER** [comment]
With current master (c8fb2d569675cd7ef37712b0b2d4efe53db752c6):
![Screenshot_20190512_213213 png](https://user-images.githubusercontent.com/11160972/57586943-93fead80-74fd-11e9-9478-dac791b6d43d.jpg)

**Comment by Dthibault** [comment]
Using 2a0c153b for D9VK, the game was frozen 6-7 times at the launch (No errors in the log).
On the last launch, the game worked but:

- Some textures were missing (A few people textures)
- After 2 minutes, the game crashed...

BUT! It worked faster than WineD3D! Very impressive!

**Comment by AccountOneOff** [comment]
Looks like it's a problem with my game save. I was able to reach in-game with a new game but it looks like this. Used d9vk 0.11

[AssassinsCreedIIGame_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3175597/AssassinsCreedIIGame_d3d9.log)

![Screenshot from 2019-05-13 19-23-56](https://user-images.githubusercontent.com/15083452/57666636-79880b00-75b5-11e9-8f66-bdb47d234f3a.png)

**Comment by AccountOneOff** [comment]
I bisected but 1e088094978965bed69f1acc37d1ac02159be98c failed to build so I tried the next commit da392277550446f2d037a3dcfd6fb15e59654daf and it has the same issue as above.

**Comment by Dthibault** [comment]
Are you using the Uplay version or the Steam+Uplay version ? (Like me)

For now, I can't get past the intro video (Need to kill the process)

**Comment by AccountOneOff** [comment]
Game looks to rendering right but yeah it hangs on launch with the state cache enabled.

**Comment by AccountOneOff** [comment]
Scratch that, the parking lot and enemies at the beginning don't render.

Invisible guards:

![Screenshot from 2019-05-15 20-50-51](https://user-images.githubusercontent.com/15083452/57825515-11bbf680-7754-11e9-9879-9c6b9b71d07d.png)

Invisible Lucy:

![Screenshot from 2019-05-15 20-52-36](https://user-images.githubusercontent.com/15083452/57825516-11bbf680-7754-11e9-800e-485df8b8a7a8.png)

Elevator not rendering:

![Screenshot from 2019-05-15 20-53-17](https://user-images.githubusercontent.com/15083452/57825517-12548d00-7754-11e9-9d1b-2152a83c2b49.png)

Parking lot not rendering:

![Screenshot from 2019-05-15 20-53-35](https://user-images.githubusercontent.com/15083452/57825518-12548d00-7754-11e9-9d1a-cddec7d17e0b.png)

Game crashed while fighting those dudes.

**Comment by AccountOneOff** [comment]
The issues in my last comment are now fixed. However, there's an issue with blood. It gets suspended in air.

![Screenshot from 2019-06-16 17-45-00](https://user-images.githubusercontent.com/15083452/59572115-bb4a1c80-905f-11e9-97c2-1c707c6eb553.png)

[AssassinsCreedIIGame_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3294855/AssassinsCreedIIGame_d3d9.log)

**Comment by AccountOneOff** [comment]
Closing since the original issue is fixed.
