### ISSUE TITLE
GTA IV - Rendering issues on AMD and Intel

### ISSUE THREAD

**Issue by ThisNameIsntTaken** [Joshua-Ashton/d9vk#99]
### Software information
GTA IV at max settings

### System information
- GPU: RX 580 4GB and UHD 620
- Driver: AMDVLK 2019.Q2.2,  RADV Git and ANV 19.0.3
- Wine version: Proton 4.2-3
- D9VK version: da39227

GTA IV has artifacting issues on AMD and Intel as well. On RADV and ANV the car textures aren't rendered correctly, AMDVLK doesn't have this problem. On Intel, there are even more issues.

AMDVLK:
![amdvlk](https://user-images.githubusercontent.com/44706448/57582193-14072200-74c2-11e9-80e4-24349737cf79.png)
![amdvlk2](https://user-images.githubusercontent.com/44706448/57582194-14072200-74c2-11e9-9e59-b4728f28eb02.png)
https://www.youtube.com/watch?v=2EukzCABdhA

RADV:
![radv](https://user-images.githubusercontent.com/44706448/57582203-3c8f1c00-74c2-11e9-8a8e-41180a023269.png)
![radv2](https://user-images.githubusercontent.com/44706448/57582204-3d27b280-74c2-11e9-9811-b4eaa040e6d1.png)
https://www.youtube.com/watch?v=P1d1mlIO8Z8

Intel:
![intel](https://user-images.githubusercontent.com/44706448/57582212-44e75700-74c2-11e9-9821-864ee8b71f28.png)
![intel2](https://user-images.githubusercontent.com/44706448/57582213-44e75700-74c2-11e9-9511-6e37e15f7db1.png)
https://www.youtube.com/watch?v=EIQZd-_AFks

### Apitrace file(s)
- https://mega.nz/#!DEFnDQLI!G0fkUFzyZSvxbImQbB8xsSFNTX4bt_IWPoOXfbUalG8
For some reason, most of the artifacting visible in the screenshots and the videos above, are not visible when replaying the trace.

### Log files
- d3d9.log (AMDVLK): [GTAIV_d3d9_amdvlk.log](https://github.com/Joshua-Ashton/d9vk/files/3170005/GTAIV_d3d9_amdvlk.log)
- d3d9.log (RADV): [GTAIV_d3d9_radv.log](https://github.com/Joshua-Ashton/d9vk/files/3170007/GTAIV_d3d9_radv.log)
- d3d9.log (Intel): [GTAIV_d3d9_intel.log](https://github.com/Joshua-Ashton/d9vk/files/3170006/GTAIV_d3d9_intel.log)

**Comment by Joshua-Ashton** [comment]
Game seems to render fine on NVidia.

I ran a spirv-val on the shaders and everything seems to be OK -- I checked the shaders and didn't see anything too crazy it was doing.

Need to compile a new version of regular vk val layers to check those (current SDK is completely broken.)

**Comment by Joshua-Ashton** [comment]
This should be fixed (well, worked around) by the [d3d9-hazards](https://github.com/Joshua-Ashton/d9vk/tree/d3d9-hazards) branch.

**Comment by jacobbrett** [comment]
The d3d9-hazards workaround fixed the issue for me, though at the expense of a framerate drop.

I tested the same scene several times, casually observing a drop from 85-110 fps (0.12 release; similar performance to native D3D9) down to 70-85 ([d3d9-hazards](https://git.froggi.es/joshua/d9vk/-/jobs/517))

Machine:
- Windows 10 1809
- Radeon RX 580
- Ryzen 2600X

**Comment by K0bin** [comment]
Unfortunately that has to be expected which is why it's a separate branch for now.

We're still looking for a better way to fix it but it's a very tricky problem.

**Comment by neVERberleRfellerER** [comment]
> AMDVLK doesn't have this problem

I can actually see this problem with AMDVLK 2019.Q2.5 . Not sure about earlier versions.

I found that when I retrace https://github.com/Joshua-Ashton/d9vk/issues/164 I see the very same corruption as with trace from here, but OP in second issue seemingly does not see any colorful corruption (it's not visible in screenshots). The difference is that OP in seconds thread is on Vega 11, and I am on POLARIS10. hasHazards=true helps in both cases. Is this expected?

**Comment by Joshua-Ashton** [comment]
This should be fixed in master? Can you try it?

**Comment by jacobbrett** [comment]
Tested with [0fd76277](https://git.froggi.es/joshua/d9vk/-/jobs/541). Looks just like native D3D9 as far as I can tell. Performance is comparable, too. There's moments where it'll drop from ~110 down to ~65 but I think that's just an underlying limitation of the game engine.

Cheers!
